### ISSUE TITLE
[Docs] Improve documentation of `DataStore.observe`

### ISSUE THREAD

**Issue by dnys1** [aws-amplify/amplify-flutter#1151] opened 2021-11-30 16:19 UTC
**Description**

https://github.com/aws-amplify/docs/issues/3233

Improve the documentation of the `DataStore.observe` API with examples and explanations: https://docs.amplify.aws/lib/datastore/real-time/q/platform/flutter/

**Comment by abdallahshaban557** [comment] 2022-10-17 23:05
I am closing this issue as a duplicate of the Docs issue https://github.com/aws-amplify/docs/issues/3233

**Closed by abdallahshaban557** 2022-10-17 23:05 UTC
Labels: Documentation, good first issue, DataStore
