### ISSUE TITLE
GraphQL API DynamoDB - internal (type mismatch) error / exception when trying to create a new model object that is connected via `@hasMany` in another model

### ISSUE THREAD

**Issue by dorontal** [aws-amplify/amplify-flutter#2704] opened 2023-02-27 14:18 UTC
### Description

When calling `ModelMutation.create(<MODEL_OBJECT>)`, the call fails with the following error in `response.errors` returned from the call:
```
[log] Could not create project. [GraphQLResponseError{
        "message": "One or more parameter values were invalid: Type mismatch for Index Key userProjectsId Expected: S Actual: NULL IndexName: gsi-User.projects (Service: DynamoDb, Status Code: 400, Request ID: 54FUNTVJU069TEMHI5TJMU8D0FVV4KQNSO5AEMVJF66Q9ASUAAJG)",
        "locations": [
          {
            "line": 1,
            "column": 96
          }
        ],
        "path": [
          "createProject"
        ],
        "extensions": {
          "errorInfo": null,
          "data": null,
          "errorType": "DynamoDB:DynamoDbException"
        }
      }]
```

but in the schema (see below) there is no entity or field that has the name `userProjectsId` that is being complained about in the exception (this field must be something "internally" generated - by its name it looks like it is the ID of the index for the user-projects table that is generated for this connection).

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Just as you can see in the schema below, you will need a schema with two models: `Project` and `User` - connect them by adding the field `projects` to the `User` model as such: `projects: [Project] @hasMany`
2. Now try to create a new `Project` model from the client code

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.5

### Amplify Flutter Version

10.8.0

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type Search
  @model(subscriptions: { level: off })
  @auth(
    rules: [
      # allow anyone not signed-in to update search via IAM Unauth Role
      { allow: public, provider: iam, operations: [create, read, update] }
      # allow anyone signed-in to update search via IAM Auth Role
      { allow: private, operations: [create, read, update] }
    ]
  ) {
  normalizedQuery: String! @primaryKey
  titles: String!
  nTimes: Float!
  nTimesInLast24h: Int!
  titlesUpdatedAt: String!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}

enum ProjectLicense {
  NO_LICENSE
  SOME_RIGHTS_RESERVED
  BY
  BY_SA
  BY_ND
  BY_NC
  BY_NC_EU
  BY_NC_SA
  BY_NC_ND_EU
  CC0
  PUBLIC_DOMAIN_MARK
}

enum ProjectVisibility {
  PRIVATE
  PUBLIC
}

type Project
  @model
  @auth(
    rules: [
      { allow: owner }
      { allow: groups, groups: ["everyone"], operations: [read] }
      { allow: groups, groupsField: "groups", operations: [read, update] }  
    ]
  ) {
  id: ID!
  # the following 'owner' explicit field-level rule ensures owner cannot
  # set the 'owner' field to be another owner, see warning generated when
  # this field level rule is commented out and discussion at:
  # https://docs.amplify.aws/cli/graphql/authorization-rules/#per-user--owner-based-data-access.
  # owner: String @auth(rules: [{ allow: owner, operations: [read] }])
  title: String!
  groups: [String]!
  visibility: ProjectVisibility!
  license: ProjectLicense!
  description: String
  titleArtist: String
    @index(
      name: "byTitleArtistCreatedAt"
      queryField: "byTitleArtistCreatedAt"
      sortKeyFields: ["createdAt"]
    )
    @index(
      name: "byTitleArtistPlays"
      queryField: "byTitleArtistPlays"
      sortKeyFields: ["nPlays"]
    )
  titleArtistUrl: String
  imgUrl: String
  nPlays: Int
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}

enum PictureType {
  INITIALS
  ICON
  IMAGE
}

type User
  @model(subscriptions: { level: off })
  @auth(
    rules: [
      # the 'allow: owner' rule is needed in order to have an owner
      # field created for us, it is needed here, at the model level
      { allow: owner, operations: [read] }
      { allow: private, operations: [read] }
      { allow: public, provider: iam, operations: [read] }
    ]
  ) {
  id: ID!
  # the following 'owner' explicit field-level rule ensures owner cannot
  # set the 'owner' field to be another owner, see warning generated when
  # this field level rule is commented out and discussion at:
  # https://docs.amplify.aws/cli/graphql/authorization-rules/#per-user--owner-based-data-access.
  # owner: String @auth(rules: [{ allow: owner, operations: [read] }])
  displayName: String!
  colorIndex: Int!
  pictureType: PictureType!
  initials: String!
  about: String!
  place: String!
  nPlays: Int!
  nProjects: Int!
  nArrangements: Int!
  nPlaylists: Int!
  nFollowing: Int!
  nFollowers: Int!
  bytesQuota: Int! @auth(rules: [{ allow: owner, operations: [read] }])
  bytesUsed: Int! @auth(rules: [{ allow: owner, operations: [read] }])
  email: String! @auth(rules: [{ allow: owner, operations: [read] }])
  nUpdatesLeft: Int! @auth(rules: [{ allow: owner, operations: [read] }])
  nUploadsLeft: Int! @auth(rules: [{ allow: owner, operations: [read] }])
  totalEarned: Float! @auth(rules: [{ allow: owner, operations: [read] }])
  lastUploadedAt: AWSDateTime! @auth(rules: [{ allow: owner, operations: [read] }])
  projects: [Project] @hasMany @auth(rules: [{ allow: owner }])
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}
```

**Comment by dorontal** [comment] 2023-02-27 15:55
Originally reported this yesterday as issue #2700 - but then quickly closed it thinking maybe it was not reported properly since so many things are involved with the GraphQL schema. I did many more tests and now I'm pretty sure it's not my code, so this is why I opened a new issue.

**Comment by dorontal** [comment] 2023-02-28 00:04
FYI, found this to be true with 10.7.3 and 10.8.0 versions of the Amplify CLI.

**Comment by ragingsquirrel3** [comment] 2023-02-28 19:43
Hey @dorontal I did not get a chance to try to reproduce this but I think the basic issue is that when you save a child model to AppSync, you need to include the parent ID to populate the index. When you do this with model helpers like `ModelMutation.create` the parent instance (in your case user) would need to be populated in the child instance passed to the helper and you might need some schema changes to make this work properly. It looks like your project model did bot specify @belongsTo so an index was generated for you to make this link, like you said "its name it looks like it is the ID of the index for the user-projects table that is generated for this connection". To fix it, I think the request will need to include an ID for that field. 

One option would be a custom request (not with model helper `ModelMutation.create`) so you can include the ID as a variable for the required field with your schema as is.

A better option might be to change your schema so it's possible to specify the user (or the user ID) on a project in the generated code model. You can have a look at the data modeling docs on https://docs.amplify.aws/cli/graphql/data-modeling/#belongs-to-relationship, especially the examples for bi-directional or uni-directional. In either case, you are giving the transformer more explicit input about how to connect these models which will then be reflected in generated code for the models which you can then pass to `ModelMutation.create`. 

Let me know if this is helpful. I realize it's a little vague so let me know if you could use more direction and I can try to spend some time getting some more specific examples together.

**Comment by dorontal** [comment] 2023-02-28 22:26
@ragingsquirrel3 thanks very much for your suggestions. I understand how adding a `@belongsTo` to the `Project` model in a way similar to how `Post` & `Comment` models do so in the documentation link you sent would work.

I'm not sure how helpful it is, because it adds code complexity and redundancy that aren't needed by the app at all other than to fix this issue.

For example, if I followed the documentation for `Post` and `Comment` models exactly, I'd need to pass a whole parent (user) object every time a child (project) is created. This is unnecessary and therefore too expensive to do in this app.

The other thing that confuses me is how to (a) only pass the `userID` and (b) this use case is a little different than the documentation because in this case, isn't the `userID` the same thing as the hidden `owner` field that is created with each model to begin with?  That would be another redundancy - why have two fields with the same value. 

Are you saying that this issue will never be fixed because those other workarounds exist and that I have to choose one of them if I want things working? I think that I would much prefer to wait, but it would help to know if that wait is years vs. months. No pressure. I am only grateful for this fantastic product you and your team are creating for us and totally see its benefits, still.

**Comment by dorontal** [comment] 2023-02-28 23:13
Trying some more variations of your suggestions... will report if anything is learned from that, or will delete this.

**Comment by dorontal** [comment] 2023-02-28 23:59
@ragingsquirrel3 I now understand your words, and the first suggestion, with just parent ID, works perfectly. The following schema change and slight code change made it work: The models are now:
   ```graphql
   type Project {
     ...
     ownerId: ID! @index(name: "byUser", sortKeyFields: ["updatedAt"])
     ...
   }

   type User {
     ...
     projects: [Project] @hasMany(indexName: "byUser", fields: ["id"]) @auth(rules: [{ allow: owner }])  
     ...
   }
   ```
and when instantiating the `Project` in the client Dart code, just add a field `ownerId` that gets the value of the ID of the currently authenticated user.

Now projects are created without error, thanks so much!

**Comment by ragingsquirrel3** [comment] 2023-03-01 17:59
So glad you got this working. This is also a cool schema I might refer back to. Thanks for sharing. I will close this one out.

**Closed by ragingsquirrel3** 2023-03-01 17:59 UTC
Labels: GraphQL API, pending-response, pending-triage

**Comment by brendjuan** [comment] 2023-04-06 15:25
Having similar issues. Looking to allow the 'ownerId' (in this case) be null by default. Is this not allowed anymore in recent versions?
