### ISSUE TITLE
DataStore Unable to Create Model with Auth Rules

### ISSUE THREAD

**Issue by afnx** [aws-amplify/amplify-flutter#3952] opened 2023-10-16 01:21 UTC
### Description

I'm trying to force some auth rules; however, DataStore is not working properly when I try to specify the rules for a particular field.

I want to make sure that only the owner of the user data can read the email field:

```graphql
email: String @auth(rules: [{ allow: owner, ownerField: "id", operations: [create, read] } ])
```

 Also, other fields can be read by anyone, but updated by the owner.

```graphql
type User @model @auth(rules: [
        { allow: owner, ownerField: "id", operations: [create, update, read] },
        { allow: private, operations: [read] }
    ]) {
    ...
}
```

I don't see any logs or errors on the console, but when I launch the app from Xcode, I see some errors:

```console
Detected multiple owner type auth rules with a READ operation. We currently do not support this use case. Please limit your type to just one owner auth rule with a READ operation restriction.
```

```console
One or more errors occurred syncing models. See below for detailed error description.
DataStoreError: An error occurred syncing User
Caused by:
DataStoreError: GraphQL service returned a partially-successful response containing errors: [Amplify.GraphQLError(message: "Not Authorized to access email on type User", locations: Optional([Amplify.GraphQLError.Location(line: 7, column: 7)]), path: Optional([Amplify.JSONValue.string("syncUsers"), Amplify.JSONValue.string("items"), Amplify.JSONValue.number(0.0), Amplify.JSONValue.string("email")]), extensions: Optional(["errorType": Amplify.JSONValue.string("Unauthorized"), "errorInfo": Amplify.JSONValue.null, "data": Amplify.JSONValue.null]))]
Recovery suggestion: The list of `GraphQLError` contains service-specific messages.
Caused by:
GraphQLResponseError<PaginatedList<AnyModel>>: GraphQL service returned a partially-successful response containing errors: [Amplify.GraphQLError(message: "Not Authorized to access email on type User", locations: Optional([Amplify.GraphQLError.Location(line: 7, column: 7)]), path: Optional([Amplify.JSONValue.string("sy
```

```console
Failed to emit ready event, error: DataStoreError: One or more errors occurred syncing models. See below for detailed error description.
Recovery suggestion: DataStoreError: An error occurred syncing User
Caused by:
DataStoreError: GraphQL service returned a partially-successful response containing errors: [Amplify.GraphQLError(message: "Not Authorized to access email on type User", locations: Optional([Amplify.GraphQLError.Location(line: 7, column: 7)]), path: Optional([Amplify.JSONValue.string("syncUsers"), Amplify.JSONValue.string("items"), Amplify.JSONValue.number(0.0), Amplify.JSONValue.string("email")]), extensions: Optional(["errorType": Amplify.JSONValue.string("Unauthorized"), "errorInfo": Amplify.JSONValue.null, "data": Amplify.JSONValue.null]))]
Recovery suggestion: The list of `GraphQLError` contains service-specific messages.
Caused by:
GraphQLResponseError<PaginatedList<AnyModel>>: GraphQL service returned a partially-successful response containing errors: [Amplify.GraphQLError(message: "Not Authorized to access email on type User", locations: Optional([Amplify.GraphQLError.Location(line: 7, column: 7)]), path: Optional([Amplify.JSONValue.string("syncUsers"), Amplify.JSONValue.string("items"), Amplify.JSONValue.number(0.0), Amplify.JSONValue.string("email")]), extensions: Optional(["errorType": Amplify.JSONValue.string("Unauthorized"), "errorInfo": Amplify.JSONValue.null, "data": Amplify.JSONValue.null]))]
Recovery suggestion: The list of `GraphQLError` contains service-specific messages.
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.6

### Amplify Flutter Version

1.4.2

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type User @model @auth(rules: [
        { allow: owner, ownerField: "id", operations: [create, update, read] },
        { allow: private, operations: [read] }
    ]) {
    id: ID! @index(name: "byUser")
    name: String!
    email: String @auth(rules: [
        { allow: owner, ownerField: "id", operations: [create, read] }
    ])
    bio: String
}
```

**Comment by dgagnon** [comment] 2023-10-16 15:55
Hi,
Datastore does not support field ACL:  https://docs.amplify.aws/lib/datastore/setup-auth-rules/q/platform/flutter/

```
DataStore only supports authorization rules specified on this page.

The links provided below to the CLI documentation for specific authorization rules only apply to those particular rules. Datastore only supports a subset of all possible authorization rules provided by the CLI. Therefore, the other authorization rules or setups described in the linked page do not apply to Datastore.
```

**Comment by afnx** [comment] 2023-10-16 18:44
@dgagnon Thanks for the response. Is there any other way to hide certain fields from unauthorized users?

**Comment by dgagnon** [comment] 2023-10-16 21:30
@afnx at the moment, I think the only way is using nullable fields and custom resolvers, but I am not 100% sure it would work.

**Comment by afnx** [comment] 2023-10-17 05:31
@dgagnon I see. There is [this documentation ](https://docs.amplify.aws/cli-legacy/graphql-transformer/resolvers/#custom-resolvers) about customizing resolvers, but it doesn't say anything about DataStore.

**Comment by afnx** [comment] 2023-10-18 18:38
@Jordan-Nelson, Is there a workaround to achieve field-level protection with DataStore? This is kind of a big deal. If there isn't, then there is no point to use DataStore for me.

**Comment by khatruong2009** [comment] 2023-10-19 23:08
Hi @afnx, DataStore currently doesn't support field level auth rules. The only workaround available right now is the remove the field-level auth rule. I am going to close this issue now as it is a duplicate of [this one](https://github.com/aws-amplify/amplify-flutter/issues/3459).

**Closed by khatruong2009** 2023-10-19 23:08 UTC
Labels: DataStore
