### ISSUE TITLE
[COGNITO] Apple sign in, no name if user 'continues' after deleting account

### ISSUE THREAD

**Issue by ToddZeil** [aws-amplify/amplify-flutter#4078] opened 2023-11-07 03:34 UTC
### Description

We are using Flutter Cognito Apple sign in, we have an issue when a user deletes their account.

After they delete their account and sign in again, they are prompted with a 'continue' screen, rather than the original sign in screen.
Which doesn't prompt the user for their name and fails to pass through the first and last name, like it does when you create an account for the first time.

If you also go into apple settings and delete the apple sign in for the app, you are presented with the original sign in screen with first and last name. But we can not expect user to do this.

Is there any way to make sure the name is passed in when the continue screen is presented but you are actually creating an account.

 

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Sign in with Apple
2. Presented with new sign in web page
3. Successfully retrieve names
4. Delete account
5. Sign in with apple
6. Presented with 'continue' with Apple 
7. Failed to retrieve names

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

 3.13.9

### Amplify Flutter Version

1.1.1

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment] 2023-11-07 18:04
Hello @ToddZeil - Unfortunately I do not think it is possible to get the info again unless the end user manually deauthorizes Apple ID for the app. Apple only provides the info on the very first login. I don't believe this is Amplify or Cognito specific. See this thread for more info: https://developer.apple.com/forums/thread/121496

**Comment by Jordan-Nelson** [comment] 2023-11-13 16:01
@ToddZeil - I am going to close this out since this is unfortunately expected behavior since Apple only provides the data on the very first login.

**Closed by Jordan-Nelson** 2023-11-13 16:01 UTC
Labels: Question, pending-close-response-required, Auth
