### ISSUE TITLE
AWSHttpRequest body not showing in Dart's dev tools

### ISSUE THREAD

**Issue by livioschlaepfer** [aws-amplify/amplify-flutter#4847] opened 2024-05-07 19:56 UTC
### Description

Using AWSHttpRequest from package aws_common fails to create a request body on web.
See attached screenshots of created request mobile vs web.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Create an AWSHttpRequest

```dart
 final request = AWSHttpRequest.post(
       Uri.parse('<your-url>'),
       headers: const {
         AWSHeaders.contentType: 'application/json',
       },
       body: json.encode({
         'first_name': 'max',
         'last_name': 'muster',
       }).codeUnits,
     );
```

2. Compare created request on mobile and web

### Screenshots

Generated request object on web:
<img width="362" alt="image" src="https://github.com/aws-amplify/amplify-flutter/assets/43854856/b366bfb6-a903-4a1e-86b6-c4359312bc0b">

Generated request object on mobile:
<img width="351" alt="image" src="https://github.com/aws-amplify/amplify-flutter/assets/43854856/f8a98178-3d92-4781-8c49-696b9f1f7a23">

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.16.8

### Amplify Flutter Version

aws_common: 0.6.3

### Deployment Method

Amplify CLI

**Comment by khatruong2009** [comment] 2024-05-07 21:52
Hi @livioschlaepfer, we will take a look at this issue and get back to you when we have an update.

**Comment by livioschlaepfer** [comment] 2024-06-04 07:24
@khatruong2009 are there any updates on this?

**Comment by Jordan-Nelson** [comment] 2024-06-11 21:14
@livioschlaepfer I am not able to reproduce the exact issue you are facing. I see there is a body on both web and mobile. The body doesn't seem to display correctly in Dart's dev tools when running on web (see screenshot below).

<img width="690" alt="Screenshot 2024-06-11 at 5 07 47 PM" src="https://github.com/aws-amplify/amplify-flutter/assets/20613561/671e0913-718a-4369-8351-448539c84b34">

However, the body is present. I can listen to it an receive data (see code snippet below). I also see the body in Chrome's dev tools when I make the request. I am unsure why it is not displaying correctly in Dart's dev tools. This maybe be an issue with Dart's dev tools.

Is the issue you are facing consistent with what I have described?

Here is the code snippet I was using:

```dart
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: Center(
          child: Column(
            children: [
              FilledButton(
                onPressed: () {
                  final request = AWSHttpRequest.post(
                    Uri.parse('https://jsonplaceholder.typicode.com/posts'),
                    headers: const {
                      AWSHeaders.contentType: 'application/json; charset=UTF-8',
                    },
                    body: jsonEncode({
                      'title': 'foo',
                      'body': 'bar',
                      'userId': 1,
                    }).codeUnits,
                  );
                  request.body.listen((data) => safePrint('got data: $data'));
                  safePrint('body: ${request.body}');
                  request.send();
                },
                child: const Text('request'),
              ),
            ],
          ),
        ),
      ),
    );
  }
```

**Comment by Jordan-Nelson** [comment] 2024-06-11 21:22
@livioschlaepfer if you are not seeing the value at all it is likely because you have the following dart settings disabled: Show Getters In Debug Views. You can follow [this comment](https://github.com/dart-lang/webdev/issues/2297#issuecomment-1865248892) to enable/disable it.

**Comment by Jordan-Nelson** [comment] 2024-06-11 21:42
I created a minimal reproduction of this and opened [an issue here](https://github.com/dart-lang/webdev/issues/2446). This seems like a dart issue to me but maybe it is intentional that this is not supported. Either way I don't think it is a bug in amplify_common. I am going to update this to a question for now.

**Comment by Jordan-Nelson** [comment] 2024-06-14 16:27
@livioschlaepfer - I am going to close this out now that there is an issue open with dart. It looks like they need to investigate if this can be supported on web. I don't think there is much we can do in amplify flutter.

**Closed by Jordan-Nelson** 2024-06-14 16:27 UTC
Labels: question, pending-response
