### ISSUE TITLE
SignedOutException for fetchAuthSession method with getAWSCredentials set to false - Android (flutter)

### ISSUE THREAD

**Issue by Mik77o** [aws-amplify/amplify-flutter#2250] opened 2022-10-17 08:24 UTC
On `Android` only: when I'm signed out and trying to check later if I'm signed in using `fetchAuthSession` with the `getAWSCredentials` option set to `false`, I always get the following information in the console for my flutter app:

D/AWSMobileClient(18715): Inspecting user state details
D/AWSMobileClient(18715): waitForSignIn: userState:SIGNED_OUT
W/AWSMobileClient(18715): getCredentials: Failed to getCredentials from Cognito Identity
W/AWSMobileClient(18715): com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Unauthenticated access is not supported for this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: xxxx....)
W/AWSMobileClient(18715): 	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
W/AWSMobileClient(18715): 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
W/AWSMobileClient(18715): 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
W/AWSMobileClient(18715): 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:1836)
W/AWSMobileClient(18715): 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:809)
W/AWSMobileClient(18715): 	at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
W/AWSMobileClient(18715): 	at com.amazonaws.mobile.client.AWSMobileClientCognitoIdentityProvider.refresh(AWSMobileClient.java:4078)
W/AWSMobileClient(18715): 	at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:687)
W/AWSMobileClient(18715): 	at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:474)
W/AWSMobileClient(18715): 	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:496)
W/AWSMobileClient(18715): 	at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:400)
W/AWSMobileClient(18715): 	at com.amazonaws.mobile.client.AWSMobileClient$1.run(AWSMobileClient.java:445)
W/AWSMobileClient(18715): 	at com.amazonaws.mobile.client.AWSMobileClient$1.run(AWSMobileClient.java:442)
W/AWSMobileClient(18715): 	at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:44)
W/AWSMobileClient(18715): 	at java.lang.Thread.run(Thread.java:920)
E/amplify:flutter:auth_cognito(18715): **SignedOutException**
E/amplify:flutter:auth_cognito(18715): SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}
E/amplify:flutter:auth_cognito(18715): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.onGetCurrentUser$lambda-20(AuthCognito.kt:430)
E/amplify:flutter:auth_cognito(18715): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.$r8$lambda$gg-VcKKMkSM4Rfv_84rvIvumCNk(Unknown Source:0)
E/amplify:flutter:auth_cognito(18715): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito$$ExternalSyntheticLambda14.accept(Unknown Source:6)
E/amplify:flutter:auth_cognito(18715): 	at com.amplifyframework.auth.cognito.MobileClientSessionAdapter$1.onError(MobileClientSessionAdapter.java:74)
E/amplify:flutter:auth_cognito(18715): 	at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:47)
E/amplify:flutter:auth_cognito(18715): 	at java.lang.Thread.run(Thread.java:920)

```
 amplify_auth_cognito: ^0.6.8
 amplify_flutter: ^0.6.8
```

**Comment by haverchuck** [comment] 2022-10-17 19:30
@Mik77o Are you seeing different behavior on iOS, or are you only using Android?

**Comment by Mik77o** [comment] 2022-10-17 19:36
I work with both platforms. On iOS for this case error doesn't occur :) I can see this info only for Android.

**Comment by Jordan-Nelson** [comment] 2022-11-09 14:55
Hi @Mik77o - You should see a SignedOutException on both iOS and Android when calling fetchAuthSession() while signed out. I have verified that is the behavior on the latest stable version of Amplify (v0.6.9). You will see more info in the logs on Android since logs from native iOS code will not be present in the console when running a flutter app. This is the case for all flutter apps, and not specific to Amplify.

I am not sure if I follow what the issue is. Are you seeing something other than a SignedOutException on iOS? Are you concerned about something you see in the logs?

**Comment by Mik77o** [comment] 2022-11-14 11:41
@Jordan-Nelson Thanks for the clarification. I just wanted to make sure this is the desired action and yes - for iOS there is less info.

**Comment by Jordan-Nelson** [comment] 2022-11-14 15:59
@Mik77o - Yes, a `SignedOutException` would be expected when calling fetchAuthSession() while signed out.

The current stable version of Amplify-Flutter is built on top of Amplify-iOS and Amplify-Android. We are in the process of removing these dependencies in favor of a version written in Dart. The Auth re-write in Dart is available in our developer preview release on pub. You should see aligned logs on all platforms in this version.

I am going to close this out. Please open a new issue if you are face additional issues in the future.

**Closed by Jordan-Nelson** 2022-11-14 15:59 UTC
Labels: Auth, pending-response, pending-triage
