### ISSUE TITLE
Amplify.Auth.signOut Method Issue

### ISSUE THREAD

**Issue by bharathiselvan** [aws-amplify/amplify-flutter#5452] opened 2024-09-13 13:20 UTC
### Description

The Amplify.Auth.signOut method is not logging the user out completely. When attempting to log in again using Amplify.Auth.signInWithWebUI, the Hosted UI allows the previously signed-out account to log in without requiring re-authentication.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Sign in using Amplify.Auth.signInWithWebUI.
Call Amplify.Auth.signOut to log out the user.
Attempt to log in again using Amplify.Auth.signInWithWebUI.
Observe that the Hosted UI allows the previously signed-out account to log in without prompting for re-authentication.

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.19.1

### Amplify Flutter Version

1.6.1

### Deployment Method

Amplify Gen 2

**Comment by mahesh87ta** [comment] 2024-09-13 13:23
I also encounter same issue.

**Comment by GitHub-user-Bala** [comment] 2024-09-13 13:40
I’m also encountering the same challenge.

**Comment by tyllark** [comment] 2024-09-13 22:34
Hi @bharathiselvan, thank you for submitting this issue. We will take a look at this issue and get back to you when we have any updates or questions.

**Comment by Equartey** [comment] 2024-09-16 15:08
Hi @bharathiselvan, this sounds like a duplicate of https://github.com/aws-amplify/amplify-flutter/issues/4747#issuecomment-2168357847. Does this comment address the what you're seeing?

**Comment by Equartey** [comment] 2024-09-16 15:11
@bharathiselvan Ah, I see your comment on the feature request: https://github.com/aws-amplify/amplify-flutter/issues/1528. 

This feature request is still in our backlog and besides the comment I linked above, we do not have any other guidance at this time. 

I'm going to close this issue as a duplicate.

**Closed by Equartey** 2024-09-16 15:11 UTC
Labels: to-be-reproduced, pending-community-response, pending-triage
