### ISSUE TITLE
Image not uploading in S3 when flutter framework is integrated in iOS app

### ISSUE THREAD

**Issue by ram-readwhere** [aws-amplify/amplify-flutter#796] opened 2021-08-11 10:02 UTC
We have created a flutter module with AWS Amplify. We are using S3 for storing images.Guest are allowed to create/delete images.Images are being uploaded on S3 successfullly. When this module is used as framework in iOS app,there is error in uploading image on S3.

Error, we are getting - [AmplifyStorageOperations] The operation couldn’t be completed. (Amplify.StorageError error 1.)
2021-08-11 11:54:13.267315+0530 IndiaTV[13950:1566135] flutter: Error uploading file: StorageException(message: Unexpected error occurred with message: An unknown error occurred, recoverySuggestion: This should not happen.
Issue encountered at:
file: /Users/rahulrana/Documents/newdev2/clickmania_mobie_app/click_mania_flutter_app/ios/Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift 

**Expected behavior**
Images should be uploaded on S3 after fluuter framework integration in iOS app like they are uploading when we run standalone flutter module

**Screenshots**
awsconfiguration.dart file screenshot attached
Error screenshot attached
<img width="530" alt="awsconfiguration dart" src="https://user-images.githubusercontent.com/3830915/129010229-d6d2bc22-dc3a-4aee-9983-f1cd00d53323.png">
<img width="1040" alt="s3_upload_error" src="https://user-images.githubusercontent.com/3830915/129010253-b24e4268-3996-43e5-b170-05b4487e5738.png">

**Comment by offlineprogrammer** [comment] 2021-08-30 16:26
Hi @ram-readwhere 

I tested in iOS, and Android and I couldn't reproduce the issue

Feel free to test using the latest build and let us know if you got any issues

You can refer to the sample app and the docs for more details on Storage

Thanks
Mo

**Comment by offlineprogrammer** [comment] 2021-09-07 15:14
Hey @ram-readwhere 

I am closing this issue for now as we didn't hear from you
We can reopen it if you are still facing the issue and when you provide details

Regards
Mo

**Closed by offlineprogrammer** 2021-09-07 15:14 UTC
Labels: pending-close-response-required
