### ISSUE TITLE
API plugin timeout configuration is not possible

### ISSUE THREAD

**Issue by odemkovychromexsoft** [aws-amplify/amplify-flutter#853] opened 2021-09-03 11:21 UTC
It is not possible to provide a socket timeout configuration for the API plugin. 
Under Android it defaults to 10sec for the time being.

**Comment by fjnoyp** [comment] 2021-09-14 20:58
Hi @odemkovychromexsoft thanks for reaching out to us.  We're looking into your request.  I'll update you here on what we find.

**Comment by fjnoyp** [comment] 2021-09-14 22:39
Hi @odemkovychromexsoft this feature is not natively supported in iOS or Android REST API so it would be trickier to implement in Flutter.  We will discuss more internally about how we might prioritize this. 

Below are some notes for future devs on how implementation might work.  Native libraries don't have timeout configuration in their APIs so we'd want to determine that as well. 

Amplify Android: 
Need to get the okhttp client using escape hatch and create a new client with socket timeout configuration. 

Amplify iOS:
Pass your own "URLSessionFactory" with desired timeout configuration. 

https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyPlugins/API/AWSAPICategoryPlugin/AWSAPIPlugin.swift#L84

https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1408259-timeoutintervalforrequest

**Comment by fjnoyp** [comment] 2021-09-14 22:39
@odemkovychromexsoft could you tell us more about your use case here - that would help us with prioritizing here appropriately.

**Comment by dnys1** [comment] 2021-09-21 22:53
Duplicate of: https://github.com/aws-amplify/amplify-flutter/issues/798

I believe this is currently possible, although I haven't thought about the Flutter API. Maybe parameters on the API plugin constructor like we have for DataStore configuration.

**Closed by dnys1** 2021-09-21 22:53 UTC
Labels: bug, API
