### ISSUE TITLE
Opted-in endpoints 0 endpoints for flutter app

### ISSUE THREAD

**Issue by latheeshvmv** [aws-amplify/amplify-flutter#1182] opened 2021-12-06 17:32 UTC
**Describe the bug**
I have added push notifications with pin point and FCM. It works fine on test device.

I am seeing two end points but when I am creating a campaign the **Opted-in endpoints 0 endpoints** 
How can this be fixed? As the end points are android apps. I have done the implementation as per documentation there is nothing about Opted in for flutter based apps?

Please help

**To Reproduce**
1. [Go to '...'](https://pub.dev/packages/amplify_analytics_pinpoint/example) - No info here
2. Nothing here : https://docs.amplify.aws/lib/analytics/getting-started/q/platform/flutter/

**Expected behavior**
documentation for implementation in flutter apps?

**Screenshots**
![image](https://user-images.githubusercontent.com/44595562/144893647-e71476f2-dba8-4f3b-b76a-43edaa18a003.png)

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[x] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```Paste your output of "flutter doctor -v" here```

</details>

<details>

  <summary>Dependencies (<code>pubspec.lock</code>)</summary>
  
  ```
  Paste the contents of your "pubspec.lock" file here
  ```

</details>

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fjnoyp** [comment] 2021-12-06 20:49
Hi @latheeshvmv thanks for reaching out to us.  Unfortunately Amplify Flutter does not support push notifications at the moment but we are discussing it internally.   

Here is the linked issue where will provide further updates:  
https://github.com/aws-amplify/amplify-flutter/issues/319

**Comment by offlineprogrammer** [comment] 2022-01-03 17:07
Hi @latheeshvmv 

I am closing this issue as it is a duplicate of [319](https://github.com/aws-amplify/amplify-flutter/issues/319) which you can use to track the updates on this feature request

Regards
Mo

**Closed by offlineprogrammer** 2022-01-03 17:07 UTC
Labels: duplicate, feature-request, requires-android-fix, requires-ios-fix
