### ISSUE TITLE
Datastore not saving model when using @belongsto with @auth

### ISSUE THREAD

**Issue by alterhuman** [aws-amplify/amplify-flutter#3553] opened 2023-08-14 16:22 UTC
### Description

When pushing new items to datastore on signup, the number of items in DynamoDb console for every model remains 0. The models are being created.

Handling auth on signedIn subscription event trying to save models to datastore:

```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Hive
  await initHive();

  // Amplify
  await _configureAmplify();

  // Listen for auth events to support subscriptions
  // PS - You can assign final subscriptions to this if you want to cancel the subscription later
  final subscriptions =
      Amplify.Hub.listen(HubChannel.Auth, (AuthHubEvent event) {
    switch (event.type) {
      case AuthHubEventType.signedIn:
        _handleAuth();
        safePrint('User is signed in. Subscriptions are now supported.');
        break;
      case AuthHubEventType.signedOut:
        safePrint('User is signed out.');
        break;
      case AuthHubEventType.sessionExpired:
        safePrint('The session has expired.');
        break;
      case AuthHubEventType.userDeleted:
        safePrint('The user has been deleted.');
        break;
    }
  });

  runApp(const ProviderScope(child: Supercyse()));
}
```

```dart
Future<void> _handleAuth() async {
  try {
    // Get the current user's ID and email
    final authUser = await Amplify.Auth.getCurrentUser();
    final userAttributes = await Amplify.Auth.fetchUserAttributes();
    final userId = authUser.userId;

    securePrint('Id of the user: $userId');

    // Check if the user already exists in the DataStore
    final existingUser = await Amplify.DataStore.query(User.classType,
        where: User.ID.eq(authUser.userId));

    if (existingUser.isNotEmpty) {
      securePrint('User already exists');
    } else {
      securePrint('User does not exist, creating a new user');
      // Get the onboarding data from the local storage
      final onboardingBox = await Hive.openBox('onboarding');
      final onboardingDataMap = onboardingBox.get('onboardingData');

      Onboarding? onboardingData;
      if (onboardingDataMap != null) {
        onboardingData =
            Onboarding.fromJson(onboardingDataMap.cast<String, dynamic>());
      }

      onboardingBox.close();
      if (onboardingData != null) {
        // Convert the onboarding data to the appropriate Amplify Datastore model
        final user = User(
          id: authUser.userId, // Use the ID assigned by Cognito
          name: onboardingData.name,
          dateOfBirth: onboardingData.age,
          email: authUser.username, // Use the email from the AuthUser object
        );

        final preferences = Preferences(
          id: user.id,
          user: user,
          experienceLevel: onboardingData.experienceLevel,
        );

        // Save the user and preferences to the Amplify Datastore
        await Amplify.DataStore.save(user);

        try {
          await Amplify.DataStore.save(user);
          securePrint('Saved user to DataStore');
        } on DataStoreException catch (e) {
          safePrint('Something went wrong saving user: ${e.message}');
        }

        try {
          await Amplify.DataStore.save(preferences);
          securePrint('Saved user preferences to DataStore');
        } on DataStoreException catch (e) {
          safePrint(
              'Something went wrong saving user preferences: ${e.message}');
        }

        // Clearing onboarding data
        final onboardingBox = await Hive.openBox('onboarding');
        await onboardingBox.clear();
        await onboardingBox.close();
      }
    }
  } catch (e) {
    securePrint('Failed to save user and preferences: $e');
  }
}
```

Unable to figure out the reason it is not syncing.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.6

### Amplify Flutter Version

1.3.0

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type User
@model
@auth(rules: [{ allow: owner }])
{
    id: ID!
    name: String!
    dateOfBirth: String!
    email: AWSEmail!
    preferences: Preferences @hasOne
}

type Preferences
@model
@auth(rules: [{ allow: owner, operations: [read, update] }])
{
    id: ID!
    user: User! @belongsTo
    experienceLevel: String!
}
```

**Comment by Jordan-Nelson** [comment] 2023-08-29 16:43
Okay. I was not able to repro that second issue using the schema below. If you are still able to reproduce this issue with that schema, please let me know. For now I will close this out since I cannot reproduce it and it sounds like you have worked around the issue you had faced.

```schema
type User
  @model
  @auth(rules: [{ allow: owner, operations: [read, update, create, delete] }]) {
  id: ID!
  name: String!
  dateOfBirth: String!
  email: AWSEmail!
  preferences: Preferences @hasOne
}

type Preferences
  @model
  @auth(rules: [{ allow: owner, operations: [read, update, create, delete] }]) {
  id: ID!
  user: User! @belongsTo
  experienceLevel: String!
}
```

**Closed by Jordan-Nelson** 2023-08-29 16:43 UTC
Labels: pending-close-response-required, DataStore, Investigating
