### ISSUE TITLE
InvalidParameterException(message: One or more parameters are incorrect.

### ISSUE THREAD

**Issue by ADLsourceCode** [aws-amplify/amplify-flutter#933] opened 2021-10-02 06:46 UTC
We get the below error during login . This is a random error , Most of the time we can login successfully but sometimes we get this error.

` InvalidParameterException(message: One or more parameters are incorrect., recoverySuggestion: Enter correct parameters., underlyingException: com.amazonaws.services.cognitoidentityprovider.model.InvalidParameterException: 2 validation errors detected: Value at 'userName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{M}\p{S}\p{N}\p{P}]+; Value at 'userAlias' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{M}\p{S}\p{N}\p{P}]+ (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException; Request ID: 6344389d-bb9c-4cf9-b5ff-889df6158588))`

Please have a look.

**Comment by Jordan-Nelson** [comment] 2021-10-02 15:20
Hello @ADLsourceCode - Thanks for opening the issue.

- What version of amplify-flutter are you using?
- Is this on Android only?
- How frequently do you see this issue? Is there a particular subset of users that you are seeing this with? Any steps to help reproduce this would be helpful.

**Comment by ADLsourceCode** [comment] 2021-10-04 13:08
What version of amplify-flutter are you using? 
amplify_core: '<1.0.0'
  amplify_flutter: <1.0.0
  amplify_auth_cognito: '<1.0.0'
  amplify_storage_s3: '<1.0.0'
  
Is this on Android only? - tested on Android only 

How frequently do you see this  issue?  - Very random


Is there a particular subset of users that you are seeing this with? Any steps to help reproduce this would be helpful. - We log in normally and it randomly gives this error. and most of the time it login well.

**Comment by abdallahshaban557** [comment] 2021-11-09 18:43
@ADLsourceCode  - are you still experiencing this error? Does the username have any special characters in it for the users attempting to login?

**Comment by Sunsiha** [comment] 2021-12-20 15:26
@ADLsourceCode for me am getting this error when I enter abcd@gmail.com

**Comment by Jordan-Nelson** [comment] 2022-03-08 15:42
@ADLsourceCode - There was a similar issue (https://github.com/aws-amplify/amplify-js/issues/3862) opened in Amplify JS that seemed to be caused by the user entering emails with whitespace at the end. Are you trimming the user input to remove whitespace?

@Sunsiha That appears to be a different issue. It looks like you are trying to reset the password for a user that doesn't have a phone number or email on file. That could happen if the user was created manually in the Cognito console, and was not given an email or phone number. If you would like help with that, can you please open a separate issue?

**Comment by Jordan-Nelson** [comment] 2022-03-14 13:46
@ADLsourceCode - Let us know if you have attempted the solution above and are still facing this issue. Thanks.

**Comment by Jordan-Nelson** [comment] 2022-03-21 19:07
@ADLsourceCode - I am going to close this out. If you are still facing this issue, please feel free to open a new issue.

**Closed by Jordan-Nelson** 2022-03-21 19:07 UTC
Labels: pending-close-response-required, Auth
