### ISSUE TITLE
AplifyAlreadyConfiguredException even wth Amplify.isConfigured check on android restart

### ISSUE THREAD

**Issue by stevegaunt** [aws-amplify/amplify-flutter#3101] opened 2023-05-24 14:48 UTC
### Description

Is this check process safe???

if (!Amplify.isConfigured) {

  try {
    await Amplify.addPlugins([
      AmplifyAuthCognito(),
      AmplifyStorageS3(),
      AmplifyAPI(),
      datastorePlugin,
    ]);
    await Amplify.configure(amplifyconfig);
  } on AmplifyAlreadyConfiguredException catch(e) {
    Log.instance.warning('[Amplify] Amplify Already Configured ${e.toString()} ');
  }
}
even with this code check in our main class, sometimes restarting the app can through this exception

AplifyAlreadyConfiguredException { "message": "Amplify has already been configured and adding plugins after configure is not supported.", "recoverySuggestion": "Check if Amplify is already configured using Amplify.isConfigured." }
STATUS

Received:2023-05-23 16:21:34
#0      AmplifyDataStore.configure (package:amplify_datastore/amplify_datastore.dart:80)
<asynchronous suspension>
#1      Future.wait.<anonymous closure> (dart:async/future.dart:525)
<asynchronous suspension>
#2      AmplifyHybridImpl.configurePlatform (package:amplify_flutter/src/hybrid_impl.dart:26)
<asynchronous suspension>
#3      AmplifyClass.configure (package:amplify_core/src/amplify_class.dart:113)
<asynchronous suspension>
#4      main (package:yepic/main.dart:76)
<asynchronous suspension>

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Steps to Reproduce

Restarting the app can generate this exception.
Our app can run in both foreground and as a background process in headless mode.
Using the Amplify.isConfigured check always seemed to hold the correct state for amplify flutter 0.6.x
Upgrading to Amplify flutter 1.1.0 this now happens on android,.  Is it possible the configured completer is out of sync with the underlying bridge plugins?

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.1

### Amplify Flutter Version

1.1.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment] 2023-05-24 20:02
@stevegaunt - The `isConfigured` boolean will be out of sync after a hot restart when using the DataStore category. This is a known issue and is being tracked [here](https://github.com/aws-amplify/amplify-flutter/issues/1658).

It sounds like you are seeing `isConfigured` out of sync in a release build. Is that correct? Can you help me better understand the scenario in which this occurs?

**Comment by stevegaunt** [comment] 2023-05-25 07:42
@Jordan-Nelson 
Yes, this is in a release build.  I guess the behaviour replicates a hot restart . 
Our app can run in both foreground and as a background process in headless mode.
going in-between these 2 states may resemble a hot restart

Handling the exception seems to carry on, and amplify behaves as expected.  
I was really asking initially if there would be no knock on effects handling the exception until it is resolved with 1658

**Comment by Jordan-Nelson** [comment] 2023-05-31 18:36
@stevegaunt - I don't believe there will be any issue with catching the exception. In the case that they get out of sync, the dart plugins (all plugins other than DS) will need to be configured again. The DS will already be configured as it is still a native iOS/Android plugin.

I am going to close this as a duplicate of #1658. If you have any further questions or see any issues please share them on that issue.

**Closed by Jordan-Nelson** 2023-05-31 18:36 UTC
Labels: DataStore, Investigating
