### ISSUE TITLE
PushNotificationException: "Error occurred awaiting for device token."

### ISSUE THREAD

**Issue by fadone** [aws-amplify/amplify-flutter#5358] opened 2024-08-22 16:09 UTC
### Description

I am following the docs [Set up Amplify Push Notifications
](https://docs.amplify.aws/gen1/flutter/build-a-backend/push-notifications/set-up-push-notifications/) and I am getting an error after adding this line:
```
id "com.google.gms:google-services" version "4.3.14" apply false
```
Error:
```
plugin id 'com.google.gms:google-services' is invalid: Plugin id contains invalid char ':' (only ASCII alphanumeric characters, '.', '_' and '-' characters are valid)
```
I fixed that by changing the ":" to a ".":
```
id 'com.google.gms.google-services' version '4.3.14' apply false
```

Then after [Initialize Amplify Push Notifications](https://docs.amplify.aws/gen1/flutter/build-a-backend/push-notifications/set-up-push-notifications/#initialize-amplify-push-notifications), I am getting the following error:
```
E/flutter ( 4348):   "underlyingException": "PlatformException(java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.example.boca_dubbing. Make sure to call FirebaseApp.initializeApp(Context) first., IllegalStateException, Cause: null, Stacktrace: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.example.boca_dubbing. Make sure to call FirebaseApp.initializeApp(Context) first.\n\tat com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:179)\n\tat com.google.firebase.messaging.FirebaseMessaging.getInstance(FirebaseMessaging.java:121)\n\tat com.amazonaws.amplify.amplify_push_notifications.PushNotificationUtilsKt.refreshToken(PushNotificationUtils.kt:96)\n\tat com.amazonaws.amplify.amplify_push_notifications.AmplifyPushNotificationsPlugin.requestInitialToken(AmplifyPushNotificationsPlugin.kt:189)\n\tat com.amazonaws.amplify.amplify_push_notifications.PushNotificationsHostApiBindings$PushNotificationsHostApi.lambda$setup$0(PushNotificationsHostApiBindings.java:360)\n\tat com.amazonaws.amplify.amplify_push_notifications.PushNotificationsHostApiBindings$PushNotificationsHostApi$$ExternalSyntheticLambda0.onMessage(Unknown Source:2)\n\tat io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)\n\tat io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)\n\tat io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)\n\tat io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)\n\tat android.os.Handler.handleCallback(Handler.java:942)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loopOnce(Looper.java:201)\n\tat android.os.Looper.loop(Looper.java:288)\n\tat android.app.ActivityThread.main(ActivityThread.java:7872)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)\n, null)"
```

I tried adding the `await Firebase.initializeApp()` before the `runApp()` after installing `firebase_core` but I getting the following error:
```
Unhandled Exception: PlatformException(java.lang.Exception: Failed to load FirebaseOptions from resource. Check that you have defined values.xml correctly., Exception, Cause: null, Stacktrace: java.lang.Exception: Failed to load FirebaseOptions from resource. Check that you have defined values.xml correctly.
```

Am I missing a step or something here?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Following the docs:
https://docs.amplify.aws/gen1/flutter/build-a-backend/push-notifications/set-up-push-notifications/

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.22.1

### Amplify Flutter Version

2.4.0

### Deployment Method

Amplify CLI

**Comment by NikaHsn** [comment] 2024-08-22 16:13
thanks for openning this issue. We will look into this and get back to you when we have updates.

**Comment by fadone** [comment] 2024-08-22 17:02
It worked after I added `id 'com.google.gms.google-services'` to plugins in `build.gradle` file on `app-level` and `id "com.google.gms.google-services" version "4.3.14" apply false` to plugins in `settings.gradle`. 

Surely there is no need to add `firebase_core` and `await Firebase.initializeApp()`.

**Comment by NikaHsn** [comment] 2024-08-22 18:21
thanks for the update and I'm glad that the issue is resovled. I'm closing this as there is no action on our end. please open a new issue if you have any question.

**Closed by NikaHsn** 2024-08-22 18:21 UTC
Labels: question, push notifications
