### ISSUE TITLE
A problem occurred configuring project ':amplify_auth_cognito_android'

### ISSUE THREAD

**Issue by jheimes-silveira** [aws-amplify/amplify-flutter#1689] opened 2022-06-06 12:36 UTC
### Description

i'm always getting this error when trying to compile

```
Launching lib/main_dev.dart on Android SDK built for x86 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':amplify_auth_cognito_android'.
> this and base files have different roots: D:\projetos\condoconta\flutter-mobile-condoconta\flut_base_app_condoconta_syndic\build\amplify_auth_cognito_android and C:\Users\jheime\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\amplify_auth_cognito_android-0.5.1\android.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Exception: Gradle task assembleDevDebug failed with exit code 1
Exited (sigterm)

```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

i'm always getting this error when trying to compile

### Screenshots

![Captura de tela 2022-06-06 093509](https://user-images.githubusercontent.com/16032899/172161705-de95cd8a-bbaf-48ac-866d-35dcdde0227e.png)

### Platforms

- [ ] iOS
- [X] Android

### Android Device/Emulator API Level

API 32+

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [versao 10.0.22000.708], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.67.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
```

### Dependencies

```bash
amplify_flutter: 0.5.1
  amplify_auth_cognito: 0.5.1
  amplify_core: 0.5.1
  amplify_auth_cognito_android: 0.5.1
  carousel_slider: 4.1.1
  camera: 0.9.5+1
  cupertino_icons: 1.0.4
  cached_network_image: 3.2.1
  cpf_cnpj_validator: 2.0.0
  dotted_border: 2.0.0+2
  device_info_plus: 3.2.3
  email_validator: 2.0.1
  enum_to_string: 2.0.1
  flutter_modular: 5.0.2
  file_picker: 4.5.1
  flutter_mobx: 2.0.6+1
  flutter_svg: 1.0.3
  flutter_keyboard_visibility: 5.2.0
  flutter_cache_manager: 3.3.0
  flutter_spinkit: 5.1.0
  fluttertoast: 8.0.9
  flutter_udid: 2.0.0
  barcode_scanner_kit: 1.0.1
  image_picker: 0.8.5
  intl: 0.17.0
  just_the_tooltip: 0.0.11+2
  jiffy: 5.0.0
  localization: 2.1.0
  logger: 1.1.0
  mocktail: 0.3.0
  mobx: 2.0.7
  mask_text_input_formatter: 2.3.0
  easy_mask: 2.0.1
  native_pdf_view: 6.0.0+1
  notification_permissions: 0.6.1
  path_provider: 2.0.9
  package_info_plus: 1.4.2
  pin_code_fields: 7.4.0
  recase: 4.0.0
  screenshot: 1.2.3
  sticky_and_expandable_list: 1.0.3 
  share_plus: 3.0.5
  shared_preferences: 2.0.13
  shimmer: 2.0.0
  timer_count_down: 2.2.1
  uuid: 3.0.5
  url_launcher: 6.1.2
  dio: 4.0.6
  flutter_image_compress: 1.1.0
  syncfusion_flutter_pdfviewer: 20.1.56-beta
  syncfusion_flutter_pdf: 20.1.56-beta
  crypto: 3.0.1
  dropdown_search: 3.0.1
  webviewx:
```

### Device

Pixel 3a XL API 30 (Android-x86 emulator)

### OS

Android 11

### CLI Version

7.6.21

**Comment by Jordan-Nelson** [comment] 2022-06-06 14:24
Hi @jheimes-silveira - Thanks for taking the time to open the issue and include the info you have provided. Can you share your `/android/build.gradle` file?

**Comment by tree1891** [comment] 2022-07-13 05:37
Same issue

**Comment by Isaac-dot** [comment] 2022-08-14 07:02
> a temporary solution I found was to redirect an environment variable: PUB_CACHE= point to the same root directory
> 
> this temporarily solved
i met the same error could you describe your solution in detail

**Comment by Jordan-Nelson** [comment] 2022-08-19 20:20
Hey everyone - Apologies for the delay in an update. I just worked with a customer who reported this same issue on our Discord server. They were able to work around it by moving flutter and the project to the same drive. They only experienced this when Flutter was installed on their C drive and the project was on their F drive. It seems that this is only an issue on Windows when flutter is located on a different drive that the project that is being run. I am not sure if there is anything that we can do within Amplify to resolve this. It seems like this may be a limitation with Flutter and Windows.

If anyone is having this issue that is either not using Windows, or is using Windows but has confirmed that flutter is located on the same drive as the project that they are building, can you please share what OS you are seeing this on?

**Comment by Isaac-dot** [comment] 2022-08-22 16:14
> OS
: Window
sdk.dir=C:/Users/52304/AppData/Local/Android/Sdk
flutter.sdk=D:\\Flutter\\scr\\flutter

this is my OS and local.properties path. Is it possible to occure the error?
project location: D:\GITup\BILJ\donewitharq

**Comment by Isaac-dot** [comment] 2022-08-22 16:16
> a temporary solution I found was to redirect an environment variable: PUB_CACHE= point to the same root directory
> 
> this temporarily solved me

thank you for providing the solution, but could you share the detail step that you solve this error

**Comment by Jordan-Nelson** [comment] 2022-08-22 16:44
@Isaac-dot - What drive is the project you are trying to build located on?

**Comment by Isaac-dot** [comment] 2022-08-22 16:48
> @Isaac-dot - What drive is the project you are trying to build located on?

the project is located on D drive 
flutter is located on D drive as well

**Comment by Jordan-Nelson** [comment] 2022-08-22 17:59
@Isaac-dot - Can you share the full exception you are seeing? Thanks

**Comment by Isaac-dot** [comment] 2022-08-23 01:21
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':amplify_auth_cognito_android'.
> java.lang.IllegalArgumentException: this and base files have different roots: D:\GITup\BILJ\donewitharq\amplify_auth_cognito_android and C:\Users\52304\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\amplify_auth_cognito_android-0.6.5\android.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Exception: Gradle task assembleDebug failed with exit code 1
![屏幕截图 2022-08-23 112003](https://user-images.githubusercontent.com/72924991/186047459-626d54ed-7876-44d9-9be4-52ec8d3f20c4.png)

**Comment by Jordan-Nelson** [comment] 2022-08-23 01:54
@Isaac-dot - it looks like your pub cache is still located on your C drive. Can you try updating this to be the D drive since that is where you have flutter installed and where the app is located? See instructions under PUB_CACHE here: https://dart.dev/tools/pub/environment-variables

**Comment by Isaac-dot** [comment] 2022-08-23 05:32
> @Isaac-dot - it looks like your pub cache is still located on your C drive. Can you try updating this to be the D drive since that is where you have flutter installed and where the app is located? See instructions under PUB_CACHE here: https://dart.dev/tools/pub/environment-variables

thank you, i understand, but how can i change the pub cache location, i have been to the link that you provide, but i dont knnow how to set  a PUB_CACHE environment variable. could you explain that  thank you so much

**Comment by Jordan-Nelson** [comment] 2022-08-23 11:32
It will vary depending on what version of windows you are on. [Here](https://geekflare.com/system-environment-variables-in-windows/) is a pretty comprehensive guide on environment variables on Windows.

**Comment by Isaac-dot** [comment] 2022-08-23 12:15
@Jordan-Nelson  Sorry to bother you alot, i am new to flutter dart and AMS i am using windows 10. I create the PUB_CHACHE environment variables 
![image](https://user-images.githubusercontent.com/72924991/186154896-130b456b-5b11-4ca7-a392-0199dfe648c3.png)
but how to redirect to it

**Comment by Jordan-Nelson** [comment] 2022-08-23 12:25
I believe all you need to do is set that environment variable. Pub should use that to determine where to download dependencies. Try running the project again and see if you get the same error.

**Comment by Jordan-Nelson** [comment] 2022-08-23 12:52
If you see that there is one set referencing the C drive, yes.

You can run 'echo %PUB_CACHE%' from command prompt to see if the var is set.

**Comment by Jordan-Nelson** [comment] 2022-08-23 13:18
You will likely need to run 'flutter clean' and 'flutter pub get' to reinstall dependencies now that you have changed the location that they are downloaded.

You might also need to run 'flutter pub cache clean' or 'flutter pub cache repair'. You can read more about those here - https://dart.dev/tools/pub/cmd/pub-cache#reinstalling-all-packages-in-the-system-cache

**Comment by Jordan-Nelson** [comment] 2022-08-24 19:24
> Hey everyone - Apologies for the delay in an update. I just worked with a customer who reported this same issue on our Discord server. They were able to work around it by moving flutter and the project to the same drive. They only experienced this when Flutter was installed on their C drive and the project was on their F drive. It seems that this is only an issue on Windows when flutter is located on a different drive that the project that is being run. I am not sure if there is anything that we can do within Amplify to resolve this. It seems like this may be a limitation with Flutter and Windows.
> 
> If anyone is having this issue that is either not using Windows, or is using Windows but has confirmed that flutter is located on the same drive as the project that they are building, can you please share what OS you are seeing this on?

I will leave this issue open for a bit longer to see if anyone is having this issue that is unable to resolve it by updating the directory of their app, flutter, and/or pub. After that I will likely close this out since it doesn't appear to be specific to Amplify.

**Comment by akmalDev98** [comment] 2022-09-06 11:12
I faced the same issues. I found out that the problem is on the Flutter SDK. You may try to download new Flutter SDK and replace with the current one. It works for me.

**Comment by Jordan-Nelson** [comment] 2022-09-07 20:51
I am going to close this issue since this appears to be a limitation with Windows/Flutter/Android, and not specific to Amplify. For anyone facing this issues, see this comment: https://github.com/aws-amplify/amplify-flutter/issues/1689#issuecomment-1221062758

**Closed by Jordan-Nelson** 2022-09-07 20:51 UTC
Labels: pending-close-response-required, Build, pending-triage

**Comment by musabibnusiraj** [comment] 2022-11-30 11:18
I faced the same issue. I moved the app to the same flutter directory & build. It works for me.

**Comment by rocosrex** [comment] 2022-12-30 02:07
Thank you @Jordan-Nelson . I faced the same issue. I set pub_cache variable and my issue is solved.

**Comment by gajendrapandeya** [comment] 2023-11-28 11:25
I am using macos and i got. the issue

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':amplify_analytics_pinpoint'.
> Failed to create Jar file /Users/gazzu/.gradle/caches/jars-8/947c1318c2bb7024446bea1314544a0f/lint-model-31.1.0.jar.
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':amplify_analytics_pinpoint' of type org.gradle.api.Project.
   > Could not find method implementation() for arguments [project ':amplify_db_common'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
   > Could not find method implementation() for arguments [project ':amplify_secure_storage'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
   > Could not find method implementation() for arguments [project ':device_info_plus'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
   > Could not find method implementation() for arguments [project ':package_info_plus'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
   > Could not get unknown property 'android' for project ':amplify_analytics_pinpoint' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

BUILD FAILED in 1s
Exception: Gradle task assembleDebug failed with exit code 1
