### ISSUE TITLE
fetchUserAttributes function cause toomanyrequestexception

### ISSUE THREAD

**Issue by mettamdaica0909** [aws-amplify/amplify-flutter#4687] opened 2024-04-10 06:36 UTC
### Description

I'm using Amplify 1.6.1 to handle the authentication. Since the 1.6.1 version, I have gotten a ton of toomanyrequestexception errors when trying to fetch the user attributes via the fetchUserAttributes function. The version 0.6.0 is fine.
- Is there any update for fetchUserAttributes in the new version before 0.6.0 everything looks good. I can not find any update related to fetchUserAttributes in the release note.
- In the new version, Does Amplify use the cache when fetchUserAttributes is called? or hit the server for that info? 

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Version 1.6.1
Use fetchUserAttributes function will hit the server to get the info. This does not happen in version 0.6.0

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.16.4

### Amplify Flutter Version

1.6.1

### Deployment Method

Amplify CLI

**Comment by Equartey** [comment] 2024-04-10 17:05
Hi @mettamdaica0909, sorry to hear you ran into an issue during migration. 

Can you confirm if you're using the Authenticator UI component? Or are you using the Auth category directly?

**Comment by mettamdaica0909** [comment] 2024-04-11 08:27
I'm using the Auth category directly. I checked both version and seem there's an update for the fetchUserAttributes function.

 Ver 0.6.0 
`  @override
  Future<List<AuthUserAttribute>> fetchUserAttributes(
      {FetchUserAttributesRequest? request}) async {
    try {
      final List<Map<dynamic, dynamic>>? data =
          (await (_channel.invokeListMethod(
        'fetchUserAttributes',
        <String, dynamic>{
          'data': request != null ? request.serializeAsMap() : {},
        },
      )));
      if (data == null)
        throw AmplifyException(
            AmplifyExceptionMessages.nullReturnedFromMethodChannel);
      return formatFetchAttributesResponse(data);
    } on PlatformException catch (e) {
      throw castAndReturnPlatformException(e);
    }
  }`

 Ver 1.6.1
Future<List<AuthUserAttribute>> fetchUserAttributes({
    FetchUserAttributesOptions? options,
  }) async {
    final tokens = await stateMachine.getUserPoolTokens();
    final resp = await _cognitoIdp
        .getUser(
          cognito.GetUserRequest(
            accessToken: tokens.accessToken.raw,
          ),
        )
        .result;
    return [
      for (final attributeType in resp.userAttributes)
        attributeType.asAuthUserAttribute,
    ];
  }

My understanding is 1.6.1 version is hitting the server for the attributes via cognito.GetUserRequest. is that correct?

**Comment by mettamdaica0909** [comment] 2024-04-15 02:30
Hi @Equartey, Thanks for your quick response.

Using a network inspector, how many requests are made before you see this exception?
-> I did. But seems the network inspector can not detect the request in v0.6, it can detect the request in v1+. I think the network inspector can not detect the request that is executed in the native code.

There is also no cache. Each call to the API will perform a network request. This was also the behavior in V0.6.
-> It means the lib always performs a network request for the user's information. correct?

**Comment by mettamdaica0909** [comment] 2024-04-15 04:01
btw, can we change the limitation (120 requests per sec) to a higher value?

**Comment by Equartey** [comment] 2024-04-15 19:27
@mettamdaica0909 

> I did. But seems the network inspector can not detect the request in v0.6, it can detect the request in v1+. I think the network inspector can not detect the request that is executed in the native code.

I'm more interested in the amount of requests being sent from your V1 project. It's easiest to grab that info from web if you have that platform enabled in your project. Let us know how many requests you see and we can continue to debug.

> It means the lib always performs a network request for the user's information. correct?

Correct. This is by design. You're welcome to cache it yourself, as we will always fetch from remote when you call the API.

> btw, can we change the limitation (120 requests per sec) to a higher value?

Where are you seeing this limit?

**Comment by mettamdaica0909** [comment] 2024-04-22 04:00
Thanks @Equartey

> Correct. This is by design. You're welcome to cache it yourself, as we will always fetch from remote when you call the API.
I think this is all I need. In this case, I have to update the code logic to reduce the API calls.

**Comment by Equartey** [comment] 2024-04-23 19:41
@mettamdaica0909 No problem. I'm going to close this issue, please reach out again if you have any more questions.

**Closed by Equartey** 2024-04-23 19:41 UTC
Labels: question, pending-response, Investigating
