### ISSUE TITLE
Hosted UI sign in or sign out immediately after configuration causes app crash

### ISSUE THREAD

**Issue by mridboy96** [aws-amplify/amplify-flutter#3089] opened 2023-05-22 16:15 UTC
I have recently upgraded my flutter project to point to amplify_flutter 1.0.1
Unfortunately I am having an issue with regard to the signInWithWebUI functionality when logging the user through google or apple.

This issue is existing only for physical iOS devices.

Here is a brief about what is actually happening.

Device - iPhone 12 Pro (iOS version - 16.5)

When the user logs in using signInWithWebUI through google or apple and after the successful login, if the app is killed and opened again the entire app just crashes. This is happening only on an iOS physical device, However on the simulator devices and android devices it is working as expected without any crashes.

Another observation I made when I moved over to amplify_flutter 1.0.1 was, even with isPreferPrivateSession flag set to true, there is a browser redirection that is taking place on iOS devices when logging out. I was under the impression that the browser redirection should not happen if isPreferPrivateSession flag is set to true for iOS devices and the same is working as expected in 0.6.13 version of amplify.

Logs from firebase_crashlytics says 
Fatal Exception: FlutterError
UserCancelledException { "message": "The user cancelled the sign-in flow" }

I am adding my code logic here, would really like it if I could get some help here as I have been struggling for quite sometime now

```
/// aws_manager.dart - [signInUser]
Future<Tuple2<bool, String>> signInUser(
      {String username = '', String password = '', bool isSocialSignIn = false, String socialAuthProvider = ''}) async {
    try {
      SignInResult result = isSocialSignIn
          ? await Amplify.Auth.signInWithWebUI(
              provider: socialAuthProvider == 'google' ? AuthProvider.google : AuthProvider.apple,
              options: CognitoSignInWithWebUIOptions(isPreferPrivateSession: true))
          : await Amplify.Auth.signIn(
              username: username,
              password: password,
            );
      if (result.isSignedIn)
        return Tuple2(true, "User authenticated");
      else if (result.isSignedIn == false && result.nextStep != null) {
        if (result.nextStep?.signInStep == "CONFIRM_SIGN_IN_WITH_NEW_PASSWORD")
          return Tuple2(false, "New Password Required");
        return Tuple2(false, 'Something went wrong');
      } else
        return Tuple2(false, "Something went wrong");
    } on AuthException catch (error) {
      String errorMessage =
          _getAppropriateErrorMessage(error: error, isPasswordException: false, identityProvider: socialAuthProvider);
      return Tuple2(false, errorMessage);
    }
  }

/// app_navigator_manager.dart
/// This is the method that executes once the app is opened again 
/// and here in case the user has logged in but not registered completely
/// I am logging out the user and when that happens the application crashes indefinately.
void showAppropriateScreen({required BuildContext context}) async {
    if (KeyValueStoreManager.getBool(key: 'hideOnboardingScreen')) {
      final sessionInformation = await AwsManager.shared.fetchCurrentUserSessionInfo();
      if (sessionInformation.item1 == false && sessionInformation.item2 == null) {
        _showUserLoginScreen(context: context);
      } else {
        // Check if social login registration is completed or not.
        bool isSocialLoginIncomplete = KeyValueStoreManager.getBool(key: 'isSocialLoginInProgress');
        if (isSocialLoginIncomplete) {
          await AwsManager.shared.signOutUser();
          _showUserLoginScreen(context: context);
          return;
        }
        _showMainHomeScreen(context: context);
      }
    } else
      _showAppOnboardingScreen(context: context);
  }
```

Additionally I am also adding a screen recording of what happens on opening the app again after the user has logged in using google / apple.

https://github.com/aws-amplify/amplify-flutter/assets/38466433/e5f68c89-9712-474a-b418-8f4f9d6e3b90

Any help towards this would be appreciated. Thank you!

**Comment by Jordan-Nelson** [comment] 2023-05-22 18:48
@mridboy96 can you share the definition of `AwsManager.shared.signOutUser()`?

**Comment by mridboy96** [comment] 2023-05-23 03:27
Sure can do!

On another note I was initaially getting a revokeTokenException here because my userpool was not having token revocation enabled, once that was enabled it was fine.
Here is the full code for user sign out.
```
/// aws_manager.dart
/// [userSignOut]
Future<void> signOutUser() async {
    try {
      final result = await Amplify.Auth.signOut();
      if (result is CognitoCompleteSignOut) {
        safePrint('Sign out completed successfully');
      } else if (result is CognitoPartialSignOut) {
        safePrint(result.revokeTokenException!);
      } else if (result is CognitoFailedSignOut) {
        safePrint('Error signing user out: ${result.exception.message}');
      }
    } on AuthException catch (authError) {
      safePrint(authError);
      throw Exception(authError);
    }
  }
```

**Comment by Jordan-Nelson** [comment] 2023-05-23 17:09
Thanks @mridboy96. I spent some time trying to reproduce the issues you mentioned.

I could not reproduce the app crash. However, I wanted to ask if you are you launching the app in debug mode. If you launch the app in debug mode, I believe this would be expected and not related to Amplify. If you are only seeing this in debug mode on physical iOS devices, can you please try to reproduce it in release mode?

I was able to reproduce the issue with the browser window displaying on sign out even when `preferPrivateSession` is true. I will look into this.

**Comment by mridboy96** [comment] 2023-05-23 17:20
Thanks for the quick update!

I have tried it on my iOS simulator on debug mode and it works completely fine.
I had initially given a test build for testing which was not in debug mode (Since we need to build the app before distributing it for testing, I am guessing it would already be in release mode?) and that was when we first encountered the crash of the application.

Another point I would actually like to add here is, when you run the flutter app on a physical device connected to the local setup it does not crash where as when the app is actually built and tried on the device independently it crashes (This is the only situation where it crashes)
 
However I will explicitly try creating a flutter build in release mode (using the flag) and distribute the app for development and try it on my iOS device again and see if the app is still crashing for this use case. Will update back here once I try it out

Thank you !

**Comment by Jordan-Nelson** [comment] 2023-05-23 17:45
Okay. If you have a physical iOS device to test on, it might be helpful to see if you can repro this without distributing it via test flight (or whatever you are using for distribution) just to simplify the repro steps. If you can only repro it after distributing it for testing, please let me know.

**Comment by mridboy96** [comment] 2023-05-23 18:14
So these are the steps I followed and unfortunately ended up with the application crashing.

#### Create flutter build in release mode
```
flutter build ios -t lib/main_dev.dart --release
```

#### Create XCode archive
```
Open XCode -> Product -> Archive
```

#### Once the archiving was done, I distributed IPA file for development and installed onto my physical device.

After I logged in to the app and reproduced the use case, it still ended up with a crash.

**Comment by Jordan-Nelson** [comment] 2023-05-23 18:25
Okay thanks. If connect your physical iOS device to your machine and run `flutter build ios --release`, can you reproduce this? Or is it only after archiving/distributing?

**Comment by Jordan-Nelson** [comment] 2023-05-23 19:37
Alright. I have been unable to reproduce this. I would like to ask a few follow up questions so that I can narrow down what is causing the crash.
1. If you launch the app without having a user signed in, there is no crash, correct?
2. If you launch the app with a user signed in with username/password that is in the same state (logged in but not registered completely), there is no crash, correct?
3. If you comment out `await AwsManager.shared.signOutUser();`, does the app still crash?
4. The crash occurs for both Sign in with Apple and Sign in with Google, correct?

**Comment by mridboy96** [comment] 2023-05-23 20:08
1. The app does not crash if there is no user signed in - Correct

2. If the app is launched again with a loggedIn session present through native username/password sign in the app does not crash - Correct

3. When I was trying to figure out what the issue was, I narrowed it down to the code line mentioned by you - 
```await AwsManager.shared.signOutUser();``` and the app does not crash if I comment out this codeline.
Additionally since I am calling ```Amplify.Auth.getPlugin(<my-auth-plugin>).fetchAuthSession();``` when the app is launched again this returns the ```CognitoAuthSession``` (Naturally as the user is not signed out).
I have added the response for the same in the end for reference. (I logged it to crashlytics as I was running it in release mode)

4. The crash occurs for both sign in with google and sign in with apple - Correct.

####Response from ```fetchAuthSession```

```
flutter_error_exception
Exception: { "isSignedIn": true, "userSub": "AWSResult [6cecd2ef-3d67-4c76-b20b-bea1c9b81179, null, AWSResultType.success]", "userPoolTokens": "AWSResult [Instance of 'CognitoUserPoolTokens', null, AWSResultType.success]", "credentials": "AWSResult [null, InvalidAccountTypeException {\n \"message\": \"No identity pool registered for this account\",\n \"recoverySuggestion\": \"Register an identity pool using the CLI\"\n}, AWSResultType.error]", "identityId": "AWSResult [null, InvalidAccountTypeException {\n \"message\": \"No identity pool registered for this account\",\n \"recoverySuggestion\": \"Register an identity pool using the CLI\"\n}, AWSResultType.error]" }
```

**Comment by Jordan-Nelson** [comment] 2023-05-24 21:13
@mridboy96 canyou share your amplify config (you can remove sensitive data or app identifying info such as API keys and app IDs)?

**Comment by Jordan-Nelson** [comment] 2023-05-24 21:15
Fyi - I have a fix up for the browser showing on sign out when preferredPrivateSession is true. I am going to remove the bug label for now while I continue to try to repro the crash.

**Comment by mridboy96** [comment] 2023-05-25 03:33
Sure!
Here is my amplify configuration given below
```
// AWS User Pool Configurations
  static String get amplifyConfiguration => jsonEncode(
        {
          "UserAgent": "aws-amplify-cli/2.0",
          "Version": "1.0",
          "auth": {
            "plugins": {
              "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {"Default": {}},
                "CognitoUserPool": {
                  "Default": {
                    "PoolId": dotenv.env['POWL_COGNITO_USER_POOL_ID'].toString(),
                    "AppClientId": dotenv.env['POWL_COGNITO_APP_CLIENT_ID'].toString(),
                    "Region": dotenv.env['POWL_COGNITO_REGION'].toString()
                  }
                },
                "Auth": {
                  "Default": {
                    "OAuth": {
                      "WebDomain": dotenv.env['POWL_COGNITO_WEB_DOMAIN'].toString(),
                      "AppClientId": dotenv.env['POWL_COGNITO_APP_CLIENT_ID'].toString(),
                      "SignInRedirectURI": "myapp://",
                      "SignOutRedirectURI": "myapp://",
                      "Scopes": ["email", "openid", "profile"]
                    },
                    "authenticationFlowType": "USER_SRP_AUTH"
                  }
                }
              }
            }
          }
        },
      );
```
Information on the browser redirection sounds good to me, is there anything different I should do in order to ensure the browser redirection is not coming up, because I have feeling the crash is maybe happening because of this ?
maybe if the redirection does not happen, the crash in turn might not happen? (just thinking out loud here, might be wrong.)

**Comment by Jordan-Nelson** [comment] 2023-05-25 13:33
How was the Cognito backend created? Was it created with the Amplify CLI/Studio, or is this an existing backend created without Amplify?

**Comment by mridboy96** [comment] 2023-05-25 14:02
The cognito user pool backend resources was created manually. 
So we are currently using an existing user pool resource.

**Comment by Jordan-Nelson** [comment] 2023-05-25 17:46
Okay thanks for all the info @mridboy96.

I have been able to reproduce this with the following steps:
- create an app (with cli, for example) w/ google sign in. Can use the Authenticator UI for sign in.
- call `Amplify.Auth.signOut()` immediately after amplify configuration
- run the app on a physical iPhone in release mode
- sign in with google
- kill the app
- open the app

I can reproduce this with or without `preferPrivateSession` set to true. However, when `preferPrivateSession` is true _and_ the fix that is linked above is applied, there is no crash.

The fix above seems to fix this for your scenario. The bug will still be present when `preferPrivateSession` is false though.

I will look to get that PR in and determine what the root cause of the crash is to fix it for all cases.

**Comment by mridboy96** [comment] 2023-05-25 18:04
Im not sure if I understood what you meant when you said "the fix that is linked above is applied"
Does it mean that I need to wait for the PR #3099 to be approved and then I should go ahead and use that in turn because essentially this PR would make sure that the browser sign out redirection does not happen based on the code I just saw and since the browser redirection does not happen, the app would not crash correct?
Am I understanding this right?

Apologies if I have misunderstood something here.

**Comment by Jordan-Nelson** [comment] 2023-05-25 19:06
Yes, that is correct. From my test https://github.com/aws-amplify/amplify-flutter/pull/3099 will address this when `preferPrivateSession` is set to true.

Once #3099 is merged it will be included in the next release so you will be able to upgrade to the latest version to get the fix.

I will likely keep this issue open until it is fully resolved (regardless of `preferPrivateSession` setting)

**Comment by mridboy96** [comment] 2023-05-25 19:27
Thats great !!

Thanks a lot for this quick fix. Will use this PR for the time being and check it.

Just to confirm one other thing, when the merge is done and the new version is released, it will be part of the 1.1.x release right?
Currently I am not on the latest release but on the 1.0.1 release

**Comment by Jordan-Nelson** [comment] 2023-05-25 19:31
Yes, it would be included in 1.1.x. 1.1.x requires flutter 3.10 / dart 3. If you have blockers to upgrading to 1.1 let us know.

**Comment by mridboy96** [comment] 2023-05-25 19:38
So I have upgraded to the latest flutter version and I also tried changing my dart sdk environment to >=3.0.0 <4.0.0
But when I ran ```flutter pub get``` I got some error which I think is mostly to do with resolving other package versions before I can bring amplify to the latest.
I will try to resolve my other packages and in case I am still blocked, I will maybe let you know

Thank you!

**Comment by dnys1** [comment] 2023-06-02 00:18
This fix for this has been released. Can you confirm it resolves your issue?

**Comment by mridboy96** [comment] 2023-06-02 02:16
Until now I was actually using the PR based fix for this.
Now that it has been merged, will maybe pick this up and check for both isPreferPrivateSession set to true / false and will confirm here.
Thank you!

**Comment by mridboy96** [comment] 2023-06-02 08:31
Just checked now and it is working as expected. 
My flutter application is currently using the PR fix that was added quite sometime back as I needed an immediate fix for it.
Will make sure to use the main branch which has the fix that has been merged or if the new version is available will directly use it for my next app build
Thanks for the fix!

**Comment by Jordan-Nelson** [comment] 2023-06-02 10:57
@mridboy96 thanks for letting us know. I'll close this issue now.

**Closed by Jordan-Nelson** 2023-06-02 10:57 UTC
Labels: bug, Auth
