### ISSUE TITLE
DataStore  publishing wrong state notifications onto Amplify's Hub. NetworkStatusEvent.active = false even with stable network

### ISSUE THREAD

**Issue by uzairleo** [aws-amplify/amplify-flutter#2680] opened 2023-02-18 19:12 UTC
### Description

Hello there amplify team the HubChannel.datastore is returning some strange data even the network is stable but still the networkstatusEvent.active is false due to which i am unable to fetch any data from datastore , and when this happens then appsync is also not going to work since the connection between datastore local and and cloud is unable to established everything is implemented according to docs , so can you please help me by suggesting some workaround thats functional.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.8

### Amplify Flutter Version

0.6.12

### Deployment Method

Amplify CLI

**Comment by HuiSF** [comment] 2023-02-22 17:05
Closing as a duplicate of https://github.com/aws-amplify/amplify-flutter/issues/2652

**Closed by HuiSF** 2023-02-22 17:05 UTC
Labels: duplicate, DataStore, pending-response
