### ISSUE TITLE
Getting 'Error: Invalid argument' when querying data with predicate containing enum.

### ISSUE THREAD

**Issue by EmmanuelOgbewe** [aws-amplify/amplify-flutter#722] opened 2021-07-15 05:29 UTC
**Describe the bug**
I have a schema that contains an enum. When querying this data and providing an enum as a predicate I receive an error saying Invalid argument. 

**Expected behavior**
The enum provided as a predicate matches the enum type used in the schema. I do not expect to get the error.

**Screenshots**
ActivityNotification model contains enum NotificationType.

![Screen Shot 2021-07-15 at 1 21 35 AM](https://user-images.githubusercontent.com/29666179/125733346-9d27a326-3a1e-4b85-82f7-ca447b257f9f.png)

Querying for recipient notifications matching the type NotificationType.FriendRequest
![Screen Shot 2021-07-15 at 1 20 42 AM](https://user-images.githubusercontent.com/29666179/125733254-e54050c4-4d5e-443f-a5e5-dd35dd9c6644.png)

Error received is `Invalid argument: Instance of 'NotificationType'`

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android
[X] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.4 19E266
    darwin-x64, locale en-US)
    • Flutter version 2.0.6 at /Users/emmanuelogbewe/flutter
    • Framework revision 1d9032c7e1 (3 months ago), 2021-04-29
      17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android
    SDK version 29.0.3)
    • Android SDK at /Users/emmanuelogbewe/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android
      Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • 2A493D3E-54BB-43AA-94CE-B0148EC28830
      • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Chrome (web)       • chrome
      • web-javascript • Google Chrome 91.0.4472.114

• No issues found!```

</details>

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Simulator IPhone 11
 - OS: [e.g. iOS8.1] 13
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by HuiSF** [comment] 2021-07-15 17:20
From the error message, it looks like the data is being sent from native side to flutter side contains data format other than json.

Which platform did you produce this error on please? @EmmanuelOgbewe

**Comment by EmmanuelOgbewe** [comment] 2021-07-15 18:05
Error produced on IOS. @HuiSF

**Comment by HuiSF** [comment] 2021-07-16 18:07
Thanks @EmmanuelOgbewe ! This issue is reproducible on my end, I will investigate and get back to you.

**Comment by HuiSF** [comment] 2021-07-16 19:46
This issue is caused by [the method `serializedDynamicValue`](https://github.com/aws-amplify/amplify-flutter/blob/90074b33f838051bb40c072805889e35e03297e0/packages/amplify_datastore_plugin_interface/lib/src/types/query/query_field_operators.dart#L55-L62) in `query_field_operators` not having a appropriate handling of serializing enum type values. I will look into it and try to find a solution to address this issue.

**Comment by EmmanuelOgbewe** [comment] 2021-07-18 21:37
Thank you! @HuiSF

**Comment by HuiSF** [comment] 2021-07-28 16:46
Hi @EmmanuelOgbewe the fix for this issue has been release along with version `0.2.1`. Please update the library to get the fix, and feel free to follow up if you encounter any issues. Thanks!

**Closed by HuiSF** 2021-07-28 16:46 UTC
Labels: DataStore, pending-release

**Comment by EmmanuelOgbewe** [comment] 2021-07-29 05:30
@HuiSF Thank you! ! Most definitely will.
