### ISSUE TITLE
Error while configuring storage category

### ISSUE THREAD

**Issue by perrydev17** [aws-amplify/amplify-flutter#5335] opened 2024-08-21 13:09 UTC
### Description

hi, I am getting an error when trying to add the storage plugin into the flutter app, I confirm auth is working as expected, but storage is erroring out

  amplify_flutter: ^2.0.0
  amplify_auth_cognito: ^2.0.0
  amplify_authenticator: ^2.0.0
  amplify_storage_s3: ^2.0.0

this is the code in main.dart
<img width="526" alt="flutter-error" src="https://github.com/user-attachments/assets/3005964d-efde-4010-aa5d-2d335804a28f">

in amplifyconfiguration.dart I have
`  "storage":{
    "aws_region":"us-east-1",
    "bucket_name":"xxx" <- the bucket was created during amplify gen2 setup
  },`

and this is the error crashing the app
<img width="549" alt="flutter-error2" src="https://github.com/user-attachments/assets/be904cff-cfea-4c97-aeb6-da31ccff56d7">

thanks in advance!

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Steps to Reproduce

app crash and can't be loaded upon the line addPlugin(storage), I have tried both method addPlugins and addPlugin

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.4.1

### Amplify Flutter Version

^2.0.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment] 2024-08-21 14:12
@perrydev17 - It look like the stack trace is from a browser. Are you able to reproduce this on any other platform? If so, can your provide the stack trace from that platform?

**Comment by perrydev17** [comment] 2024-08-24 11:18
hi @Jordan-Nelson also not able to run in other platforms (Android)

`amplify_secure_storage-0.5.4/android/src/main/kotlin/com/amazonaws/amplify/amplify_secure_storage/AmplifySecureStoragePlugin.kt: (49, 16): Class 'kotlin.Result' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.`

**Comment by Jordan-Nelson** [comment] 2024-08-26 14:15
@perrydev17 Before running on Android you will need to follow the Android platform setup steps here: https://docs.amplify.aws/flutter/start/platform-setup/#android

I am not able to reproduce the error you are seeing on web. Can you provide the following info:
- Your full `amplify_outputs.dart` file (with sensitive or app specific info redacted)
- The output of `dart pub deps -s compact`

**Comment by NikaHsn** [comment] 2024-10-15 22:32
I'm closing this issue as we did not hear back. Please feel free to open a new issue if the issue is not resolved.

**Closed by NikaHsn** 2024-10-15 22:32 UTC
Labels: question, pending-close-response-required, storage, not-reproducible, pending-community-response
