### ISSUE TITLE
Bug: fetchAuthSession() returns signed in even when user doesn't exist

### ISSUE THREAD

**Issue by bibaswan-bhawal** [aws-amplify/amplify-flutter#3292] opened 2023-06-22 07:28 UTC
### Description

Calling Amplify.Auth.fetchAuthSession() returns isSignedIn true even if the user has been deleted from the coginto admin dashboard. 

```
flutter: {
  "isSignedIn": true,
  "userSub": "AWSErrorResult<String, UserNotFoundException> {\n  \"exception\": {\n    \"message\": \"User does not exist.\",\n    \"underlyingException\": \"UserNotFoundException {\\n  message=User does not exist.,\\n}\"\n  },\n  \"stackTrace\": \"#0      HttpOperation.deserializeOutput (package:smithy/src/http/http_operation.dart:316:7)\\n<asynchronous suspension>\\n#1      CancelableCompleter.complete.<anonymous closure> (package:async/src/cancelable_operation.dart:425:16)\\n<asynchronous suspension>\\n\"\n}",
  "userPoolTokens": "AWSErrorResult<CognitoUserPoolTokens, UserNotFoundException> {\n  \"exception\": {\n    \"message\": \"User does not exist.\",\n    \"underlyingException\": \"UserNotFoundException {\\n  message=User does not exist.,\\n}\"\n  },\n  \"stackTrace\": \"#0      HttpOperation.deserializeOutput (package:smithy/src/http/http_operation.dart:316:7)\\n<asynchronous suspension>\\n#1      CancelableCompleter.complete.<anonymous closure> (package:async/src/cancelable_operation.dart:425:16)\\n<asynchronous suspension>\\n\"\n}",
  "credentials": "AWSErrorResult<AWSCredentials, SessionExpiredException> {\n  \"exception\": {\n    \"message\": \"The AWS credentials could not be retrieved\",\n    \"recoverySuggestion\": \"Invoke Amplify.Auth.signIn to re-authenticate the user\",\n    \"underlyingException\": \"NotAuthorizedException {\\n  message=Invalid login token. Token expired: 1687418069 >= 1686677543,\\n}\"\n  },\n  \"stackTrace\": \"#0      HttpOperation.deserializeOutput (package:smithy/src/http/http_operation.dart:316:7)\\n<asynchronous suspension>\\n#1      CancelableCompleter.complete.<anonymous closure> (package:async/src/cancelable_operation.dart:425:16)\\n<asynchronous suspension>\\n\"\n}",
  "identityId": "AWSErrorResult<String, SessionExpiredException> {\n  \"exception\": {\n    \"message\": \"The AWS credentials could not be retrieved\",\n    \"recoverySuggestion\": \"Invoke Amplify.Auth.signIn to re-authenticate the user\",\n    \"underlyingException\": \"NotAuthorizedException {\\n  message=Invalid login token. Token expired: 1687418069 >= 1686677543,\\n}\"\n  },\n  \"stackTrace\": \"#0      HttpOperation.deserializeOutput (package:smithy/src/http/http_operation.dart:316:7)\\n<asynchronous suspension>\\n#1      CancelableCompleter.complete.<anonymous closure> (package:async/src/cancelable_operation.dart:425:16)\\n<asynchronous suspension>\\n\"\n}"
}
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Sign in using  ```Amplify.Auth.signIn()```
2. Close app and delete user from coginto dashboard
3. Open app and call Amplify.Auth.fetchAuthSession()

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.4

### Amplify Flutter Version

1.2.0

### Deployment Method

Amplify CLI

**Comment by bibaswan-bhawal** [comment] 2023-06-22 16:48
If the user doesn't exist then how can they be signed in. It should return false and in v0 it used to return false.

**Comment by dnys1** [comment] 2023-06-22 16:55
Understood. I will investigate to see why the behavior differs from v0.

**Comment by dnys1** [comment] 2023-06-23 15:19
I'm observing the same behavior in v0. 

Let me discuss with my team and see what we can do here to perhaps improve the developer experience or improve our documentation. I will get back to you by early next week.

**Comment by bibaswan-bhawal** [comment] 2023-06-28 08:41
Any updates on this?

**Comment by dnys1** [comment] 2023-06-28 15:00
Hi @bibaswan-bhawal, I apologize I don't have any update. We are still investigating the behavior here. Thank you so much for your patience.

**Comment by krosiek** [comment] 2023-07-26 13:13
Logging-in deleted user does not make any sense.
Let us know if we should perform additional checks or the bug will be fixed, please.

**Comment by dnys1** [comment] 2023-07-31 22:06
Note that this is similar to https://github.com/aws-amplify/amplify-flutter/issues/2914. In the case where a refresh token has terminally expired, or in the case where a user is deleted, they will not be automatically signed out. It is the responsibility of the developer to check the token validity.

We are still investigating how this can be improved, but as it stands, I would recommend always checking the token validity if you are currently using the `isSignedIn` for understanding terminal cases such as this.

I understand the confusion around the `isSignedIn` flag, but we are not considering this a bug in behavior. The flag conveys whether or not a call to `Amplify.Auth.signIn` has been performed. The library will not automatically sign out a user - it is the responsibility of the developer to do so.

**Comment by dnys1** [comment] 2023-07-31 22:13
Another option is to listen to the Amplify Hub for sessionExpired events and reactively sign out the user.

```dart
Amplify.Hub.listen(HubChannel.Auth, (event) {
  if (event.type == AuthHubEventType.sessionExpired) {
    Amplify.Auth.signOut();
  }
});
```

**Comment by Jordan-Nelson** [comment] 2023-08-30 23:50
Hi folks - I am going to close this as a duplicate of https://github.com/aws-amplify/amplify-flutter/issues/2914. Please see that issue, as well as [this comment](https://github.com/aws-amplify/amplify-flutter/issues/2914#issuecomment-1699989645) for workarounds. Thanks.

**Closed by Jordan-Nelson** 2023-08-30 23:50 UTC
Labels: duplicate, Question, Auth, Investigating
