### ISSUE TITLE
[CRITICAL] UnknownException(message: Unexpected error occurred with message: Unable to get valid sign in session from the end user.)

### ISSUE THREAD

**Issue by brunovsiqueira** [aws-amplify/amplify-flutter#1042] opened 2021-11-08 15:11 UTC
Hi there.

We have some users in production environment getting the following error:

`UnknownException(message: Unexpected error occurred with message: Unable to get valid sign in session from the end user., recoverySuggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Users/caravath/Development/Projects/BTGPass/Develop/BTGMaisBusiness/ios/Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 80, underlyingException: null)`

Stacktrace:
`#0      AmplifyAuthCognitoMethodChannel.signIn (package:amplify_auth_cognito/method_channel_auth_cognito.dart:122)
<asynchronous suspension>
#1      AmplifyAuthCognito.signIn (package:amplify_auth_cognito/amplify_auth_cognito.dart:69)
<asynchronous suspension>
#2      AuthService.signIn (package:btg_login/src/services/auth_service.dart:25)
<asynchronous suspension>
#3      LoginViewModel.login (package:btg_login/src/viewmodels/login_viewmodel.dart:204)
<asynchronous suspension>
#4      _LoggedUser.build.<anonymous closure> (package:btg_login/src/pages/login_main_page.dart:83)
<asynchronous suspension>
`

Seems that, after getting this exception, the same user gets this:

`InvalidStateException(message: There is already a user which is signed in. Please log out the user before calling showSignIn., recoverySuggestion: Operation performed is not a valid operation for the current auth state, underlyingException: null)`

Which points that, even getting the "UnknowException" in signIn method, Amplify signs in the user.

One thing to notice is that we are forcing sign out (calling signOut method) when we got a not handled AuthException. Also, we force signOut when Amplify returns SessionExpiredException or InvalidStateException when calling fetchAuthSession method.

Can somebody help to explain why are we getting this strange exception? Shouldn't we at least get a more detailed exception?

I could not reproduce yet, I can just see these erros in my application logs for differents iOS devices.

**Comment by brunovsiqueira** [comment] 2021-11-09 19:58
@Amplifiyer any updates on this?

**Comment by fdarsot** [comment] 2021-11-12 00:24
@brunovsiqueira im having the exact same issue in production as well. what version of the package are you using?

@Jordan-Nelson @haverchuck can someone take a look? its a pressing issue for our users. it's messing up our caching

**Comment by dnys1** [comment] 2021-11-17 17:27
Hi @brunovsiqueira - can you share your auth configuration? Which methods do you allow users to login with? Specifically, do you support Hosted UI as well as email/username/password flows?

Can you also share the code you're using so we may attempt to reproduce this issue?

**Comment by brunovsiqueira** [comment] 2021-11-19 13:28
Auth configuration:
`String amplifyConfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "${getPoolIdForEnv()}",
                        "AppClientId": "${getAppClientIdForEnv()}",
                        "Region": "${getRegionForEnv()}"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
               
            }
        }
    }
}''';`

This is the only method my users sign in:
`await Amplify.Auth.signIn(
        username: username.trim(),
        password: password.trim(), // default password : BTGP4ctual!
        options: CognitoSignInOptions(clientMetadata: metadata),
 );`

We don't support Hosted UI.

Is there any more code do you want me to share with you?

**Comment by brunovsiqueira** [comment] 2021-11-19 14:25
@dnys1 
We are using:
```yaml
amplify_auth_cognito: 0.2.4
amplify_core: 0.2.4
amplify_flutter: 0.2.4
```

Auth configuration:

```json
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "${getPoolIdForEnv()}",
                        "AppClientId": "${getAppClientIdForEnv()}",
                        "Region": "${getRegionForEnv()}"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
               
            }
        }
    }
}
```


This is the only method my users sign in:
```dart
await Amplify.Auth.signIn(
        username: username.trim(),
        password: password.trim(), 
        options: CognitoSignInOptions(clientMetadata: metadata),
 );
```

We don't support Hosted UI.

Is there any more code do you want me to share with you?

**Comment by fdarsot** [comment] 2021-11-28 22:35
@Jordan-Nelson @haverchuck  @dnys1 Im having the same issue. this is really critical to us as like i mentioned before it's messing up our caching.

do we have any progress on this? can this issue be escalated?

**Comment by brunovsiqueira** [comment] 2021-11-29 06:55
Any updates?

**Comment by dnys1** [comment] 2021-11-29 15:48
@brunovsiqueira @fdarsot - sorry for missing your responses. Are you guys both building your own configurations? 

@fdarsot - can you confirm that your code is similar, i.e. you are forcing sign out of users in exception cases?

**Comment by fdarsot** [comment] 2021-11-29 22:10
@dnys1 the code that @brunovsiqueira shared is very similar to mine yes.

and we do have an identity pool as well, but i dont believe we're using it. we are using the User pool though.

**Comment by brunovsiqueira** [comment] 2021-12-17 22:23
It is still happening in production.
Any updates? It is urgente since we have users experiencing this is issue and complaining about it.

**Comment by dnys1** [comment] 2021-12-17 23:45
Hi @brunovsiqueira - sorry for the lack of updates.

I haven't been able to reproduce it yet or gather any more insight. Are you able to provide any more details such as full client logs, etc.? Would you be able to open an issue with the iOS team with any and all information which could help them deduce the problem? They may have more insight as to what is going on. Thanks, and sorry again.

https://github.com/aws-amplify/amplify-ios/issues/new?assignees=&labels=&template=bug_report.yaml

**Comment by brunovsiqueira** [comment] 2021-12-20 12:27
@dnys1 in my first issue comment I have provided all the logs I have. I am going to open an issue in the iOS team Amplify.

**Comment by brunovsiqueira** [comment] 2022-01-25 15:04
Any updates?
@fdarsot have you figured something out?

**Comment by dnys1** [comment] 2022-01-25 15:57
Hi @brunovsiqueira - unfortunately, I do not have any updates at the moment. Were you able to make a ticket for the iOS team? It's very possible they have more information since I suspect this issue originates deep in their library.

**Comment by hpop** [comment] 2022-01-28 18:06
Hey,

this is happening on my phone as well. Interestingly it seems that I am the only one in our team that faces this error. @dnys1  Let me know if I can somehow help investigate it.

**Comment by brunovsiqueira** [comment] 2022-01-28 18:24
Maybe with @hpop help we can reproduce and solve this issue. Which device are you testing it @hpop?


@dnys1 I tried to open this issue on Amplify iOS github but the "Submit new issue" button is always disabled so I can't open it. Can you help me opening it?

<img width="1032" alt="Screen Shot 2022-01-28 at 15 22 55" src="https://user-images.githubusercontent.com/18200284/151601052-98ab9d82-6460-435d-be2b-4f07a8b45288.png">

**Comment by hpop** [comment] 2022-01-29 14:11
The device is an iPhone 12 Pro Max.
I debugged a bit more and found the original Error in `AuthorizationProviderAdapter+SignedInSession.swift:62`

```
Error Domain=com.amazonaws.AWSCognitoIdentityProviderErrorDomain Code=37 "(null)" UserInfo={__type=UserNotFoundException, message=User does not exist.}
``` 

I am not sure but it is possible, that I still have a session of a user that I have deleted in Cognito.

**Comment by hpop** [comment] 2022-02-04 09:42
For now, this is my workaround:

```
    try {
      AuthSession res = await Amplify.Auth.fetchAuthSession(
        options: CognitoSessionOptions(getAWSCredentials: true),
      );
      return (res as CognitoAuthSession);
    } on UnknownException catch (e) {
      await Amplify.Auth.signOut();
    }
```

**Comment by Jordan-Nelson** [comment] 2022-03-08 20:09
@hpop - are you able to consistently reproduce this, or is it also intermittent for you?

@brunovsiqueira - The "Submit new issue" button will be disabled if all the required fields are not filled in. Have you filled in all the required fields?

**Comment by brunovsiqueira** [comment] 2022-04-01 18:42
No, I haven't been able to reproduce it and it's been a longe time since I saw the last log with this Exception. If it happens again I'll let you guys know.

**Comment by dnys1** [comment] 2022-04-04 23:46
Thanks for the update @brunovsiqueira. I'm closing this ticket for the time being as we're unable to reproduce it and don't have enough context to investigate further. Please feel free to re-open as needed.

**Closed by dnys1** 2022-04-04 23:46 UTC
Labels: Auth, pending-triage
