### ISSUE TITLE
IOS(14.2, 14.3) frozen screen when auth with WebUI

### ISSUE THREAD

**Issue by Ekoios-Teddy** [aws-amplify/amplify-flutter#2766] opened 2023-03-21 16:46 UTC
### Description

I'm working for auth with google, apple. I'm developing with ios simulator version 16.0 and it's working. So I built for testing with real devices IOS (`14.2`, `14.3`, `14.7`, `15.5`) but it not working on `14.2` and `14.3`. I don't know why it happen and i will show you my environment and sample code.
<img width="905" alt="Screenshot 2023-03-21 at 23 41 08" src="https://user-images.githubusercontent.com/83799773/226680664-a9c6ecb2-7cf2-4dfe-9e0e-32050c8a75bf.png">
<img width="905" alt="Screenshot 2023-03-21 at 15 53 26" src="https://user-images.githubusercontent.com/83799773/226680667-80fa7697-aadd-46bd-9e2b-f3483bee349a.png">
<img width="906" alt="Screenshot 2023-03-21 at 15 53 15" src="https://user-images.githubusercontent.com/83799773/226680673-9c3e6902-5164-43e4-9979-a7b7e9edaa76.png">
<img width="909" alt="Screenshot 2023-03-21 at 15 52 51" src="https://user-images.githubusercontent.com/83799773/226680677-f65f8b35-98df-415e-bc2f-4ebb78e02324.png">

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Open Xcode and run build
2. After app launched, click to handle login with google
3. Screen is frozen and terminal show error.

### Screenshots

<img width="624" alt="Screenshot 2023-03-21 at 23 41 58" src="https://user-images.githubusercontent.com/83799773/226681250-5a8a6376-6000-4512-b96d-9dff7efc8a18.png">
<img width="756" alt="Screenshot 2023-03-21 at 23 41 35" src="https://user-images.githubusercontent.com/83799773/226681274-c11085e5-569b-4e2a-bd49-0b3512c8d7bd.png">
<img width="915" alt="Screenshot 2023-03-21 at 23 41 23" src="https://user-images.githubusercontent.com/83799773/226681292-3a49c459-c445-4ba2-9248-58c61413c627.png">
<img width="905" alt="Screenshot 2023-03-21 at 23 41 08" src="https://user-images.githubusercontent.com/83799773/226681315-acc17360-f891-4b8d-8b82-8dcef55ed1e4.png">
<img width="905" alt="Screenshot 2023-03-21 at 15 53 26" src="https://user-images.githubusercontent.com/83799773/226681342-4fe7b110-d66c-4539-b236-1eb27afd9237.png">
<img width="906" alt="Screenshot 2023-03-21 at 15 53 15" src="https://user-images.githubusercontent.com/83799773/226681358-56b72b7e-6a46-445a-8773-2d4c79fb39d5.png">
<img width="536" alt="Screenshot 2023-03-21 at 23 45 44" src="https://user-images.githubusercontent.com/83799773/226681627-cbfd2702-fe88-4893-bad8-97f959541a44.png">

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.6

### Amplify Flutter Version

1.0.0.nex-.6

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment] 2023-03-21 19:09
Hi @Ekoios-Teddy, I believe this could be an issue with Xcode itself after reading this thread: https://forums.swift.org/t/xcode-14-1-withcheckedcontinuations-body-will-run-on-background-thread-in-case-of-starting-from-main-actor/60953/18

Could you try updating your Xcode installation to the latest version (14.2) and try to reproduce the problem again? So far I have not been able to reproduce it, although I am running Xcode 14.1.

**Comment by Ekoios-Teddy** [comment] 2023-03-22 04:53
@dnys1 thanks. I updated Xcode to 14.2 and frozen disappeared and i could show login web ui but i got stuck after enter email and next. I attached image.
![IMG_0618](https://user-images.githubusercontent.com/83799773/226805463-ff4c10d8-0edd-4e39-be5c-ae8665f9de29.PNG)

**Comment by Ekoios-Teddy** [comment] 2023-03-22 05:00
By the way, I'm working on chrome extension (by build flutter web) and i think amplify-flutter supported for this because chrome extension base on web. So If amplify-flutter support, can you give how to get redirectUrl on extension. If you have some idea and solution for my problem, please give me guide. Thanks so much!

**Comment by Ekoios-Teddy** [comment] 2023-03-22 17:24
@dnys1 Are you there?

**Comment by Ekoios-Teddy** [comment] 2023-03-22 17:48
Now, I only test on some android 12 device and it work. With ios, it keep works and not working on those versions I mentioned above.

**Comment by dnys1** [comment] 2023-03-22 17:49
Are there any errors like before when you run the app in Xcode?

**Comment by Ekoios-Teddy** [comment] 2023-03-22 17:53
Because it's stuck in the web UI so I can't log the error details. I will try it right now and hope to get something helpful.

**Comment by Ekoios-Teddy** [comment] 2023-03-22 17:58
@dnys1 I just retried and nothing is logged in Xcode and the web ui keep loading after i enter email and next.

**Comment by Ekoios-Teddy** [comment] 2023-03-22 18:03
@dnys1 I have just canceled auth flow and get this in Xcode, maybe it helpful for investigate
<img width="903" alt="Screenshot 2023-03-23 at 01 02 48" src="https://user-images.githubusercontent.com/83799773/226996806-9024c47a-d5d9-41bf-9c9e-9126a17ea417.png">

**Comment by dnys1** [comment] 2023-03-22 19:19
I'm not able to reproduce the issue. To clarify, you are only experiencing this on iOS 14.2/14.3 and it is working correctly on newer versions, right?

**Comment by Ekoios-Teddy** [comment] 2023-03-23 07:47
@dnys1 i tested on older version `13.5` and it work. Then i tested on simulator `14.3` and it work too? So i don't know what happen with my device ( Iphone X - `14.3`). I have reset the setting, network but the problem not disappear :(((.

**Comment by Ekoios-Teddy** [comment] 2023-03-23 16:38
@dnys1 I tested on older version 13.5 and it work. Then i tested on simulator 14.3 and it work too. I thought it might be due to the configuration of the device so i have reset the setting, network but the problem not disappear. Finally,  i tried to update latest version of device from `14.3` and it work.

**Comment by dnys1** [comment] 2023-03-23 21:37
Hi @Ekoios-Teddy, so I purchased an old iPhone which has iOS 13.6 installed. I attempted Hosted UI login with Amazon and Google in both debug and release mode builds, and I was not able to reproduce this issue.

It's hard to say what exactly you faced and I apologize for any frustration you've experienced.

Since I am not able to reproduce this issue, I will be closing this ticket. Please feel free to respond if you have any more information which would help me reproduce the issue. And please open a new ticket if you run into any new issues.

**Closed by dnys1** 2023-03-23 21:37 UTC
Labels: Question, Auth, pending-response

**Comment by Ekoios-Teddy** [comment] 2023-03-24 02:45
@dnys1 Sorry, have you tested on the device as I said above? I am having problem on device 14.2 and 14.3. I tested it on iphone 13.5 and it works fine, I also tested it on simulator 14.3 and it works fine. My device with version 14.3 is not working but when updating to version 16.3 works. Why is that so? I don't think the cause is from my code.

**Comment by dnys1** [comment] 2023-03-24 15:29
I understand. Currently, it's not possible to upgrade/downgrade directly to any iOS 14.x version. So someone with a phone running <iOS 15 would be forced to upgrade to iOS 15/16 if they chose to upgrade their phone.

If this is an issue on 14.2/14.3 devices only, then the recommendation would be to have users upgrade their device to iOS 15+.

**Comment by Ekoios-Teddy** [comment] 2023-03-27 03:40
@dnys1 thanks so much.
