### ISSUE TITLE
[Feature Request] Auth Get Device Details API / Ability to get Device Key

### ISSUE THREAD

**Issue by SKarausAWS** [aws-amplify/amplify-flutter#2340] opened 2022-11-10 16:21 UTC
Our mobile team has run into a blocker with Amplify Flutter SDK (https://docs.amplify.aws/lib/auth/signin/q/platform/flutter/#sign-in-a-user ) with extracting the device key after the user has signed in successfully. 

We have been able to get the device key in website using the Amplify Javascript SDK, Android SDK and IOS SDK. 
This issue was discussed in the Discord channel and the Amplify Flutter team acknowledged that device key is not returned through the SDK (https://discord.com/channels/705853757799399426/1032390735334486067 ).

Can the same function be added to the Flutter SDK that is seen in the following:

It appears to be possible in Android, Swift, React Native in the 'Get Device Details' section. https://docs.amplify.aws/sdk/auth/device-features/q/platform/ios/#remember-device

**Comment by Jordan-Nelson** [comment] 2022-11-10 19:40
@SKarausAWS - Thank you for opening the issue. I think this is actually a duplicate of https://github.com/aws-amplify/amplify-flutter/issues/1472.

Would you mind giving that issue a 👍 to express your support? If you would be able to comment on the issue and explain a bit about your use case that would be helpful. These APIs appear to be available as part of the underlying SDKs which Amplify use, but they are not actually exposed from Amplify. Understanding different use cases that customers have for these APIs will help use ensure we are exposing the right API from Amplify.

**Closed by Jordan-Nelson** 2022-11-10 19:40 UTC
Labels: feature-request, Auth
