### ISSUE TITLE
DataStore.stop or DataStore.clear may interrupt DataStore.start

### ISSUE THREAD

**Issue by Rayv1** [aws-amplify/amplify-flutter#1479] opened 2022-03-27 09:21 UTC
### Description

Hi,

iam trying to use datastore but cant get **Selective Sync** to work.
I want to change my userId / sub to logged-in users id. Additionally if would add an updateAt Sort Key, which is not inside Code yet.

  Here is my Code:

```dart
// Used to identify the owner, which is not present at start.
var sub = '';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool isBusy = true;
  @override
  void initState() {
    _configureAmplify();
    super.initState();
  }

  Future<void> _configureAmplify() async {
    try {
      AmplifyDataStore _dataStorePlugin = AmplifyDataStore(
          modelProvider: ModelProvider.instance,
          syncExpressions: [
            DataStoreSyncExpression(FoodTransaction.classType, () {
              return FoodTransaction.OWNER.eq(sub);
            })
          ]);

      // add Amplify plugins
      await Amplify.addPlugins([_dataStorePlugin]);

      // configure Amplify
      //
      // note that Amplify cannot be configured more than once!
      if (!Amplify.isConfigured) {
        await Amplify.configure(amplifyconfig);
        setState(() {
          isBusy = false;
        });
      }
    } catch (e) {
      // error handling can be improved for sure!
      // but this will be sufficient for the purposes of this tutorial
      print('An error occurred while configuring Amplify: $e');
    }
  }

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Amplified Todo',
      home: isBusy ? CircularProgressIndicator() : TodosPage(),
      // builder: Authenticator.builder(),
    );
  }
}

class TodosPage extends StatefulWidget {
  @override
  _TodosPageState createState() => _TodosPageState();
}

class _TodosPageState extends State<TodosPage> {
  // loading ui state - initially set to a loading state
  bool _isLoading = true;

  // list of Todos - initially empty
  List<FoodTransaction> _todos = [];

  @override
  void initState() {

    super.initState();
  }

  @override
  void dispose() {
    // to be filled in a later step
    super.dispose();
  }



  changeSync() async {
    sub = 'facebook_xxxx';
    await Amplify.DataStore.stop();
    await Amplify.DataStore.start();
    _todos = await Amplify.DataStore.query(FoodTransaction.classType);
    setState(() {
      if (_isLoading) _isLoading = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('My Todo List'),
      ),
      // body: Center(child: CircularProgressIndicator()),
      body: _isLoading
          ? Center(child: CircularProgressIndicator())
          : TodosList(todos: _todos),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () async {
          changeSync();
        },
        tooltip: 'change sync',
        label: Row(
          children: [Icon(Icons.add), Text('Add todo')],
        ),
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
    );
  }
}

```

I Checked my Appsync Cloudwatch Logs and cant see any new sync or query action after my changeSync Method. I guess iam just missing some code or something else.
I also noted that i cant use QueryPredicate.None because its not implemented as in Amplify-android, right?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [X] Android

### Environment

```bash
[✓] Flutter (Channel stable, 2.10.3, on Ubuntu 20.04.4 LTS 5.13.0-37-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2021.1)
[✓] Android Studio
[✓] VS Code
[✓] Connected device (1 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

### Dependencies

```bash
- amplify_api 0.4.1 [amplify_api_plugin_interface amplify_core collection flutter meta plugin_platform_interface]
- amplify_auth_cognito 0.4.1 [flutter amplify_auth_plugin_interface amplify_core collection plugin_platform_interface]
- amplify_authenticator 0.1.0 [amplify_auth_cognito amplify_auth_plugin_interface amplify_core amplify_flutter collection flutter flutter_localizations intl]
- amplify_core 0.4.1 [flutter plugin_platform_interface collection date_time_format meta uuid]
- amplify_datastore 0.4.1 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.4.1 [amplify_analytics_plugin_interface amplify_api_plugin_interface amplify_auth_plugin_interface amplify_core amplify_datastore_plugin_interface amplify_storage_plugin_interface collection flutter json_annotation meta plugin_platform_interface]
- cupertino_icons 1.0.4
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- hive 2.1.0 [meta crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- path_provider 2.0.9 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]

transitive dependencies:
- amplify_analytics_plugin_interface 0.4.1 [amplify_core flutter meta]
- amplify_api_plugin_interface 0.4.1 [amplify_core collection flutter json_annotation meta]
- amplify_auth_plugin_interface 0.4.1 [flutter meta amplify_core]
- amplify_datastore_plugin_interface 0.4.1 [flutter meta collection amplify_core]
- amplify_storage_plugin_interface 0.4.1 [flutter meta amplify_core]
- async 2.8.2 [collection meta]
- characters 1.2.0
- clock 1.1.0
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- date_time_format 2.0.1
- ffi 1.1.2
- file 6.1.2 [meta path]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path typed_data vector_math]
- intl 0.17.0 [clock path]
- json_annotation 4.4.0 [meta]
- material_color_utilities 0.1.3
- meta 1.7.0
- path 1.8.0
- path_provider_android 2.0.12 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.8 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.5 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.5 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.3 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.5 [ffi flutter path path_provider_platform_interface win32]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- sky_engine 0.0.99
- typed_data 1.3.0 [collection]
- uuid 3.0.6 [crypto]
- vector_math 2.1.1
- win32 2.4.4 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
```

### Device

Pixel 5 API 31

### OS

Android 11

### CLI Version

7.6.26

**Comment by HuiSF** [comment] 2022-03-28 17:01
Hi @Rayv1 thanks for reporting this issue.

Regarding your `changeSync` function implementation -
You invoked query right after `Amplify.DataStore.start()`. At this moment, the data sync may be in still progress, where the `query` may return empty result as the data hasn't been written into local DB. To get around of this you have two options:

* Start querying when Amplify Hub emits DataStore `ready` event
  e.g.
  ```dart
  hubSubscription = Amplify.Hub.listen([HubChannel.DataStore], (msg) { 
    if (msg.eventName == "ready") { 
      _todos = await Amplify.DataStore.query(FoodTransaction.classType);
    } 
  }); 
  ```
* To use [`observeQuery` API](https://docs.amplify.aws/lib/datastore/real-time/q/platform/flutter/#observe-query-results-in-real-time)
* For your use case, you may want to use `Amplify.DataStore.clear()` instead of `Amplify.DataStore.stop()` to clear previously synced data against the previous user sub

>I Checked my Appsync Cloudwatch Logs and cant see any new sync or query action after my changeSync Method.

I will test and verify this point. Can you share your `FoodTransaction` model schema?

**Comment by HuiSF** [comment] 2022-03-28 21:37
Update re:
>I Checked my Appsync Cloudwatch Logs and cant see any new sync or query action after my changeSync Method.

I created an App to replicate @Rayv1 provide steps.
I noticed that **consecutively** invoking `DataStore.clear()` and `DataStore.start()`, may cause an issue.

* `DataStore.clear()` starts DataStore clearing process, this process is asynchronous
* `DataStore.start()` instructs DataStore to start API sync, and this process is asynchronous

It may happen that, when the sync engine starts subscription, the clear process has just completed, where it instructs terminate all ongoing subscription, therefore, the `clear` interrupts the `start`. I think amplify-flutter lacks a "locking" mechanism to prevent this from happening. I will look into a fix.

In the meantime, here's a workaround:

```dart
  changeSync() async {
    sub = 'facebook_xxxx';
    await Amplify.DataStore.stop();
    // add a manual delay to ensure the previous stop call not to interrupt the next start call
    await Future.delay(const Duration(seconds: 2));
    await Amplify.DataStore.start();
    _todos = await Amplify.DataStore.query(FoodTransaction.classType);
    setState(() {
      if (_isLoading) _isLoading = false;
    });
  }
```

**Comment by HuiSF** [comment] 2022-03-28 22:29
Did a thorough testing in both Android and iOS platforms.  Above mentioned issue is not reproducible in iOS. Looking at the source code of amplify-android of the [`stop` API](https://github.com/aws-amplify/amplify-android/blob/main/aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java#L310-L318) and [`clear` API](https://github.com/aws-amplify/amplify-android/blob/main/aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java#L329-L336), it looks like that the `onComplete` action is not guaranteed to be executed after the `stop` or `clear` process is completely finished.

Therefore, in the amplify-flutter [implementation](https://github.com/aws-amplify/amplify-flutter/blob/main/packages/amplify_datastore/android/src/main/kotlin/com/amazonaws/amplify/amplify_datastore/AmplifyDataStorePlugin.kt#L381-L384), may not be effective.

Created an issue https://github.com/aws-amplify/amplify-android/issues/1690 for amplify-android for a further triaging.

**Comment by Rayv1** [comment] 2022-03-29 06:45
HI @HuiSF 

thanks for your research on my issue. 

> Did a thorough testing in both Android and iOS platforms. Above mentioned issue is not reproducible in iOS. Looking at the source code of amplify-android of the [`stop` API](https://github.com/aws-amplify/amplify-android/blob/main/aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java#L310-L318) and [`clear` API](https://github.com/aws-amplify/amplify-android/blob/main/aws-datastore/src/main/java/com/amplifyframework/datastore/AWSDataStorePlugin.java#L329-L336), it looks like that the `onComplete` action is not guaranteed to be executed after the `stop` or `clear` process is completely finished.

Thats exactly what i saw on my Tests and thought its an issue on my site. 


A brief feedback for Datastore:
It seems like there is still much work to do on Amplify datastore and not useful for my app or larger apps. I plan with ~15000 Entries in Datastore , consisting of 15 different types / models and for me it seems that datastore is not ready for such data. I want to control each type of data separate to clear or start the sync expression for it and not for the all Data. Iam not sure what happens when i have 15 different sync expressions and restart the datastore plugins so much, because i want to add a new 'updated_at' timestamp to get only the newest data. 

Iam also wondering why i cant do a new dynamic sync expression without to do a datastore restart. Additionally the async Datastore actions which cant be awaited makes the whole datastore thing max complex. Finally i ask myself why the default sync would do a full table scan, which is really the last thing you should do against dynamodb and increases costs. How long should the scan take when you handle more data and not just 100 items?
As now and for me its easier to integrate the logic myself instead of using datastore.

Cheers
Ray

**Comment by HuiSF** [comment] 2022-03-29 16:00
Thanks for the write up @Rayv1 with details and your thoughts.

> I want to control each type of data separate to clear

Unfortunenatly, this is not currently supported by DataStore, you are welcome to open a feature request for this.
There is a workaround is that to use the `delete` API to delete the record that you want to clear.

>I am also wondering why i cant do a new dynamic sync expression without to do a datastore restart.

The `syncExpression` is being re-evaluated every time when DataStore subscription event comes. Which will behave as a client filter to determine whether merge the subscription event into local DB.

If you want the updated `syncExpression` to be effective for the base/delta sync, you'd need to restart DataStore.

>because i want to add a new 'updated_at' timestamp to get only the newest data

I may need more details on this use case... but you meant your App doesn't need data before the DataTime presented by `updated_at`? If this is true, you may try:

* Flip `_deleted` value to `true` in DynamoDB for the records that has `updated_at` < the desired value (this can be done in various ways, such a lambda function, custom API with AppSync etc)
* When App starts the base/delta sync will reconsolidate remote data (with `_deleted = true`) which will eliminate corresponding records from the local DB
* When App receives subscription event triggered by updating the `_deleted` field, DataStore reconciliation eliminate record from local DB with `_deleted=true`
* Specific `updated_at` as a Global Secondary Index (GSI) ([document](https://docs.amplify.aws/cli/graphql/data-modeling/#configure-a-secondary-index) for configuring GSI)
  e.g.
  ```graphql
  type FoodTransaction @model {
    id: ID!
    owner: String!
    updated_at: AWSDateTime @index(name: "byUpdatedAt", sortKeyFields: ["owner"])
  }
  ```
   
  ```dart
  final datastore = AmplifyDataStore(
    modelProvider: ModelProvider.instance,
    syncExpressions: [
        DataStoreSyncExpression(
          FoodTransaction.classType,
          () => FoodTransaction.UPDATED_AT.gt(TemporalDateTime(DateTime(2022, 3, 26))),
        ),
      ],
  )
  ```

>Datastore actions which cant be awaited makes the whole datastore thing max complex.

I agree, sorry for the inconvenient, but to clarify, this unfortunately a bug is in amplify-android, we anticipate a fix soon.
* All DataStore operations are await-able in iOS platform
* Except `stop` and `clear`, other operations are await-able in Android platform

>Finally i ask myself why the default sync would do a full table scan,

DataStore base/delta sync supports `Query` operation. To enable `Query`, you'd need to define GSI on your model schema, and use a `syncExpression` that matches the GSI (above code example). Details please refer to [this document](https://docs.amplify.aws/lib/datastore/sync/q/platform/flutter/#advanced-use-case---query-instead-of-scan).

>As now and for me it's easier to integrate the logic myself instead of using datastore

We'd love to hear your thoughts on how to improve DataStore, please feel free to open feature request with description of your use cases. :)

**Comment by Rayv1** [comment] 2022-04-14 06:22
Hi @HuiSF 

thanks for your reply. Can i await the Datastore to be full "synced"? 
Just for example..when i would store UserProfiles with DynamoDB and a user who already has a valid UserProfile would login with a new device with no local UserProfile, how can i await, that the UserProfile is loaded and synced, before showing the first screen? 
Are there events when a specific model is full synced?

**Comment by Jordan-Nelson** [comment] 2022-04-26 21:45
@Rayv1 There are events emitted for each model type. See [ModelSynced Event](https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/flutter/#modelsynced).

**Comment by HuiSF** [comment] 2023-06-13 19:32
Hi @harrynguyen2510 DataStore currently doesn't have a selective clear functionality, here's the feature request issue: https://github.com/aws-amplify/amplify-flutter/issues/2528

**Comment by harrynguyen2510** [comment] 2023-06-14 07:03
@HuiSF Thanks, hope the team can add more options on data clear features in the future

**Comment by wojciechzahradnikdeviniti** [comment] 2023-06-22 15:07
Hi, any updates on this issue? I still have a problem with that.

**Comment by dgagnon** [comment] 2023-08-03 17:42
I want to chime in with what we have tried, the issues we have faced and so far what worked and what does not.

1. no await on close: can be solved this inelegant way (adjust timing as needed):  
```dart
    Timer(const Duration(seconds: 1), () async {
      try {
        await Amplify.DataStore.stop();
        Timer(const Duration(seconds: 3), () async {
          try {
            await Amplify.DataStore.start();
          } on Exception catch (error, stackTrace) {
            err('Error starting DataStore: $error', stackTrace, cat: 'DATASTORE');
            if (kDebugMode) rethrow;
          }
        });
      } catch (error, stackTrace) {
        err('Error stopping DataStore: $error', stackTrace, cat: 'DATASTORE');
        if (kDebugMode) rethrow;
      }
    });
```  
2.  Be careful with syncExpressions that are referencing models with foreign keys, especially when mixed with MaxRecordSize.  If not, you will get foreign key errors since some records are missing.
3. To avoid the long initial load time as mentioned here, we tried a two-step approach where we have an initial and a default datastore configuration.  Like most users, we have a User model that needs to be handled first and early, so like most, we wait until the datastore is fully ready before accessing it.  Then we reset the syncExpression and restart the datastore to get the full load, allowing a faster loading of the user's preference and interactiveness. 

Unfortunately, all my efforts to have the syncExpression re-evaluated are failing on android.  I can inspect the datastore plugin config and see the the syncExpressions have changed, but it just does not sync the new data.  I have tried so many things that the code I have right now is probably not ideal, but here is part of the class anyway.  The ready first event triggers the fullLoad and then the second ready events actually returns control to the app.

```dart
  // How can we set this to false if the datastore is already fully initialized ? do a query ?
  bool isInitialSync = true;

  // default is 86400
  int initialSyncInterval = 8640000;
  int defaultSyncInterval = 864000;

  int? get syncInterval {
    return isInitialSync ? initialSyncInterval : defaultSyncInterval;
  }

  set syncInterval(int? value) {
    datastorePlugin.syncInterval = value ?? defaultSyncInterval;
  }

  // default is 10000
  int initialSyncMaxRecords = 100;
  int defaultSyncMaxRecords = 100000;

  int? get syncMaxRecords {
    return isInitialSync ? initialSyncMaxRecords : defaultSyncMaxRecords;
  }

  set syncMaxRecords(int? value) {
    datastorePlugin.syncMaxRecords = value ?? defaultSyncMaxRecords;
  }

  // default is 1000
  int initialSyncPageSize = 100;
  int defaultSyncPageSize = 1000;

  int? get syncPageSize {
    return isInitialSync ? initialSyncPageSize : defaultSyncPageSize;
  }

  set syncPageSize(int? value) {
    datastorePlugin.syncPageSize = value ?? defaultSyncPageSize;
  }

  QueryPredicate<Model> initialUserSyncExpression = User.STATUS.eq(UserStatus.ACTIVE).or(User.STATUS.eq(UserStatus.SUSPENDED));
  QueryPredicate<Model> defaultUserSyncExpression = User.STATUS.eq(UserStatus.ACTIVE).or(User.STATUS.eq(UserStatus.SUSPENDED));
  QueryPredicate<Model> getUserSyncExpression() {
    return isInitialSync ? initialUserSyncExpression : defaultUserSyncExpression;
  }

  QueryPredicate<Model> initialProjectSyncExpression = Project.ID.eq("1");
  QueryPredicate<Model> defaultProjectSyncExpression = Project.STATUS.eq(Status.ACTIVE).or(Project.STATUS.eq(Status.COMPLETED));
  QueryPredicate<Model> getProjectSyncExpression() {
    return isInitialSync ? initialProjectSyncExpression : defaultProjectSyncExpression;
  }

  QueryPredicate<Model> initialTaskSyncExpression = Task.ID.eq("1");
  QueryPredicate<Model> defaultTaskSyncExpression = Task.STATUS.eq(Status.ACTIVE).or(Project.STATUS.eq(Status.COMPLETED));
  QueryPredicate<Model> getTaskSyncExpression() {
    return isInitialSync ? initialTaskSyncExpression : defaultTaskSyncExpression;
  }

  late List<DataStoreSyncExpression> syncExpressions = [
    DataStoreSyncExpression(
      // should query by ID directly since we need our user, since we limit the amount of records, an account with lots of shared User could possibly not received its own user this way
      User.classType,
      getUserSyncExpression,
    ),
    DataStoreSyncExpression(
      Project.classType,
      getProjectSyncExpression,
    ),
    DataStoreSyncExpression(
      Task.classType,
      getTaskSyncExpression,
    )
  ];

  /// When there are lots of items, the datastore takes forever to load, even on a good connection.
  /// By restricting whats get synced on an initial load (User profile and anything else needed to get started)
  /// We can return interactiveness to the user faster.
  Future<void> loadFullDatastore() async {
    isInitialSync = false;
    datastorePlugin.syncExpressions = syncExpressions;
    syncMaxRecords = defaultSyncMaxRecords;
    syncInterval = defaultSyncInterval;
    syncPageSize = defaultSyncPageSize;
    dbg("resetting Datastore", cat: 'DATASTORE');

    // using Timer to avoid all sorts of weird timing issues with the underlying libraries.
    // it was actually crashing the app.  these timings worked on the first try, did not try other ones.
    Timer(const Duration(seconds: 1), () async {
      try {
        await Amplify.DataStore.stop();
        Timer(const Duration(seconds: 3), () async {
          try {
            await Amplify.DataStore.start();
          } on Exception catch (error, stackTrace) {
            err('Error starting DataStore: $error', stackTrace, cat: 'DATASTORE');
            if (kDebugMode) rethrow;
          }
        });
      } catch (error, stackTrace) {
        err('Error stopping DataStore: $error', stackTrace, cat: 'DATASTORE');
        if (kDebugMode) rethrow;
      }
    });
    final test = datastorePlugin.syncExpressions;
    dbg(test);
  }

  /// Configure Datastore to use queries instead of table scans.
  /// https://docs.amplify.aws/lib/datastore/sync/q/platform/flutter/#advanced-use-case---query-instead-of-scan
  /// And perform a two stage loading
  /// https://docs.amplify.aws/lib/datastore/conflict/q/platform/flutter/#custom-configuration
  late AmplifyDataStore datastorePlugin = AmplifyDataStore(
    modelProvider: ModelProvider.instance,

    /// Pools are default with iam secondary for admin access.
    authModeStrategy: AuthModeStrategy.multiAuth,

    /// Custom ErrorHandler to propagate errors to the user as needed
    errorHandler: ((error) {
      err('Custom DataStore ErrorHandler received: $error', null, cat: 'DATASTORE');
    }),

    /// Sync configuration defaults:
    syncInterval: syncInterval,
    syncMaxRecords: syncMaxRecords,
    syncPageSize: syncPageSize,

    // TODO: make the sync expression configurable
    syncExpressions: syncExpressions!,
  );
```

But the sync never changes:  
[GETX] [DATASTORE] package:flutter_demo_with_docs/modules/aws/services/datastore.dart:330:15 <String> In DatastoreService._configureDatastoreService.<fn> => (Task)  [DeltaSync]. added 0, updated 0, deleted 0                    [DATASTORE]

**Comment by wojciechzahradnikdeviniti** [comment] 2023-08-29 09:28
Thanks - fixed in 1.4.0

**Comment by LucasBourne** [comment] 2023-09-06 08:49
I'm still getting this issue on 1.4.0. I see this was [fixed in Amplify Android 2.12.0](https://github.com/aws-amplify/amplify-android/pull/2569), is this available in 1.4.0 or are we still waiting on these changes?

**Comment by LucasBourne** [comment] 2023-09-14 08:01
> I'm still getting this issue on 1.4.0. I see this was [fixed in Amplify Android 2.12.0](https://github.com/aws-amplify/amplify-android/pull/2569), is this available in 1.4.0 or are we still waiting on these changes?

Just following up on this, it seems like this is now working as of 1.4.1 💯

**Comment by Jordan-Nelson** [comment] 2023-09-14 16:04
@LucasBourne Amplify Flutter v1.4.0 does include the fix in Amplify Android v2.12.0. However, as noted on [the Amplify Android issue](https://github.com/aws-amplify/amplify-android/issues/1690#issuecomment-1692358164), there are limitations with the current fix.

Are you calling stop or clear more than once in a row? Could you share the code you use when stopping/starting DataStore?

**Comment by Jordan-Nelson** [comment] 2023-09-14 17:39
As of v1.4.0, calling stop (or clear) and then start should not result in an issue. As noted in https://github.com/aws-amplify/amplify-android/issues/1690#issuecomment-1692358164 and https://github.com/aws-amplify/amplify-android/issues/1464, you may still see issues when calling clear/stop and then start multiple times in a row or when calling clear multiple times in a row. You can follow https://github.com/aws-amplify/amplify-android/issues/1464 for updates on that issue.

**Closed by Jordan-Nelson** 2023-09-14 17:39 UTC
Labels: bug, Android, requires-android-fix, DataStore

**Comment by stevegaunt** [comment] 2023-09-22 14:17
@Jordan-Nelson what version of amplify flutter is this fixed in??
we still see this with amplify flutter 1.4.0 
after doing an amplify datastore.clear(), we have had to put a 10 second delay before it can start again ( which is not ideal - especially on signing up as a different user)

we are using sync expressions , 
so initially on startup we gave to sync against user_id being 0, then when the user signs in we then stop/clear/start to the sync expression users the correct username token from auth to pull the changes from dynamodb.

**Comment by Jordan-Nelson** [comment] 2023-09-22 15:44
@stevegaunt can you share the code you are using to clear and then restart DataStore?
