### ISSUE TITLE
Exception Handling in Flutter Amplify Cognito.

### ISSUE THREAD

**Issue by riyan-datalyca** [aws-amplify/amplify-flutter#561] opened 2021-05-06 13:16 UTC
**Describe the bug**
When there is any Exception occured in the function call on Amplify.Auth.***() the Exception always jumps to AuthException. How will I be able to catch the Exception present in the Error Code?

**To Reproduce**
```
void _forgotPassword(BuildContext context) async {
    try {
       UpdatePasswordResult res = await Amplify.Auth.confirmPassword(
            username: _userName,
            newPassword: _passwordController.text,
            confirmationCode: _otpController.text);
      }
    } on LimitExceededException {
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(
          content: Text('Too many attempts, please try after few minutes.')));
    } on CodeMismatchException {
      setState(() {
        _otpError = true;
      });
    } on CodeExpiredException {
      setState(() {
        _otpError = true;
      });
    } on InvalidParameterException {
      setState(() {
        _passwordError=true;
      });
    } on UserNotFoundException {
      setState(() {
        _usernameError = true;
      });
    } 
  }
```
**Error Code**
```
E/amplify:flutter:auth_cognito(26434): AuthException
E/amplify:flutter:auth_cognito(26434): AuthException{message=An error occurred confirming password recovery code,
 cause=com.amazonaws.services.cognitoidentityprovider.model.InvalidParameterException: 1 validation error detected: 
Value at 'password' failed to satisfy constraint: Member must have length greater than or equal to 6 (Service: 
AmazonCognitoIdentityProvider; Status Code: 400; **_Error Code: InvalidParameterException;_** 
Request ID: a66683a1-a59f-43eb-adb9-92fd3544ec96), recoverySuggestion=
See attached exception for more details}
```

**Expected behavior**
If the Code is wrong or expired it must be caught in CodeMismatchException  or CodeExpiredException  handler. 

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.1 at C:\Flutter\flutter
    • Framework revision c5a4b4029c (9 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code, 64-bit edition (version 1.54.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (2 available)
    • Chrome (web)              • chrome             • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)                • edge               • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!```

</details>

**Smartphone (please complete the following information):**
 - Device: [Nexus_5]
 - OS: [Android 7.0]

**Comment by riyan-datalyca** [comment] 2021-05-06 13:35
The LimitExceededException can be caught since it throws the Exception. 
```
E/amplify:flutter:auth_cognito(26434): LimitExceededException
E/amplify:flutter:auth_cognito(26434): AuthException{message=An error occurred confirming password recovery code, 
cause=com.amazonaws.services.cognitoidentityprovider.model.LimitExceededException: Attempt limit exceeded, 
please try after some time. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: LimitExceededException; 
Request ID: 98887aea-acc1-48ce-9b42-0a33dbbd82a5), recoverySuggestion=See attached exception for more details}
```

**Comment by fjnoyp** [comment] 2021-05-06 21:14
Hi @riyan-datalyca looking at your error code it seems that the password provided did not have a `length greater than or equal to 6`.  Because this password input didn't satisfy the base constraint you got the `InvalidParameterException`.  Have you tried providing password input of length > 6 - in that case did you get the CodeException instead?

**Comment by riyan-datalyca** [comment] 2021-05-07 02:31
Hello @fjnoyp , I had removed the password validation to check Exception Handling. I'm able to catch `LimitExceededException` but unable to catch other errors. My primary goal is to handle errors with Exception Handling. Thank you for the response.

**Comment by Jordan-Nelson** [comment] 2021-05-17 15:45
I believe #533 will fix this (will be included in the next release). We added mappings for `InvalidParameterException`, `ExpiredCodeException`, `CodeMismatchException`,  and `CodeDeliveryFailureException` from cognito. A mapping for `LimitExceededException` was added in #522 (released in 0.1.3). The last exception included in the steps to reproduce is `UserNotFoundException`, which should already be handled properly.

@riyan-datalyca can you confirm that you are not having issues catching `UserNotFoundException` exceptions? The remainder of the exceptions should be addressed in the next release. I can post here when the next version is available w/ the fix.

**Comment by riyan-datalyca** [comment] 2021-05-17 16:07
@Jordan-Nelson Thank you for the response. This is great, I will be waiting for the fixed release. The `UserNotFoundException` works as expected. There is no issue with the it.

**Comment by Jordan-Nelson** [comment] 2021-05-17 19:07
@riyan-datalyca version 0.1.5 is now available and has the fix mentioned above. I am going to close this issue, but let us know if that does not address the issue as expected.

**Closed by Jordan-Nelson** 2021-05-17 19:07 UTC
Labels: Auth, pending-release, platform-discrepancy
