### ISSUE TITLE
[Feature Request] Single Device Sign on

### ISSUE THREAD

**Issue by fdarsot** [aws-amplify/amplify-flutter#418] opened 2021-03-02 04:56 UTC
Hey guys, 

Was wondering, is there any way currently to prevent a user from logging in from multiple devices? Essentially we want a user to only be able to log in to one device at a time. If they log in to another device, the first user session should be voided (signed out) or some similar functionality. 

Thank you

**Comment by haverchuck** [comment] 2021-03-02 19:05
@fdarsot Our roadmap includes the implementation of a global signout  - which would sign a user out on all devices.  Would access to this method satisfy your case?

**Comment by fdarsot** [comment] 2021-03-03 00:07
@haverchuck It would possibly. If i had access to global sign out, would it be possible for me to call global sign out on a particular user before signing them in? Do you think that would work?

one hurdle i see with that method is that since the user is not yet signed in to begin with, there might be an issue calling the global signout. Am i right?

**Comment by haverchuck** [comment] 2021-03-03 18:06
@fdarsot Yes, I believe in this globalSignout error you may have to swallow an error either client side or possibly in a Cognito Lambda Trigger - so it would definitely be more of a workaround.  

It sounds like what you're really looking for, optimally, is a new feature in the Cognito service itself.

**Comment by fdarsot** [comment] 2021-03-03 22:16
@haverchuck yes it does feel like it should be a new feature within the Cognito Service. If you can implement something like that on your side that would be amazing as this is one of the main functionalities that my team and i are looking for.

In the mean time, i can try that workaround that with the global sign out, however how do i access this method? if i recall in the new update the global sign out option is deprecated right?

**Comment by fdarsot** [comment] 2021-03-08 01:01
hi @haverchuck any update?

**Comment by fdarsot** [comment] 2021-03-18 21:46
Hi please let me know @haverchuck

**Comment by SalahAdDin** [comment] 2021-03-27 21:55
> Hi please let me know @haverchuck

Did you get a workaround about this?

**Comment by fdarsot** [comment] 2021-03-28 23:52
> > Hi please let me know @haverchuck
> 
> Did you get a workaround about this?

Hi I did not, still waiting on a fix/comment from @haverchuck  and team

**Comment by fdarsot** [comment] 2021-03-30 21:15
@haverchuck @Amplifiyer @fjnoyp

**Comment by fdarsot** [comment] 2021-05-04 08:14
My team and i still need a solution to this. Any progress/updates/help? @haverchuck @Amplifiyer @fjnoyp

**Comment by Ashish-Nanda** [comment] 2021-05-04 08:28
@fdarsot Thanks for your patience. We will discuss your use-case among the team this week and let you know if this can be achieved once we support `globalSignOut()` or if there is a potential workaround you can use right now. Will update this thread once we have more details.

**Comment by fdarsot** [comment] 2021-05-04 19:58
@Ashish-Nanda Thank you for the reply! much appreciated!

**Comment by fdarsot** [comment] 2021-05-12 07:22
hi @Ashish-Nanda sorry to bother, but any updates?

**Comment by fdarsot** [comment] 2021-05-17 19:47
@Ashish-Nanda @offlineprogrammer

**Comment by Ashish-Nanda** [comment] 2021-05-20 21:15
@fdarsot This week @haverchuck had a meeting with the Cognito team to discuss this and will update the thread with his findings.

**Comment by haverchuck** [comment] 2021-05-20 22:21
@fdarsot Cognito does not support anything like this out of the box. In order to support this, we can work on implementing globalSignout, so that you could simply call the method before signIng users in... but even this is a bit of a workaround and could lead to a weird user expireence if you are using Cognito Hosted UI.  The other option that you could look into is to implement your own store of active sessions in something like dynamoDB which using Cognito Lambda triggers (this would not be trivial work). 

We will be working on implementing globalSignout in any case.

**Comment by fdarsot** [comment] 2021-05-21 00:57
Thank you @haverchuck @Ashish-Nanda  for the replies/updates.

I see. I guess in the mean time we can just forego this feature, however once that globalSignout is implemented my team and I will call globalSignout before signing users in. 

when implementing this feature though,  i would suggest making it so you can pass in a user's email or UID as a parameter so you can directly call globalSignout on a user's account. otherwise if you tried calling globalSignout before signing users in, it might throw an error saying there was no user signed in to begin with or something.

Thank you guys for all the work!!

**Comment by fdarsot** [comment] 2021-06-28 21:42
Hey guys, any update on this? @haverchuck @Ashish-Nanda @offlineprogrammer

**Comment by fdarsot** [comment] 2021-07-16 18:51
@haverchuck @Ashish-Nanda @offlineprogrammer any updates on the global sign out stuff?

If it helps there's a non official aws package that has a global sign out, do you think i can somehow incorporate both packages and use that global sign out?

https://pub.dev/packages/amazon_cognito_identity_dart_2

**Comment by Jordan-Nelson** [comment] 2021-08-04 20:45
@fdarsot - Sorry for the delay in a response. I am looking into global sign out. There is a small discrepancy between how global sign out functions in the amplify iOS and Android libraries that I need to look into before we add this to amplify-flutter. I will comment on this issue when I have an update.

**Comment by fdarsot** [comment] 2021-08-05 21:18
@Jordan-Nelson Thank you for the update. 

Please keep in mind our use case for this global signout as well. Essentially we want to use it to enforce Single Device Sign on/login.

we should somehow be able to use this at the time of a user logging in, (possibly before they login) this would ensure they are logged out of all other devices, and then log them in to the single device that they are trying to login to.

Appreciate the work! Thank you!

**Comment by Jordan-Nelson** [comment] 2021-08-09 21:35
@fdarsot - Right now I am looking into implementing global sign out as it exists in the iOS and Android libraries. 

It isn't intended for your exact use case. As @haverchuck mentioned, you could likely use this API for your use case, but it is definitely not the intended use case and would be a work around. There could be unexpected behavior since it isn't the intended use of global sign out.

In order to invoke global sign out, the user will have to already be authenticated. Calling global sign out will sign them out from their current device as well though. So, you will likely have to sign the user in, call global sign out, and then immediately sign the user back in again.

We can keep this issue open after global sign out is implemented to track your specific use case. I also see you have another similar issue open (https://github.com/aws-amplify/amplify-flutter/issues/398). We could use that to track your use case as well.

**Comment by fdarsot** [comment] 2021-08-09 23:26
@Jordan-Nelson Ah i see. Yes that would be great. lets keep this open for tracking/help. 

Any idea approx on the eta for the feature to be implemented and released?

thank you btw

**Comment by Jordan-Nelson** [comment] 2021-08-10 14:56
@fdarsot - I do not have an ETA at the moment.

I am going to update the title of this issue and #398 just to make it clear this ticket is tracking single device sign on, and #398 is tracking global sign out.

**Comment by HuiSF** [comment] 2021-12-16 17:35
Closing this issue in favor of https://github.com/aws-amplify/amplify-flutter/issues/1206

**Closed by HuiSF** 2021-12-16 17:35 UTC
Labels: feature-request, Auth
