### ISSUE TITLE
$ctx.identity.sourceIp is null in request template resolver.

### ISSUE THREAD

**Issue by hackrx** [aws-amplify/amplify-flutter#999] opened 2021-10-24 17:16 UTC
**Describe the bug**
I am trying to get the IP address of the client with the request which they are sending, but I am getting null in the request template.
Here is the code which I am using to send a mutation request: 
```
var operationMutation = Amplify.API.mutate(request: createRequest);
```
And in the request template: 
```
$util.qr($context.args.input.put("sourceIP",$ctx.identity.sourceIp))
```
It is storing null value in the dynamodb: 
![image](https://user-images.githubusercontent.com/54453778/138604883-37e97d8c-fb26-4a87-ab23-1fe26da90b8f.png)

**To Reproduce**
1. You can edit a generated mutation, and test it.
 

**Expected behavior**
It should send the sourceIP in the header. 
[Link to the context docs](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-context-reference.html)

> **sourceIp**
The source IP address of the caller received by AWS AppSync. **If the request doesn’t include the x-forwarded**-for header, the source IP value contains **only a single IP address from the TCP connection**. If the request includes a x-forwarded-for header, the source IP is a list of IP addresses from the x-forwarded-for header, in addition to the IP address from the TCP connection.

I also tried giving Location permission to my app, but still, it is not sending any client ip address. And I think, location isn't required to get the caller IP address.

Please look into the matter, and let me know if I need to add more information.
Thanks.

**Comment by dnys1** [comment] 2021-11-18 22:33
Hi @hackrx - as you noted in the docs, `sourceIp` is only available for IAM and Cognito User Pools authentication modes. It will be `null` otherwise. For IAM and User Pools, `sourceIp` is a list object - it's important that you consider this in your API. 

Without seeing more of your resolver/schema, I'm unable to say what the issue might be. I did try to create a minimum reproduction with the following schema and resolver, and got the results expected.

`schema.graphql`
```graphql
type Query {
  getIPAddress: String
    @aws_api_key
    @aws_cognito_user_pools
}
```

`CustomResources.json`
```json
"Resources": {
  "EmptyDataSource": {
    "Type": "AWS::AppSync::DataSource",
    "Properties": {
      "ApiId": {
        "Ref": "AppSyncApiId"
      },
      "Name": "EmptyDataSource",
      "Type": "NONE"
    }
  },
  "GetIPAddress": {
    "Type": "AWS::AppSync::Resolver",
    "Properties": {
      "ApiId": {
        "Ref": "AppSyncApiId"
      },
      "TypeName": "Query",
      "FieldName": "getIPAddress",
      "DataSourceName": {
        "Fn::GetAtt": "EmptyDataSource.Name"
      },
      "Kind": "UNIT",
      "RequestMappingTemplate": "{\"version\":\"2018-05-29\"}",
      "ResponseMappingTemplate": "#set($ip = $ctx.identity.sourceIp)\n#if($util.isList($ip)) #set($ip = $ip[0]) #end\n$util.toJson($ip)"
    }
  }
}
```

I get the following for API Key:

```json5
{
  "data": {
    "getIPAddress": null
  }
}
```

And the following for User Pools:

```json5
{
  "data": {
    "getIPAddress": "98.171.81.206"
  }
}
```

**Comment by dnys1** [comment] 2021-11-24 15:58
Closing for now since I was unable to reproduce, but please feel free to re-open if you continue to experience other issues.

**Closed by dnys1** 2021-11-24 15:58 UTC
Labels: API
