### ISSUE TITLE
Getting AMPLIFY_FETCH_SESSION_FAILED exception when fetching AWS session credentials

### ISSUE THREAD

**Issue by willstepp** [aws-amplify/amplify-flutter#163] opened 2020-10-24 02:15 UTC
**Describe the bug**

I've been working my way through the documentation at https://docs.amplify.aws/lib/auth/getting-started/q/platform/flutter to set up a Flutter application that will use the AWS Amplify Auth library to authenticate my calls to API Gateway endpoints. Since the Amplify Flutter library does not yet provide functionality for calling API Gateway, I intend to fetch the AWS Credentials manually for now. But when I call the function fetchAuthSession() using the example on this page: https://docs.amplify.aws/lib/auth/access_credentials/q/platform/flutter, it throws an exception: AMPLIFY_FETCH_SESSION_FAILED, and I cannot figure out why. Some additional information: I have confirmed I am signed in before calling this function, and it still happens.

**To Reproduce**

```
try {

CognitoAuthSession sess = await Amplify.Auth.fetchAuthSession(options: CognitoSessionOptions(getAWSCredentials: true));
if (sess.isSignedIn) {
  print("SIGNED IN");
} else {
  print("NOT SIGNED IN");
}

} on AuthError catch (e) {

  print(e);
  print(e.cause);

}
```

**Expected behavior**
I expect to receive a CognitoAuthSession instance that has the AWS Credentials for the current session.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android
[X] iOS

**Smartphone (please complete the following information):**
 - Device: iPhone SE Simulator 
 - OS: macOS Big Sur
 - Browser: Stock Browser
 - Version iOS 14

Please help me if you can. I can provide any additional information. I'd love to use this library, but if I can't get the AWS credentials I'll have to try another route. Thanks!

**Comment by haverchuck** [comment] 2020-10-25 04:14
@willstepp Is this happening for you on Android as well?

**Comment by willstepp** [comment] 2020-10-25 14:00
@haverchuck I have since figured this out. There was additional information in the exception for AMPLIFY_FETCH_SESSION_FAILED, which said I had not yet configured an identity pool. Digging into that I learned the option I chose during setup "User Sign-Up & Sign-In only (Best used with a cloud API only)", which I had thought was the correct one for my use case (calling into API Gateway) does not go through the identity pool creation, but the other option does: "User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for images or other con
tent, Analytics, and more)" -- so long story short, I backed out all my changes and went through the setup process again using the latter option, which configured an identity pool, and once I had done that, I was able to call the fetchAuthSession() function and receive AWS credentials.

<img width="816" alt="Screen Shot 2020-10-25 at 9 54 21 AM" src="https://user-images.githubusercontent.com/307240/97109298-db084080-16a8-11eb-9a3d-5224f79cf98c.png">

**Comment by aaronsamkennedy** [comment] 2020-10-25 21:34
I have the same issue, even though the isSignedIn is true in responding from Amplify. I also looked into the e.details and it just said 'See logs for details.' would this be in the flutter logs in AWS? I didn't see anything in cognito or cloudwatch.

**Comment by haverchuck** [comment] 2020-10-26 19:40
@aaronsamkennedy - Thanks for noting the ambiguity with the logs.  These should be logs in the actual application, not AWS.  This should definitely be clarified.

**Comment by haverchuck** [comment] 2020-10-26 20:30
@willstepp Can you please post your amplifyconfiguration.dart (with values removed/redacted)?

**Comment by willstepp** [comment] 2020-10-26 22:51
@haverchuck here is what I **think** it looked like originally, following the setup for "User Sign-Up & Sign-In only (Best used with a cloud API only)". Basically no section for CredentialsManager/CognitoIdentity:

```
const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-1_xxxxxxxxxx",
                        "AppClientId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                        "AppClientSecret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}'''; 
```

**Comment by Ashish-Nanda** [comment] 2020-11-19 18:52
Hi @willstepp @aaronsamkennedy we are working on a fix for this and hope to release it next week.

**Comment by brunovsiqueira** [comment] 2020-11-25 13:41
Hi guys. When the solution is going to be released? Needing it a lot.

**Comment by Ashish-Nanda** [comment] 2020-11-25 18:40
Hi @brunovsiqueira 

We plan to merge the fix this week and do a release early next week.

**Comment by brunovsiqueira** [comment] 2020-12-01 23:09
Hi @Ashish-Nanda. Looking forward for this fix. Any news?

**Comment by Ashish-Nanda** [comment] 2020-12-02 15:36
@brunovsiqueira We plan to release the fix this week. I'll update this thread as soon as the release with the fix is out.

**Comment by Ashish-Nanda** [comment] 2020-12-03 23:00
@brunovsiqueira The fix has been released! Please let us know if you still face the issue.

**Comment by willstepp** [comment] 2020-12-04 19:16
Thank you for the fix and response. I have a workaround in place for this, so it's not easy for me to verify atm.

**Comment by brunovsiqueira** [comment] 2020-12-07 17:39
Hi @Ashish-Nanda. I haven't done all tests I want to but it seems to be working properly.

The only problem is that when I call the Amplify.Auth.signIn method the following exception is raised, even everything seeming to work well (I can get session, tokens, etc):

`[+13605 ms] W/CognitoUserSession(12969): CognitoUserSession is not valid because idToken is null.
[   +3 ms] D/AWSMobileClient(12969): Sending password.
[+1445 ms] D/AWSMobileClient(12969): _federatedSignIn: Putting provider and token in store
[  +29 ms] W/AWSMobileClient(12969): Failed to federate tokens during sign-in
[        ] W/AWSMobileClient(12969): java.lang.Exception: Federation is not enabled, please check if you have CognitoIdentity configured.
[        ] W/AWSMobileClient(12969): 	at com.amazonaws.mobile.client.AWSMobileClient$10.run(AWSMobileClient.java:1696)
[        ] W/AWSMobileClient(12969): 	at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
[        ] W/AWSMobileClient(12969): 	at com.amazonaws.mobile.client.AWSMobileClient.federatedSignInWithoutAssigningState(AWSMobileClient.java:1649)
[        ] W/AWSMobileClient(12969): 	at com.amazonaws.mobile.client.AWSMobileClient$6$1.onSuccess(AWSMobileClient.java:1189)
[        ] W/AWSMobileClient(12969): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$6.onSuccess(CognitoUser.java:1099)
[        ] W/AWSMobileClient(12969): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$29.run(CognitoUser.java:3118)
[        ] W/AWSMobileClient(12969): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$24.run(CognitoUser.java:2965)
[        ] W/AWSMobileClient(12969): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.continuations.AuthenticationContinuation.continueTask(AuthenticationContinuation.java:147)
[        ] W/AWSMobileClient(12969): 	at com.amazonaws.mobile.client.AWSMobileClient$6$1.getAuthenticationDetails(AWSMobileClient.java:1224)
[        ] W/AWSMobileClient(12969): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:1032)
[        ] W/AWSMobileClient(12969): 	at com.amazonaws.mobile.client.AWSMobileClient$6.run(AWSMobileClient.java:1174)
[        ] W/AWSMobileClient(12969): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
[        ] W/AWSMobileClient(12969): 	at java.lang.Thread.run(Thread.java:919)
[+30468 ms] D/AWSMobileClient(12969): Inspecting user state details
[   +3 ms] D/AWSMobileClient(12969): hasFederatedToken: false provider: <MyCognitoPool>`

I don't want to configure CognitoIdentity, it is not necessary in my case. Should I get this Exception anyway?

**Comment by Ashish-Nanda** [comment] 2020-12-08 16:29
@haverchuck are you able to reproduce this?

**Comment by brunovsiqueira** [comment] 2020-12-17 15:45
Hi guys. Any updates?

**Comment by imrikim** [comment] 2020-12-22 19:44
hello @Ashish-Nanda , any updates are available ? please specify the version number :)

**Comment by brunovsiqueira** [comment] 2021-02-10 01:46
Hello @Ashish-Nanda. I am facing this issue in my production environment (0.0.1-dev.4). Can you guys please help me? It is extremely critical, my users cannot refresh session.

**Comment by Amplifiyer** [comment] 2021-02-11 18:38
@brunovsiqueira is this the same issue as https://github.com/aws-amplify/amplify-flutter/issues/370
In your last comment you mentioned you are using 0.0.1-dev.4, are you facing these issues with the latest release as well?

**Closed** 2021-02-11 18:39 UTC
Labels: Auth, investigating, pending-close-response-required
