### ISSUE TITLE
Failed since user is not authorized

### ISSUE THREAD

**Issue by prakash2596** [aws-amplify/amplify-flutter#3048] opened 2023-05-15 12:23 UTC
### Description

NotAuthorizedException(message: Failed since user is not authorized., recoverySuggestion: Check whether the given values are correct and the user is authorized to perform the operation., underlyingException: com.amazonaws.services.cognitoidentityprovider.model.NotAuthorizedException: User password cannot be reset in the current state. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 0d73101a-7d4f-445b-aaae-c5dccaad71fa))

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [x] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.12

### Amplify Flutter Version

0.6.13

### Deployment Method

Amplify CLI

**Comment by HuiSF** [comment] 2023-05-15 16:46
I remember "User password cannot be reset in the current state." would be thrown when call the `forgotPassword` API when the user is at `FORCE_CHANGE_PASSWORD` state. For users who are at this state, they should've received a one-time password, which will be used to sign in, and the next step will be reset password. 

Could you provide details of your Auth configuration, @prakash2596  and check the user state?

**Comment by prakash2596** [comment] 2023-05-16 04:30
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-2:***************",
                            "Region": "us-east-2"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-2_********",
                        "AppClientId": "****************",
                        "Region": "us-east-2"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [],
                        "usernameAttributes": [
                            "EMAIL"
                        ],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}''';

**Comment by Jordan-Nelson** [comment] 2023-05-17 16:39
@prakash2596 can you please provide reproduction steps, including code sample that result in this exception?

Also, I see that you are using Amplify Flutter v0.6.13. I recommend you upgrade to 1.0or higher if possible. 1.0 is written in Dart for all platforms, whereas v0 relied on Amplify iOS and Amplify Android. Moving to a single Dart implementation has allowed us to reduce discrepancies across platforms.

**Comment by Jordan-Nelson** [comment] 2023-05-30 13:44
I am going to close this out since we have not heard back. Let us know if you are still experiencing this issue.

**Closed by Jordan-Nelson** 2023-05-30 13:44 UTC
Labels: pending-close-response-required, Auth, Investigating
