### ISSUE TITLE
Flutter AWS Cognito Token showing invalid signature

### ISSUE THREAD

**Issue by Tapasm1212** [aws-amplify/amplify-flutter#244] opened 2020-12-08 09:46 UTC
I am stared developing a flutter project with AWS Cognito login features. In flutter, AWS Cognito login was working fine and I am getting the access token but when checking that in API or JWT its shows the error "Invalid Signature".

<img width="1677" alt="Screenshot 2020-12-07 at 11 32 04 AM" src="https://user-images.githubusercontent.com/14312152/101467239-119fcf00-3968-11eb-9f89-3b07ebca2818.png">

I add the below code for the AWS Cognito login features. I have installed the amplify_auth_cognito: '<1.0.0' in pubspec.yaml file to create the AWS Cognito login features in the app. Login codes working fine and perfectly but the token which returns from that code shows "Invalid Signature".

`Future<String> _signIn(LoginData data) async {
try {
  SignInResult res = await Amplify.Auth.signIn(
    username: data.name,
    password: data.password,
  );
  final resp = await Amplify.Auth.fetchAuthSession(
    options: CognitoSessionOptions(getAWSCredentials: true),
  );
  if (resp.isSignedIn) {
    final sess = resp as CognitoAuthSession;
    print("TOKEN FROM THE COGNITO: ${sess.userPoolTokens.accessToken}");
  }
  setState(() {
    isSignedIn = res.isSignedIn;
  });
  if (isSignedIn) {
    _btnController.success();
    AWSConfigurationHelper().getUserDetails();

    Timer(Duration(seconds: 1), () {
      _btnController.reset();
      Navigator.pushReplacementNamed(context, DeviceList.routeName);
    });
  }
} on AuthError catch (e) {
  Alert(
    context: context,
    type: AlertType.error,
    title: "Login Failed",
    desc: e.cause.toString(), //e.toString(),
  ).show();

  _btnController.error();

  Timer(Duration(seconds: 1), () {
    _btnController.reset();
  });

  print(e.cause);

  for (final exception in e.exceptionList) {
    print(exception.exception);
    print(exception.detail);
  }

  return 'Log In Error: ' + e.toString();
}}`

My pubspec.yaml file screenshot was attached. In that file I am using amplify_auth_cognito: '<1.0.0' for the Cognito login.

<img width="1366" alt="Screenshot 2020-12-07 at 11 22 11 AM" src="https://user-images.githubusercontent.com/14312152/101467433-5166b680-3968-11eb-8a57-ba0c0f68bd14.png">

I am new to this Flutter so I really need someone help to fix this problem. I have done the AWS Cognito Login features in iOS and web with the same AWS credentials but there I am not getting this type of "Invalid Signature" issue in the access token. Someone, please help me because I am not any good link where this type of issue has been discussed.

Thanks in advance

**Comment by haverchuck** [comment] 2020-12-08 14:54
@Tapasm1212 - Is this happening with the token on both Android and iOS devices?

**Comment by Tapasm1212** [comment] 2020-12-09 07:03
I have created this project only for Android. I have done this iOS project in native Xcode as I am very familiar with iOS mobile app development.  In the iOS project, I have to use the same AWS Credential and I get the proper access token but with that same AWS Credential in the flutter android project, I am not getting the proper access token. 

I am not able to understand why this token issue arises in the flutter android project. I have added the AWS Amplify file details with this.

<img width="1225" alt="Screenshot 2020-12-07 at 11 36 05 AM" src="https://user-images.githubusercontent.com/14312152/101596075-76b3fd00-3a1a-11eb-9eee-bdc62add36af.png">

I need some suggestions and help why this happed in the android flutter project.

Thanks

**Comment by haverchuck** [comment] 2020-12-11 17:45
@Tapasm1212 
1. Is this happening with a newly-created user, immediately after signin? 
2. Have you previously signed in another use without calling signout?  Could you try calling signout be signin, and then try the tokens?

**Comment by RyanHedges** [comment] 2021-01-26 19:11
@Tapasm1212 I thought I was running into this issue too when attempting to validate my token manually. In my case I was printing the token to console, copying it, and pasting it trying to inspect it on jwt.io. Looks like [mobile clients under the hood](https://github.com/flutter/flutter/issues/22665#issuecomment-496130148) limit what's printed so I wasn't getting the entire token. I used [this suggestion](https://github.com/flutter/flutter/issues/22665#issuecomment-458186456) to be able to get the whole token, clean it up, and then I was able to see jwt.io say the signature is valid.

Not sure if that's what you're specifically running into, but putting this here for anyone else that finds this.

**Comment by haverchuck** [comment] 2021-02-17 23:13
@Tapasm1212 Are you still having this issue?

**Comment by haverchuck** [comment] 2021-02-25 20:43
Closing this issue as it appears to be a dupe of #120 .  According to the discussion on this other issue, this problem is a caused by truncation in the logs.  I believe the conversation details some solutions.

**Closed by haverchuck** 2021-02-25 20:43 UTC
Labels: Auth, clarification-needed, investigating, pending-close-response-required

**Comment by ash1497** [comment] 2024-12-09 15:10
> @Tapasm1212 I thought I was running into this issue too when attempting to validate my token manually. In my case I was printing the token to console, copying it, and pasting it trying to inspect it on jwt.io. Looks like [mobile clients under the hood](https://github.com/flutter/flutter/issues/22665#issuecomment-496130148) limit what's printed so I wasn't getting the entire token. I used [this suggestion](https://github.com/flutter/flutter/issues/22665#issuecomment-458186456) to be able to get the whole token, clean it up, and then I was able to see jwt.io say the signature is valid.
> 
> Not sure if that's what you're specifically running into, but putting this here for anyone else that finds this.

This was EXACTLY my issue. Thank you so much for putting it out there for someone to find, I am that someone hahah.
