### ISSUE TITLE
Flutter Web API - No schema found for the ModelType provided

### ISSUE THREAD

**Issue by jobypthomas** [aws-amplify/amplify-flutter#2418] opened 2022-11-26 14:57 UTC
### Description

While prototyping for the new API support for the flutter web, I found an issue when accessing the deployed app. The app works just fine locally. Auth with the Authenticator component works just fine in local and in deployed url. I am using Amplify  hosting. Error is below:
`minified:l3:(message: No schema found for the ModelType provided: minified:lh, recoverySuggestion: Pass in a valid modelProvider instance while instantiating APIPlugin or provide a valid ModelType, underlyingException: null) `

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Deploy using Github actions and Amplify Hosting.

### Screenshots

<img width="636" alt="Screen Shot 2022-11-26 at 7 40 53 AM" src="https://user-images.githubusercontent.com/5605476/204095048-e9b7465a-336f-4a5b-8339-f5dec88af136.png">

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.8, on macOS 11.7.1 20G918 darwin-x64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS (Xcode 13.2)
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.72.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.
```

### Dependencies

```bash
Dart SDK 2.18.4
Flutter SDK 3.3.8
amplify_grocery_list 1.0.0+1

dependencies:
- amplify_api 1.0.0-next.1 [amplify_api_android amplify_api_ios amplify_core amplify_flutter async aws_common collection connectivity_plus flutter json_annotation meta plugin_platform_interface web_socket_channel]
- amplify_auth_cognito 1.0.0-next.1 [amplify_auth_cognito_android amplify_auth_cognito_dart amplify_auth_cognito_ios amplify_core amplify_flutter amplify_secure_storage async flutter flutter_web_plugins meta path plugin_platform_interface]
- amplify_authenticator 1.0.0-next.1 [amplify_auth_cognito amplify_core amplify_flutter async aws_common collection flutter flutter_localizations intl meta smithy stream_transform]
- amplify_flutter 1.0.0-next.1+1 [amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios amplify_secure_storage aws_common collection flutter meta plugin_platform_interface]
- amplify_storage_s3 1.0.0-next.1+1 [amplify_core amplify_db_common amplify_storage_s3_dart aws_common flutter meta path_provider]
- collection 1.16.0
- file_picker 5.2.2 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

transitive dependencies:
- amplify_api_android 1.0.0-next.1 [flutter]
- amplify_api_ios 1.0.0-next.1 [amplify_core flutter]
- amplify_auth_cognito_android 1.0.0-next.1 [flutter]
- amplify_auth_cognito_dart 0.2.4 [amplify_core amplify_secure_storage_dart async aws_common aws_signature_v4 built_collection built_value collection convert crypto fixnum http intl js json_annotation meta oauth2 path smithy smithy_aws stream_transform uuid worker_bee]
- amplify_auth_cognito_ios 1.0.0-next.1 [amplify_core flutter]
- amplify_core 1.0.0-next.1 [async aws_common aws_signature_v4 collection intl json_annotation logging meta retry uuid]
- amplify_datastore_plugin_interface 1.0.0-next.1 [amplify_core collection flutter meta]
- amplify_db_common 0.1.1 [amplify_db_common_dart drift flutter path path_provider]
- amplify_db_common_dart 0.1.1 [amplify_core async aws_common drift meta path sqlite3]
- amplify_flutter_android 1.0.0-next.1 [flutter]
- amplify_flutter_ios 1.0.0-next.1 [amplify_core flutter]
- amplify_secure_storage 0.1.3 [amplify_secure_storage_dart async file flutter meta path path_provider]
- amplify_secure_storage_dart 0.1.3 [async aws_common built_collection built_value ffi file js meta path win32 worker_bee]
- amplify_storage_s3_dart 0.1.1 [amplify_core amplify_db_common_dart async aws_common aws_signature_v4 built_collection built_value drift fixnum meta path smithy smithy_aws]
- args 2.3.1
- async 2.9.0 [collection meta]
- aws_common 0.3.2 [async built_collection built_value collection http2 js json_annotation logging meta os_detect path stream_transform uuid]
- aws_signature_v4 0.3.0 [async aws_common collection convert crypto json_annotation meta path]
- built_collection 5.1.1
- built_value 8.4.2 [built_collection collection fixnum meta]
- characters 1.2.1
- clock 1.1.1
- connectivity_plus 2.3.9 [flutter connectivity_plus_platform_interface connectivity_plus_linux connectivity_plus_macos connectivity_plus_web connectivity_plus_windows]
- connectivity_plus_linux 1.3.1 [flutter connectivity_plus_platform_interface meta nm]
- connectivity_plus_macos 1.2.6 [connectivity_plus_platform_interface flutter]
- connectivity_plus_platform_interface 1.2.3 [flutter meta plugin_platform_interface]
- connectivity_plus_web 1.2.5 [connectivity_plus_platform_interface flutter_web_plugins flutter js]
- connectivity_plus_windows 1.2.2 [connectivity_plus_platform_interface flutter]
- convert 3.1.1 [typed_data]
- crclib 3.0.0 [meta tuple]
- crypto 3.0.2 [typed_data]
- dbus 0.7.8 [args ffi meta xml]
- drift 2.2.0 [async convert collection js meta stream_channel sqlite3]
- ffi 2.0.1
- file 6.1.4 [meta path]
- fixnum 1.0.1
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_plugin_android_lifecycle 2.0.7 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http 0.13.5 [async http_parser meta path]
- http2 2.0.1
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.4
- json_annotation 4.7.0 [meta]
- logging 1.1.0
- material_color_utilities 0.1.5
- meta 1.8.0
- nm 0.5.0 [dbus]
- oauth2 2.0.1 [collection crypto http http_parser]
- os_detect 2.0.1
- path 1.8.2
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.22 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.5 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.3 [ffi flutter path path_provider_platform_interface win32]
- petitparser 5.1.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.3 [meta]
- process 4.2.4 [file path platform]
- retry 3.1.0
- shelf 1.4.0 [async collection http_parser path stack_trace stream_channel]
- sky_engine 0.0.99
- smithy 0.3.0 [async aws_common built_collection built_value collection convert crypto fixnum http_parser intl json_annotation meta path retry shelf typed_data xml]
- smithy_aws 0.3.0 [aws_common aws_signature_v4 built_collection built_value collection convert crclib crypto intl json_annotation meta path smithy xml]
- source_span 1.9.0 [collection path term_glyph]
- sqlite3 1.9.1 [collection ffi js meta path]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.1.0
- string_scanner 1.1.1 [source_span]
- term_glyph 1.2.1
- tuple 2.0.1
- typed_data 1.3.1 [collection]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
- web_socket_channel 2.2.0 [async crypto stream_channel]
- win32 3.1.1 [ffi]
- worker_bee 0.1.2 [async aws_common built_collection built_value collection js meta path stack_trace stream_channel stream_transform]
- xdg_directories 0.2.0+2 [meta path process]
- xml 6.1.0 [collection meta petitparser]
```

### Device

Chrome and Safari

### OS

N/A

### Deployment Method

Amplify CLI

### CLI Version

10.4.0

### Amplify Config

const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-1:xxx",
                            "Region": "us-east-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-1xxx",
                        "AppClientId": "xxx",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [],
                        "usernameAttributes": [
                            "EMAIL"
                        ],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "xxx/graphql",
                        "Region": "us-east-1",
                        "AuthMode": "AMAZON_COGNITO_USER_POOLS",
                        "ClientDatabasePrefix": "xxx_AMAZON_COGNITO_USER_POOLS"
                    }
                },
                "S3TransferUtility": {
                    "Default": {
                        "Bucket": "xxx-dev",
                        "Region": "us-east-1"
                    }
                }
            }
        }
    },
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "amplifygrocerylist": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://xxx.amazonaws.com/graphql",
                    "region": "us-east-1",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    },
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "xxx-dev",
                "region": "us-east-1",
                "defaultAccessLevel": "guest"
            }
        }
    }
}''';

**Comment by dnys1** [comment] 2022-11-27 17:31
Duplicate of https://github.com/aws-amplify/amplify-flutter/issues/2330.

Sorry you are facing this issue, @jobypthomas. This has been fixed and is currently pending a release in the Amplify CLI. I will update #2330 when that fix is released.

**Closed by dnys1** 2022-11-27 17:31 UTC

**Comment by finkmoritz** [comment] 2022-12-09 22:16
So now amplify-cli 10.5.2 has been released, containing mentioned fix, i.e. "amplify-codegen": "^3.3.2".

I faced the same issue before (with 10.5.1) and unfortunately, **I am still facing the originally reported issue with the new version.**

I am using the newest web preview dependencies:
  amplify_api: ^1.0.0-next.2
  amplify_datastore: ^1.0.0-next.2
  amplify_flutter: ^1.0.0-next.2

In general, I just performed following steps for updating and testing:
1. npm install -g @aws-amplify/cli
2. flutter clean
3. flutter pub get
4. flutter codegen models
5. flutter build web
6. cd build/web
7. python -m http.server 8000
8. Tested app in Chrome and Firefox

The only difference I can see in the generated model code is an added Map<String, Object?> toMap() method.

@jobypthomas Can you please also check if the fix works for you? Maybe I am just missing something else...

**Comment by finkmoritz** [comment] 2022-12-09 22:35
Ok, I could manually fix it by overriding the String modelName() method for each of my model classes. As I understood this should have been fixed in codegen.

Anyway, for everyone that needs a quick workaround, perform following steps for each generated model class:
1. Find the class extending ModelType at the end of the file
2. Add a method that returns the type name as String, e.g.:
```@override
  String modelName() {
    return 'Post';
  }```

Attention: If you run codegen, you have to do the changes again (of course).

**Comment by jobypthomas** [comment] 2022-12-10 11:37
@finkmoritz @dnys1 @abdallahshaban557 I am confirming that the code fix in amplify-cli [10.5.2](https://github.com/aws-amplify/amplify-cli/releases/tag/v10.5.2) did not resolve the issue :(

**Comment by jobypthomas** [comment] 2022-12-30 18:35
@dnys1 @abdallahshaban557 @finkmoritz @Amplifiyer any updates on the release of the fix?

**Comment by abdallahshaban557** [comment] 2023-01-03 20:23
Hi @jobypthomas  - we will provide updates on issue #2330. Our fix is ready and will be released ASAP. We will provide an update when a solid ETA is available.
