### ISSUE TITLE
Gen2 - Quick Start guide does not work - ConfigurationError: The provided configuration is not a valid json

### ISSUE THREAD

**Issue by naedx** [aws-amplify/amplify-flutter#4920] opened 2024-05-24 23:21 UTC
### Description

I am following the [quickstart page](https://docs.amplify.aws/flutter/start/quickstart/). Everything works up to creating the sandbox environment with `npx ampx sandbox --outputs-format dart --outputs-out-dir lib`. From here, I have the `data` category and `auth` category defined in my `amplify_outputs.dart` (aside: the cli prints that it has written amplify_outputs.JSON).

When starting the application the following error is thrown:

```
ConfigurationError (ConfigurationError {
  "message": "The provided configuration is not a valid json. Check underlyingException.",
  "recoverySuggestion": "Inspect your amplifyconfiguration.dart and ensure that the string is proper json"
})
```

at line 23 of ['amplify_config.g.dart':](https://github.com/aws-amplify/amplify-flutter/blob/4dc0df53942f3d536c6162402aa5705b1d5c41d7/packages/amplify_core/lib/src/config/amplify_config.g.dart#L23)

```dart

part of 'amplify_config.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

AmplifyConfig _$AmplifyConfigFromJson(Map<String, dynamic> json) =>
    AmplifyConfig(
      userAgent: json['UserAgent'] as String? ?? 'aws-amplify-cli/2.0',
      version: json['Version'] as String? ?? '1.0',
      api: json['api'] == null
          ? null
          : ApiConfig.fromJson(json['api'] as Map<String, dynamic>),
      analytics: json['analytics'] == null
          ? null
          : AnalyticsConfig.fromJson(json['analytics'] as Map<String, dynamic>),
      auth: json['auth'] == null
          ? null
          : AuthConfig.fromJson(json['auth'] as Map<String, dynamic>), // <<<<<<<<<< here
      notifications: json['notifications'] == null
          ? null
          : NotificationsConfig.fromJson(
              json['notifications'] as Map<String, dynamic>),
      storage: json['storage'] == null
          ? null
          : StorageConfig.fromJson(json['storage'] as Map<String, dynamic>),
    );


```

I removed the configuration for "data" to simplify the project which yields:

amplify_outputs.dart
```dart
const amplifyConfig = '''{
  "auth": {
    "user_pool_id": "XXXXXXX",
    "aws_region": "XXXXXXX",
    "user_pool_client_id": "XXXXXXX",
    "identity_pool_id": "XXXXXXX:XXXXXXX",
    "standard_required_attributes": [
      "email"
    ],
    "username_attributes": [
      "email"
    ],
    "user_verification_types": [
      "email"
    ],
    "password_policy": {
      "min_length": 8,
      "require_numbers": true,
      "require_lowercase": true,
      "require_uppercase": true,
      "require_symbols": true
    },
    "unauthenticated_identities_enabled": true
  },
  "version": "1"
}''';
```

This still produces the error.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Create a [skeleton flutter project ](https://docs.flutter.dev/get-started/test-drive#create-app-vs-code)
2. Init an [Amplify Gen2 project following the quickstart guide](https://docs.amplify.aws/flutter/start/quickstart/) 
3. Observe that `amplify_outputs.dart` is generated as above.
4. Observe that the error is thrown as above

### Platforms

- [ ] iOS
- [X] Android
- [X] Web
- [X] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

 3.19.0

### Amplify Flutter Version

2.0.0

### Deployment Method

Amplify CLI

**Comment by naedx** [comment] 2024-05-24 23:35
Also, I've also noticed that the `AmplifyConfig` class looks for the configuration for AppSync using the key "api" instead of "data" key which is in the generated config .dart file. Is this a bug?

<details>

```dart
//amplify_config.g.dart

AmplifyConfig _$AmplifyConfigFromJson(Map<String, dynamic> json) =>
    AmplifyConfig(
      userAgent: json['UserAgent'] as String? ?? 'aws-amplify-cli/2.0',
      version: json['Version'] as String? ?? '1.0',
      api: json['api'] == null
          ? null
          : ApiConfig.fromJson(json['api'] as Map<String, dynamic>),                                <<<<< here
      analytics: json['analytics'] == null
          ? null
          : AnalyticsConfig.fromJson(json['analytics'] as Map<String, dynamic>),
      auth: json['auth'] == null
          ? null
          : AuthConfig.fromJson(json['auth'] as Map<String, dynamic>),
      notifications: json['notifications'] == null
          ? null
          : NotificationsConfig.fromJson(
              json['notifications'] as Map<String, dynamic>),
      storage: json['storage'] == null
          ? null
          : StorageConfig.fromJson(json['storage'] as Map<String, dynamic>),
    );

```


const amplifyConfig = '''{
  "auth": {
    "user_pool_id": "XXXXXXX",
    "aws_region": "XXXXXXX",
    "user_pool_client_id": "XXXXXXX",
    "identity_pool_id": "XXXXXXX:XXXXXXX",
    "standard_required_attributes": [
      "email"
    ],
    "username_attributes": [
      "email"
    ],
    "user_verification_types": [
      "email"
    ],
    "password_policy": {
      "min_length": 8,
      "require_numbers": true,
      "require_lowercase": true,
      "require_uppercase": true,
      "require_symbols": true
    },
    "unauthenticated_identities_enabled": true
  },
  "data": {
    "url": "XXXXXXX.amazonaws.com/graphql",
    "aws_region": "XXXXXXX",
    "default_authorization_type": "AWS_IAM",
    "authorization_types": [
      "AMAZON_COGNITO_USER_POOLS"
    ],
    "model_introspection": {
      "version": 1,
      "models": {
        "Todo": {
          "name": "Todo",
          "fields": {
            "id": {
              "name": "id",
              "isArray": false,
              "type": "ID",
              "isRequired": true,
              "attributes": []
            },
            "content": {
              "name": "content",
              "isArray": false,
              "type": "String",
              "isRequired": false,
              "attributes": []
            },
            "createdAt": {
              "name": "createdAt",
              "isArray": false,
              "type": "AWSDateTime",
              "isRequired": false,
              "attributes": [],
              "isReadOnly": true
            },
            "updatedAt": {
              "name": "updatedAt",
              "isArray": false,
              "type": "AWSDateTime",
              "isRequired": false,
              "attributes": [],
              "isReadOnly": true
            }
          },
          "syncable": true,
          "pluralName": "Todos",
          "attributes": [
            {
              "type": "model",
              "properties": {}
            },
            {
              "type": "auth",
              "properties": {
                "rules": [
                  {
                    "allow": "public",
                    "provider": "iam",
                    "operations": [
                      "create",
                      "update",
                      "delete",
                      "read"
                    ]
                  }
                ]
              }
            }
          ],
          "primaryKeyInfo": {
            "isCustomPrimaryKey": false,
            "primaryKeyFieldName": "id",
            "sortKeyFieldNames": []
          }
        }
      },
      "enums": {},
      "nonModels": {}
    }
  },
  "version": "1"
}''';
</details>

**Comment by naedx** [comment] 2024-05-25 00:51
I have found the issue. The command to generate the config file for the sandbox environment must include ` --outputs-version 0` when using flutter. Therefore the full command becomes:

`npx ampx sandbox --outputs-format dart --outputs-out-dir lib --outputs-version 0` 

I've proposed a [pull request](https://github.com/aws-amplify/docs/pull/7660) to clarify this in the docs.

**Comment by Jordan-Nelson** [comment] 2024-05-28 17:11
@naedx - Thanks for raising the issue and the PR. I am going to close this as a duplicate of https://github.com/aws-amplify/docs/issues/7495

**Closed by Jordan-Nelson** 2024-05-28 17:11 UTC
