### ISSUE TITLE
type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast in utils.dart [amplify_api_dart]

### ISSUE THREAD

**Issue by Laebrye** [aws-amplify/amplify-flutter#4129] opened 2023-11-14 20:08 UTC
### Description

Have hit an error this evening where type conversion isn't null safe. Not sure if something has gone wrong with my model or if I'm misinterpreting things, but the error reported by Sentry is on line 175 of the above file (https://github.com/aws-amplify/amplify-flutter/blob/main/packages/api/amplify_api_dart/lib/src/graphql/utils.dart) 

If you look at line 120 of that file, there's a similar mapping operation happening on a list there, but there's a null check in there before the cast is attempted. I think lines 146 and 174 9and potentially 156) could do with similar null checks.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Not sure exactly what caused this issue, whether there was a network interruption that reulted in some data being unexpectedly null or something else happening.

All I'm trying to do is read data over the API

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.9

### Amplify Flutter Version

1.4.0

### Deployment Method

Amplify CLI

**Comment by Equartey** [comment] 2023-11-15 15:35
Hey @Laebrye 

Thanks for reporting this. 

I assume you are seeing this in a deployed app, are you seeing multiple instances of this error?

Do you have the response that triggers the error?

**Comment by Laebrye** [comment] 2023-11-15 21:12
Hi, 

Yes this was in a deployed app.

I don't have the response that triggered the error sadly. I wasn't debugging and the info I have right now is purely from my sentry report (which truth be told I'm still trying to get my head around)

Thanks for the speedy response

**Comment by Equartey** [comment] 2023-11-16 19:27
@Laebrye understood. We'll continue to look into this.

Please let us know if you are able to get reproduction steps or the response that triggered the error.

**Comment by Equartey** [comment] 2023-11-16 19:31
@Laebrye also could you please provide the request being made? And your `schema.graphql` file?

**Comment by Laebrye** [comment] 2023-11-19 19:42
Hi. Unfortunately, I'm not in a position to share the schema as we're a fledgling company and consider the data model to be an important part of our USP, as well as giving away an important upcoming feature.

I'll keep trying to reproduce the issue. I was debugging something else today and hit an error that may or may not be related. Will update you when I know for sure.

**Comment by sweeneyartstudio** [comment] 2023-12-19 12:26
Hi. I am also having similar issues on the same error message you are experiencing.
Null' is not a subtype of type 'Map<String, dynamic>' in type cast
Please can anyone help me out in fixing the issue. I will really appreciate it.
Please find attached a screenshot of the error message.

![Null Safety error](https://github.com/aws-amplify/amplify-flutter/assets/66186688/b8affd27-5773-4d6c-ab02-e4d44556ac0d)

**Comment by Equartey** [comment] 2023-12-19 21:23
Hi @sweeneyartstudio, 

I'm not sure what's going given the screenshot. Can you provide more context: 

1. Provide the entire error log including the stack trace
2. GraphQL Schema of the model 
3. The Request being made
4. Any additional instructions on how to reproduce the error

**Comment by sweeneyartstudio** [comment] 2023-12-19 21:25
Ok. I will send that. Thanks

**Comment by Equartey** [comment] 2024-01-25 18:51
Hi @Laebrye are you still experiencing this issue? If so, can you provide the extra context request?

**Comment by abdushkur** [comment] 2024-01-30 00:03
I'm facing same thing in different situation and I think I know the reason,
I have API that returns json, one of the value is null,
_result.data!['articles']
        .map<ArticleModel>((dynamic i) => ArticleModel.fromJson(i as Map<String, dynamic>))
so when this code executed ,"map" lambda expresstion to be specific, when trying to cast its value to dynamic, exception  will be thrown

**Comment by sweeneyartstudio** [comment] 2024-01-30 09:36
I have resolved it though. Thanks a lot!!

**Comment by Equartey** [comment] 2024-02-05 22:26
@abdushkur this sounds like an issue currently being tracked in this issue: https://github.com/aws-amplify/amplify-flutter/issues/816 

@Laebrye I'm going to close this issue for now, please comment or open a new issue if you run into this issue again.

**Closed by Equartey** 2024-02-05 22:26 UTC
Labels: pending-close-response-required, GraphQL API
