### ISSUE TITLE
amplify_storage_s3 faces timeout issue for slow internet

### ISSUE THREAD

**Issue by absarrahman** [aws-amplify/amplify-flutter#802] opened 2021-08-12 09:14 UTC
**Describe the bug**
Basically the storage fails to load the file because of slow internet. As a result the it fails to load the data

**To Reproduce**

After the app starts, the data starts loading and during that time the timeout occurs. Possible reason is due to slow bandwidth. 

**Expected behavior**
The data was supposed to load. 

**Screenshots**

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android

<details>

  <summary>LOGCAT</summary>
 `
E/amplify:flutter:storage_s3( 9460): StorageException
E/amplify:flutter:storage_s3( 9460): StorageException{message=Something went wrong with your AWS S3 Storage download file operation, cause=com.amazonaws.AmazonClientException: SocketTimeoutException: Unable to retrieve contents over network: timeout, recoverySuggestion=See attached exception for more information and suggestions}
E/amplify:flutter:storage_s3( 9460): 	at com.amplifyframework.storage.s3.operation.AWSS3StorageDownloadFileOperation$DownloadTransferListener.onError(AWSS3StorageDownloadFileOperation.java:191)
E/amplify:flutter:storage_s3( 9460): 	at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$4.run(TransferStatusUpdater.java:306)
E/amplify:flutter:storage_s3( 9460): 	at android.os.Handler.handleCallback(Handler.java:907)
E/amplify:flutter:storage_s3( 9460): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/amplify:flutter:storage_s3( 9460): 	at android.os.Looper.loop(Looper.java:223)
E/amplify:flutter:storage_s3( 9460): 	at android.app.ActivityThread.main(ActivityThread.java:7478)
E/amplify:flutter:storage_s3( 9460): 	at java.lang.reflect.Method.invoke(Native Method)
E/amplify:flutter:storage_s3( 9460): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
E/amplify:flutter:storage_s3( 9460): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
E/amplify:flutter:storage_s3( 9460): Caused by: com.amazonaws.AmazonClientException: SocketTimeoutException: Unable to retrieve contents over network: timeout
E/amplify:flutter:storage_s3( 9460): 	at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.saveToFile(DownloadTask.java:198)
E/amplify:flutter:storage_s3( 9460): 	at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:111)
E/amplify:flutter:storage_s3( 9460): 	at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:42)
E/amplify:flutter:storage_s3( 9460): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/amplify:flutter:storage_s3( 9460): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/amplify:flutter:storage_s3( 9460): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/amplify:flutter:storage_s3( 9460): 	at java.lang.Thread.run(Thread.java:923)
E/amplify:flutter:storage_s3( 9460): Caused by: java.net.SocketTimeoutException: timeout
E/amplify:flutter:storage_s3( 9460): 	at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:214)
E/amplify:flutter:storage_s3( 9460): 	at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:263)
E/amplify:flutter:storage_s3( 9460): 	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
E/amplify:flutter:storage_s3( 9460): 	at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:51)
E/amplify:flutter:storage_s3( 9460): 	at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:395)
E/amplify:flutter:storage_s3( 9460): 	at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:372)
E/amplify:flutter:storage_s3( 9460): 	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:73)
E/amplify:flutter:storage_s3( 9460): 	at com.amazonaws.services.s3.model.S3ObjectInputStream.read(S3ObjectInputStream.java:126)
E/amplify:flutter:storage_s3( 9460): 	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:73)
E/amplify:flutter:storage_s3( 9460): 	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:73)
E/amplify:flutter:storage_s3( 9460): 	at com.amazonaws.event.ProgressReportingInputStream.read(ProgressReportingInputStream.java:132)
E/amplify:flutter:storage_s3( 9460): 	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:73)
E/amplify:flutter:storage_s3( 9460): 	at com.amazonaws.util.LengthCheckInputStream.read(LengthCheckInputStream.java:99)
E/amplify:flutter:storage_s3( 9460): 	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:73)
E/amplify:flutter:storage_s3( 9460): 	at com.amazonaws.services.s3.model.S3ObjectInputStream.read(S3ObjectInputStream.java:126)
E/amplify:flutter:storage_s3( 9460): 	at com.amazonaws.services.s3.model.S3ObjectInputStream.read(S3ObjectInputStream.java:118)
E/amplify:flutter:storage_s3( 9460): 	at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.saveToFile(DownloadTask.java:191)
E/amplify:flutter:storage_s3( 9460): 	... 6 more
E/amplify:flutter:storage_s3( 9460): Caused by: java.net.SocketException: Socket closed
E/amplify:flutter:storage_s3( 9460): 	at java.net.SocketInputStream.read(SocketInputStream.java:209)
E/amplify:flutter:storage_s3( 9460): 	at java.net.SocketInputStream.read(SocketInputStream.java:144)
E/amplify:flutter:storage_s3( 9460): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:898)
E/amplify:flutter:storage_s3( 9460): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:862)
E/amplify:flutter:storage_s3( 9460): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:777)
E/amplify:flutter:storage_s3( 9460): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:750)
E/amplify:flutter:storage_s3( 9460): 	at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
E/amplify:flutter:storage_s3( 9460): 	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
E/amplify:flutter:storage_s3( 9460): 	... 20 more
`

</details>

**Smartphone (please complete the following information):**
 - Device: Pixel 3 API R
 - OS: Android R

**Comment by absarrahman** [comment] 2021-08-12 09:18
![image](https://user-images.githubusercontent.com/35573458/129172061-3d5ea6c5-0aab-4d51-a77e-dcb227828fa5.png)

**Comment by Jordan-Nelson** [comment] 2021-08-12 16:34
Hello @absarrahman - This looks like a duplicate of https://github.com/aws-amplify/amplify-flutter/issues/774. Do you mind adding the logs in a comment on that issue so that they can be tracked on one spot? Info about the file size and network bandwidth would be helpful as well.

I am going to close this out as a duplicate.

**Closed by Jordan-Nelson** 2021-08-12 16:34 UTC
Labels: duplicate, Storage
