### ISSUE TITLE
[Amplify Storage] [uploadFile] uploading a medium/large size file takes too much time 

### ISSUE THREAD

**Issue by delfme** [aws-amplify/amplify-flutter#4097] opened 2023-11-09 09:34 UTC
### Description

Uploading a file takes huge time when file is bigger than 2-3MB.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Steps to Reproduce

Use sample https://github.com/delfme/sample_demo_amplify

**Configure code before run:**
Add your bucket here
https://github.com/delfme/sample_demo_amplify/blob/076064605de3fbb88f7ba798b372af202537f4ce/lib/main.dart#L53

Configure your amplify settings here
https://github.com/delfme/sample_demo_amplify/blob/main/lib/aws/amplify_configuration.dart

**How to reproduce issue**
1) tap button 1 to download a 2MB image and 10MB video from web
2) tap button 3 to upload video. It can be noticed that it takes huge time.

Note: 
Sample code is not printing time due to bug https://github.com/aws-amplify/amplify-flutter/issues/4095
However, issue is noticeable by looking at progress logs and sometimes uploads even stalls. 
Also, you can workarounding 4095 by force waiting a wrapping func and print upload time this way.

Maybe it is also intertwined with issue https://github.com/aws-amplify/amplify-flutter/issues/3968

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

Channel master, 3.17.0-1.0.pre.37

### Amplify Flutter Version

1.6.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment] 2023-11-09 20:54
@delfme - I am seeing 350-400ms for the 2mb file and 1,000-1,100ms for the 10mb file. Is this roughly what you are seeing?

**Comment by delfme** [comment] 2023-11-09 21:08
I'm seeing mostly 1000-2500ms with a worst case of 6-7000ms

**Comment by Jordan-Nelson** [comment] 2023-11-09 21:12
> I'm seeing mostly 1000-2500ms with a worst case of 6-7000ms

Are both those times for the 10mb file?

**Comment by delfme** [comment] 2023-11-09 21:26
yes

**Comment by Jordan-Nelson** [comment] 2023-11-09 22:15
Okay. That is a pretty large range. I am pretty consistently seeing between 1,000-1,100ms with an occasional request closer to 1,200ms.

Is it possible that you are on a network connection that is not very consistent?

What time are you seeing for the 2mb file?

**Comment by delfme** [comment] 2023-11-09 23:25
With a native plugin I get 1000ms, network is okay, I think it might be a dart issue

**Comment by delfme** [comment] 2023-11-09 23:32
@Jordan-Nelson Sorry for asking this here, but can you explain why I cannot pass auth token inside headers when using a standard http client?
```
...
        headers: {
          'authorization': 'Bearer $sessionToken',
```

For sessionToken I tried both
1)
` final sessionToken = await auth.credentialsResult.value.sessionToken!;`
and
2)
```
  final auth = await Amplify.Auth.fetchAuthSession() as CognitoAuthSession;
  final sessionToken = (auth as CognitoAuthSession).userPoolTokensResult.value.idToken;
```

With 1) I get api auth error (so I guess I'm not supposed to pass that token) 

And with 2) I get
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SignedOutException {
  "message": "No user is currently signed in"
}
which is thrown on `userPoolTokensResult.value.idToken;`

**Comment by Jordan-Nelson** [comment] 2024-01-09 16:19
@delfme thanks for the info. I was not able to reproduce the longer times that your are seeing. It is certainly possible that the call times will be different from native versus Dart. If you can create a reproduction of the issue we can investigate more. Without a reproduction of the issue I will close this out as I have been unable to reproduce and their could be many other factor at play with slow network times.

**Comment by Jordan-Nelson** [comment] 2024-01-16 16:06
@delfme I am going to close this out since we have been unable to reproduce and have not heard back. If you are able to provide a minimal reproduction we can reopen the issue. Thanks.

**Closed by Jordan-Nelson** 2024-01-16 16:06 UTC
Labels: pending-close-response-required, storage, Investigating
