### ISSUE TITLE
I can't upload file with flutter i received this erreor "UPLOAD_FILE_OPERATION_FAILED"

### ISSUE THREAD

**Issue by eroamba** [aws-amplify/amplify-flutter#377] opened 2021-02-11 12:12 UTC
Hi, I want to upload file with amplify.I tried all video and Tuto but didn't worked .I received This error "UPLOAD_FILE_OPERATION_FAILED". This is my code and my configuration amplify    

```dart
void _configureAmplify() async { 

    Amplify.addPlugin(AmplifyAuthCognito());
    Amplify.addPlugins([AmplifyStorageS3()]);

    await Amplify.configure(amplifyconfig);

    try {
      setState(() {
        _amplifyConfigured = true;
      });

      print("Connexion est ok");
    } catch (e) {
      print(e);
    }
  }
 void uploadFile(File value) async {
   
    File path = File('assets/images/hi.txt');

    final key = "amplify-cfn-templates/storage/s3-cloudformation-template.json";
    Map<String, String> metadata = <String, String>{};
    metadata['name'] = 'filename';
    metadata['desc'] = 'A test file';
    S3UploadFileOptions options = S3UploadFileOptions(
        accessLevel: StorageAccessLevel.guest, metadata: metadata);
    try {
      UploadFileResult result = await Amplify.Storage.uploadFile(
          key: key, local: path, options: options);
      print(result);
    } catch (e) {
      print(e.toString());
    }
  }
```

**This my amplify configuration:** 

```dart
const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-1:6f876558-b8de-42aa-8c2a-f2aa408ff87e",
                            "Region": "us-east-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-1_8mnJYZJue",
                        "AppClientId": "6knt93qd0248u6qfp975rljqv5",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                },
                "S3TransferUtility": {
                    "Default": {
                        "Bucket": "trancheadvance38ee8026503b40f9a60a72d2d0f9657920619-dev",
                        "Region": "us-east-1"
                    }
                }
            }
        }
    },
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "trancheadvance38ee8026503b40f9a60a72d2d0f9657920619-dev",
                "region": "us-east-1",
                "defaultAccessLevel": "guest"
            }
        }
    }
}'''; 
```

*I would like to know , should I Configurate authCognito login and password first?** 
Thanks

**Comment by Ashish-Nanda** [comment] 2021-02-15 17:57
@eroamba What version of the library are you using. 
Also can you share he error details so we can see the underlying reason why the error occurred?

**Comment by eroamba** [comment] 2021-02-15 19:23
Hi ,this is my code error and my function upload
StorageException
runtimeType:Type (StorageException)
hashCode:17530881
message:"UPLOAD_FILE_OPERATION_FAILED"
details:Map (1 item)
code:"UPLOAD_FILE_FAILED"
```
 void uploadFile(File value) async {
 
    File path = File('assets/images/hi.txt');

    final key = "amplify-cfn-templates/storage/s3-cloudformation-template.json";
    Map<String, String> metadata = <String, String>{};
    metadata['name'] = 'filename';
    metadata['desc'] = 'A test file';
    S3UploadFileOptions options = S3UploadFileOptions(
        accessLevel: StorageAccessLevel.guest, metadata: metadata);
    try {
      UploadFileResult result = await Amplify.Storage.uploadFile(
          key: key, local: path, options: options);
      print(result);
    } catch (e) {
      print(e.toString());
    }
  } 
```

**Comment by NimaSoroush** [comment] 2021-02-15 19:32
I have similar issue.
I confirm that my setup works perfectly fine on IOS but android fails with above error

**Comment by eroamba** [comment] 2021-02-26 12:20
@NimaSoroush can you solve the problem with android amplify storage?I have always the same problem

**Comment by Ashish-Nanda** [comment] 2021-03-05 12:02
@eroamba The error message here is from an older version of the library. 

Can you delete your `pubspec.lock` file and run a `flutter pub get` once again.

@NimaSoroush are you facing this on `0.1.0` as well?

**Comment by NimaSoroush** [comment] 2021-03-05 12:06
@Ashish-Nanda : No I'm on 0.0.2

```
  amplify_flutter: "0.0.2-dev.1"
  amplify_auth_cognito: "0.0.2-dev.1"
  amplify_analytics_pinpoint: "0.0.2-dev.1"
  amplify_storage_s3: "0.0.2-dev.1"
```

**Comment by offlineprogrammer** [comment] 2021-05-05 19:36
Hi @NimaSoroush & @eroamba 

I tested this on Android (Pixel 3 XL phone) and couldn't reproduce it ... below is my code


```dart
File local = await FilePicker.getFile(type: FileType.image);
    local.existsSync();

    final key = "amplify-cfn-templates/storage/s3-cloudformation-template.json";
    Map<String, String> metadata = <String, String>{};
    metadata['name'] = 'filename';
    metadata['desc'] = 'A test file';
    S3UploadFileOptions options = S3UploadFileOptions(
        accessLevel: StorageAccessLevel.guest, metadata: metadata);
    try {
      UploadFileResult result = await Amplify.Storage.uploadFile(
          key: key, local: local, options: options);
      print('File uploaded.  Key: ' + result.key);
      Navigator.pop(context, result.key);
    } catch (e) {
      print('UploadFile Err: ' + e.toString());
    }
```

I am using the following on pubspec.yaml

```xml

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^1.8.0+1
  amplify_flutter: 0.1.0
  amplify_auth_cognito: 0.1.0
  amplify_analytics_pinpoint: 0.1.0
  amplify_storage_s3: 0.1.0

```

Please check our example app ([here](https://github.com/aws-amplify/amplify-flutter/tree/master/example)) for a working file upload function

Feel free to test using the latest build and let us know if you got any issues

Thanks
Mo

**Comment by NimaSoroush** [comment] 2021-05-05 22:02
This has been resolved for me using newer version of packages. Thanks @offlineprogrammer

**Comment by offlineprogrammer** [comment] 2021-05-21 16:38
Hey @NimaSoroush & @eroamba

I am closing this issue for now as I couldn't reproduce as per my comment above.
We can reopen it if you are still facing the issue and when you provide details

Regards
Mo

**Closed by offlineprogrammer** 2021-05-21 16:38 UTC
Labels: Storage, pending-close-response-required

**Comment by offlineprogrammer** [comment] 2021-05-21 17:34
> This has been resolved for me using newer version of packages. Thanks @offlineprogrammer

Thanks for the confirmation @NimaSoroush
