### ISSUE TITLE
DataStoreException

### ISSUE THREAD

**Issue by sandeepmr29** [aws-amplify/amplify-flutter#529] opened 2021-04-21 09:26 UTC
I am inserting data to Dynamo DB using graphQL and aws amplify from flutter app.
The app  is getting crashed and getting the below error message

"Initial cloud sync failed.
W/amplify:aws-datastore( 3108): DataStoreException
{message=Error in saving the model: Player[id=f4e13a14-afe3-4dd8-9e9e-3391fe003db5], 
cause=java.lang.ClassCastException: java.lang.Double cannot
 be cast to com.amplifyframework.core.model.temporal.Temporal$Timestamp"

this is schema.graphql
type Player @model @auth(rules: [{allow: private, operations: [read, create, update, delete]}]) {
  id: ID!
  game_id: Int
  status: String
  time: AWSTimestamp
  avatar: String
  name: String
  user_id: Int
}
 
I think data to be saved without exception

This issue is reproducible in Android 
Device Lenovo X3a40
Android version 6.0.1
![awsamplify-error](https://user-images.githubusercontent.com/5539562/115530779-b5ec3780-a2b1-11eb-9e9a-dbffcb958f57.png)

**Comment by HuiSF** [comment] 2021-06-11 21:06
Hi @sandeepmr29 thanks for reporting this issue. I will need some more information to understand the cause.

- Could you please provide example code snippet that you invoke `Amplify.DataStore.save()`?
- What data type did you define as the value of the `time` field?

**Comment by offlineprogrammer** [comment] 2021-08-18 19:04
Hi @sandeepmr29 

I am closing this issue for now as we didn't hear from you
We can reopen it if you are still facing the issue and when you provide more details

Regards
Mo

**Closed by offlineprogrammer** 2021-08-18 19:04 UTC
Labels: pending-close-response-required

**Comment by b-cancel** [comment] 2021-08-20 17:09
This is a bug report I just filed that includes a couple of bugs I found and the workarounds to each
after reading your bug report I think it could help others that might land on this page
https://github.com/aws-amplify/amplify-flutter/issues/822
