### ISSUE TITLE
StreamBuilder with observeQuery doesn't update items

### ISSUE THREAD

**Issue by JoakimMellonn** [aws-amplify/amplify-flutter#1350] opened 2022-02-10 09:54 UTC
**Describe the bug**
I'm using a StreamBuilder with observeQuery to show a list of DataStore elements. It loads the elements as expected, but from there it doesn't update the values (example: If I update the title from the console, it won't update in the app).

**To Reproduce**
Here's the code I'm using:

```dart
StreamBuilder(
  stream: Amplify.DataStore.observeQuery(
    Recording.classType,
    sortBy: [Recording.DATE.descending()],
  ).skipWhile((snapshot) => !snapshot.isSynced),
  builder: (context,
      AsyncSnapshot<QuerySnapshot<Recording>> snapshot) {
    if (snapshot.data == null) {
      return Center(
        child: CircularProgressIndicator(),
      );
    }
    QuerySnapshot<Recording> querySnapshot = snapshot.data!;
    var now = DateTime.now();
    bool status = querySnapshot.isSynced;
    return ListView.builder(
      itemCount: querySnapshot.items.length + 1,
      itemBuilder: (context, index) {
        if (index == 0) {
          return Text(
              'Current status isSynced: $status, last synced: $now');
        } else {
          Recording recording = querySnapshot.items[index - 1];
          return RecordingElement(
            recordingName: recording.name,
            recordingDate: recording.date,
            recordingDescription: recording.description!,
            fileName: recording.fileName!,
            fileKey: recording.fileKey!,
            id: recording.id,
            fileUrl: recording.fileUrl!,
            speakerCount: recording.speakerCount,
          );
        }
      },
    );
  },
),
```

This is the model I'm using:
```GraphQL
type Recording @model @auth(rules: [{allow: owner}]) {
  id: ID!
  name: String!
  date: AWSDateTime
  description: String
  fileKey: String
  fileName: String
  fileUrl: String
  speakerCount: Int!
  languageCode: String
}
```

**Expected behavior**
The elements should update seamlessly when it's updated in the backend.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[x] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.2 21D49 darwin-arm, locale en-DK)
    • Flutter version 2.8.1 at /Users/joakimrosenfeldtpedersen/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (8 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/joakimrosenfeldtpedersen/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.64.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • iPhone 13 Pro (mobile) • 0FB03DAE-6EE6-4264-9523-4F72C8546B38 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 98.0.4758.80

• No issues found!
```

</details>

<details>

  <summary>Dependencies (<code>pubspec.lock</code>)</summary>
  
  ```
  # Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  amplify_analytics_plugin_interface:
    dependency: transitive
    description:
      name: amplify_analytics_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_api:
    dependency: "direct main"
    description:
      name: amplify_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_api_plugin_interface:
    dependency: transitive
    description:
      name: amplify_api_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_auth_cognito:
    dependency: "direct main"
    description:
      name: amplify_auth_cognito
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_auth_plugin_interface:
    dependency: transitive
    description:
      name: amplify_auth_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_core:
    dependency: transitive
    description:
      name: amplify_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_datastore:
    dependency: "direct main"
    description:
      name: amplify_datastore
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_datastore_plugin_interface:
    dependency: transitive
    description:
      name: amplify_datastore_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_flutter:
    dependency: "direct main"
    description:
      name: amplify_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_storage_plugin_interface:
    dependency: transitive
    description:
      name: amplify_storage_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_storage_s3:
    dependency: "direct main"
    description:
      name: amplify_storage_s3
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  archive:
    dependency: transitive
    description:
      name: archive
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.9"
  args:
    dependency: transitive
    description:
      name: args
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.3.0"
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.8.2"
  audio_session:
    dependency: transitive
    description:
      name: audio_session
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.6+1"
  audio_video_progress_bar:
    dependency: "direct main"
    description:
      name: audio_video_progress_bar
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.0"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  characters:
    dependency: transitive
    description:
      name: characters
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.1"
  clock:
    dependency: transitive
    description:
      name: clock
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.15.0"
  crypto:
    dependency: transitive
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.1"
  csslib:
    dependency: transitive
    description:
      name: csslib
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.17.1"
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.4"
  date_time_format:
    dependency: transitive
    description:
      name: date_time_format
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  docx_template:
    dependency: "direct main"
    description:
      name: docx_template
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  fake_async:
    dependency: transitive
    description:
      name: fake_async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  ffi:
    dependency: transitive
    description:
      name: ffi
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.2"
  file:
    dependency: "direct main"
    description:
      name: file
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.1.2"
  file_picker:
    dependency: "direct main"
    description:
      name: file_picker
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.3.2"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_launcher_icons:
    dependency: "direct dev"
    description:
      name: flutter_launcher_icons
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.2"
  flutter_localizations:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_plugin_android_lifecycle:
    dependency: transitive
    description:
      name: flutter_plugin_android_lifecycle
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.5"
  flutter_stripe:
    dependency: "direct main"
    description:
      name: flutter_stripe
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.1"
  flutter_svg:
    dependency: transitive
    description:
      name: flutter_svg
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_web_plugins:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
  font_awesome_flutter:
    dependency: "direct main"
    description:
      name: font_awesome_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "9.2.0"
  freezed_annotation:
    dependency: transitive
    description:
      name: freezed_annotation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  get:
    dependency: "direct main"
    description:
      name: get
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.6.1"
  google_fonts:
    dependency: "direct main"
    description:
      name: google_fonts
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.0"
  html:
    dependency: "direct main"
    description:
      name: html
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.15.0"
  http:
    dependency: "direct main"
    description:
      name: http
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.13.4"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.0"
  image:
    dependency: transitive
    description:
      name: image
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.1"
  in_app_purchase:
    dependency: "direct main"
    description:
      name: in_app_purchase
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  in_app_purchase_android:
    dependency: transitive
    description:
      name: in_app_purchase_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.2+1"
  in_app_purchase_platform_interface:
    dependency: transitive
    description:
      name: in_app_purchase_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.1"
  in_app_purchase_storekit:
    dependency: transitive
    description:
      name: in_app_purchase_storekit
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.1"
  infinite_listview:
    dependency: transitive
    description:
      name: infinite_listview
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  intl:
    dependency: "direct main"
    description:
      name: intl
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.17.0"
  js:
    dependency: transitive
    description:
      name: js
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.3"
  json_annotation:
    dependency: transitive
    description:
      name: json_annotation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.4.0"
  just_audio:
    dependency: "direct main"
    description:
      name: just_audio
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.18"
  just_audio_platform_interface:
    dependency: transitive
    description:
      name: just_audio_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.0"
  just_audio_web:
    dependency: transitive
    description:
      name: just_audio_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.2"
  matcher:
    dependency: transitive
    description:
      name: matcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.11"
  meta:
    dependency: "direct main"
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.0"
  nested:
    dependency: transitive
    description:
      name: nested
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  numberpicker:
    dependency: "direct main"
    description:
      name: numberpicker
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.1"
  path:
    dependency: "direct main"
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.0"
  path_drawing:
    dependency: transitive
    description:
      name: path_drawing
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  path_parsing:
    dependency: transitive
    description:
      name: path_parsing
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  path_provider:
    dependency: "direct main"
    description:
      name: path_provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.8"
  path_provider_android:
    dependency: transitive
    description:
      name: path_provider_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.11"
  path_provider_ios:
    dependency: transitive
    description:
      name: path_provider_ios
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.7"
  path_provider_linux:
    dependency: transitive
    description:
      name: path_provider_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.5"
  path_provider_macos:
    dependency: transitive
    description:
      name: path_provider_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.5"
  path_provider_platform_interface:
    dependency: transitive
    description:
      name: path_provider_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.3"
  path_provider_windows:
    dependency: transitive
    description:
      name: path_provider_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.5"
  pay:
    dependency: "direct main"
    description:
      name: pay
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.7"
  pay_android:
    dependency: transitive
    description:
      name: pay_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.6"
  pay_ios:
    dependency: transitive
    description:
      name: pay_ios
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.5"
  pay_platform_interface:
    dependency: transitive
    description:
      name: pay_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  petitparser:
    dependency: transitive
    description:
      name: petitparser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.4.0"
  platform:
    dependency: transitive
    description:
      name: platform
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.0"
  plugin_platform_interface:
    dependency: transitive
    description:
      name: plugin_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.2"
  process:
    dependency: transitive
    description:
      name: process
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.2.4"
  provider:
    dependency: "direct main"
    description:
      name: provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.0.2"
  rxdart:
    dependency: transitive
    description:
      name: rxdart
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.27.3"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.1"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.10.0"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  stripe_android:
    dependency: transitive
    description:
      name: stripe_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.1"
  stripe_ios:
    dependency: transitive
    description:
      name: stripe_ios
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.1"
  stripe_platform_interface:
    dependency: transitive
    description:
      name: stripe_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.1"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  test_api:
    dependency: transitive
    description:
      name: test_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.3"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0"
  url_launcher:
    dependency: "direct main"
    description:
      name: url_launcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.0.18"
  url_launcher_android:
    dependency: transitive
    description:
      name: url_launcher_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.0.14"
  url_launcher_ios:
    dependency: transitive
    description:
      name: url_launcher_ios
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.0.14"
  url_launcher_linux:
    dependency: transitive
    description:
      name: url_launcher_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.3"
  url_launcher_macos:
    dependency: transitive
    description:
      name: url_launcher_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.3"
  url_launcher_platform_interface:
    dependency: transitive
    description:
      name: url_launcher_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.5"
  url_launcher_web:
    dependency: transitive
    description:
      name: url_launcher_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.6"
  url_launcher_windows:
    dependency: transitive
    description:
      name: url_launcher_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  uuid:
    dependency: transitive
    description:
      name: uuid
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.5"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.1"
  win32:
    dependency: transitive
    description:
      name: win32
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.3.6"
  xdg_directories:
    dependency: transitive
    description:
      name: xdg_directories
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0"
  xml:
    dependency: transitive
    description:
      name: xml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.3.1"
  yaml:
    dependency: transitive
    description:
      name: yaml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.0"
sdks:
  dart: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

  ```

</details>

**Smartphone (please complete the following information):**
 - Device: iOS Simulator iPhone 13 Pro
 - OS: iOS 15.2

**Additional context**
I can get it to update when using DataStore.clear(), but it clears the list and takes very long to load the elements again (minutes).

**Comment by HuiSF** [comment] 2022-02-10 20:11
>But I'm also updating the elements using a Lambda function, this function uses DynamoDB to update them, could this cause problems?

I don't think directly modifying data in DynamoDB will trigger a realtime update event from AppSync and deliver the updates to AppSync clients. You may need to extra setup to achieve this, this document may help: https://aws.amazon.com/premiumsupport/knowledge-center/appsync-notify-subscribers-real-time/

> I'm using the Amplify console

If you meant Amplify Studio Content interface, the change should be able to notify model subscribers. If it's not doing it, could you watch the GraphQL response in browser dev tool when you update a record, see if the response contains all fields of the model or it's missing some fields?

**Comment by JoakimMellonn** [comment] 2022-02-11 14:22
I have just tried what the article tells me to do, but it looks like AppSync has already been set up the way the article tells me to. But trying to use the AppSync console to subscribe to model updates everything seems to work fine when doing changes in the Amplify Studio Content interface, but it just doesn't update in the app.
The only time it actually updates in the app, is when i use the DataStore.clear() function or if I stop debugging the app and start it again.

I will have to do something with the Lambda function, I'm sure of that, but that's not the cause when I'm testing right now.

**Comment by HuiSF** [comment] 2022-02-11 21:20
I've set up a minimal App to test the flow:

1. using `observeQuery` to observe a model
2. Update a record of the model in Amplify Studio
3. After saving updates made in Amplify Studio, the stream created by `observeQuery` received a new snapshot, which contains the updated record

**Comment by HuiSF** [comment] 2022-02-11 21:32
>The only time it actually updates in the app, is when i use the DataStore.clear() function or if I stop debugging the app and start it again.

This is because Amplify.DataStore.clear() will eventually cause an initial sync, which will re-sync all data from the cloud, where you can see the updated records.

>But trying to use the AppSync console to subscribe to model updates everything seems to work fine when doing changes in the Amplify Studio Content interface, but it just doesn't update in the app.

From my testing above, I don't see issue in the flow: Updating record in Amplify Studio Content, and receiving realtime update in an end device. Can you clarify  @JoakimMellonn, are you still experiencing issue in this flow, or you were able to isolate the issue to lambda use case only?

**Comment by HuiSF** [comment] 2022-02-12 16:38
You enabled auth owner rule on the model, did you sign in the user that is the owner of this record you were updating in Amplify Studio in order to get the update from observeQuery?

**Comment by JoakimMellonn** [comment] 2022-02-12 20:11
> You enabled auth owner rule on the model, did you sign in the user that is the owner of this record you were updating in Amplify Studio in order to get the update from observeQuery?

If you you mean in the app, then yes.

**Comment by dfourcfive** [comment] 2022-02-16 11:02
I'm having a very similar problem , can't receive any real time events from observe/observeQuery when updating the data in amplify studio or in the console

**Comment by JoakimMellonn** [comment] 2022-02-16 12:45
> I'm having a very similar problem , can't receive any real time events from observe/observeQuery when updating the data in amplify studio or in the console

After some more testing I have found that it still doesn't work when updating data with Amplify Studio, but it does work quite well when creating/deleting some new data with Datastore.save()/delete() inside the app.
This I find extremely weird since I could subscribe to updates from Amplify Studio from inside the AppSync console, as mentioned before.

**Comment by dfourcfive** [comment] 2022-02-16 14:38
@JoakimMellonn  for some reasons i have fixed the problem by editing the @auth rules
type User @model @aws_cognito_user_pools @auth(rules: [{ allow: owner ,ownerField: "phone_number", operations: [create,read,update]}, { allow: private, provider: iam }])
so i added @aws_cognito_user_pools
and ownerField

and also created a subscription 


type Subscription {
    onCreateUserPublic: User
        @aws_subscribe(mutations: ["createUser"])
    onUpdateUserPublic: User
        @aws_subscribe(mutations: ["updateUser"])
    onDeleteUserPublic: User
        @aws_subscribe(mutations: ["deleteUser"])
}

i had a trouble with amplify api push (socket errors)
so i removed the api and added it again and pushed it to the cloud

**Comment by egyangel** [comment] 2022-02-21 19:02
+1 
me also,  can't receive any real time events from observeQuery when updating the data in amplify studio or in the console
I'm using 
 amplify_api: ^0.4.0
  amplify_flutter: ^0.4.0
  amplify_datastore: ^0.4.0
  amplify_core: ^0.4.0

**Comment by HuiSF** [comment] 2022-02-21 20:57
Hi @egyangel Could you provide the model schema that you were updating data for from Amplify Studio? Also which field were you updating?

**Comment by JoakimMellonn** [comment] 2022-03-31 12:13
I have finally come around to update my backend, to use AppSync and Graphql to update the elements. But even after this, it isn't updated in the frontend without using DataStore.clear()...
Right now I'm lost for ideas as to why this happens.

I'm using the AWSAppSyncClient inside a Lambda function to update the element, and I can see in real time that it's working. To see that it's working, I'm both using the AppSync console to subscribe to the stream, and the Amplify Studio to watch the element.

**Comment by HuiSF** [comment] 2022-03-31 17:23
Hi @JoakimMellonn there is a known issue cross Amplify platform libraries, that GraphQL subscription and mutation selection set is incompatible cross platform. Hence, in most cases, iOS cannot receive real time update via GraphQL subscription internally maintained by DataStore from events triggered by mutations made with other platform libraries.

I think your workaround may resolve this issue while the team is looking into a solution.
Please be sure, when you update the element using the Lambda function, you would need to list all fields in selection set, including all meta fields added by conflict detection feature, such as `_deleted`, `_version`, `_lastChangedAt` etc. You can find this info via AppSync console, view schema interface.

There was a discussion in https://github.com/aws-amplify/amplify-flutter/issues/898.

**Comment by HuiSF** [comment] 2022-03-31 18:31
Yes @JoakimMellonn that's correct, glad you find this information. `_version` is required as when an API is used for DataStore, `_version` is a required field of a model. 

What I meant is that if you have doubt, you can always check what fields are require in AppSync console by viewing the schema, e.g.

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/10602282/161125265-6187c7df-1b15-4973-a914-46281b088755.png">

**Comment by JoakimMellonn** [comment] 2022-03-31 18:37
> Yes @JoakimMellonn that's correct, glad you find this information. `_version` is required as when an API is used for DataStore, `_version` is a required field of a model.
> 
> What I meant is that if you have doubt, you can always check what fields are require in AppSync console by viewing the schema, e.g.

Okay, then I understand! The reason then for my to run into this problem, was that I used the "Queries" tab to make the mutation model. In there the only one that is required (indicated by the *), is the id field. That is a little unintuitive, but it doesn't matter for me now, I found the solution quite quickly!
Anyways, thank you for the help, I will be looking forward to a fix to my other problem!

**Comment by HuiSF** [comment] 2022-03-31 18:41
Glad to hear @JoakimMellonn . I will close this issue as a duplicate of #663 Please feel free to follow up if anything! Thanks.

**Closed by HuiSF** 2022-03-31 18:41 UTC
Labels: DataStore, pending-response, pending-triage
