### ISSUE TITLE
InvalidParameterException thrown when saving birthdate attribute

### ISSUE THREAD

**Issue by 12tilak34** [aws-amplify/amplify-flutter#2034] opened 2022-08-12 09:08 UTC
I'm using the correct format of date MM/DD/YYYY still it is giving me an error.. help me to resolve it, please

Exception:

```
E/flutter (23340): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: InvalidParameterException(message: One or more parameters are incorrect., recoverySuggestion: Enter correct parameters., underlyingException: com.amazonaws.services.cognitoidentityprovider.model.InvalidParameterException: Attributes did not conform to the schema: birthdate: String must be no shorter than 10 characters
```

**Comment by Jordan-Nelson** [comment] 2022-08-12 11:49
Hi @12tilak34 - I believe the format should be "YYYY-MM-DD", which follows the [open ID spec](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims).

If you are using that format, can you provide the code sample that is throwing this exception so that I can attempt to reproduce it? Thanks.

**Comment by Jordan-Nelson** [comment] 2022-08-12 11:51
Can you also let me know which version of amplify flutter you are using and which platform you are running on? Thanks.

**Comment by 12tilak34** [comment] 2022-08-12 11:58
I had tried both formats. I'm using amplify version 9.0.1 and running on windows, code editor is android studio

**Comment by 12tilak34** [comment] 2022-08-12 11:59
import 'package:amplify_auth_cognito/amplify_auth_cognito.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:fincept/AmplifyConfig/amplifyconfiguration.dart';
import 'package:flutter/material.dart';

class SignUpScreen extends StatefulWidget {
  const SignUpScreen({Key? key}) : super(key: key);

  @override
  State<SignUpScreen> createState() => _SignUpScreenState();
}

class _SignUpScreenState extends State<SignUpScreen> {
  late final TextEditingController _activationCodeController;
  late final TextEditingController _phoneNumberController;
  late final TextEditingController _passwordController;
  late final TextEditingController _emailController;
  late final TextEditingController _name;
  late final TextEditingController _picture;
  late final TextEditingController _gender;
  late final TextEditingController _birthdate;
  late final TextEditingController _address;

  Future<void> _configureAmplify() async {
    final auth = AmplifyAuthCognito();

    // Use addPlugins function to add more than one Amplify plugins
    await Amplify.addPlugin(auth);

    await Amplify.configure(amplifyconfig);
  }

  @override
  void initState() {
    super.initState();
    _activationCodeController = TextEditingController();
    _phoneNumberController = TextEditingController();
    _passwordController = TextEditingController();
    _emailController = TextEditingController();
    _name = TextEditingController();
    _gender = TextEditingController();
    _address = TextEditingController();
  }

  @override
  void dispose() {
    _activationCodeController.dispose();
    _phoneNumberController.dispose();
    _passwordController.dispose();
    _emailController.dispose();
    _name.dispose();
    _gender.dispose();
    _address.dispose();
    super.dispose();
  }

  Future<void> _signUpUser(
      String phoneNumber,
      String password,
      String email,
      String name,
      String gender,
      String address,
      ) async {
    final result = await Amplify.Auth.signUp(
      username: phoneNumber,
      password: password,
      options: CognitoSignUpOptions(
        userAttributes: {
          CognitoUserAttributeKey.email: email,
          CognitoUserAttributeKey.name: name,
          CognitoUserAttributeKey.address: address,
          CognitoUserAttributeKey.gender: gender,
        },
      ),
    );
    if (result.isSignUpComplete) {
      debugPrint('Sign up is done.');
    } if(result.isSignUpComplete){
      showDialog<void>(
        context: context,
        builder: (context) => AlertDialog(
          title: const Text('Confirm the user'),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Text('Check your phone number and enter the code below'),
              OutlinedAutomatedNextFocusableTextFormField(
                controller: _activationCodeController,
                padding: const EdgeInsets.only(top: 16),
                labelText: 'Activation Code',
                inputType: TextInputType.number,
              ),
            ],
          ),
          actions: <Widget>[
            TextButton(
              child: const Text('Dismiss'),
              onPressed: () => Navigator.of(context).pop(),
            ),
            TextButton(
              child: const Text('Confirm'),
              onPressed: () {
                Amplify.Auth.confirmSignUp(
                  username: phoneNumber,
                  confirmationCode: _activationCodeController.text,
                ).then((result) {
                  if (result.isSignUpComplete) {
                    Navigator.of(context).pop();
                  }
                });
              },
            ),
          ],
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Amplify SMS Flow'),
      ),
      body: FutureBuilder<void>(
          future: _configureAmplify(),
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.done) {
              return ListView(
                children: [
                  OutlinedAutomatedNextFocusableTextFormField(
                    controller: _phoneNumberController,
                    labelText: 'Phone Number',
                    inputType: TextInputType.phone,
                  ),
                  OutlinedAutomatedNextFocusableTextFormField(
                    controller: _passwordController,
                    obscureText: true,
                    labelText: 'Password',
                  ),
                  OutlinedAutomatedNextFocusableTextFormField(
                    controller: _emailController,
                    labelText: 'E-mail address',
                  ),
                  OutlinedAutomatedNextFocusableTextFormField(
                    controller: _name,
                    labelText: 'Name',
                  ),
                  OutlinedAutomatedNextFocusableTextFormField(
                    controller: _gender,
                    labelText: 'Gender',
                  ),
                  OutlinedAutomatedNextFocusableTextFormField(
                    controller: _address,
                    labelText: 'Address',
                  ),
                  Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: ElevatedButton(
                      onPressed: () async {
                        final phoneNumber = _phoneNumberController.text;
                        final password = _passwordController.text;
                        final email = _emailController.text;
                        final name = _name.text;
                        final gender = _gender.text;
                        final address = _address.text;
                        if (phoneNumber.isEmpty ||
                            password.isEmpty ||
                            email.isEmpty ||
                          name.isEmpty
                        ) {
                          debugPrint(
                              'One of the fields is empty. Not ready to submit');
                        } else {
                          _signUpUser(phoneNumber, password, email,name,gender,address);
                        }
                      },
                      child: const Text('Sign Up'),
                    ),
                  ),
                ],
              );
            }
            if (snapshot.hasError) {
              return Text('Some error happened: ${snapshot.error}');
            } else {
              return const Center(child: CircularProgressIndicator());
            }
          }),
    );
  }
}

class OutlinedAutomatedNextFocusableTextFormField extends StatelessWidget {
  const OutlinedAutomatedNextFocusableTextFormField({
    this.padding = const EdgeInsets.all(8),
    this.obscureText = false,
    this.labelText,
    this.controller,
    this.inputType,
    Key? key,
  }) : super(key: key);

  final String? labelText;
  final TextEditingController? controller;
  final TextInputType? inputType;
  final EdgeInsets padding;
  final bool obscureText;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: padding,
      child: TextFormField(
        controller: controller,
        obscureText: obscureText,
        keyboardType: inputType,
        textInputAction: TextInputAction.next,
        decoration: InputDecoration(
          border: const OutlineInputBorder(),
          labelText: labelText,
        ),
      ),
    );
  }
}



I HAD JUST REMOVED THE BIRTHDATE PARAMETER FROM EVERY FUNCTION YOU CAN ADD IT AND CHECK ON YOUR SYSTEM

**Comment by 12tilak34** [comment] 2022-08-12 12:02
you can download the dart file here:- https://www.mediafire.com/file/mbx9sigi8ntdz2v/SignUpTest.dart/file i had removed birthdate from everywhere because it was causing it error you can add it and check... it won't take more than 2 minutes

**Comment by Jordan-Nelson** [comment] 2022-08-12 12:28
9.0.1 is likely the version of the Amplify CLI that you are using. If you are running on Windows you must be using the latest dev-preview (1.0.0) of amplify flutter. We will attempt to reproduce this on Windows with that version.

**Comment by Jordan-Nelson** [comment] 2022-08-12 13:58
@12tilak34 Can you share the output of `flutter pub deps --no-dev --style=compact` so that I can confirm the versions of each amplify package?

is Windows the target platform, or are you running it on an Android emulator?

**Comment by Jordan-Nelson** [comment] 2022-08-12 15:15
I was unable to reproduce this with the latest dev-preview version of amplify flutter on Windows. If you provide the info above I can attempt to reproduce it with the version you are using.

**Comment by 12tilak34** [comment] 2022-08-12 18:13
Dart SDK 2.17.6
Flutter SDK 3.0.5
fincept 1.0.0+1

dependencies:
- amplify_analytics_pinpoint 0.6.5 [amplify_analytics_pinpoint_android amplify_analytics_pinpoint_ios amplify_core aws_common flutter meta]
- amplify_auth_cognito 0.6.5 [amplify_auth_cognito_android amplify_auth_cognito_ios amplify_core aws_common collection flutter meta plugin_platform_interface]
- amplify_authenticator 0.2.1 [amplify_auth_cognito amplify_core amplify_flutter aws_common collection flutter flutter_localizations intl]
- amplify_datastore 0.6.5 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.6.5 [amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios aws_common collection flutter meta plugin_platform_interface]
- amplify_storage_s3 0.6.5 [amplify_storage_s3_android amplify_storage_s3_ios amplify_core aws_common flutter meta plugin_platform_interface]
- aws_lambda_api 1.2.0 [shared_aws_api]
- cupertino_icons 1.0.5
- email_validator 2.1.17
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_glow 0.2.0 [flutter]
- flutter_svg 1.0.3 [flutter meta path_drawing vector_math xml]
- google_fonts 3.0.1 [flutter http path_provider crypto]
- image_picker 0.8.5+3 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
- local_auth 2.1.0 [flutter intl local_auth_android local_auth_ios local_auth_platform_interface local_auth_windows]
- pin_code_fields 7.4.0 [flutter]
- responsive_framework 0.2.0 [flutter collection]
- settings_ui 2.0.2 [flutter]
- showcaseview 1.1.6 [flutter]
- upi_india 3.0.1 [flutter]

transitive dependencies:
- amplify_analytics_pinpoint_android 0.6.5 [flutter]
- amplify_analytics_pinpoint_ios 0.6.5 [flutter]
- amplify_auth_cognito_android 0.6.5 [flutter]
- amplify_auth_cognito_ios 0.6.5 [amplify_core flutter]
- amplify_core 0.6.5 [aws_common collection flutter intl json_annotation meta plugin_platform_interface uuid]
- amplify_datastore_plugin_interface 0.6.5 [amplify_core collection flutter meta]
- amplify_flutter_android 0.6.5 [flutter]
- amplify_flutter_ios 0.6.5 [amplify_core flutter]
- amplify_storage_s3_android 0.6.5 [flutter]
- amplify_storage_s3_ios 0.6.5 [flutter]
- async 2.8.2 [collection meta]
- aws_common 0.1.1 [async collection http meta stream_transform uuid]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.16.0
- cross_file 0.3.3+1 [js meta]
- crypto 3.0.2 [typed_data]
- ffi 2.0.1
- file 6.1.2 [meta path]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_plugin_android_lifecycle 2.0.6 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http 0.13.4 [async http_parser meta path]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- image_picker_android 0.8.5+2 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.8 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.5+6 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.6.1 [cross_file flutter http plugin_platform_interface]
- intl 0.17.0 [clock path]
- js 0.6.4
- json_annotation 4.5.0 [meta]
- local_auth_android 1.0.5 [flutter flutter_plugin_android_lifecycle intl local_auth_platform_interface]
- local_auth_ios 1.0.7 [flutter intl local_auth_platform_interface]
- local_auth_platform_interface 1.0.4 [flutter intl plugin_platform_interface]
- local_auth_windows 1.0.1 [flutter local_auth_platform_interface]
- material_color_utilities 0.1.4
- meta 1.7.0
- path 1.8.1
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.19 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.2 [ffi flutter path path_provider_platform_interface win32]
- petitparser 5.0.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- shared_aws_api 1.2.0 [crypto http meta xml intl uuid collection]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- typed_data 1.3.1 [collection]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
- win32 2.7.0 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 5.4.1 [collection meta petitparser]

**Comment by 12tilak34** [comment] 2022-08-12 18:13
@Jordan-Nelson 

Dart SDK 2.17.6
Flutter SDK 3.0.5
fincept 1.0.0+1

dependencies:
- amplify_analytics_pinpoint 0.6.5 [amplify_analytics_pinpoint_android amplify_analytics_pinpoint_ios amplify_core aws_common flutter meta]
- amplify_auth_cognito 0.6.5 [amplify_auth_cognito_android amplify_auth_cognito_ios amplify_core aws_common collection flutter meta plugin_platform_interface]
- amplify_authenticator 0.2.1 [amplify_auth_cognito amplify_core amplify_flutter aws_common collection flutter flutter_localizations intl]
- amplify_datastore 0.6.5 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.6.5 [amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios aws_common collection flutter meta plugin_platform_interface]
- amplify_storage_s3 0.6.5 [amplify_storage_s3_android amplify_storage_s3_ios amplify_core aws_common flutter meta plugin_platform_interface]
- aws_lambda_api 1.2.0 [shared_aws_api]
- cupertino_icons 1.0.5
- email_validator 2.1.17
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_glow 0.2.0 [flutter]
- flutter_svg 1.0.3 [flutter meta path_drawing vector_math xml]
- google_fonts 3.0.1 [flutter http path_provider crypto]
- image_picker 0.8.5+3 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
- local_auth 2.1.0 [flutter intl local_auth_android local_auth_ios local_auth_platform_interface local_auth_windows]
- pin_code_fields 7.4.0 [flutter]
- responsive_framework 0.2.0 [flutter collection]
- settings_ui 2.0.2 [flutter]
- showcaseview 1.1.6 [flutter]
- upi_india 3.0.1 [flutter]

transitive dependencies:
- amplify_analytics_pinpoint_android 0.6.5 [flutter]
- amplify_analytics_pinpoint_ios 0.6.5 [flutter]
- amplify_auth_cognito_android 0.6.5 [flutter]
- amplify_auth_cognito_ios 0.6.5 [amplify_core flutter]
- amplify_core 0.6.5 [aws_common collection flutter intl json_annotation meta plugin_platform_interface uuid]
- amplify_datastore_plugin_interface 0.6.5 [amplify_core collection flutter meta]
- amplify_flutter_android 0.6.5 [flutter]
- amplify_flutter_ios 0.6.5 [amplify_core flutter]
- amplify_storage_s3_android 0.6.5 [flutter]
- amplify_storage_s3_ios 0.6.5 [flutter]
- async 2.8.2 [collection meta]
- aws_common 0.1.1 [async collection http meta stream_transform uuid]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.16.0
- cross_file 0.3.3+1 [js meta]
- crypto 3.0.2 [typed_data]
- ffi 2.0.1
- file 6.1.2 [meta path]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_plugin_android_lifecycle 2.0.6 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http 0.13.4 [async http_parser meta path]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- image_picker_android 0.8.5+2 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.8 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.5+6 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.6.1 [cross_file flutter http plugin_platform_interface]
- intl 0.17.0 [clock path]
- js 0.6.4
- json_annotation 4.5.0 [meta]
- local_auth_android 1.0.5 [flutter flutter_plugin_android_lifecycle intl local_auth_platform_interface]
- local_auth_ios 1.0.7 [flutter intl local_auth_platform_interface]
- local_auth_platform_interface 1.0.4 [flutter intl plugin_platform_interface]
- local_auth_windows 1.0.1 [flutter local_auth_platform_interface]
- material_color_utilities 0.1.4
- meta 1.7.0
- path 1.8.1
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.19 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.2 [ffi flutter path path_provider_platform_interface win32]
- petitparser 5.0.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- shared_aws_api 1.2.0 [crypto http meta xml intl uuid collection]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- typed_data 1.3.1 [collection]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
- win32 2.7.0 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 5.4.1 [collection meta petitparser]

**Comment by Jordan-Nelson** [comment] 2022-08-12 18:15
Thanks. It looks like you are using amplify_flutter v0.6.5. Can you confirm that you are running on an Android emulator?

**Comment by 12tilak34** [comment] 2022-08-12 18:31
no i was running on my phone but i tried on emulator also but it didn't work

**Comment by Jordan-Nelson** [comment] 2022-08-12 18:57
@12tilak34 - I am unable to reproduce this with amplify_flutter v0.6.5 on an Android emulator. I am able to call signUp with a birthdate in either format - `YYYY-MM-DD` or `MM/DD/YYYY` and it is working as expected.

Can you confirm that the value being passed to Amplify is in that format? For testing purposes, can you hard code the date? This will allow me to attempt to reproduce it with the exact same value you are using.

If you are still experiencing this issue after confirming the format, can you please provide the code you are using, and include the hard coded date you are using?

Thanks.

**Comment by 12tilak34** [comment] 2022-08-12 19:15
I will try the hard coded data also but when I take input from user side it generally gives me error.. i will update you this issue in some hours because it's night here so i will try the code tomorrow

**Comment by Jordan-Nelson** [comment] 2022-08-16 13:42
@12tilak34 - Let me know if you were able to try to reproduce this with the value hard coded. Thanks.

**Comment by Jordan-Nelson** [comment] 2022-08-24 19:22
Hello @12tilak34 - I am going to close this out since it has been a while without an update and I was unable to reproduce this. If you are able to reproduce this, please open a new issue. It would be helpful to include a minimal reproduction includes the date you are having issues with.

**Closed by Jordan-Nelson** 2022-08-24 19:22 UTC
Labels: pending-close-response-required, Auth, not-reproducible, pending-response, pending-triage
