### ISSUE TITLE
DataStore query fail on iOS

### ISSUE THREAD

**Issue by hyobbb** [aws-amplify/amplify-flutter#422] opened 2021-03-03 12:47 UTC
**Describe the bug**
`Query failed: DataStoreException(message: The operation couldn’t be completed. (SQLite.Result error 0.), recoverySuggestion: The operation couldn’t be completed. (SQLite.Result error 0.), underlyingException: The operation couldn’t be completed. (SQLite.Result error 0.))`

query relational model causes error (query comments by postId for example)
on Android it doesn't throw error.

Also, HotRestart on iOS crash app because of AmplifyAlreadyConfiguredException although it should be caught by try&catch.

```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: AmplifyException(message: An unknown exception has happened.           Please take a look at 
        https://github.com/aws-amplify/amplify-flutter/issues to see if there are any existing issues that 
        match your scenario, and file an issue with the details of the bug if there isn't.
  , recoverySuggestion: We currently don't have a recovery suggestion for this exception., underlyingException: PlatformException(AmplifyAlreadyConfigured, Translating platform exception failed. Please take a look at https://github.com/aws-amplify/amplify-flutter/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't., {recoverySuggestion: Remove the duplicate call to `Amplify.configure()`, underlyingException: nil, message: Amplify has already been configured.}, null))
#0      AmplifyClass.configure (package:amplify_flutter/amplify.dart:187:9)
<asynchronous suspension>
#1      M<…>
```

**Comment by fjnoyp** [comment] 2021-03-04 01:55
Hi @hyobbb your issue sounds similar to #415 

Have you changed or modified your schema at all?

**Comment by hyobbb** [comment] 2021-03-04 02:04
@fjnoyp Hi. Yes I did change schema like below

```
enum TagStatus {
  ACTIVE
  INACTIVE
}

type Tag @model {
  id: ID!
  text: String!
  rating: Int!
  status: TagStatus!
  # New field with @connection
  videos: [Video] @connection(keyName: "byTag", fields: ["id"])
}

# New model
type Video @model
@key(name: "byTag", fields: ["tagID", "contentUrl"]) {
  id: ID!
  tagID: ID!
  tag: Tag! @connection(fields: ["tagID"])
  contentUrl: String!
  thumbUrl : String!
}
```

Also, will it support new null safety feature of flutter 2.0 soon?

**Comment by fjnoyp** [comment] 2021-03-05 01:04
Thanks for sharing that @hyobbb.  It looks like you are getting the same problem as describe in #415 

The response I gave there is same for your situation.  The issue you encountered comes from the underlying Amplify iOS Library behavior. I have been in communication with their devs and created an issue on their Amplify iOS repo linked here: aws-amplify/amplify-ios#1083.

Once they fix the issue and we update our Amplify iOS Library dependencies, your problem will be resolved. I don't know how long this will take on their side but can provide updates as we investigate/triage it.

We are actively looking into support the new null safety feature of flutter 2.0.  We don't have any firm dates for this support but understand its importance for your upgrade to flutter 2.0.

**Comment by hyobbb** [comment] 2021-03-05 01:23
@fjnoyp Thanks. I found another issue to report. In my case Video model does not sync even in Android. Tag models sync normally so I can check them in Dynamo DB but Video model only appears in internal sqlite data although it is not in offline mode. Should I open another issue for that?

**Comment by fjnoyp** [comment] 2021-03-05 19:48
Yes please report that in a separate issue @hyobbb 

When creating that issue, could you specify if you ran amplify push after adding the Video model to your schema?  Could you share your logs as well?

**Comment by hyobbb** [comment] 2021-03-06 11:33
@fjnoyp Hi.
I cleaned up to local database with Amplify.DataStore.clear() and push it again.
Now it works without any problem. I think it is okay to close this issue as it is the same one with #415 
Thank you

**Comment by b-cancel** [comment] 2021-08-20 17:02
This is a bug report I just filed that includes a couple of bugs I found and the workarounds to each
after reading your bug report I think it could help
https://github.com/aws-amplify/amplify-flutter/issues/822

**Comment by HuiSF** [comment] 2021-08-28 01:23
Closing this issue as the issue can be resolved by the workaround, and the root cause is tracked separately.

**Closed by HuiSF** 2021-08-28 01:23 UTC
Labels: iOS, requires-ios-fix, DataStore
