### ISSUE TITLE
Expose federatedSignIn APIs from mobile client

### ISSUE THREAD

**Issue by NepipenkoIgor** [aws-amplify/amplify-flutter#1439] opened 2022-03-07 13:39 UTC
### Description

Hi All currently  i trying to implement  federation sign in with web ui 
 by doc https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/flutter/.  Should say that regular sign in , reset password ..... works awesome . But when i try to call `Amplify.Auth.signInWithWebUI(provider:  AuthProvider.apple);`, not mater which provider i get an error `AWSMobileClient/AWSMobileClient.swift:538: Fatal error: Unexpectedly found nil while unwrapping an Optional value` .  Lost connection to device. (debug mode)

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [x] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Call Amplify.Auth.signInWithWebUI(provider:  AuthProvider.apple);
2. error -> AWSMobileClient/AWSMobileClient.swift:538: Fatal error: Unexpectedly found nil while unwrapping an Optional value
3. Lost connection to device. (debug mode)

### Platforms

- [X] iOS
- [ ] Android

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.64.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!
```

### Dependencies

```bash
Dart SDK 2.16.1
Flutter SDK 2.10.3
core 0.4.3

dependencies:
- amplify_auth_cognito 0.4.1 [flutter amplify_auth_plugin_interface amplify_core collection plugin_platform_interface]
- amplify_flutter 0.4.1 [amplify_analytics_plugin_interface amplify_api_plugin_interface amplify_auth_plugin_interface amplify_core amplify_datastore_plugin_interface amplify_storage_plugin_interface collection flutter json_annotation meta plugin_platform_interface]
- connectivity_plus 2.2.1 [flutter connectivity_plus_platform_interface connectivity_plus_linux connectivity_plus_macos connectivity_plus_web connectivity_plus_windows]
- dio 4.0.4 [http_parser path]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutter_blue 0.8.0 [flutter convert protobuf rxdart collection meta]
- flutter_markdown 0.6.9 [flutter markdown meta path]
- flutter_screenutil 5.3.1 [flutter]
- flutter_svg 1.0.3 [flutter meta path_drawing vector_math xml]
- package_info_plus 1.4.0 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- provider 6.0.2 [collection flutter nested]
- sentry_flutter 6.3.0 [flutter flutter_web_plugins sentry package_info_plus]
- shared_preferences 2.0.13 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- ui_kit 0.0.28 [flutter flutter_spinkit qr_code_scanner flutter_map flutter_map_marker_cluster location]

transitive dependencies:
- amplify_analytics_plugin_interface 0.4.1 [amplify_core flutter meta]
- amplify_api_plugin_interface 0.4.1 [amplify_core collection flutter json_annotation meta]
- amplify_auth_plugin_interface 0.4.1 [flutter meta amplify_core]
- amplify_core 0.4.1 [flutter plugin_platform_interface collection date_time_format meta uuid]
- amplify_datastore_plugin_interface 0.4.1 [flutter meta collection amplify_core]
- amplify_storage_plugin_interface 0.4.1 [flutter meta amplify_core]
- animated_stack_widget 0.0.4 [flutter]
- args 2.3.0
- async 2.8.2 [collection meta]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.15.0
- connectivity_plus_linux 1.3.0 [flutter connectivity_plus_platform_interface meta nm]
- connectivity_plus_macos 1.2.1 [connectivity_plus_platform_interface flutter]
- connectivity_plus_platform_interface 1.2.0 [flutter meta plugin_platform_interface]
- connectivity_plus_web 1.2.0 [connectivity_plus_platform_interface flutter_web_plugins flutter]
- connectivity_plus_windows 1.2.0 [connectivity_plus_platform_interface flutter]
- convert 3.0.1 [typed_data]
- crypto 3.0.1 [collection typed_data]
- date_time_format 2.0.1
- dbus 0.7.1 [args ffi meta xml]
- ffi 1.1.2
- file 6.1.2 [meta path]
- fixnum 1.0.0
- flutter_map 0.14.0 [async collection flutter http intl latlong2 meta positioned_tap_detector_2 proj4dart transparent_image tuple vector_math]
- flutter_map_marker_cluster 0.4.4 [flutter flutter_map latlong2 flutter_map_marker_popup]
- flutter_map_marker_popup 2.1.2 [flutter flutter_map latlong2 animated_stack_widget]
- flutter_spinkit 5.1.0 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- http 0.13.4 [async http_parser meta path]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.3
- json_annotation 4.4.0 [meta]
- latlong2 0.8.1 [intl]
- lists 1.0.1 [meta]
- location 4.3.0 [flutter location_platform_interface location_web]
- location_platform_interface 2.3.0 [flutter meta plugin_platform_interface]
- location_web 3.1.1 [flutter flutter_web_plugins http_parser js location_platform_interface meta]
- markdown 4.0.1 [args charcode meta]
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- mgrs_dart 2.0.0 [unicode]
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- package_info_plus_linux 1.0.3 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.4 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.4 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.0
- path_drawing 1.0.0 [vector_math meta path_parsing flutter]
- path_parsing 1.0.0 [vector_math meta]
- path_provider_linux 2.1.5 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.0.3 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.5 [ffi flutter path path_provider_platform_interface win32]
- petitparser 4.4.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- positioned_tap_detector_2 1.0.4 [flutter]
- process 4.2.4 [file path platform]
- proj4dart 2.0.0 [mgrs_dart wkt_parser meta]
- protobuf 2.0.1 [fixnum collection]
- qr_code_scanner 0.6.1 [js flutter flutter_web_plugins]
- quiver 3.0.1+1 [matcher]
- rxdart 0.26.0
- sentry 6.3.0 [http meta stack_trace uuid]
- shared_preferences_android 2.0.11 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.0 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.3 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.3 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- transparent_image 2.0.0
- tuple 2.0.0 [quiver]
- typed_data 1.3.0 [collection]
- unicode 0.3.1 [lists]
- uuid 3.0.6 [crypto]
- vector_math 2.1.1
- win32 2.4.1 [ffi]
- wkt_parser 2.0.0
- xdg_directories 0.2.0+1 [meta path process]
- xml 5.3.1 [collection meta petitparser]
```

### Device

iPhone XR and IPhone 13 Simulator

### OS

iOS 15.1

### CLI Version

no

**Comment by Jordan-Nelson** [comment] 2022-03-07 13:46
Hello @NepipenkoIgor - Can you confirm you have gone through all the steps listed [here](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/flutter/#setup-your-auth-provider) to set up apple as an auth provider?

**Comment by NepipenkoIgor** [comment] 2022-03-07 13:53
Hi @Jordan-Nelson . No . But for goggle and another providers a have the same errors . 
Should i create configuration for all providers ?
And short question by my business needs i need Azure provider . We implemented successfully  federation sign in with Angular
`this.amplifyService.auth().federatedSignIn(customerProvider);`
But i didn't find any information about federatedSignIn in flutter and how to use custom providers

**Comment by Jordan-Nelson** [comment] 2022-03-07 21:15
@NepipenkoIgor - Have you tried calling signInWithWebUI() without a provider? It should open the web UI with the option to choose between all the configured providers. If you have configured Azure as a provider for your Cognito backend already (following steps similar to [this](https://aws.amazon.com/blogs/security/how-to-set-up-amazon-cognito-for-federated-authentication-using-azure-ad/), for example), I believe you will see Azure listed. This setup would have to be done outside of Amplify, and it isn't something I have tested personally.

As for federated sign in, it looks like there is an open feature request for federated sign in - https://github.com/aws-amplify/amplify-flutter/issues/438. You can give that a 👍  to show your interest. It would help to comment with some info about your use case if you would like to see this implemented.

As for work arounds for federated sign in, the only short term option would be to write code that uses the iOS/Android Mobile SDKs using flutter platform Channels. This is a fair amount of effort (especially if you are not familiar with platform channels), which is why I suggested trying signInWithWebUI() without a provider as an alternate option.

**Comment by NepipenkoIgor** [comment] 2022-03-08 08:53
Hi @Jordan-Nelson  . Just given 👍 for feature request .
tried calling signInWithWebUI()  but get the same result 
Error 
```
AWSMobileClient/AWSMobileClient.swift:538: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Lost connection to device.
```
I recheck all steps from doc
1) Added to all. Info.plist, Info-Debug.plist, Info-Release.plist
 ```
     <key>CFBundleURLTypes</key>
    <array>
        <dict>
            <key>CFBundleURLSchemes</key>
            <array>
                <string>myapp</string>
            </array>
        </dict>
    </array>
 ```
 2)  tried calling signInWithWebUI() 
 
 I tired to use the same configuration that we use for web ( for web everything good). I get this config dynamically from REST and then configure Amplify. 
 
Where could be a problem ? Maybe i lost something ?

**Comment by Jordan-Nelson** [comment] 2022-03-09 16:08
@NepipenkoIgor - Can you share the config you are using (with sensitive info removed/masked)? If it was set up for web, it is possible it is missing something that is required for mobile.

**Comment by Jordan-Nelson** [comment] 2022-03-10 16:05
Assuming you want to redirect the user back to the mobile app after authentication, it should match the value you added for `CFBundleURLSchemes` to your project's info.plist. You can use something more specific than `myapp`. That is just for example in the docs.

Before we close out this issue, I want to make sure #438 would meet your use case. After looking at #438 again, I think the main piece of functionality it is asking for is to sign in with google/apple/other providers with a custom UI, rather than Amplify's Hosted UI. Is this what you are hoping to achieve as well?

**Comment by Jordan-Nelson** [comment] 2022-03-11 14:48
Okay. For now I am going to mark this as a separate feature request to expose the federatedSignIn APIs from the mobile clients. It is possible that this feature request will have some overlap with #438, but I think this is really a different request.

**Comment by haverchuck** [comment] 2022-06-02 16:30
Closing this issue as a duplicate of #182. We understand this is an important feature, and want to track it under one issue.

**Closed by haverchuck** 2022-06-02 16:30 UTC
Labels: feature-request, Auth
