### ISSUE TITLE
amplify Sign up function not working while running flutter release build

### ISSUE THREAD

**Issue by mufeedamhdali** [aws-amplify/amplify-flutter#317] opened 2021-01-21 11:49 UTC
I have configured a flutter project with amplify authentication. Authentication process works fine when I debug through USB. When I installed the release apk on my android device, authentication process does not work.

I want to go to my home page of the app when I sign in/sign up

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[+] Android

 - Device: Samsung M31s
 - OS: Android 10

**Comment by Ashish-Nanda** [comment] 2021-01-21 16:22
@mufeedamhdali could you share your steps for creating the release apk so we can replicate exactly?

Also could you elaborate on what happens when you say `authentication process does not work`. Does it result in an error? Could you share the stacktrace or logs?

**Comment by uttusharma** [comment] 2021-01-24 10:21
Refer here same as [#305](https://github.com/aws-amplify/amplify-flutter/issues/305)

**Comment by brunovsiqueira** [comment] 2021-01-26 13:58
Same problem was happening to me and I fixed by adding --no-shrink to the build command. @mufeedamhdali please try flutter build apk --no-shrink and let me know if it works.

**Comment by haverchuck** [comment] 2021-02-12 18:42
@brunovsiqueira @mufeedamhdali Does this still happen on `amplify-flutter 0.0.2-dev.2`?

**Comment by brunovsiqueira** [comment] 2021-02-12 18:43
@haverchuck I will test and I let you know.

**Comment by haverchuck** [comment] 2021-02-25 17:48
@mufeedamhdali Are you still encountering this issue with the latest version?

**Comment by haverchuck** [comment] 2021-03-04 17:02
Closing this issue due to inactivity (and cannot reproduce on latest build).

**Closed by haverchuck** 2021-03-04 17:02 UTC
Labels: Auth, pending-close-response-required
