### ISSUE TITLE
Datastore: Tried to get a plugin before it was configured.  Make sure you call Amplify.configure() first.

### ISSUE THREAD

**Issue by primico** [aws-amplify/amplify-flutter#2719] opened 2023-03-01 19:09 UTC
### Description

I configure datastore and get no exceptions. Then I get the exception below when I try to use DataStore.... Amplify.DataStore.observe(Product.classType).listen((event)

```
      final AmplifyAPI apiPlugin = AmplifyAPI(modelProvider: ModelProvider.instance);
      final AmplifyAuthCognito authPlugin = AmplifyAuthCognito();
      final AmplifyDataStore dataStorePlugin = AmplifyDataStore(modelProvider: ModelProvider.instance);
      await Amplify.addPlugins([
        authPlugin,
        dataStorePlugin,
        apiPlugin
      ]);
      await Amplify.configure(amplifyconfig);
```

```
java.lang.IllegalStateException: Tried to get a plugin before it was configured.  Make sure you call Amplify.configure() first.
	at com.amplifyframework.core.category.Category.getPluginIfConfiguredOrThrow(Category.java:239)
	at com.amplifyframework.core.category.Category.getPlugin(Category.java:186)
	at com.amazonaws.amplify.amplify_datastore.AmplifyDataStorePlugin.onSetUpObserve(AmplifyDataStorePlugin.kt:397)
	at com.amazonaws.amplify.amplify_datastore.AmplifyDataStorePlugin.onMethodCall(AmplifyDataStorePlugin.kt:127)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Steps to Reproduce

1. Add datastore plugin
2. Amplify.configure
3. Amplify.DataStore.observe

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.5

### Amplify Flutter Version

1.0.0-next.5

### Deployment Method

Amplify CLI

**Comment by HuiSF** [comment] 2023-03-02 01:10
Hi @primico thanks for opening this issue.

Are you calling `Amplify.DataStoer.observe()` or `Amplify.DataStore.observeQuery()` some where in your code? If so, could you double check if you are calling them after `await Amplify.configure()`?

**Comment by primico** [comment] 2023-03-02 01:34
Yes, I put breakpoints and this is completed first without any exceptions:
await Amplify.configure(amplifyconfig);
And then later I call:
await Amplify.DataStore.query(Product.classType);
Or:
Amplify.DataStore.observe(Product.classType).listen((event) { _fetchProduct(); });
And then I get the DataStore Exception

**Comment by primico** [comment] 2023-03-02 01:43
I recently upgraded to 1.0.0-next.5.. previously I was using 0.6.12 and it was working.

**Comment by primico** [comment] 2023-03-02 16:26
After I call Amplify.configure, I check Amplify.isConfigured and it is true and there are no exceptions. Here are my plugin objects (API, Auth, Datastore) after I configure:
<img width="360" alt="api" src="https://user-images.githubusercontent.com/6954991/222489912-9df54853-13c8-4fc1-b8c9-8ea7c346cce3.PNG">
<img width="380" alt="auth" src="https://user-images.githubusercontent.com/6954991/222489936-d08b88f3-410f-4c07-8162-197c617c3426.PNG">
<img width="386" alt="datastore" src="https://user-images.githubusercontent.com/6954991/222489975-7743751c-11b4-4be0-8563-e13b5f8ca91c.PNG">

**Comment by HuiSF** [comment] 2023-03-03 01:20
Thank you @primico we recently discovered an issue that the native DataStore plugin might not be configured properly.

Could you help me testing the following see whether it resolves the issue you are experiencing?

Changing the code block initialize Amplify plugin to 

```dart
final AmplifyAuthCognito authPlugin = AmplifyAuthCognito();
final AmplifyDataStore dataStorePlugin = AmplifyDataStore(modelProvider: ModelProvider.instance);
await Amplify.addPlugins([
  authPlugin,
  dataStorePlugin,
  AmplifyAPI(modelProvider: ModelProvider.instance), // initialize the API plugin inline
]);
await Amplify.configure(amplifyconfig);
```

**Comment by primico** [comment] 2023-03-03 01:27
I’ll be at my computer in about two hours and then I’ll test. Thanks!

**Comment by primico** [comment] 2023-03-03 04:08
Looks like I am not getting the exception anymore. Thanks!

**Comment by HuiSF** [comment] 2023-03-06 15:14
Thanks for confirming @primico A fix has been merged for https://github.com/aws-amplify/amplify-flutter/issues/2647 which caused by the same root cause. I will close this issue as a duplicate, and we will release the fix soon. After that where to instantiate the `AmplifyAPI` won't be an issue. Thanks.

**Closed by HuiSF** 2023-03-06 15:14 UTC
Labels: duplicate, DataStore, found-in-release-candidate
