### ISSUE TITLE
How to create a cognitoUserSession

### ISSUE THREAD

**Issue by manhtran-itr** [aws-amplify/amplify-flutter#3141] opened 2023-06-05 04:42 UTC
### Description

- In React Native we have a function to create CognitoUserSession with idToken, accessToken, refreshToken. 

I don't see any method in Amplify flutter to support this feature.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.0.5

### Amplify Flutter Version

0.6.5

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment] 2023-06-10 17:04
Hi @manhtran-itr - I think this is a duplicate of https://github.com/aws-amplify/amplify-flutter/issues/593. If you have a different use case can you please let us know. Otherwise we will close this as a duplicate.

**Comment by Jordan-Nelson** [comment] 2023-06-12 16:51
@manhtran-itr I am closing this as a duplicate of #593. If you have a different use case please let us know and we can consider re-opening the issue.

**Closed by Jordan-Nelson** 2023-06-12 16:51 UTC
Labels: pending-close-response-required, Auth, Investigating
