### ISSUE TITLE
Where can I find the format of the amplifyConfig.dart file?

### ISSUE THREAD

**Issue by denxorz** [aws-amplify/amplify-flutter#3591] opened 2023-08-22 15:08 UTC
Hello,

We are using the Amplify client libraries to connect to our AppSync/Cognito backend. Currently we do not have a Amplify backend. The configuration works fine, except for the Social login of the Windows app. When the user clicks the 'Sign in with Google' button that is generated by the Amplify Auth UI, it results in the following error.
```
flutter: ERROR | StateMachineBloc | Error signing in: InvalidUserPoolConfigurationException {
  "message": "No sign in redirect URLs registered for localhost. Add one or more sign in redirect URLs that start with \"http://localhost:\" followed by a random port greater than 1024, for example: \"http://localhost:3084/\". See the docs for more info: https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/flutter/"
}
```

I checked the page given in the error, but I cant figure out where to add an extra redirect URL into the config file. The only way that is described is the use of the `amplify` command. Is it possible to run this without backend? Or is it possible to provide the format of the file, so that I can add the extra redirect manually?

Can you give me a push into the right direction?

Thanks, 
Dennis

**Comment by denxorz** [comment] 2023-08-29 08:11
Hello @dnys1 , thanks for your quick answer and all the documentation.

Even with the extra documentation I was still unable to find out where to add "more sign in redirect URLs". 

It seems that the `SignInRedirectURI` is a string, so it can not hold a list of URI. So I have tried to copy the `Auth` section, but only the 'Default' one seems to be used.

```
const amplifyConfig = '''
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {

                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "xx.com",
                            "AppClientId": "xx",
                            "SignInRedirectURI": "myapp://",
                            "SignOutRedirectURI": "myapp://",
                            "Scopes": [
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "socialProviders": [
                            "GOOGLE",
                            "APPLE"
                        ],
... snip ...
                    },

                    "DefaultCopy": {
                        "OAuth": {
                            "WebDomain": "xx.com",
                            "AppClientId": "xx",
                            "SignInRedirectURI": "http://localhost:8080/",
                            "SignOutRedirectURI": "http://localhost:8080/",
                            "Scopes": [
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "socialProviders": [
                            "GOOGLE",
                            "APPLE"
                        ],
... snip ...
                    }
                },

                "UserAgent": "aws-amplify/cli",
                "Version": "0.1.0",
                "IdentityManager": { "Default": {} },
                "CredentialsProvider": { ... snip ... },
                "CognitoUserPool": { ... snip ... }
            }
        }
    }
}''';
```

Do you have another hint for me?

Thanks!
Dennis

**Comment by NikaHsn** [comment] 2024-03-14 21:43
@denxorz are you still facing this issue? 
would you please clarify if the issue is how/where to set the a SignInRedirectURI or is about using a list of SignInRedirectURI?

**Comment by denxorz** [comment] 2024-03-15 10:02
@NikaHsn the issue is indeed about adding multiple SignInRedirectURI. Normal OAuth login used in apps works fine, but using the same app on Windows Desktop gives the error given in the first post: `Add one or more sign in redirect URLs that start with \"http://localhost:\" followed by a random port greater than 1024`. It is not clear to me where this extra SignInRedirectURI should be added, is this an "extra section with a different name" or is it a "list" and what should I use as delimiter.  

So the error tells me to add an extra SignInRedirectURI, but it does not tell me how. And up till now I am not able to find any documentation that describes this either. So I am still facing the same issue.

**Comment by NikaHsn** [comment] 2024-03-18 22:19
sorry that it is not clear. you can add multiple uri to the `SignInRedirectURI` property in a string value with `,` as delimiter. so it will be like
```
"SignInRedirectURI": "myapp://,http://localhost:8080",
```

**Comment by NikaHsn** [comment] 2024-04-15 23:45
I'm closing this issue as we did not hear back. Please feel free to open an issue if it is still not resolved.

**Closed by NikaHsn** 2024-04-15 23:45 UTC
Labels: duplicate, question, pending-close-response-required, auth, pending-response
