### ISSUE TITLE
Automatic logout after migration from ^0.6.8 to ^1.1.1 

### ISSUE THREAD

**Issue by Mik77o** [aws-amplify/amplify-flutter#3246] opened 2023-06-20 12:58 UTC
### Description

A large number of our prod users are experiencing automatic logout after migrating to 1.1.1
When starting the app, we call:

```
final session = await Amplify.Auth.getPlugin(AmplifyAuthCognito.pluginKey).fetchAuthSession(
        options: FetchAuthSessionOptions(forceRefresh: false),
      );
if (token != null) {
      return true;
    } else {
...
```
Can JWT token after migration be no longer valid?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.0

### Amplify Flutter Version

1.1.1

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment] 2023-06-20 14:30
@Mik77o - Credentials are stored in a different manner in v0 and v1. However, they automatically migrated on the first app launch after upgrading to v1.

Are you seeing an exception, or are you seeing that the credentials are not present? Can you share a bit more of the code you are using on app launch? What is the value of `token` in the snippet you shared?

Are you seeing any correlation (similar devices, OS, etc.) between users that are reporting being logged out?

**Comment by Mik77o** [comment] 2023-06-21 07:24
@Jordan-Nelson 

According to the reporting system we use, most reports come from iOS.

`fetchAuthSession`, which we call in the initial actions after startup: mainly throws two exceptions:

- `SignedOutEception {"message": No user is currently signed in" }`,
-  `SessionExpiredException {"message": The tokens could not be refreshed, "recoverySuggestion: Invoke Amplify.Auth.signIn to re-authenticate the user, "underlyingException": NotAuthorizedException {message=Refresh Token has expired`.

Below is more code where these exceptions are caught.

```
  Future<String?> fetchAuthSession({bool forceRefreshCachedCredentials = false}) async {
    try {
      final session = await Amplify.Auth.getPlugin(AmplifyAuthCognito.pluginKey).fetchAuthSession(
        options: FetchAuthSessionOptions(forceRefresh: forceRefreshCachedCredentials),
      );

      final cognitoIdToken = session.userPoolTokensResult.value.idToken.toJson();
      _isSignedIn.add(session.isSignedIn);
      _awsToken.add(cognitoIdToken);
      unawaited(_updateDatadogUserId());
      debugPrint('AWS access token: $cognitoIdToken');
      await tryToGetCurrentCognitoUser();

      return cognitoIdToken;
    } on SignedOutException catch (e, stackTrace) {
      unawaited(trackLogout(manuallyTriggered: false));
      ... // exception reporting in our observability service
    } on SessionExpiredException catch (e, stackTrace) {
      unawaited(trackLogout(manuallyTriggered: false));
      ... // exception reporting in our observability service
    } on NetworkException catch (e, stackTrace) {
     ...
    } on Exception catch (e, stackTrace) {
    ...
    }
    clearUserData();
    return null;
  }
```

```
  Future<AuthUser?> tryToGetCurrentCognitoUser() async {
    try {
      final currentAWSUser = await Amplify.Auth.getCurrentUser();
      _awsUser.add(currentAWSUser);
      return awsUser;
    } on Exception catch (e, stackTrace) {
      _awsUser.add(null);
      ...
      return null;
    }
  }
```

**Comment by Mik77o** [comment] 2023-06-21 08:14
We noticed that migration works locally, but probably not for old, production users. We tested two versions via Testflight, where it had the latest changes, but the second one didn't. We were logged in on the older version and on the new one as well.

**Comment by Mik77o** [comment] 2023-06-21 10:55
I see something similar has been reported recently - https://github.com/aws-amplify/amplify-flutter/issues/3121

**Comment by Mik77o** [comment] 2023-06-21 13:34
Related issue: Shouldn't someone who doesn't have an account yet be served by throwing a separate exception? 
Currently, calling `fetchAuthSession` in guest mode causes this method to throw a `SignedOutException`.

**Comment by Jordan-Nelson** [comment] 2023-06-21 14:57
> fetchAuthSession, which we call in the initial actions after startup: mainly throws two exceptions:

SignedOutException indicates no tokens are present. If a user was logged in prior to upgrading the app and then saw this exception immediately after upgrade, that could indicate there was an issue migrating tokens. Users would also see this exception if they: 
- Signed out and then relaunched the app
- Had an expired session, closed the app, and then relaunched the app.
- Launched the app for the very first time (new users)
- uninstalled/re-installed the app

SessionExpiredException indicates there are tokens present, but they are expired. This means that the migration succeeded and the refresh token has expired. The user will need to sign in again. This would have been the case even if they did not upgrade.

> We noticed that migration works locally, but probably not for old, production users. We tested two versions via Testflight, where it had the latest changes, but the second one didn't. We were logged in on the older version and on the new one as well.

I am not sure that I understand. Are you saying that you were able to reproduce a scenario where you were logged in (with valid tokens) prior to upgrade and then logged out immediately after upgrade? If so, can you provide reproduction steps?

A couple things to note:
- If you uninstall and then re-install the app, your credentials will be cleared. This is intentional.
- Unless you completely uninstall the app, credential migration is a one time event. If you are using v0.6.x and upgrade to v1, credentials will be migrated. If you are switching back and forth between versions, credential migration will not take place a second time (unless you uninstall the app).

> Shouldn't someone who doesn't have an account yet be served by throwing a separate exception

If there are no tokens, a SignedOutException is thrown. There isn't really a way to tell if someone has an account until they attempt to sign in. They could have created the account on another device. Are you asking if a different exception should be thrown if a user had previously sign in on the current device? If so, we do not track if a user had previously sign in. Even if we did track this, it would not indicate that the current user has an account as it could be shared device. If you wanted to explore this more, I would suggest opening a feature request with the use case.

**Comment by Mik77o** [comment] 2023-06-22 07:57
@Jordan-Nelson 

Thanks for the explanation. Now I have a better understanding of when `SignedOutException` is thrown. Anyway, your answer also confirms that the token migration failed for a large number of product users.

_If a user was logged in prior to upgrading the app and then saw this exception immediately after the upgrade, that could indicate there was an issue migrating tokens_

This sentence you wrote is a problem that has affected us. Many users were previously logged in and after updating the app to the latest version with updated amplify_flutter they got this exception and they could not be logged in automatically.

We are concerned that this may happen with every future app update, which may be annoying to users 
to re-login every time. Unless this problem is purely migration-related.

As for our testing: what I meant was that we couldn't reproduce auto-logout locally. We have installed the version of the application with the older version of amplify_flutter. We logged in to the app on this version. Then, we installed the app version with the latest amplify_flutter. We were still logged in so the migration probably succeeded. So, it is even more difficult to find the cause because this migration problem affected prod users who updated the app from the store.

`SignedOutException` indicates various reasons. We'd like to have more insight into automatic user logout, but we can't judge this based on this exception. Any user who doesn't have an account (new user as you wrote) throws this exception and also our prod users reported this exception due to migration issues, so we can't rely on it. We can rely on other exceptions, but all this does not fully reflect reality.

**Comment by Jordan-Nelson** [comment] 2023-06-22 14:54
> Many users were previously logged in and after updating the app to the latest version with updated amplify_flutter they got this exception and they could not be logged in automatically

Do you know that these users met the following conditions?
1. They were signed in on the current device prior to the upgrade (they has not called sign out, or were not previously signed out due to an expired session)
2. They did not uninstall the app prior to the upgrade
3. The SignedOutException was thrown in the very first call to fetchAuthSession. If they had expired credentials, there should be a SessionExpiredException thrown on the very first call from fetchAuthSession. The expired credentials will then be cleared and SigneOutExceptions will be thrown on subsequent calls. _Note:_ Calling APIs from other categories will call fetchAuthSession if the call requires authentication. The SessionExpiredException will only be thrown on the very first call.

We need to be able to either reproduce the issue or see some sort of error or stack trace determine what could be causing it. We do log an error if the migration fails. Below is a code sample of how you could capture that log. This will only log exceptions thrown during the migration. If no credentials are found, there won't be an error thrown.

```dart
class MyPlugin implements AWSLoggerPlugin {
  @override
  void handleLogEntry(LogEntry entry) {
    if (entry.loggerName == 'CredentialStoreStateMachine') {
      // log messages or send to logging service
      safePrint('Message: ${entry.message}, stacktrace: ${entry.stackTrace}');
    }
  }
}

void main() {
  AmplifyLogger().logLevel = LogLevel.error;
  AmplifyLogger().registerPlugin(MyPlugin());
  runApp(const MyApp());
}
```

**Comment by Mik77o** [comment] 2023-06-26 10:19
@Jordan-Nelson 

1. Yes, they were signed in before. Sometimes users throw `SessionExpiredException` which is natural.
For the most part, however, these are `SignedOutException` reports and they cannot sing in automatically.

2. Haven't uninstalled the app before. They just updated it through the App Store/Google Play.
3. _If they had expired credentials, there should be a SessionExpiredException thrown on the very first call from fetchAuthSession._ - This did not happen in many cases.

I added `AmplifyLogger` with the suggested override. We'll see what we discover, but the current version is already in stores and only the next update will enable this reporting.

One more question: If all users will already have versions with the new `amplify_flutter`, then they should not have such problems with the next updates of the application, right? This problem is purely related to the transition from the old to the new version?

**Comment by Mik77o** [comment] 2023-06-28 11:41
@Jordan-Nelson 
Ok, I'll come back with an answer if we discover anything new after publishing the version with added `AmplifyLogger`.

**Comment by Jordan-Nelson** [comment] 2023-07-12 14:42
@Mik77o - Have you been able to collect logs for this?

**Comment by Mik77o** [comment] 2023-07-13 14:23
@Jordan-Nelson 

Unfortunately, we haven't been able to collect even one log for `CredentialStoreStateMachine`.

We can see a huge drop in `SignedOutException` reports. These are isolated cases and we are constantly monitoring them.

It seems that the problem was only with the transition to a new version of the library.

**Comment by Jordan-Nelson** [comment] 2023-07-20 18:45
@Mik77o thanks for the update. Without reproduction steps, logs, or stack traces, there isn't much we will be able to do. We are unable to reproduce this, and have integration tests in place for this specific migration case.

I am going to close this issue out. If you manage to collect logs or gather any additional info, please let me know and we can reopen in.

**Closed as completed** 2023-07-31 01:12 UTC
Labels: not-reproducible, pending-community-response

**Comment by luxurystorecc1** [comment] 2026-05-07 00:23
Mastering the Global Lifestyle: A Guide to Premium Apparel and Cultural Identity
Introduction: The Power of Authentic Branding
In a world saturated with options, authenticity has become the most valuable currency in fashion. Whether it is the history behind a pair of [Air Jordan 1 retro high OG shoes](https://www.airjordan-1.com/) or the official licensing of a professional sports jersey, consumers are looking for brands that stand for something. This guide explores how to build a global lifestyle wardrobe that honors tradition while embracing the cutting edge of design.

The Sneaker Phenomenon: Culture in Every Step
Sneakers are no longer just footwear; they are a form of social currency. The [Air Jordan 1s iconic basketball silhouettes](https://www.jordan1s.com/) have become universal symbols of style, recognized from Chicago to Shanghai. As collectors diversify their rotations, the demand for [Jordan 1 mid-top colorways](https://www.jordan1s.com/) has grown, offering a unique middle ground between the classic high-top and the casual low-top.

For those who prioritize modern technology, the [adidas Yeezy boost collection online](https://www.yeezyboost-350.com/collections/adidas-yeezy) offers a glimpse into the future. These designs prioritize the natural movement of the foot, making them a favorite for those who lead an active, urban lifestyle. Even the most casual items, such as [premium Yeezy slides and foam runners](https://www.yeezyboost-350.com/), are now seen as essential components of a high-fashion, low-effort aesthetic.

Fandom Across Borders: The Professional Jersey Market
The reach of professional sports leagues like the NFL, NHL, and NBA is truly global. For fans living outside of team cities, the [official NFL shop online store](https://www.nflshopofficialonline-store.com/) is the primary gateway to authentic team gear. Finding [cheap NFL jerseys with high-quality embroidery](https://www.nflshopofficialonline-store.com/) allows international fans to participate in the excitement of the season without logistical barriers.

The culture of "The Jersey" also extends to accessories. [NFL headwear and official team caps](https://www.cheapnfl-jerseys.com/collections/headwear-nfl-headwear) are now staple items in streetwear, often paired with luxury outerwear for a high-low look. Similarly, the growing popularity of the [Spain national team soccer kit](https://www.soccerjerseysstore.com/collections/national-teams-europe-spain) shows how sporting excellence can influence fashion trends thousands of miles away from the pitch.

Performance Luxury: From the Fairway to the Boardroom
For the sophisticated athlete, [Peter Millar women's golf outerwear](https://www.peter-milla.com/collections/golf-women-s-golf-outerwear) represents the peak of performance luxury. These pieces are designed to handle the variable conditions of the golf course while looking refined enough for a post-round dinner at the club. The broader [Peter Millar apparel for men and women](https://www.peter-milla.com/) line continues to define the "Modern American" style, characterized by clean lines and exceptional fabrics.

Celebrating Life: Formal Wear and Intimates
The most memorable moments in life require clothing that rises to the occasion. For wedding guests, particularly during the autumn season, the variety of [fall wedding guest dresses](https://www.swim-outlet.com/collections/wedding-fall-wedding-guest) provides ample opportunity to showcase personal style while adhering to seasonal themes. For those who prefer a bold, classic statement, [red formal dresses for evening events](https://www.swim-outlet.com/collections/dresses-red) remain a powerful and elegant choice.

The fashion industry’s focus on the "Total Look" includes the often-overlooked category of [luxury sleepwear and intimates for women](https://www.cheapdressesformal.com/collections/clothing-sleepwear-sintimates). By choosing high-quality materials for even the most private moments, consumers can maintain a standard of luxury throughout their day. This commitment to quality is also found in the [plus size formal dress collection](https://www.cheapdressesformal.com/), which offers designer-level styling for every body type.

Conclusion: Authenticity as a Lifestyle
Whether you are diving into a competition with gear from a [professional swim outlet](https://www.swim-outlet.com/) or attending a gala in a [white formal gown](https://www.cheapdressesformal.com/collections/dresses-white), the key to a successful wardrobe is authenticity. By sourcing products that are verified, well-designed, and culturally significant, you build a lifestyle that is not only stylish but also meaningful. In the global marketplace, quality is the language that everyone understands.
