### ISSUE TITLE
[Auth] Fetch Auth Session fail after relogin

### ISSUE THREAD

**Issue by jack24254029** [aws-amplify/amplify-flutter#1438] opened 2022-03-07 03:12 UTC
### Description

When call `fetchAuthSession` fail first time, the app will call signout and signin then call `fetchAuthSession` again, but it still fail.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

User DON'T refresh token after a week or more maybe can reproduce this behavior.

### Platforms

- [X] iOS
- [x] Android

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.1 21C52 darwin-x64, locale zh-Hant-TW)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.64.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

### Dependencies

```bash
Dart SDK 2.16.1
Flutter SDK 2.10.2
gp926_flutter 1.0.0+1

dependencies:
- amplify_auth_cognito 0.4.0 [flutter amplify_auth_plugin_interface amplify_core collection plugin_platform_interface]
- amplify_flutter 0.4.0 [amplify_analytics_plugin_interface amplify_api_plugin_interface amplify_auth_plugin_interface amplify_core amplify_datastore_plugin_interface amplify_storage_plugin_interface collection flutter json_annotation meta plugin_platform_interface]
- archive 3.2.1 [crypto path]
- connectivity_plus 2.2.0 [flutter connectivity_plus_platform_interface connectivity_plus_linux connectivity_plus_macos connectivity_plus_web connectivity_plus_windows]
- country_codes 2.1.1 [flutter]
- crypto 3.0.1 [collection typed_data]
- dart_jsonwebtoken 2.4.1 [crypto pointycastle convert collection]
- device_info_plus 3.2.2 [flutter device_info_plus_platform_interface device_info_plus_macos device_info_plus_linux device_info_plus_web device_info_plus_windows]
- dio 4.0.4 [http_parser path]
- drift 1.4.0 [async convert collection meta stream_channel sqlite3]
- drift_inspector 1.0.0 [dart_service_announcement drift synchronized uuid]
- firebase_analytics 9.1.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 1.12.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.5.2 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 4.0.7 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_messaging 11.2.6 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutter_hooks 0.18.2+1 [flutter]
- flutter_local_notifications 9.3.2 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path typed_data vector_math]
- flutter_screenutil 5.3.1 [flutter]
- flutter_svg 1.0.3 [flutter meta path_drawing vector_math xml]
- hive 2.0.5 [meta crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- hooks_riverpod 1.0.3 [collection flutter flutter_hooks flutter_riverpod riverpod state_notifier]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image_picker 0.8.4+9 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- indent 2.0.0
- intl 0.17.0 [clock path]
- json_annotation 4.4.0 [meta]
- logger 1.1.0
- package_info_plus 1.3.1 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- path_provider 2.0.9 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.12 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.8 [flutter path_provider_platform_interface]
- permission_handler 9.2.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- phone_number 0.12.0+1 [flutter meta]
- qr_code_scanner 0.7.0 [js flutter flutter_web_plugins]
- shared_preferences 2.0.13 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shared_preferences_android 2.0.11 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.0 [flutter shared_preferences_platform_interface]
- shimmer 2.0.0 [flutter]
- sms_autofill 2.2.0 [pin_input_text_field flutter]
- sqlite3_flutter_libs 0.5.4 [flutter]
- sticky_headers 0.2.0 [flutter]
- tuple 2.0.0 [quiver]
- url_launcher 6.0.20 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- webview_flutter 2.0.12 [flutter]
- xml 5.3.1 [collection meta petitparser]

dependency overrides:
- webview_flutter 2.0.12 [flutter]

transitive dependencies:
- amplify_analytics_plugin_interface 0.4.0 [amplify_core flutter meta]
- amplify_api_plugin_interface 0.4.0 [amplify_core collection flutter json_annotation meta]
- amplify_auth_plugin_interface 0.4.0 [flutter meta amplify_core]
- amplify_core 0.4.0 [flutter plugin_platform_interface collection date_time_format meta uuid]
- amplify_datastore_plugin_interface 0.4.0 [flutter meta collection amplify_core]
- amplify_storage_plugin_interface 0.4.0 [flutter meta amplify_core]
- args 2.3.0
- async 2.8.2 [collection meta]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.15.0
- connectivity_plus_linux 1.2.0 [flutter connectivity_plus_platform_interface meta nm]
- connectivity_plus_macos 1.2.1 [connectivity_plus_platform_interface flutter]
- connectivity_plus_platform_interface 1.2.0 [flutter meta plugin_platform_interface]
- connectivity_plus_web 1.2.0 [connectivity_plus_platform_interface flutter_web_plugins flutter]
- connectivity_plus_windows 1.2.0 [connectivity_plus_platform_interface flutter]
- convert 3.0.1 [typed_data]
- cross_file 0.3.2 [flutter js meta]
- dart_service_announcement 1.0.3 [logging synchronized]
- date_time_format 2.0.1
- dbus 0.6.8 [args ffi meta xml]
- device_info_plus_linux 2.1.1 [device_info_plus_platform_interface file flutter meta]
- device_info_plus_macos 2.2.2 [device_info_plus_platform_interface flutter]
- device_info_plus_platform_interface 2.3.0+1 [flutter meta plugin_platform_interface]
- device_info_plus_web 2.1.0 [device_info_plus_platform_interface flutter_web_plugins flutter]
- device_info_plus_windows 2.1.1 [device_info_plus_platform_interface ffi flutter win32]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_analytics_platform_interface 3.1.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.0+6 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 4.2.4 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.5.4 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.2.1 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.1+1 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 3.1.6 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.2.7 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_local_notifications_linux 0.4.1+1 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.5 [flutter]
- flutter_riverpod 1.0.3 [collection flutter meta riverpod state_notifier]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- http 0.13.4 [async http_parser meta path]
- image_picker_for_web 2.1.6 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_platform_interface 2.4.4 [cross_file flutter http plugin_platform_interface]
- js 0.6.3
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- nm 0.4.4 [dbus]
- package_info_plus_linux 1.0.3 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.4 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.4 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.0
- path_drawing 1.0.0 [vector_math meta path_parsing flutter]
- path_parsing 1.0.0 [vector_math meta]
- path_provider_linux 2.1.5 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.5 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.3 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.5 [ffi flutter path path_provider_platform_interface win32]
- permission_handler_android 9.0.2 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.0.2 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.0 [flutter permission_handler_platform_interface]
- petitparser 4.4.0 [meta]
- pin_input_text_field 4.1.1 [flutter]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- pointycastle 3.5.1 [collection convert js]
- process 4.2.4 [file path platform]
- quiver 3.0.1+1 [matcher]
- riverpod 1.0.3 [collection meta state_notifier]
- shared_preferences_linux 2.1.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.3 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.3 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- sqlite3 1.5.1 [collection ffi meta]
- stack_trace 1.10.0 [path]
- state_notifier 0.7.2+1 [meta]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- timezone 0.8.0 [path]
- typed_data 1.3.0 [collection]
- url_launcher_android 6.0.15 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.15 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.0 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.0.5 [flutter plugin_platform_interface]
- url_launcher_web 2.0.8 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.0 [flutter url_launcher_platform_interface]
- uuid 3.0.5 [crypto]
- vector_math 2.1.1
- win32 2.4.1 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
```

### Device

(Maybe more)
- iPhone XR
- iPhone X
- iPhone 13

### OS

(Maybe more)
- 15.1.1
- 14.7.1
- 14.6

### CLI Version

N/A

### Additional Context

When `idToken` is expired, I called `fetchAuthSession` to refresh token, but sometimes had a exception, like `Your session has expired.` or `Session expired could not fetch user sub`.

When I got the exception on first time, I called sing out and signin then `fetchAuthSession` again, sometimes it return a exception, like `There is no user signed in to retreive user sub`.

How do I resolve this issue?
Thank you.

Code
```dart
    CognitoAuthSession session;
    try {
      refreshTokenLog += 'Fetch Auth Session.\n';
      session = await Amplify.Auth.fetchAuthSession(options: CognitoSessionOptions(getAWSCredentials: true))
          as CognitoAuthSession;
    } on AmplifyException catch (error) {
      refreshTokenLog += 'Fetch auth session fail: ${error.message}\n';
      try {
        refreshTokenLog += 'Try to sign out\n';
        await signOut();
      } on AmplifyException catch (error) {
        refreshTokenLog += 'Sign out fail: ${error.message}\n';
      }
      refreshTokenLog += 'Try to sign in';
      final bool isSignIn = await signIn();
      if (isSignIn == false) {
        refreshTokenLog += 'Sign in fail\n';
        apiLogger.i(refreshTokenLog);
        debugLogger.i(refreshTokenLog);
        return;
      }
      try {
        refreshTokenLog += 'Try to fetch auth session\n';
        session = await Amplify.Auth.fetchAuthSession(options: CognitoSessionOptions(getAWSCredentials: true))
            as CognitoAuthSession;
      } on AmplifyException catch (error) {
        refreshTokenLog += 'fetch auth session fail again: ${error.message}\n';
        apiLogger.i(refreshTokenLog);
        debugLogger.i(refreshTokenLog);
        return;
      }
    }
```

**Comment by Jordan-Nelson** [comment] 2022-03-07 03:22
Hi @jack24254029 - Can you confirm you have seen this on both iOS and Android?

**Comment by jack24254029** [comment] 2022-03-07 03:52
Hi @Jordan-Nelson 
According to my log, I search these user's device platform is iOS and device follow below list:
- iPhone Xʀ / 14.7.1
- iPhone X / 14.6
- iPhone 13 / 15.1.1

**Comment by jack24254029** [comment] 2022-03-07 04:09
I don't see this on Android, but I will keep observe it.

**Comment by Jordan-Nelson** [comment] 2022-03-07 12:29
@jack24254029 Okay, thanks for that info. 

Are you able to reproduce this behavior, or have you only been able to observe it via the logs?

**Comment by Jordan-Nelson** [comment] 2022-03-07 19:47
Okay. What is the implementation of `signIn()`, which is referenced in the line `final bool isSignIn = await signIn();`? Is the prompting the user to sign back in with username / password?

**Comment by jack24254029** [comment] 2022-03-08 01:44
No, we use a rule to generate password.
```
  Future<bool> signIn() async {
    final ProfileData? profile = await ProviderContainer().read(profileRepositoryProvider).getProfile();
    if (profile == null) {
      return false;
    }
    final SignInResult signInResult = await Amplify.Auth.signIn(
      username: profile.account,
      password: 'pwd_${appId}_${profile.account}',
    );
    return signInResult.isSignedIn;
  }
```

**Comment by Jordan-Nelson** [comment] 2022-03-10 17:23
@jack24254029 Is it possible that this is also happening after an initial log in as well (do you have logs in that scenario), or does it only occur in the scenario you have above? It could help to know if this is only happening after the initial session expires, or it it can be observed in other scenarios.

**Comment by jack24254029** [comment] 2022-03-11 01:36
I don't have log after the initial session, but I can add it.
I think relogin is same with initial sign in.

**Comment by Jordan-Nelson** [comment] 2022-03-11 15:19
@jack24254029 do you have an idea of how frequently you see this happen? Roughly what percentage of the `Try to fetch auth session` logs are followed by `fetch auth session fail again`?

**Comment by jack24254029** [comment] 2022-03-11 15:42
Fetch auth session fail first time about two or three users pre day.
In these users have zero or one user fetch auth session fail second times.

**Comment by jack24254029** [comment] 2022-03-11 15:46
Active users of day in my app about thirty (Android and iOS)

**Comment by Jordan-Nelson** [comment] 2022-03-11 21:09
@jack24254029 is `error.message` always the same in the code snippet below? The issue description says, "but sometimes had a exception, like Your session has expired. or Session expired could not fetch user sub".

Are those two separate errors you have seen, and are those the exact messages? Have you seen any others?

```dart
refreshTokenLog += 'fetch auth session fail again: ${error.message}\n';
```

**Comment by jack24254029** [comment] 2022-03-12 02:15
I only saw two errors on fetch fail first time and one error on fetch fail second times

```
FetchAuthSession Fail (First time)
Uid: 203068
Error Message:
Your session has expired.
```

```
FetchAuthSession Fail (First time)
Uid: 192598
Error Message:
Session expired could not fetch user sub

**After relogin**

FetchAuthSession (Second times)
Uid: 192598
Error Message:
There is no user signed in to retreive user sub
```

**Comment by Jordan-Nelson** [comment] 2022-03-15 13:21
@jack24254029 I am unable to reproduce this. I have run an automated test that attempts to call fetchAuthSession every 5 minutes. If fetchAuthSession fails, sign out / sign in is called, and then fetchAuthSession is called again. All failures of fetchAuthSession are logged. The app I am testing with has session token expiration set to 5 minutes and refresh token expiration set to 60 minutes. I consistently see fetchAuthSession succeed for 60 minutes until the refresh token expires. At that point the tests calls sign out / sign in, and then consistently is able to call fetchAuthSession. I do not see a second failure after sign out / sign in. This is the behavior that I would expect.

Can you log the full `AmplifyException`? Right now your logs contain the `message`. It would be helpful to see the `recoverySuggestion` and `underlyingException` if those exist.

Can you also tell me what settings you have for token expiration (session token and refresh token)? You can find this in Cognito under "General Settings" -> "App Clients".

For reference, here is the integration test code I am running. `signIn()` is similar to your `signIn()` method. It uses username/password stored in memory to sign the user back in.

```dart
testWidgets(
  'should sign a user back in after session expiration',
  (WidgetTester tester) async {
    await signIn();
    for (int i in List.generate(1000, (index) => index)) {
      print('starting test $i');
      AuthSession? session;
      int count = 0;
      while (session == null) {
        count++;
        try {
          session = await Amplify.Auth.fetchAuthSession(
            options: CognitoSessionOptions(getAWSCredentials: true),
          );
          print('Fetch auth session succeeded.');
        } on AmplifyException catch (error) {
          print(
            'Fetch auth session failed - count: $count, error: ${error.message}',
          );
          await Amplify.Auth.signOut();
          await signIn();
        }
      }
      await Future.delayed(Duration(minutes: 5));
    }
  },
  timeout: Timeout(Duration(days: 1)),
);
```

**Comment by jack24254029** [comment] 2022-03-15 13:38
Our case is that when a user had login the app, and did not open the app more than seven days.

**Comment by Jordan-Nelson** [comment] 2022-03-15 14:10
> Our case is that when a user had login the app, and did not open the app more than seven days.

What is the refresh token expiration set to?

**Comment by brunovsiqueira** [comment] 2022-03-15 21:00
I think the issue my users are having is the same. Seems that it happens in both login/relogin and also in both platforms (Android and iOS).
By looking at out logs, it is happening with several users. 
These are the exceptions I see this users are getting:

```
SessionExpiredException(message: Session expired could not fetch user sub, recoverySuggestion: Invoke Auth.signIn to re-authenticate the user, underlyingException: null)

SignedOutException(message: There is no user signed in to retreive user sub, recoverySuggestion: Call Auth.signIn to sign in a user and then call Auth.fetchSession, underlyingException: null)
```

**Comment by brunovsiqueira** [comment] 2022-03-15 22:00
Looking at an iOS user specific behavior: 
1- User is logging in normally and using our app (I can see by his logs)
2- Following method is called and returns true because SessionExpiredException is thrown:
```
Future<bool> isSessionExpired() async {
    try {
      await _fetchSession();
      return false;
    } on SignedOutException {
      return false;
    } on SessionExpiredException {
      return true;
    } on InvalidStateException {
      return true;
    } on AuthException {
      rethrow;
    }
  }
```
3- By determining that session is expired, we call: "await Amplify.Auth.signOut()"  in order to try to signout an user which his session expired.
4- After it user signs in "normally" (without throwing an exception) by entering his username and password and the app calls await Amplify.Auth.signIn. We check isUserSignedIn flag and it also returns true.
5- Right after it, we call "await Amplify.Auth.fetchAuthSession" and it throws SignedOutException. By throwing this exception, we are unable to get the access token.

**Comment by brunovsiqueira** [comment] 2022-03-15 22:15
In android, the behavior changes depending on the user. One thing never changes: user gets SessionExpiredException right after signIn (on iOS seems that he get SignedOutException).
We have some users who got SessionExpiredException even in their first signIn attempts which is really sad.

**Comment by jack24254029** [comment] 2022-03-16 01:44
> Can you also tell me what settings you have for token expiration (session token and refresh token)? You can find this in Cognito under "General Settings" -> "App Clients".

![image](https://user-images.githubusercontent.com/13265628/158500065-8dd1d0de-9336-4259-a19e-7e2a0970f0a6.png)

**Comment by jack24254029** [comment] 2022-03-16 09:28
I add the `Recovery Suggestion` into my log
```
FetchAuthSession Fail (First time)
Date time: Date Time: 2022-03-16 17:13:24.732 (GMT+08:00)
App version: 1.0.05 (339)
Platform: iOS
Device: iPhone XR
OS Version: 15.1
Uid: 92441
Error Message:
Session expired could not fetch user sub
Recovery Suggestion:
Invoke Auth.signIn to re-authenticate the user

FetchAuthSession (Second times)
Date time: Date Time: 2022-03-16 17:13:31.007 (GMT+08:00)
App version: 1.0.05 (339)
Platform: iOS
Device: iPhone XR
OS Version: 15.1
Uid: 92441
Error Message:
There is no user signed in to retreive user sub
Recovery Suggestion:
Call Auth.signIn to sign in a user and then call Auth.fetchSession
```

**Comment by brunovsiqueira** [comment] 2022-03-16 12:34
Digging deep into the problem, I found out a pattern. The users' devices who gets this problem right after signIn are not being listed in "Device tracking log" even though their events are shown as "Sign-in passed" in "User event history". Look at this user:
![MicrosoftTeams-image (32)](https://user-images.githubusercontent.com/18200284/158590957-e708bb93-84d9-4d00-a1ea-28c6fcea9dad.png)

If you see, the user tried to log in using two different devices: an iPhone and a SM-G9600 (Android). However, the only device which is listed in "Device tracking log" is the iPhone. It is a pattern, all user who had this problem I can observe the same behavior: I see the sign in event in "User event history" but I don't see the device which I see the logs in "Device tracking log".

**Comment by dnys1** [comment] 2022-03-16 18:00
Thanks for diving deep, @brunovsiqueira - I will try to reproduce the problem using this information. Apologies for the delay in resolving this issue.

@jack24254029 - does the info @brunovsiqueira shared provide any insight into your problem?

**Comment by dnys1** [comment] 2022-03-16 19:00
@brunovsiqueira - Can you share your settings for this section?

<img width="1082" alt="Screen Shot 2022-03-16 at 11 59 58 AM" src="https://user-images.githubusercontent.com/24740863/158666704-625050cf-a6c3-461c-baad-269933d8b955.png">

**Comment by jack24254029** [comment] 2022-03-17 02:02
> @jack24254029 - does the info @brunovsiqueira shared provide any insight into your problem?

Our case doesn't enable `Device tracking`
![image](https://user-images.githubusercontent.com/13265628/158721740-ecd26fae-2845-4be3-94ef-ae076bb8b302.png)

**Comment by jack24254029** [comment] 2022-03-17 09:03
New log on Android
```
FetchAuthSession Fail (First time)
Date time: Date Time: 2022-03-17 15:59:03.159 (GMT+08:00)
App version: 1.0.0.5 (339)
Platform: Android
Device: ASUS_I002D
OS Version: 11
Uid: 123917
Error Message:
Your session has expired.
Recovery Suggestion:
Please sign in and reattempt the operation.
```

**Comment by brunovsiqueira** [comment] 2022-03-17 18:23
@dnys1 here it goes:

![MicrosoftTeams-image (37)](https://user-images.githubusercontent.com/18200284/158864529-582da6d3-551f-4219-b0bf-dd633efb8f25.png)

**Comment by brunovsiqueira** [comment] 2022-03-22 14:10
@dnys1 any updates on this?

**Comment by dnys1** [comment] 2022-03-22 15:00
Hi @brunovsiqueira - I haven't been able to reproduce it yet. I've tried to trigger this using Android and iOS emulators and physical devices, signing in, signing out, reinstalling the app, etc. Everything has been working correctly so far - devices are re-registered on reinstall and no sign in attempts have been blocked yet.

**Comment by dnys1** [comment] 2022-03-22 15:01
One thing I noticed is that your user has sign ins from Web - does that mean you are using Amplify JS in a web app as well?

**Comment by brunovsiqueira** [comment] 2022-03-23 20:19
That's correct: we have a Flutter App and a React web App.

@dnys1 can you try change you client and refresh token to the minimum available and try to reproduce again?

**Comment by dnys1** [comment] 2022-03-24 14:50
Yeah, lemme try that. Thanks 👍

**Comment by dnys1** [comment] 2022-03-25 00:29
You mention reducing the refresh token duration as well - how low have you set it? If the refresh token expires, then the expected behavior is to expire the session completely, which I've been able to reproduce. In the case where just the access token has expired, I haven't yet been able to reproduce it.

**Comment by brunovsiqueira** [comment] 2022-03-25 14:10
> @brunovsiqueira You mention reducing the refresh token duration as well - how low have you set it? If the refresh token expires, then the expected behavior is to expire the session completely, which I've been able to reproduce. In the case where just the access token has expired, I haven't yet been able to reproduce it.

I have set to the minimum possible: access 10 min, refresh 1 hours. When these were my app client configurations, this error was happening a lot.

Then I reverted it app client tokens configurations to access 1 hour and refresh 24 hours and it seems to be gone or happening a lot less.

When I was investigating it I found out a big delay (more than 10 minutes, my access token expiration) between the signIn event in cognito console and the SessionExpired exception being thrown when fetching credential. I couldn't find a reason why this delay happened since the fetchAuthSession call was right after the signIn call. Additionaly, I don't understand why session wasn't refreshed when getting credentials, even when it is 10+ minutes after signIn.

**Comment by brunovsiqueira** [comment] 2022-03-25 16:52
Yeah, that's totally true. What I think is strange is the fact that user just signed in and in his first try to refresh its access token (I deduced it is first try because it happens right  -sequentially- after  signIn) gets SessionExpired.

**Comment by Jordan-Nelson** [comment] 2022-04-04 13:56
> New log on Android
> 
> ```
> FetchAuthSession Fail (First time)
> Date time: Date Time: 2022-03-17 15:59:03.159 (GMT+08:00)
> App version: 1.0.0.5 (339)
> Platform: Android
> Device: ASUS_I002D
> OS Version: 11
> Uid: 123917
> Error Message:
> Your session has expired.
> Recovery Suggestion:
> Please sign in and reattempt the operation.
> ```

@jack24254029 - Are you able to tell if the user attempted to sign in after this? Since the refresh token is set to 30 days, the user will have to re-authenticate with a username and password after 30 days. So in this case, this may be expected behavior.

**Comment by jack24254029** [comment] 2022-04-06 01:01
> @jack24254029 - Are you able to tell if the user attempted to sign in after this? ....

Yes, the user can sign in after this.

**Comment by MarlonJD** [comment] 2022-06-16 16:19
https://github.com/aws-amplify/amplify-android/issues/1763#issuecomment-1157867774

**Comment by Jordan-Nelson** [comment] 2022-08-02 20:21
Hello everyone - We have been unable to reproduce this issue. However, I am going to label this as a bug since the info provided indicates there may be a race condition present.

We have recently released a new developer preview version of the Auth category ([amplify_flutter v1.0.0-next.0](https://pub.dev/packages/amplify_flutter/versions/1.0.0-next.0)). This new version is a full re-write of the auth category in dart. While the primary purpose of this re-write was to add support for Web and Desktop, we also implemented a new design using state machines that is intended to solve issues such as race conditions.

I believe this will address the issue described above. If you are willing to experiment with this new version while it is in dev-preview we would appreciate any feedback you have.

I will provide an update on this ticket once this version is out of dev-preview and is ready for production use.

Let me know if you have any questions.

**Comment by Jordan-Nelson** [comment] 2023-01-12 22:24
@MarlonJD - Were you able to reproduce this issue consistently? If so, could you share the steps you took to reproduce it?

**Comment by MarlonJD** [comment] 2023-01-12 22:28
> @MarlonJD - Were you able to reproduce this issue consistently? If so, could you share the steps you took to reproduce it?

Hey, i couldn't remember so much, it was so long ago, but i remember that it was solved when i closed remember me option on cognito console on AWS. Maybe you can reproduce same error with remember me option true.

**Comment by Jordan-Nelson** [comment] 2023-04-17 18:57
@jack24254029 - We believe that this issue has been addressed in v1.0.0 of Amplify Flutter, which is now stable. Would you please upgrade to the latest version and let us know if you still observe this issue?

This release also includes web and desktop support for Auth, API, Analytics, and Storage. You can see the list of new features and bug fixes in the [release notes](https://github.com/aws-amplify/amplify-flutter/releases/tag/v1.0.0), and see more details on how to migrate in the [upgrade guide](https://docs.amplify.aws/lib/project-setup/upgrade-guide/q/platform/flutter/).

**Comment by jack24254029** [comment] 2023-04-18 05:58
OK. I will try it. Thank you very much.

**Comment by Jordan-Nelson** [comment] 2023-05-01 14:11
Hello @jack24254029 - I wanted to check in to see if you have had a chance to migrate to the latest version of amplify flutter. Let me know if you are facing any issues.

**Comment by jack24254029** [comment] 2023-05-02 02:35
I had migrated it in Dev enviroment. It looks like well.

**Comment by Jordan-Nelson** [comment] 2023-05-04 19:51
Great to hear. I am going to close this out. If you face any issue when moving to production, please let me know and I can re-open this.

**Closed by Jordan-Nelson** 2023-05-04 19:51 UTC
Labels: bug, pending-close-response-required, Auth, fixed-in-release-candidate
