### ISSUE TITLE
Inconsistent Network Timeout between iOS and Android

### ISSUE THREAD

**Issue by aayushkedawat** [aws-amplify/amplify-flutter#774] opened 2021-08-03 09:35 UTC
I am getting this in the error log-
E/amplify:flutter:storage_s3(23398): StorageException
E/amplify:flutter:storage_s3(23398): StorageException{message=Something went wrong with your AWS S3 Storage upload file operation, cause=com.amazonaws.AmazonClientException: Unable to execute HTTP request: SSL handshake timed out, recoverySuggestion=See attached exception for more information and suggestions}
E/amplify:flutter:storage_s3(23398):    at com.amplifyframework.storage.s3.operation.AWSS3StorageUploadFileOperation$UploadTransferListener.onError(AWSS3StorageUploadFileOperation.java:203)
E/amplify:flutter:storage_s3(23398):    at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$4.run(TransferStatusUpdater.java:306)
E/amplify:flutter:storage_s3(23398):    at android.os.Handler.handleCallback(Handler.java:914)
E/amplify:flutter:storage_s3(23398):    at android.os.Handler.dispatchMessage(Handler.java:100)
E/amplify:flutter:storage_s3(23398):    at android.os.Looper.loop(Looper.java:224)
E/amplify:flutter:storage_s3(23398):    at android.app.ActivityThread.main(ActivityThread.java:7551)
E/amplify:flutter:storage_s3(23398):    at java.lang.reflect.Method.invoke(Native Method)
E/amplify:flutter:storage_s3(23398):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/amplify:flutter:storage_s3(23398):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
E/amplify:flutter:storage_s3(23398): Caused by: com.amazonaws.AmazonClientException: Unable to execute HTTP request: SSL handshake timed out
E/amplify:flutter:storage_s3(23398):    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:456)
E/amplify:flutter:storage_s3(23398):    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
E/amplify:flutter:storage_s3(23398):    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4829)
E/amplify:flutter:storage_s3(23398):    at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1912)
E/amplify:flutter:storage_s3(23398):    at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:282)
E/amplify:flutter:storage_s3(23398):    at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:114)
E/amplify:flutter:storage_s3(23398):    at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:59)
E/amplify:flutter:storage_s3(23398):    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/amplify:flutter:storage_s3(23398):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/amplify:flutter:storage_s3(23398):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/amplify:flutter:storage_s3(23398):    at java.lang.Thread.run(Thread.java:919)
E/amplify:flutter:storage_s3(23398): Caused by: java.net.SocketTimeoutException: SSL handshake timed out
E/amplify:flutter:storage_s3(23398):    at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
E/amplify:flutter:storage_s3(23398):    at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
E/amplify:flutter:storage_s3(23398):    at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
E/amplify:flutter:storage_s3(23398):    at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
E/amplify:flutter:storage_s3(23398):    at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
E/amplify:flutter:storage_s3(23398):    at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
E/amplify:flutter:storage_s3(23398):    at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
E/amplify:flutter:storage_s3(23398):    at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
E/amplify:flutter:storage_s3(23398):    at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
E/amplify:flutter:storage_s3(23398):    at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:302)
E/amplify:flutter:storage_s3(23398):    at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245)
E/amplify:flutter:storage_s3(23398):    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
E/amplify:flutter:storage_s3(23398):    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
E/amplify:flutter:storage_s3(23398):    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
E/amplify:flutter:storage_s3(23398):    at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
E/amplify:flutter:storage_s3(23398):    at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
E/amplify:flutter:storage_s3(23398):    at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:162)
E/amplify:flutter:storage_s3(23398):    at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:75)
E/amplify:flutter:storage_s3(23398):    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:386)
E/amplify:flutter:storage_s3(23398):    ... 10 more
W/.marketwork.de(23398): Accessing hidden field Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe; (greylist, reflection, allowed)
W/.marketwork.de(23398): Accessing hidden method Lsun/misc/Unsafe;->allocateInstance(Ljava/lang/Class;)Ljava/lang/Object; (greylist, reflection, allowed)
I/flutter (23398): UploadFile Err: StorageException(message: Something went wrong with your AWS S3 Storage upload file operation, recoverySuggestion: See attached exception for more information and suggestions, underlyingException: com.amazonaws.AmazonClientException: Unable to execute HTTP request: SSL handshake timed out)

**My code**
await AmplifyStorageS3.instance.uploadFile(request:UploadFileRequest(local: image, key: imageKey, options: options),);

**Platform**
 Android

**Comment by Jordan-Nelson** [comment] 2021-08-03 16:44
Hello @aayushkedawat - Can you let me know the details of the network connection (in particular the network bandwidth) when you experienced this, and the size of the file you were uploading? Thanks.

**Comment by aayushkedawat** [comment] 2021-08-05 08:49
@Jordan-Nelson Network connection is low like 50-70 KBPS, and the size of the image is around 150-200 KB.

**Comment by Jordan-Nelson** [comment] 2021-08-05 14:46
@aayushkedawat - Thanks for the info. I will try to reproduce this and get back to you.

**Comment by Jordan-Nelson** [comment] 2021-08-12 20:16
Hello @aayushkedawat - I was able to reproduce this with a similar file size and network speed. This is happening due to the default 15 second network timeout in amplify-android, which amplify flutter uses when targeting android.

Currently there is no way to customize that timeout. If you have a use case for a longer timeout, we can make this a feature request.

I am going to at least mark this as a platform discrepancy for now since iOS does not have that same timeout.

**Comment by Jordan-Nelson** [comment] 2023-04-17 20:01
This issue has been addressed in v1.0.0 of Amplify Flutter, which is now stable. There is no timeout on the request (on any platform) in this version.

This release also includes web and desktop support for Auth, API, Analytics, and Storage. You can see the list of new features and bug fixes in the [release notes](https://github.com/aws-amplify/amplify-flutter/releases/tag/v1.0.0), and see more details on how to migrate in the [upgrade guide](https://docs.amplify.aws/lib/project-setup/upgrade-guide/q/platform/flutter/).

**Closed by Jordan-Nelson** 2023-04-17 20:01 UTC
Labels: bug, Android, Storage, platform-discrepancy, fixed-in-release-candidate
