### ISSUE TITLE
A problem occurred configuring project ':amplify_auth_cognito_android'.

### ISSUE THREAD

**Issue by anusrivas** [aws-amplify/amplify-flutter#5111] opened 2024-07-03 19:30 UTC
### Description

I keep getting following error

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':amplify_auth_cognito_android'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Error: Gradle task assembleDebug failed with exit code 1

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

on typing command flutter run

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.19.6

### Amplify Flutter Version

0.5.1

### Deployment Method

Amplify CLI

**Comment by NikaHsn** [comment] 2024-07-05 16:49
@anusrivasWhat Gradle version are you currently using? 
Newer versions of the Android Gradle Plugin (AGP) required specifying a namespace within the module's build file. Given that Amplify Flutter v0 was developed with an older Gradle version, the namespace is not defined for this project. 
I recommend that you upgrade to Amplify Flutter version ^2.0.0, as v0.x is now in maintenance mode and will only receive critical bug fixes.

**Comment by anusrivas** [comment] 2024-07-14 15:31
@NikaHsn - amplify flutter 2.2.0 is not compatible with json_annotation & json_serializable latest version, once I degraded them back to one version below and upgraded the amplify flutter it worked fine.

please look into this.

**Comment by billdacat** [comment] 2024-07-23 16:26
Also having this issue.

Because (myproject) depends on amplify_core ^2.0.0 which depends on json_annotation >=4.8.1 <4.9.0, json_annotation >=4.8.1 <4.9.0 is required.
So, because  (myproject) depends on json_annotation ^4.9.0, version solving failed.

**Comment by Jordan-Nelson** [comment] 2024-07-24 17:34
> @NikaHsn - amplify flutter 2.2.0 is not compatible with json_annotation & json_serializable latest version, once I degraded them back to one version below and upgraded the amplify flutter it worked fine.
> 
> please look into this.

@anusrivas - Amplify Flutter does not yet support json_annotation v4.9. This seems to be a different issue/error than what you first reported. Is the original issue resolved?

**Comment by Jordan-Nelson** [comment] 2024-07-24 17:46
I have opened https://github.com/aws-amplify/amplify-flutter/issues/5196 to track support for json_annotation v4.9. If the original issue is not longer reproducible I will close this out and we can use the other issue to track json_annotation v4.9. Thanks.

**Comment by Jordan-Nelson** [comment] 2024-07-30 15:28
I am closing this out since it sounds like this issue is resolved by upgrading to the latest version of amplify, and we have separate issue tracking support for json_annotation v4.9.

**Closed by Jordan-Nelson** 2024-07-30 15:28 UTC
Labels: question, pending-close-response-required, auth, pending-response
