### ISSUE TITLE
aws_signature_v4 - SerializationException: Expected null

### ISSUE THREAD

**Issue by Simon-PumpAndUp** [aws-amplify/amplify-flutter#2146] opened 2022-09-21 11:39 UTC
### Description

Hi,

Since Amplify doesn't integrate yet Rekognition I wanted to use [aws_signature_v4](https://pub.dev/packages/aws_signature_v4) to send myself HTTP post requests to verify pictures. 

There is literally no documentation about where to find the info to use the package.

I figured out small chunks of it. For instance, in the header, the target (X-Amz-Target) can be found in "the normal.json files for each service and it usually is a combination of the targetPrefix property and the actual operation name: https://github.com/aws/aws-sdk-js/tree/master/apis" ([source](https://repost.aws/questions/QUbRw_C7KISoOrFN5ShYNuFQ/http-resolver-x-amz-target))

Nonetheless, when I try to execute the following code I get:
Header: **400** 
`{x-amzn-requestid: 20c7eb27-4f7d-46cb-ad63-6e7abf9c0f92, content-type: application/x-amz-json-1.1, content-length: 61, date: Wed, 21 Sep 2022 11:27:11 GMT, connection: close}`

Body: `{"__type":"SerializationException","Message":"Expected null"}`

Here is my code: 

```
Future<List<dynamic>> verifyPicture(bool isFirstPicture, String photoPath) async {
      List<int> imageBytes = File(photoPath).readAsBytesSync();
      String base64SrcImage = base64Encode(imageBytes);
      File tplFileImage = await getImageFileFromAssets(isFirstPicture ? 'verif_pose1.png' : 'verif_pose2.png');
      imageBytes = tplFileImage.readAsBytesSync();
      String base64TplImage = base64Encode(imageBytes);

      const signer = AWSSigV4Signer(
        credentialsProvider: AWSCredentialsProvider.environment(),
      );

      // Create the signing scope and HTTP request
      const region = 'eu-central-1';
      final scope = AWSCredentialScope(
        region: region,
        service: AWSService.rekognition,
      );
      final request = AWSHttpRequest(
        method: AWSHttpMethod.post,
        uri: Uri.https('rekognition.$region.amazonaws.com', '/'),
        headers: const {
          AWSHeaders.target: 'RekognitionService.CompareFaces',
          AWSHeaders.contentType: 'application/x-amz-json-1.1',
        },
        body: json.encode({
          'QualityFilter': 'HIGH',
          ~~'SourceImage': base64SrcImage,~~
          ~~'TargetImage': base64TplImage,~~
          'SourceImage': {'Bytes': base64SrcImage},
          'TargetImage': {'Bytes': base64TplImage},
          'SimilarityThreshold': 0
        }).codeUnits,
      );

      // Sign and send the HTTP request
      final signedRequest = await signer.sign(
        request,
        credentialScope: scope,
      );
      final resp = await signedRequest.send();
      final respBody = await resp.decodeBody();

      return [];
  }
```

**EDIT:** I have replaced the HTTP request's body with the following as indicated [here](https://docs.aws.amazon.com/rekognition/latest/APIReference/API_CompareFaces.html#API_CompareFaces_RequestSyntax):
```
'SourceImage': {'Bytes': base64SrcImage},
'TargetImage': {'Bytes': base64TplImage},
```

And I get:
`{"__type":"InvalidParameterException","Code":"InvalidParameterException","Message":"Request has invalid parameters"}`

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

- flutter run --dart-define=AWS_ACCESS_KEY_ID=XXX --dart-define=AWS_SECRET_ACCESS_KEY=XXX
- Take a picture with the camera using image_picker
- Retrieve picture from assets
- Encode the picture files to base64
- Retrieve AWS credentials to sign request
- Prepare signing scope and HTTP request
- Sign and send the request
- Response's body -> SerializationException: Expected null

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment

```bash
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.5 21G72 darwin-x64, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2021.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

### Dependencies

```bash
- aws_common 0.1.1 [async collection http meta stream_transform uuid]
- aws_signature_v4 0.1.2 [async aws_common collection convert crypto http json_annotation meta path]
- image_picker_android 0.8.5+3 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.8 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.6 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.6.1 [cross_file flutter http plugin_platform_interface]
```

### Device

N/A

### OS

N/A

### Deployment Method

Amplify CLI

### CLI Version

10.0.0

### Amplify Config

const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "analytics": {
        "plugins": {
            "awsPinpointAnalyticsPlugin": {
                "pinpointAnalytics": {
                    "appId": "XXX",
                    "region": "XXX"
                },
                "pinpointTargeting": {
                    "region": "XXX"
                }
            }
        }
    },
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "pumpandup": {
                    "endpointType": "GraphQL",
                    "endpoint": "XXX",
                    "region": "XXX",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                },
                "restAPI": {
                    "endpointType": "REST",
                    "endpoint": "XXX",
                    "region": "XXX",
                    "authorizationType": "AWS_IAM"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "XXX",
                        "Region": "XXX",
                        "AuthMode": "AMAZON_COGNITO_USER_POOLS",
                        "ClientDatabasePrefix": "pumpandup_AMAZON_COGNITO_USER_POOLS"
                    },
                    "pumpandup_AWS_IAM": {
                        "ApiUrl": "XXX",
                        "Region": "XXX",
                        "AuthMode": "AWS_IAM",
                        "ClientDatabasePrefix": "pumpandup_AWS_IAM"
                    }
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "XXX",
                            "Region": "XXX"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "XXX",
                        "AppClientId": "XXX",
                        "Region": "XXX"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH | USER_PASSWORD_AUTH | CUSTOM_AUTH",
                        "socialProviders": [],
                        "usernameAttributes": [
                            "XXX"
                        ],
                        "signupAttributes": [],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "XXX"
                        ]
                    }
                },
                "PinpointAnalytics": {
                    "Default": {
                        "AppId": "XXX",
                        "Region": "XXX"
                    }
                },
                "PinpointTargeting": {
                    "Default": {
                        "Region": "XXX"
                    }
                },
                "S3TransferUtility": {
                    "Default": {
                        "Bucket": "XXX",
                        "Region": "XXX"
                    }
                }
            }
        }
    },
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "pumpandupd4fdd05f36a349788eedb71838e3c310235122-dev",
                "region": "eu-west-3",
                "defaultAccessLevel": "guest"
            }
        }
    }
}''';

**Comment by Jordan-Nelson** [comment] 2022-09-21 12:45
Hi @Simon-PumpAndUp - based on the response, I think the request is probably signed correctly but does not have the correct parameters. Unfortunately the error message isn't giving much info on which parameters are invalid. I can take a look at the Rekognition docs and try to see what might be wrong with the request.

**Comment by Simon-PumpAndUp** [comment] 2022-09-21 13:01
@Jordan-Nelson thank you for investigating! 

I've tried to send the bytes directly:
```
'SourceImage': {'Bytes': File(photoPath).readAsBytesSync().toString()},
'TargetImage': {'Bytes': tplFileImage.readAsBytesSync().toString()},
```
And then I'm getting:

`{"__type":"InvalidImageFormatException","Code":"InvalidImageFormatException","Message":"Request has invalid image format"}`

**Comment by dnys1** [comment] 2022-09-21 15:18
Hi @Simon-PumpAndUp - sorry you are running into troubles with the sigv4 client. It is, unfortunately, a very low level API which we hope to build off of with an official AWS SDK. In the meantime, I believe you may have a better experience working with an unofficial package like this one which has higher level APIs: https://pub.dev/packages/aws_rekognition_api

From comparing your request to the API docs, it seems correct (with base64-encoded images). Could this be the cause?
> If no faces are detected in the source or target images, CompareFaces returns an InvalidParameterException error.

**Comment by Simon-PumpAndUp** [comment] 2022-09-21 15:54
> If no faces are detected in the source or target images, CompareFaces returns an InvalidParameterException error.

Nope can't be. I tried with different combinations and got the same output each time. I tested my pictures on console.aws.amazon.com/rekognition directly and it worked perfectly. 

I'll check the package thank you!

**Comment by dnys1** [comment] 2022-09-22 15:47
Gotcha, well I hope the other package works for you. Thanks for raising the issue and apologies for any headaches!

I'll close the issue for now. We are working on bringing an AWS SDK to Dart, so problems like this will hopefully be non-existent in the future 😄

**Closed by dnys1** 2022-09-22 15:47 UTC
Labels: Question, Sig-v4-Signer

**Comment by Jordan-Nelson** [comment] 2022-09-22 19:15
@Simon-PumpAndUp - It seems that the Rekognition API expects a base64 encoded string representing the image data. The API docs are not clear about that. Below is an example of how to get a properly encoded image from a URL.

```dart
import 'dart:convert';

Future<String> getBase64EncodedString(String url) async {
  final asset = await NetworkAssetBundle(Uri.parse(url)).load(url);
  final bytes = asset.buffer.asUint8List();
  return base64.encode(bytes);
}
```

It looks like you already are passing in Uint8List. You can used `dart:convert` to convert to a base64 encoded string. I think with that change you should be able to get this to work. I was able to get this working in a sample app. Let me know if you have troubles.

For future reference, since the API docs are not clear, I was able to figure this out by looking at the network request in the dev tools in my browser when using the AWS console.

![Screen Shot 2022-09-22 at 3 13 58 PM](https://user-images.githubusercontent.com/20613561/191832079-f3ebb730-17c0-4813-ae73-1a828f420fb1.png)

**Comment by Simon-PumpAndUp** [comment] 2022-09-23 07:41
Thank you so much guys, the unofficial package for Rekognition works and yes changing the encoding did the trick.
