### ISSUE TITLE
UrlLauncherException when calling signInWithWebUI()

### ISSUE THREAD

**Issue by xonaman** [aws-amplify/amplify-flutter#2726] opened 2023-03-05 21:07 UTC
### Description

I execute the following code:
```dart
Amplify.Auth.signInWithWebUI(AuthProvider.apple);
```
or
```dart
Amplify.Auth.signInWithWebUI(AuthProvider.google);
```

Which gives me the following error:
```
The following UrlLauncherException was thrown:
UrlLauncherException {
  "message": "Instance of 'Future<Uri>'"
}
When the exception was thrown, this was the stack:
#0      AmplifyAuthCognitoDart.signInWithWebUI (package:amplify_auth_cognito_dart/src/auth_plugin_impl.dart:432:11)
<asynchronous suspension>
```

These are the flutter plugins I am using:
```yaml
amplify_flutter: ^1.0.0-next.5+1
amplify_auth_cognito: ^1.0.0-next.5+1
```

When downgrading both to ^0.6.0, everything works as intended.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.6

### Amplify Flutter Version

1.0.0-next.5+1

### Deployment Method

Amplify CLI

**Comment by Rohithgilla12** [comment] 2023-03-06 09:26
@xonaman Can use `1.0.0-next.3` for a temporary workaround!

**Comment by Jordan-Nelson** [comment] 2023-03-06 14:42
Hi @xonaman - Sorry that you are facing this issue. I believe this is a duplicate of https://github.com/aws-amplify/amplify-flutter/issues/2697 and https://github.com/aws-amplify/amplify-flutter/issues/2705. I am going to close this since we have other issues tracking it.

**Closed by Jordan-Nelson** 2023-03-06 14:42 UTC
Labels: duplicate
