### ISSUE TITLE
[DataStore] If a required list of CustomType is empty it returns null for Android

### ISSUE THREAD

**Issue by ebo8** [aws-amplify/amplify-flutter#1370] opened 2022-02-17 14:30 UTC
Hi. We're using DataStore with AppSync enabled. The following works fine for iOS but not for Android. 

Example of schema.graphql:
```
type Movie @model {
  id: ID!
  title: String!
  awards: [Award]!
}
type Award {
  name: String!
}
```

If the required list awards is empty then it results in a null problem for Android.

**Comment by HuiSF** [comment] 2022-02-17 17:46
Hi @ebo8 to clarify the issue impact, you meant, when the field `awards: [Award]!` list is empty
- in iOS it returns an empty list
- in Android it returns a `null` instead of an empty list

**Comment by ebo8** [comment] 2022-02-18 07:59
> Hi @ebo8 to clarify the issue impact, you meant, when the field `awards: [Award]!` list is empty
> 
> * in iOS it returns an empty list
> * in Android it returns a `null` instead of an empty list

Yes it works perfectly for iOS.

On Android it results in a problem with the sync, only when a required field list is empty.

DataStoreException{message=Invalid SQL statement: INSERT INTO `ClassName` (`id`, `aList`, `createdAt`, `field3`, `field4`) VALUES (?, ?, ?, ?, ?), cause=android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: ClassName.aList (code 1299 SQLITE_CONSTRAINT_NOTNULL)

**Comment by HuiSF** [comment] 2022-02-18 21:38
Reproduced the issue. Investigating.

**Comment by HuiSF** [comment] 2022-02-18 21:52
Root cause identified, will implement a fix in amplify-android...

**Comment by HuiSF** [comment] 2022-02-24 17:20
Once amplify-android releases the fix, amplify-flutter will bump amplify-android version to integrate the fix.

**Comment by ebo8** [comment] 2022-03-08 07:56
> Once amplify-android releases the fix, amplify-flutter will bump amplify-android version to integrate the fix.

@HuiSF is there any timeline on this? Looking forward to try this out :)
https://github.com/aws-amplify/amplify-android/releases/tag/release_v1.32.1

**Comment by HuiSF** [comment] 2022-03-09 18:45
Hi @ebo8 thanks for following up, we are going to bump the version of amplify-android soon and arrange a release. Thanks for your patience.

**Comment by HuiSF** [comment] 2022-03-24 18:47
The fix for this issue has been release with version [0.4.2](https://github.com/aws-amplify/amplify-flutter/releases/tag/v0.4.2).

I'm closing this issue now, please feel free to follow up if anything. Thanks!

**Closed by HuiSF** 2022-03-24 18:47 UTC
Labels: bug, requires-android-fix, DataStore
