### ISSUE TITLE
Pubspec version failed

### ISSUE THREAD

**Issue by decodevM** [aws-amplify/amplify-flutter#5311] opened 2024-08-16 20:14 UTC
### Description

Because no versions of amplify_auth_cognito match >2.3.0 <3.0.0 and amplify_auth_cognito 2.3.0 depends on amplify_analytics_pinpoint >=2.3.0 <2.4.0, amplify_auth_cognito ^2.3.0 requires amplify_analytics_pinpoint >=2.3.0 <2.4.0.
Because amplify_analytics_pinpoint 2.3.0 depends on package_info_plus ^6.0.0 and no versions of amplify_analytics_pinpoint match >2.3.0 <2.4.0, amplify_analytics_pinpoint >=2.3.0 <2.4.0 requires package_info_plus ^6.0.0.
Thus, amplify_auth_cognito ^2.3.0 requires package_info_plus ^6.0.0.
So, because project depends on both package_info_plus ^8.0.2 and amplify_auth_cognito ^2.3.0, version solving failed.
Process finished with exit code 1

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1: Go to pubspec.yaml
2: Flutter upgrade (to get latest version of web:)
3: add  **package_info_plus ^8.0.2** and ** amplify_auth_cognito ^2.3.0**
4: Flutter pub get
5: You will get the error message (version solving failed)

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.22.2

### Amplify Flutter Version

2.3.0

### Deployment Method

Amplify CLI

**Comment by khatruong2009** [comment] 2024-08-16 21:24
Hi @decodevM, this change is pending release. I'm going to close this issue because it is a duplicate of [this one](https://github.com/aws-amplify/amplify-flutter/issues/5255).

**Closed by khatruong2009** 2024-08-16 21:24 UTC
