### ISSUE TITLE
AuthUser.username: Inconsistent behavior on iOS and Android 

### ISSUE THREAD

**Issue by fafriat** [aws-amplify/amplify-flutter#600] opened 2021-05-28 08:48 UTC
**Describe the bug**
With Cognito configured with email:
On Android, AuthUser.username  gives user email
while on IOS, AuthUser.username gives user id

**To Reproduce**
1. Configure Cognito with email as login.
2. Do login with Amplify.Auth.signIn()
3. Use Authuser authUser = await Amplify.Auth.getCurrentUser() to get connected user
4. Then authUser.username on both Android and IOS

**Expected behavior**
A consistency between Android  and IOS.

**Comment by kjones** [comment] 2021-05-28 13:27
Related: #201

**Comment by Jordan-Nelson** [comment] 2021-06-08 19:01
Hello @fafriat - Thanks for opening the issue. I was able to reproduce this. I think this is a result of an issue in the amplify-ios library used by amplify-flutter on iOS. There is an issue open in the amplify-ios repo currently here: https://github.com/aws-amplify/amplify-ios/issues/1255. I will follow up with the team and see if this is being looked into.

As a workaround, you can get the email address consistently on both platforms using `Amplify.Auth.fetchUserAttributes()`

**Comment by Jordan-Nelson** [comment] 2021-06-08 19:53
@fafriat I am going to close this as a duplicate since #201 is already tracking this issue. Please add any further info to #201.

**Closed by Jordan-Nelson** 2021-06-08 19:53 UTC
Labels: Auth, iOS, platform-discrepancy, requires-ios-fix
