### ISSUE TITLE
Link existing user account in a user pool to an identity from an external identity provider

### ISSUE THREAD

**Issue by gnsslrrcs** [aws-amplify/amplify-flutter#580] opened 2021-05-15 01:03 UTC
Do we have existing solution for this feature of cognito? 
https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminLinkProviderForUser.html

I really need this in linking accounts. Thank you.

**Comment by Jordan-Nelson** [comment] 2022-08-23 17:12
Hello @gnsslrrcs - Would you be able to elaborate on your use case? Are you looking to automatically link an identity from a social provider (google, facebook, etc.) to an existing user when using Hosted UI / Social Sign In? If so, we are tracking that here: https://github.com/aws-amplify/amplify-flutter/issues/1716.

Let me know if your use case differs from the one in that issue. If these two issues have significant overlap, I will probably combine them. Thanks.

**Comment by abdallahshaban557** [comment] 2022-11-16 06:19
Closing as a duplicate of #1716. Please inform us if you think otherwise @gnsslrrcs

**Closed by abdallahshaban557** 2022-11-16 06:19 UTC
Labels: feature-request, Auth
