### ISSUE TITLE
Authenticator signIn does not throw any error

### ISSUE THREAD

**Issue by kamami** [aws-amplify/amplify-flutter#5276] opened 2024-08-13 09:06 UTC
### Description

I am calling state.signIn() with a custom button, but it does not throw any error I could fetch to show some feedback to the user.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

```
  void submit() async {
    if (widget.state.formKey.currentState!.validate()) {
   
      try {
   
        await widget.state.signIn();

      } catch (e) {
        if (mounted) {
       
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Row(
                children: [
                  const Icon(
                    Icons.error_rounded,
                    color: Colors.white,
                  ),
                  const SizedBox(
                    width: 8,
                  ),
                  Expanded(child: Text(e.toString())),
                ],
              ),
              backgroundColor: Colors.redAccent,
            ),
          );
        }
      } finally {}
    }
  }
```

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.24.0

### Amplify Flutter Version

2.3.0

### Deployment Method

Custom Pipeline

**Comment by khatruong2009** [comment] 2024-08-13 16:09
Hi @kamami, thank you for submitting this issue. We will take a look at it and get back to you with any questions or updates.

**Comment by khatruong2009** [comment] 2024-08-15 19:14
Hi @kamami, this is expected behavior when calling `signIn` from the state machine. You could call 
`await Amplify.Auth.signIn(state.username, state.password);` which would return a future containing any sign in errors that you would have. This would also take care of the state machine moving forward as well. If you have MFA enabled, you may have to manually progress the state.

**Comment by NikaHsn** [comment] 2024-08-21 18:18
@kamami Let us know if you have any further questions. Otherwise I will close this out since there isn't any action required in Amplify.

**Closed** 2024-08-28 13:59 UTC
Labels: question, pending-close-response-required, Authenticator
