### ISSUE TITLE
`Amplify.Storage.getUrl` stuck in the future - Does not return anything

### ISSUE THREAD

**Issue by AldrinMathew** [aws-amplify/amplify-flutter#1441] opened 2022-03-08 06:58 UTC
### Description

This happens only on iOS, Android works perfectly.
Calling `Amplify.Storage.getUrl` does not return anything.
When it is `await`ed, it never returns the awaited value, when it is used as a `Future`, there never is any data returned, when `then` is used for the future, the execution never reaches that block of code.
One factor that might make our use case different from most might be that we don't use Cognito for authentication. Also the files are accessed with `StorageAccessLevel.guest`

My bet is that the iOS plugin interface for Amplify Storage does not honor timeout specifications. Usually when a request is timed out, there shoud be `408` error. There is no exception or log messages in the emulator when this happens during debugging.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Storage

### Steps to Reproduce

Use the following code
```dart
try {
  await Amplify.Storage.getUrl(
    key: 'the_section/hello/icon',
    options: GetUrlOptions(expires: 7200),
  ).then((value) {
    _icon = value.url;
    print(value.url);
  });
} catch (e) {
  print(e);
}
```

### Platforms

- [X] iOS
- [ ] Android

### Environment

```bash
[✓] Flutter (Channel stable, 2.10.3, on Ubuntu 20.04.4 LTS 5.13.0-30-generic, locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.65.0)
[✓] VS Code (version 1.66.0-insider)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

### Dependencies

```bash
Dart SDK 2.16.1
Flutter SDK 2.10.3
es_app 0.6.2+42

dependencies:
- add_2_calendar 2.1.2 [flutter]
- amplify_auth_cognito 0.2.10 [flutter amplify_auth_plugin_interface amplify_core collection plugin_platform_interface]
- amplify_core 0.2.10 [plugin_platform_interface meta flutter uuid]
- amplify_flutter 0.2.10 [flutter plugin_platform_interface amplify_storage_plugin_interface amplify_analytics_plugin_interface amplify_auth_plugin_interface amplify_datastore_plugin_interface amplify_api_plugin_interface amplify_core]
- amplify_storage_s3 0.2.10 [flutter amplify_storage_plugin_interface plugin_platform_interface amplify_core]
- audioplayers 0.19.1 [uuid path_provider http flutter flutter_web_plugins]
- auto_size_text 3.0.0 [flutter]
- contacts_service 0.6.3 [flutter collection quiver]
- crypto 3.0.1 [collection typed_data]
- cupertino_icons 1.0.4
- favorite_button 0.0.4 [flutter]
- firebase_auth 3.3.3 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.10.5 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 11.2.3 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_dotenv 5.0.2 [flutter]
- flutter_fadein 2.0.0 [flutter]
- flutter_launcher_icons 0.9.2 [args image path yaml]
- flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]
- form_field_validator 1.1.0 [flutter intl]
- google_sign_in 5.2.1 [flutter google_sign_in_platform_interface google_sign_in_web meta]
- http 0.13.4 [async http_parser meta path]
- image_crop 0.4.0 [flutter]
- image_picker 0.8.4+4 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- intl 0.17.0 [clock path]
- keyboard_dismisser 2.0.0 [flutter]
- material_design_icons_flutter 5.0.6595 [flutter]
- package_info_plus 1.3.0 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- path_provider 2.0.8 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- pay 1.0.6 [flutter flutter_localizations pay_android pay_ios pay_platform_interface meta]
- permission_handler 8.3.0 [flutter meta permission_handler_platform_interface]
- provider 6.0.1 [collection flutter nested]
- shared_preferences 2.0.11 [flutter meta shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- sign_in_with_apple 3.3.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- sleek_circular_slider 2.0.1 [flutter]
- social_share 2.2.1 [flutter path_provider]
- table_calendar 3.0.3 [flutter intl simple_gesture_detector]
- turbo 1.2.1 [flutter]
- uuid 3.0.5 [crypto]
- video_player 2.2.7 [flutter meta video_player_platform_interface video_player_web html]

transitive dependencies:
- amplify_analytics_plugin_interface 0.2.10 [amplify_core flutter meta]
- amplify_api_plugin_interface 0.2.10 [amplify_core collection flutter meta uuid]
- amplify_auth_plugin_interface 0.2.10 [flutter meta amplify_core]
- amplify_datastore_plugin_interface 0.2.10 [flutter meta collection date_time_format uuid amplify_core]
- amplify_storage_plugin_interface 0.2.10 [flutter meta amplify_core]
- archive 3.1.6 [crypto path]
- args 2.3.0
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.15.0
- cross_file 0.3.2 [flutter js meta]
- csslib 0.17.1 [source_span]
- date_time_format 2.0.1
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_auth_platform_interface 6.1.8 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.3.4 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.2.2 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.5.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.1.3 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.2.4 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path typed_data vector_math]
- flutter_plugin_android_lifecycle 2.0.5 [flutter]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph typed_data]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- google_sign_in_platform_interface 2.1.0 [flutter meta quiver]
- google_sign_in_web 0.10.0+3 [flutter flutter_web_plugins google_sign_in_platform_interface js meta]
- html 0.15.0 [csslib source_span]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.1.0 [archive meta xml]
- image_picker_for_web 2.1.4 [flutter flutter_web_plugins image_picker_platform_interface meta]
- image_picker_platform_interface 2.4.1 [flutter http meta plugin_platform_interface cross_file]
- js 0.6.3
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- nested 1.0.0 [flutter]
- package_info_plus_linux 1.0.3 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.4 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.4 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.0
- path_drawing 0.5.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider_android 2.0.9 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.7 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.2 [flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.4 [flutter meta path_provider_platform_interface]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.4 [ffi flutter meta path path_provider_platform_interface win32]
- pay_android 1.0.5 [flutter flutter_localizations pay_platform_interface flutter_svg]
- pay_ios 1.0.5 [flutter pay_platform_interface]
- pay_platform_interface 1.0.2 [flutter yaml]
- pedantic 1.11.1
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- petitparser 4.4.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.0.2 [meta]
- process 4.2.4 [file path platform]
- quiver 3.0.1+1 [matcher]
- rxdart 0.27.3
- shared_preferences_android 2.0.9 [flutter meta shared_preferences_platform_interface]
- shared_preferences_ios 2.0.8 [flutter meta shared_preferences_platform_interface]
- shared_preferences_linux 2.0.3 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.2 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.2 [flutter flutter_web_plugins meta shared_preferences_platform_interface]
- shared_preferences_windows 2.0.3 [file flutter meta path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- simple_gesture_detector 0.2.0 [flutter]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.2 [flutter sqflite_common path]
- sqflite_common 2.2.0 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.4.8 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.1
- video_player_platform_interface 4.2.0 [flutter flutter_test meta]
- video_player_web 2.0.4 [flutter flutter_web_plugins meta video_player_platform_interface]
- win32 2.3.1 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

### Device

iPhone XR, iPhone 12, iPhone SE

### OS

iOS 15.1, iOS 14...

### CLI Version

7.6.4

**Comment by Jordan-Nelson** [comment] 2022-03-10 17:06
Hello @AldrinMathew - Can you provide some more info on your auth setup so that we can attempt to reproduce this?

**Comment by fjnoyp** [comment] 2022-03-15 01:36
Hi @AldrinMathew how are you calling getUrl with `StorageAccessLevel.guest`? 

Can you rewrite your code to match the example code we have here - make sure to pass in the `S3GetUrlOptions` with guest access as shown below. 
```

  void getUrl() async {
    try {
      print('In getUrl');
      String key = _uploadFileResult;
      S3GetUrlOptions options = S3GetUrlOptions(
          accessLevel: StorageAccessLevel.guest, expires: 10);
      GetUrlResult result =
          await Amplify.Storage.getUrl(key: key, options: options);

      setState(() {
        _getUrlResult = result.url;
      });
    } catch (e) {
      print('GetUrl Err: ' + e.toString());
    }
  }
```

**Comment by fjnoyp** [comment] 2022-03-16 20:18
Hi @AldrinMathew any updates on this new attempt?

**Comment by AldrinMathew** [comment] 2022-03-17 08:27
@fjnoyp 
We were passing `GetUrlOptions` to get the URL. With an `expires` value of 7200 in some cases and `null` in other cases.
Does the `expires` value should be in seconds or minutes?
Also why is there a `GetUrlOptions` and an `S3GetUrlOptions`?

**Comment by AldrinMathew** [comment] 2022-03-17 16:28
@fjnoyp 
Just made another deployment with the provided code sample, and the issue persists

**Comment by fjnoyp** [comment] 2022-03-18 19:08
Hi @AldrinMathew the value is in seconds for expires. 
There are 2 options for making our library more flexible.  `S3GetUrlOptions` are Amazon S3 specific options.  Our framework could feasibly work with another cloud provider that isn't S3 which would extend from the base `GetUrlOptions`. 

Your issue is quite strange.  As you don't have any log output for iOS it's hard to know what the issue is.  Furthermore, our example app on iOS is working for getURL with guestAccess.  

1) Do you have any unique configurations to your storage? 

2) Do you add the Auth category in your Dart code?  The code shouldn't run properly if you didn't add it, but I wonder how you configured it. 

3) Since you probably have to add Auth, I wonder how it might be conflicting with your Google Auth.  To see this interaction, I would need to debug your code on my machine.  You can share with my github id: @fjnoyp

**Comment by AldrinMathew** [comment] 2022-03-24 12:59
@fjnoyp 
### 1
```
"UserAgent": "aws-amplify-cli/2.0",
"Version": "1.0",
"auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "******************************************",
                            "Region": "********"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "*****************",
                        "AppClientId": "*************************",
                        "Region": "*********"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [],
                        "usernameAttributes": [],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                },
                "S3TransferUtility": {
                    "Default": {
                        "Bucket": "***************************",
                        "Region": "********"
                    }
                }
            }
        }
    },
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "*****************************",
                "region": "*********",
                "defaultAccessLevel": "guest"
            }
        }
    }
```

### 2
Yes, the `AmplifyAuthCognito` and `AmplifyStorageS3` plugins are already added before configuration

### 3
Why should it conflict to begin with? These are entirely different packages and services. Also, why is it conflicting only on iOS devices?

**I think there might be a dependency for the iOS libraries for the Amplify package that is causing the issue. Also does the `getUrl` function honor request timeout? If so how many seconds? If not, why isn't it?**

**Comment by fjnoyp** [comment] 2022-05-07 22:12
Hi @AldrinMathew do you have this issue anymore?

**Comment by Jordan-Nelson** [comment] 2022-06-06 15:06
@AldrinMathew - Let us know if you are still experiencing this issue. If we do not hear back, we will close this out. Thanks.

**Closed** 2022-06-27 22:46 UTC
Labels: iOS, pending-close-response-required, Storage, pending-triage
