### ISSUE TITLE
Flutter Hot-restart doesnt work (app just stops) after adding AmplifyPushNotificationsPinPoint plugin.

### ISSUE THREAD

**Issue by sprisao** [aws-amplify/amplify-flutter#3026] opened 2023-05-11 04:48 UTC
### Description

Flutter Hot-restart doesnt work (app just stops) after adding AmplifyPushNotificationsPinPoint plugin.

### Categories

- [X] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Add AmplifyPushNotificationsPinpoint()
2. Perfom flutter hot reload

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10

### Amplify Flutter Version

11.1.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment] 2023-05-11 10:49
Closing as a duplicate of https://github.com/aws-amplify/amplify-flutter/issues/2989

**Closed** 2023-05-11 10:49 UTC
Labels: duplicate, pending-triage, push notifications
