### ISSUE TITLE
Relationship names generated by Admin UI conflicts with model names by default

### ISSUE THREAD

**Issue by hackrx** [aws-amplify/amplify-flutter#787] opened 2021-08-06 19:01 UTC
**Describe the bug**
I created a data model in the amplify and I used the following types:
1. Enum
2. CustomType
3. Scalar types
Enum and Scalar types along with model fetched perfectly with the amplify pull, but for the custom type, blank file with these two imports are generating.
```
/*
* Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License").
* You may not use this file except in compliance with the License.
* A copy of the License is located at
*
*  http://aws.amazon.com/apache2.0
*
* or in the "license" file accompanying this file. This file is distributed
* on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
* express or implied. See the License for the specific language governing
* permissions and limitations under the License.
*/

// ignore_for_file: public_member_api_docs

import 'package:amplify_datastore_plugin_interface/amplify_datastore_plugin_interface.dart';
import 'package:flutter/foundation.dart';

```

**To Reproduce**
1. Create a data model with custom type,
2. Pull this model using `amplify pull --appId <appID> --envName staging `
3. Now check the `models` folder
4. You will found the blank file for custom types

One more thing, my other model is also not working fine, eg. I have a user model which is working fine at the backend if I query anything using AppSync query, but after fetched successfully from the Amplify, it shows this error:
![image](https://user-images.githubusercontent.com/54453778/128558815-d5f69e47-c33d-4abe-ae83-553b94822cb3.png)

I even tried importing the files manually but it didn't work.

**Expected behavior**
It should store the custom types properly, and it should recognize the class type.

 
**Platform**
Amplify Flutter currently supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[x] iOS

<details>
amplify -v
5.1.0

  amplify_flutter: ^0.2.1
  amplify_auth_cognito: ^0.2.0
  amplify_analytics_pinpoint: ^0.2.0
  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/hackrx/Documents/Development/flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/hackrx/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/hackrx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```

</details>

**Comment by cshfang** [comment] 2021-08-06 19:38
Hi @hackrx would you be able to share with me what graphql schema you're using that's leading to the blank files above?

Could you also share with me what version of the CLI you're currently using?
```bash
$ npm list @aws-amplify/cli -g 
```

**Comment by hackrx** [comment] 2021-08-06 20:25
Hi @cshfang, thanks for the quick reply. I can't share the complete graphQL schema, but yes I can share a part that is having issues.
`Notification` [Model]
![image](https://user-images.githubusercontent.com/54453778/128566577-367c94a0-ae4c-4237-b5fe-034f06dfe83f.png)
`NotificationObjectType` [CustomType] 
![image](https://user-images.githubusercontent.com/54453778/128566636-72f32bae-0d11-4ef9-b13a-ac9ee54831c8.png)
`NotificationType` [Enum]
![image](https://user-images.githubusercontent.com/54453778/128566699-f2179791-a21c-47dc-87b0-d0021ef4bdc7.png)

```
$ npm list @aws-amplify/cli -g 
/usr/local/lib
└── @aws-amplify/cli@4.51.3
```
`lib/models/NotificationObjectType`
![image](https://user-images.githubusercontent.com/54453778/128567061-f8219e40-e522-4694-a2df-c0efb87e2efb.png)

`lib/models/Notificatio.dart`
![image](https://user-images.githubusercontent.com/54453778/128567183-04bbd5d2-1034-4c97-be35-374b0d6609b9.png)

I m facing a similar issue with the user model, also in other models `user` is showing an error of isn't a type.

>  Do you mean in the Amplify Admin UI or via AWS Console?
>
I created the model using Amplify Admin UI.
Thanks.

**Comment by cshfang** [comment] 2021-08-06 21:04
Thanks for following up with the above, @hackrx 

Regarding the empty `NotificationObjectType` model, this is the result of CustomType being a nested model. Unfortunately, at this time, amplify-flutter does not yet support nested models but we are actively working towards this. You can track the progress of this effort here: https://github.com/aws-amplify/amplify-flutter/issues/260

> @aws-amplify/cli@4.51.3

Regarding the CLI version you shared above, I would also like to point out that there have been a lot of changes made to the codegen models (including introduction of dart null safety) and it would be advisable to upgrade to the latest if it is feasible for your project to do so. I bring this up because I believe when we do add the support for nested models there will certainly be changes to codegen that will require updating to the latest CLI at that time.

I do wish I had a better answer for you at this time but, for now, I will close this ticket in favor of the larger/older thread.

Duplicate of #260

**Comment by hackrx** [comment] 2021-08-07 05:23
Thanks @cshfang, I upgraded the amplify CLI version to 
`5.1.0`
Now nested custom type issue is solved but still, I am facing issues with the model.

`MSubscription` [Model]

![image](https://user-images.githubusercontent.com/54453778/128588923-7730d226-6aad-4053-976a-51c4a5382030.png)

`lib/models/MSubscription` [file]


![image](https://user-images.githubusercontent.com/54453778/128588948-8eed4899-77ac-45af-9180-ccb7d96111f3.png)

I tried manually importing the `User` model in the MSubsciption but it is not working, the model provider has a User export too.

![image](https://user-images.githubusercontent.com/54453778/128589005-361c4404-6386-44b5-98b1-ee67408e7c16.png)

`lib/models/User.dart` model has error of `MSubscription`

![image](https://user-images.githubusercontent.com/54453778/128589063-946ab403-2bab-487d-8b90-d3650cd06b1c.png)


I am facing the same issue with other models too.

**Comment by hackrx** [comment] 2021-08-07 08:22
I found a solution for this, when I commented the getter from the file, then it is recognizing the type:
`lib/models/User.dart`
![image](https://user-images.githubusercontent.com/54453778/128593856-bf895140-8f5f-4503-a199-29c404eb4689.png)

and in `lib/models/MSubscription.dart`

![image](https://user-images.githubusercontent.com/54453778/128593926-c621af01-7f92-42a8-8b42-472f736c3f91.png)

but I am not sure if this should be the solution to this problem. Please help me to fix this issue.

**Comment by hackrx** [comment] 2021-08-08 10:55
I am able to solve this issue, by editing models relationship, like if I have a relationship user to MSubscription i.e 1:1. So I named this relationship as MSubscription (Default) in the user model, which was creating conflict in the generated dart file. In getter function, it was written as
```MSubscrition get MSubscription{
...
```
that's why it was creating conflict, instead of MSubcription (default) I changed it to userToMSubscription in the user model, then I pulled the change and the error was solved.
```MSubscrition get userToMSubscription{
...
```
This needs to be fixed in amplify-cli to export all the names properly covering this case too i.e if the name of the relationship is the same as of any model then it should be named differently at the backend at least the first letter of the relationship name should be lower case, then also it will solve the problem, right now it adds `_` and in getter function field name also generates as same as the model name which is a type.

I hope this will be fixed in the next release :)
@cshfang now you can close this issue if you find this solution helpful.
Thanks.

**Comment by cshfang** [comment] 2021-08-09 17:40
Hi @hackrx 
Thank you for your investigation and explanation. I was able to reproduce this via Admin UI and would like to keep this issue open for tracking this problem. In general, I think we use lowercase for the relationship field in models and I suspect that's the reason why we had no run into this so thank you for calling it to our attention.

**Comment by cshfang** [comment] 2021-08-09 18:31
Sharing minimal repro steps:

Given models created via Admin UI, the default relationship name is often exactly the same as the related model:
![image](https://user-images.githubusercontent.com/5827964/128754684-f63b89cc-bc53-4952-9ca9-a9c76f484ee8.png)

This results in a schema like the one below:
```graphql
type Author @model @auth(rules: [{ allow: public }]) {
  id: ID!
  name: String
}

type Book @model @auth(rules: [{ allow: public }]) {
  id: ID!
  title: String
  Author: Author @connection
}
```
This results in a conflict as both the `Author` model and the `Author` relationship would be used in the `Book` model:
```dart
class Book extends Model {
  ...
  final Author? _Author;  // Author here is intended to be the Author model/type
  ...
  Author? get Author {    // Author here is intended to be the relationship field
    return _Author;
  }
}
```

### Expected behavior
Relationship field not to conflict with model _by default_

**Comment by HuiSF** [comment] 2021-11-08 22:43
Hi @hackrx amplify-flutter `0.3.0-rc.2` has been release which includes the support of CustomType.

This preview release requires a corresponding preview release of `@aws-amplify/cli`. Please refer to the [changelog](https://pub.dev/packages/amplify_datastore/versions/0.3.0-rc.2/changelog#030-rc2-2021-11-08) to get the detail how to start using CustomType with this preview release. Please test with your project, and follow up if you encounter any issues. Feedback is much appreciated!

**Comment by yucomds** [comment] 2021-12-13 13:24
@HuiSF do you know when it will be released as main version?

**Comment by HuiSF** [comment] 2021-12-14 16:57
Hi @yucomds thanks for inquiry, you meant `0.3.0`? We have a little polishing to do, it will be soon available as a formal release.

**Closed** 2022-02-26 02:43 UTC
Labels: bug, Model Gen
