### ISSUE TITLE
 compiling for iOS 9.0, but module 'Starscream' has a minimum deployment target of iOS 11.0:

### ISSUE THREAD

**Issue by seanbrhn3** [aws-amplify/amplify-flutter#359] opened 2021-02-06 02:19 UTC
**Describe the bug**
After the newest update using amplify_flutter: '<1.0.0' ,amplify_auth_cognito: '<1.0.0' and  amplify_analytics_pinpoint: '<1.0.0'
causes this error ```compiling for iOS 9.0, but module 'Starscream' has a minimum deployment target of iOS 11.0:```
changing the IOS deployment version to the specified deployment target still does not fix the issue

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] iOS

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: [e.g. iOS11.0

**Comment by fjnoyp** [comment] 2021-02-06 03:53
Hi @seanbrhn3 how did you change the iOS deployment version?  Within your project folder, did you go to ios/Podfile and at line 2, write platform :ios, '11.0'?

Could you run 'flutter run clean build' afterwards and then try again.

**Comment by seanbrhn3** [comment] 2021-02-06 04:29
Thanks you for the fast reply, I ran ```flutter run clean build``` and ```clean``` doesn't seem to be an argument for ```flutter run```  I ran ```flutter clean``` instead then ```flutter run``` but still got the same error. I've changed the ios target to '11.0'
in the podfile and I went to project.pbxproj and changed the ```IPHONEOS_DEPLOYMENT_TARGET``` to '11.0' as well and still the error persists.

**Comment by fjnoyp** [comment] 2021-02-10 23:02
Hi @seanbrhn3 unfortunately I am not able to reproduce this error on my side.  Could you try updating to ios platform 13 in your podfile instead and see if that fixes your problem.

**Comment by seanbrhn3** [comment] 2021-02-11 01:32
So I did that and this is the error ```  /Users/seanbrown/projects/apps_flutter/watMobile/ios/Pods/AppSyncRealTimeClient/AppSyncRealTimeClient/Connection/AppSyncConnection/AppSyncSubscriptionConnection+ErrorHandler.swift:9:8: error: compiling for iOS 9.0, but module 'Starscream' has a minimum deployment target of iOS 13.0: /Users/seanbrown/projects/apps_flutter/watMobile/build/ios/Debug-iphonesimulator/Starscream/Starscream.framework/Modules/Starscream.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
    import Starscream
```

**Comment by Amplifiyer** [comment] 2021-02-11 20:58
@seanbrhn3 I tried your reproduction steps on a new app with these dependencies and I'm unable to reproduce it. Would you be able to upload your app to a github repository which we can pull down to see this error?

**Comment by seanbrhn3** [comment] 2021-02-15 21:55
@Amplifiyer I'll add you as a collaborator to take a look sorry for the wait.

**Comment by Amplifiyer** [comment] 2021-02-17 20:03
thanks @seanbrhn3. What flutter version are you using? I was on a stable Flutter 1.22 and I didn't get the error and your project build successfully. I then changed to master channel and upgraded to latest flutter `Flutter 1.27.0-2.0.pre.135` and started seeing the error you observed.

**Comment by Amplifiyer** [comment] 2021-02-17 20:10
Changing back to latest stable branch of flutter also fixed the issue 

(after cleaning the workspace `cd ios && pod deintegrate && pod cache clean --all && rm Podfile.lock && cd .. && flutter clean`)

**Comment by seanbrhn3** [comment] 2021-02-18 04:55
I see I've been running Flutter 1.27.0-2.0.pre.64  I think I need to go back to the stable version of flutter

**Comment by rhamnett** [comment] 2021-03-01 23:42
Hello, I am seeing this error using master or beta channel of flutter. Seems not to take notice of the target v 11.0. Using the example straight from git at https://github.com/graphicbeacon/amplify_flutter_authflow

**Comment by Amplifiyer** [comment] 2021-03-03 21:02
Now that the beta version is new flutter 2.0, if you are facing this problem again, can you try updating your auto generated Podfile 
```diff
 post_install do |installer|
   installer.pods_project.targets.each do |target|
     flutter_additional_ios_build_settings(target)
+    target.build_configurations.each do |config|
+      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
+    end
   end
 end
```

and let us know if it works.

**Comment by rhamnett** [comment] 2021-03-03 21:10
This fixed it for me! @Amplifiyer

**Comment by rmargolinross** [comment] 2021-03-04 23:38
Flutter 2 is no in stable and there really should be a proper fix put in place for this. Not just some workaround

**Comment by Amplifiyer** [comment] 2021-03-05 00:16
@rmargolinross you are right, this is only a temporary workaround to unblock customers who are using flutter v2 and we will figure out the actual root cause and fix. Leaving this issue open to track it.

**Comment by JamesMcIntosh** [comment] 2021-03-15 12:42
@Amplifiyer The suggested fix didn't work but reinstalling the pods worked for me.
```
cd ios
rm -rf Pods/*
rm -f Podfile.lock
pod install
```

**Comment by cto-leaps** [comment] 2021-03-16 20:41
Any plan to make the fix more permanent now that stable version is out?

**Comment by Amplifiyer** [comment] 2021-03-17 23:13
I spent some time looking into it to evaluate if there is any workaround we can provide in the library itself and have not been successful. Next we need to look into the difference between Flutter 1.x and Flutter 2.x and understand why it's causing an issue only in 2.x (e.g. the auto generated Podfiles are different). Appreciate everyone's patience with it while we figure this out.

**Comment by mprogers** [comment] 2021-03-25 00:06
This did not solve my problem:

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end

I cleaned the project and and get the same message.

**Comment by mprogers** [comment] 2021-03-25 00:48
I don't know if this is the same problem, but I too am getting an error about Starscream and deployment targets:

/Users/me/Downloads/desperado-3/ios/Pods/Socket.IO-Client-Swift/Source/SocketIO/Engine/SocketEngine.swift:27:8: Compiling for iOS 10.0, but module 'Starscream' has a minimum deployment target of iOS 13.0: /Users/me/Library/Developer/Xcode/DerivedData/Runner-bvpvzsabnkerxeefbmvnaewlbfey/Build/Products/Debug-iphonesimulator/Starscream/Starscream.framework/Modules/Starscream.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

**Comment by Amplifiyer** [comment] 2021-03-30 23:20
@mprogers can you provide a minimal reproducible app where you are seeing this issue? The workaround has worked for other customers, so I wanted to know if there is any difference in your setup. (Flutter version, podfile, pubspec.yaml etc)

**Comment by BoshiLee** [comment] 2021-04-25 09:17
> I don't know if this is the same problem, but I too am getting an error about Starscream and deployment targets:
> 
> /Users/me/Downloads/desperado-3/ios/Pods/Socket.IO-Client-Swift/Source/SocketIO/Engine/SocketEngine.swift:27:8: Compiling for iOS 10.0, but module 'Starscream' has a minimum deployment target of iOS 13.0: /Users/me/Library/Developer/Xcode/DerivedData/Runner-bvpvzsabnkerxeefbmvnaewlbfey/Build/Products/Debug-iphonesimulator/Starscream/Starscream.framework/Modules/Starscream.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

i have same issue

**Comment by offlineprogrammer** [comment] 2021-05-12 21:06
Hi @seanbrhn3 @rmargolinross @cto-leaps @mprogers @BoshiLee 

I couldn't reproduce this issue using Flutter 2.0.5. I didn't need the post_install workaround. The only pod file change I needed is to set the platform to 13

My setup details 

```yaml


dependencies:
  flutter:
    sdk: flutter
  amplify_flutter: ^0.1.4
  amplify_auth_cognito: ^0.1.4
  amplify_analytics_pinpoint: ^0.1.4
  amplify_datastore: ^0.1.4

```

podfile 

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

```

Feel free to test using the latest build and let us know if you got any issues

Thanks
Mo

**Comment by offlineprogrammer** [comment] 2021-05-21 16:36
Hey @seanbrhn3 @rmargolinross @cto-leaps @mprogers @BoshiLee

I am closing this issue for now as I didn't hear from you and I couldn't reproduce as per my comment above.
We can reopen it if you are still facing the issue and when you provide details

Regards
Mo

**Closed by offlineprogrammer** 2021-05-21 16:36 UTC
Labels: Analytics, bug, pending-close-response-required

**Comment by aaronsamkennedy** [comment] 2021-06-19 22:35
This happened to me and what worked was a combination of what @Amplifiyer said earlier and some others on various posts. 

edit Podfile: 
`post_install do |installer|
   installer.pods_project.targets.each do |target|
     flutter_additional_ios_build_settings(target)
+    target.build_configurations.each do |config|
+      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET' = '11.0'
+    end
   end
 end`

Make sure MinimumOSVersion is set to 11.0 in ios/Flutter/AppFrameworkInfo.plist and that it matches platform:ios, 11.0 in the Podfile. 

For reference I am currently on Flutter 2.0.2 with all Amplify packages at version 1.0.0 and this issue only arose when I added the amplify_api to my pubspec, storage, pinpoint, and auth all worked prior with no issues. 

Here's a link to a related problem and solution https://stackoverflow.com/questions/63973136/the-ios-deployment-target-iphoneos-deployment-target-is-set-to-8-0-in-flutter

**Comment by aaronsamkennedy** [comment] 2021-06-19 22:52
This happened to me and what worked was a combination of what @Amplifiyer said earlier and some others on various posts. 

edit Podfile: 

`post_install do |installer|
   installer.pods_project.targets.each do |target|
     flutter_additional_ios_build_settings(target)
+    target.build_configurations.each do |config|
+      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0' 
+    end
   end
 end`

Make sure MinimumOSVersion is set to 11.0 in ios/Flutter/AppFrameworkInfo.plist and that it matches platform:ios, 11.0 in the Podfile. 

For reference I am currently on Flutter 2.0.2 with all Amplify packages at version 1.0.0 and this issue only arose when I added the amplify_api to my pubspec, storage, pinpoint, and auth all worked prior with no issues. 

Here's a link to a related problem and solution https://stackoverflow.com/questions/63973136/the-ios-deployment-target-iphoneos-deployment-target-is-set-to-8-0-in-flutter

**Comment by Thakursandy** [comment] 2024-01-17 05:59
<img width="1302" alt="Screenshot 2024-01-17 at 11 11 06 AM" src="https://github.com/aws-amplify/amplify-flutter/assets/58584565/e6f0760e-dd7a-4396-92d6-5db79a499a13">
showing this same error.
