### ISSUE TITLE
Unable to delete relationship between two tables with a one-many relationship

### ISSUE THREAD

**Issue by AdamMoroff75** [aws-amplify/amplify-flutter#2935] opened 2023-04-25 23:25 UTC
### Description

**Problem statement**
I am unable to *delete* a relationship between two tables which have a one-to-many relationship.   

**What's happening?**
I have two tables defined as listed below.  The first is a Customer and the second is a Vehicle.  A Customer can have many Vehicles and a Vehicle can belong to one customer.

```
type Customer @model @auth(rules: [{ allow: private }]){
  id: ID!
  first_name: String!
  last_name: String!
  drivers_license: String
  email: String
  phone: String!
  Notes: String
  business: Business @belongsTo
  vehicles: [Vehicle] @hasMany
}

type Vehicle @model @auth(rules: [{allow: private}]){
  id: ID!,
  registration_number: String!,
  make: String,
  model: String,
  vin: String,
  colour: String,
  notes: String
  customer: Customer @belongsTo
  business: Business @belongsTo
}

```

I can save instances of both record types as such:

```
Customer customer = Customer(
            id: "1234",
            first_name: "Bob",
            last_name: "Smith,
            phone: "555",
            email: "bob@home.com",
            business: business,
            drivers_license: "12345",
            Notes: "my notes");
        
await Amplify.DataStore.save(customer);


Vehicle vehicle = Vehicle(
            id: "1234",
            registration_number: "1234",
            make: "Mazda",
            model: "2012",
            vin: "12233",
            colour: "Whte",
            business: business,
            notes: "my notes");

await Amplify.DataStore.save(vehicle);
```

At this point the records are *not* linked together and are independent of each other.

Next, I create a relationship between the Vehicle and the Customer by updating the Vehicle's *customer* property with a Customer object as such:

```
var updatedVehicle = vehicle.copyWith(customer: customer);
await Amplify.DataStore.save(vehicle);
```
It is at this point that a relationship has now been established between the Customer and Vehicle records.  Now this is where Im having an issue.  If I want to *remove* the link between the two records I would expect to update the Vehicle's *customer* property with a *null* object thus removing the link as described below, remember I dont **not** want to delete the Vehicle or Customer records, just the link between the two records. 

```
var updatedVehicle = vehicle.copyWith(customer: null);   <------ this should remove the link, right??
await Amplify.DataStore.save(vehicle);

```
This doesnt seem to work because during the *copyWith* operation there is a coalese statement that states:

```
Vehicle copyWith({String? id, String? registration_number, String? make, String? model, String? vin, String? colour, String? notes, Customer? customer, Business? business}) {
    return Vehicle._internal(
      id: id ?? this.id,
      registration_number: registration_number ?? this.registration_number,
      make: make ?? this.make,
      model: model ?? this.model,
      vin: vin ?? this.vin,
      colour: colour ?? this.colour,
      notes: notes ?? this.notes,
      customer: customer ?? this.customer, <------ this is preventing me from removing the link.
      business: business ?? this.business);
  }

```

Is this a bug or perhaps I'm missing something?  I've checked the documentation and it only describes deleting a relationship by deleting a parent record which in-turn deletes all of its related children, but that's not what I want to do here, I just want to *remove the link* between the two records.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Steps to Reproduce

**Step 1**
Create two tables as listed below.  A customer can have many vehicles and a vehicle can belong to just one customer.  

```
type Customer @model @auth(rules: [{ allow: private }]){
  id: ID!
  first_name: String!
  last_name: String!
  drivers_license: String
  email: String
  phone: String!
  Notes: String
  business: Business @belongsTo
  vehicles: [Vehicle] @hasMany
}

type Vehicle @model @auth(rules: [{allow: private}]){
  id: ID!,
  registration_number: String!,
  make: String,
  model: String,
  vin: String,
  colour: String,
  notes: String
  customer: Customer @belongsTo
  business: Business @belongsTo
}

```
**Step 2:**
Create two records of each type:
```
Customer customer = Customer(
            id: "1234",
            first_name: "Bob",
            last_name: "Smith,
            phone: "555",
            email: "bob@home.com",
            business: business,
            drivers_license: "12345",
            Notes: "my notes");
        
await Amplify.DataStore.save(customer);


Vehicle vehicle = Vehicle(
            id: "1234",
            registration_number: "1234",
            make: "Mazda",
            model: "2012",
            vin: "12233",
            colour: "Whte",
            business: business,
            notes: "my notes");

await Amplify.DataStore.save(vehicle);
```
**Step 3: Link the Vehicle to the Customer **
```
var updatedVehicle = vehicle.copyWith(customer: customer);
await Amplify.DataStore.save(vehicle);
```
**Step 4: Remove the kinbk between the Vehicle and the Customer **
```
var updatedVehicle = vehicle.copyWith(customer: null);   <------ this should remove the link, right??
await Amplify.DataStore.save(vehicle);

```

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.10

### Amplify Flutter Version

11.0.3

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type Business @model @auth(rules: [{ allow: private }]) {
    id: ID!
    businessName: String!
    address: Address @hasOne
    users: [User] @hasMany
    customers: [Customer] @hasMany
    vehicles: [Vehicle] @hasMany
}

type User @model @auth(rules: [{ allow: owner },
{ allow: private, operations: [read]}]) {
  id: ID!
  first_name: String!
  last_name: String!
  email: String,
  phone: String!
  stripe_customer_id: String  
  business: Business @belongsTo
}

type Address @model @auth(rules: [{ allow: private }]) {
    id: ID!
    address: String!
    lng: String
    lat: String
    business: Business @belongsTo
}

type Customer @model @auth(rules: [{ allow: private }]){
  id: ID!
  first_name: String!
  last_name: String!
  drivers_license: String
  email: String
  phone: String!
  Notes: String
  business: Business @belongsTo
  vehicles: [Vehicle] @hasMany
}

type Vehicle @model @auth(rules: [{allow: private}]){
  id: ID!,
  registration_number: String!,
  make: String,
  model: String,
  vin: String,
  colour: String,
  notes: String
  customer: Customer @belongsTo
  business: Business @belongsTo
}
```

**Comment by AdamMoroff75** [comment] 2023-04-26 21:03
Thank you @HuiSF 
Do you have an ETA on when the fix is likely to be implemented? I note that the referenced issue was raised a year ago.  

Thank you.

**Comment by dnys1** [comment] 2023-04-26 21:21
Closing as a duplicate of https://github.com/aws-amplify/amplify-flutter/issues/1480. We will follow up there @AdamMoroff75. I apologize for the delay resolving this issue.

**Closed by dnys1** 2023-04-26 21:21 UTC
Labels: duplicate, DataStore, pending-triage
