### ISSUE TITLE
HubEvent no longer works as expected

### ISSUE THREAD

**Issue by w0da** [aws-amplify/amplify-flutter#1300] opened 2022-01-24 10:46 UTC
**Describe the bug**
hubEventPayload? h̶a̶s̶ ̶n̶o̶ ̶d̶a̶t̶a̶ no longer works as expected.  The example at [Documentation](https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/flutter/#usage) no longer works, 

hubEvent.payload!.active; <-  The getter 'active' isn't defined for the type 'HubEventPayload'

**To Reproduce**
 - Follow example in the above link to listen to datastore events

**Expected behavior**
Payload should have HubChannel.DataStore Events

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[x] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 2.10.0-0.2.pre, on Microsoft Windows [Version 10.0.19042.1466], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Android Studio (version 4.2)
[√] Connected device (1 available)
[√] HTTP Host Availability
```

</details>

Thanks for your work

**Comment by Jordan-Nelson** [comment] 2022-01-24 12:47
Hi @w0da - Thanks for opening the issue.

I will take a look at the documentation and see if I can reproduce the issue you are experiencing.

Just to clarify, do you believe this behavior was working as you would expect in an earlier version of the library?

**Comment by Jordan-Nelson** [comment] 2022-01-24 15:23
I took a look at this and was able to reproduce the issue you are seeing. I believe the payload from the hub event stream use to be of type `dynamic`, and is now of type `HubEvent`. This was a breaking change introduced in 0.3.0, and the docs have not been updated to reflect this change.

Ideally you should be able to check to see if the event is of type `NetworkStatusEvent` (which does have `.active`) and then safely cast the event to check `.active`. See example below.

```dart
StreamSubscription hubSubscription = Amplify.Hub.listen(
  [HubChannel.DataStore],
  (hubEvent) {
    if (hubEvent is NetworkStatusEvent) {
      var networkStatusEvent = hubEvent as NetworkStatusEvent;
      setState(() {
        networkIsUp = networkStatusEvent.active;
      });
    }
  },
);
```

Unfortunately it looks like `NetworkStatusEvent` is not exposed as part of the public API. As a workaround, you can do the following. This is very similar to the way this was done prior to 0.3.0. The only difference is that `hubEvent` is declared as a `dynamic`, essentially casting it to `dynamic` like it was prior to 0.3.0.

```dart
StreamSubscription hubSubscription = Amplify.Hub.listen(
  [HubChannel.DataStore],
  (dynamic hubEvent) {
    if (hubEvent.eventName == 'networkStatus') {
      setState(() {
        networkIsUp = hubEvent.payload.active;
      });
    }
  },
);
```

I am going to mark this as both a bug (since `NetworkStatusEvent` is not exported) and a docs issue (since the docs need to be updated).

Thanks for bringing this to our attention.

**Comment by w0da** [comment] 2022-01-24 21:44
Casting to dynamic works as expected.
Thanks!

**Comment by fjnoyp** [comment] 2022-01-27 17:53
Hi @w0da that's great to hear - can we close this issue then?

**Comment by Jordan-Nelson** [comment] 2022-01-28 02:41
@fjnoyp I would consider this more of a work around, not a permanent fix. Lets leave this open until:
- `NetworkStatusEvent` (and other hub events) are made available as part of the public API
- The docs are updated to use the `NetworkStatusEvent`

This should be a fairly simple change. I just haven't had a chance to make it yet.

**Comment by Knupper** [comment] 2022-02-03 14:48
I have a similar problem with the newest flutter_amplify 0.3.2 plugin. Before it was possible to access `AmplifyClass` to are type safe. we used it for example inside our get_it instance.

```
class _ComponentProvider {
  amplify.AmplifyClass amplifyClass() => amplify.Amplify;
}

  static void register() {
    final GetIt getIt = GetIt.I;
    final components = _ComponentProvider();
    getIt.registerLazySingleton(() => components.amplifyClass());
}
```

This worked without problems before, but now the class is not visible to the outside anymore. Is there a simple trick to fix this or should i open a own ticket for it?

**Comment by HuiSF** [comment] 2022-03-10 18:28
Hi @dnys1 thanks for merge the change. Is the linked PR. Since we have released this change, is it enough to fix this issue?

**Comment by dnys1** [comment] 2022-03-10 18:59
Yes, this issue should be resolved now.

**Closed by dnys1** 2022-03-10 18:59 UTC
Labels: bug, Documentation, DataStore
