### ISSUE TITLE
Module 'amplify_auth_cognito' not found on GeneratedPluginRegistrant.m

### ISSUE THREAD

**Issue by ThewyRogue99** [aws-amplify/amplify-flutter#3700] opened 2023-09-06 21:09 UTC
### Description

I am trying to publish an app to TestFlight but XCode fails to build my project. It says that **Module 'amplify_auth_cognito' not found** on GeneratedPluginRegistrant.m file.

I first tried the solution on issue #151 by changing the IOS platform to 13.0. It solved the problem of not building when running `flutter build ios` command but XCode still fails to build. I even changed the IOS platform on XCode but it still doesn't help at all.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Click 'Product' on MacOS menu bar
2. Click on 'Build'
3. After this, the build will fail and you will be able to see the error

### Screenshots

<img width="601" alt="Screenshot 2023-09-07 at 00 07 45" src="https://github.com/aws-amplify/amplify-flutter/assets/66677253/bb319f35-c877-4bed-a21b-18045408cf0a">

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.2

### Amplify Flutter Version

1.4.0

### Deployment Method

Amplify CLI

**Comment by dgagnon** [comment] 2023-09-07 15:09
Hi,
we have had the same issue for quite a while now.  This will happen whenever amplify is updated.  I think we've spent over 100 dev hours on these issues but never could find the root cause.  Here is how we fix it internally.  

1. org.gradle.caching=false
2. fvm flutter clean 
3. fvm dart pub get 
4. fvm dart pub upgrade
5. fvm dart pub cache repair 
6. fvm flutter -v build apk --debug --dart-define env=dev
6.1. This step is needed in our case, but I believe it is a bug on our side.  Without this step, the error below happens.
7. org.gradle.caching=true


Error mentioned in 6.1.  I am including it here in case anyone else gets it.
```dart
[  +25 ms] package identifier or launch activity not found.
[   +1 ms] Please check E:\Dan\Code\Project Pipeline\flutter-demo-with-docs\android\app\src\main\AndroidManifest.xml for errors.
[   +2 ms] No application found for TargetPlatform.android_x64.
           Is your project missing an android\app\src\main\AndroidManifest.xml?
           Consider running "flutter create ." to create one.
```

**Comment by dnys1** [comment] 2023-09-07 15:33
Hi @ThewyRogue99, sorry you are facing this issue. Can you please confirm you have followed all the steps in the [Platform Setup](https://docs.amplify.aws/lib/project-setup/platform-setup/q/platform/flutter/) guide for iOS?

Can you try running the following commands after?

```console
$ flutter clean
$ flutter pub upgrade
$ cd ios
$ rm -rf Pods Podfile.lock
$ pod install
```

Then try re-running your application.

**Comment by ThewyRogue99** [comment] 2023-09-07 20:30
Thanks for a quick response.

Let me start from first response: @dgagnon I want to try your solution but I want to know how I can set the `org.gradle.caching` variable to `false` or `true`.

Now for the second response: @dnys1 I already have followed the steps on Platform Setup Guide and I also tried running the commands that you asked me to run. With this, I am able to run my program with IOS Simulator using VSCode with Flutter extension. This is not my problem though. The problem is that I fail to build this code on XCode.

This issue is important for me because I am using your library on a project that I work on with a company and also my superiors are asking me to publish a test app. Since I fail to build it because of this issue, I can't provide them with a test app. I hope you can understand me.

**Comment by dgagnon** [comment] 2023-09-08 01:40
@ThewyRogue99 gradle is specific to the android platform, which is what I develop on.  You can ignore this for iOS AFAIK,

**Comment by dgagnon** [comment] 2023-09-08 16:56
@ThewyRogue99 I'd try merging in the commands from @dnys1 
Hopefully you can get it to work or the amplify team can figure out what is the root cause of this!

**Comment by ThewyRogue99** [comment] 2023-09-08 20:24
Hello @dgagnon I realized that in your first response you said _**This will happen whenever amplify is updated**_. So, I would like to know what do you mean by this. Does this happen when Amplify CLI is updated or Amplify-Flutter is updated but not the Amplify as the AWS Service itself? If it is, then I can gladly downgrade anything that you ask. If it is not, then I will have nothing but hope that your team will fix the issue.

**Comment by dgagnon** [comment] 2023-09-08 20:26
@ThewyRogue99 when upgrading the amplify packages with `dart pub upgrade`

**Comment by ThewyRogue99** [comment] 2023-09-08 20:32
With a little hope, I tried downgrading the packages. Still nothing :(

Please comment on this issue if a solution is found.

**Comment by dnys1** [comment] 2023-09-08 21:17
I'm not able to reproduce this. I performed the following steps:

1. `flutter create -e auth_test`
2. `cd auth_test`
3. `flutter pub add amplify_flutter amplify_auth_cognito`
4. Edit `main.dart` to initialize Auth
5. Edit `Podfile` to iOS 13
6. `cd ios && pod install`
7. Open Xcode project and update minimums
8. Enable code signing
9. Run `flutter build ios`
10. Open Xcode and select Product > Build

App is successfully built. If you can provide an example app where the issue is reproducible, I'll be happy to look into it. Unfortunately, I'm not able to assist further without a reproduction.

**Comment by dgagnon** [comment] 2023-09-11 17:17
@dnys1 I am able to replicate on android by upgrading to 1.4.1, see #3726

**Comment by dgagnon** [comment] 2023-09-11 17:22
I have open an issue, I realized mine is slightly different:  #3726

**Comment by ThewyRogue99** [comment] 2023-09-11 20:22
Hello, @dnys1 I also created and configured my project same as you. There is one difference though. I create the project with a custom organization name like this: `flutter create app_name --org com.organization`. Do you think that this may be the cause for this?

**Comment by ThewyRogue99** [comment] 2023-09-11 20:24
@dgagnon Yes, your issue is different. Your problem is with Android and mine is with IOS. So, does Android have a similar problem like this?

**Comment by dgagnon** [comment] 2023-09-11 20:27
@ThewyRogue99 I am reasonably sure that both issues are linked, but I have not replicated it on ios.  Sorry for muddying the waters.

**Comment by ThewyRogue99** [comment] 2023-09-11 20:29
@dgagnon  No problem. I hope that this issue gets fixed for both of us :D

**Comment by dnys1** [comment] 2023-09-11 23:08
I'm wondering if you even need to run `Product > Build`. To create an IPA for uploading to TestFlight/App Store can you use the `flutter build ipa` method as described [here](https://docs.flutter.dev/deployment/ios#create-a-build-archive-and-upload-to-app-store-connect)?

**Comment by ThewyRogue99** [comment] 2023-09-12 20:03
Thank you, @dnys1 I didn't know that I could build with `flutter build ipa` command, I just followed the tutorials on the internet. I tried your command and it successfully built the app. I also hope that you'll be able to fix the problem for XCode.

@dgagnon I think you should try building it with `flutter build apk` command. Maybe it will help.

**Comment by dnys1** [comment] 2023-09-12 20:19
Glad to hear that worked. 

We'll keep an eye on the Xcode issue. As I wasn't able to reproduce it, I'm going to close this issue for now.

Please let us know if you face any more issues.

**Closed by dnys1** 2023-09-12 20:19 UTC
Labels: pending-close-response-required, Auth, not-reproducible, pending-response
