### ISSUE TITLE
sync expression predicate not working 

### ISSUE THREAD

**Issue by Lance-Kraakman** [aws-amplify/amplify-flutter#3941] opened 2023-10-12 10:49 UTC
### Description

When performing a sync expression, QueryPredicate.all works fine but using a predicate i.e. AthleteWorkout.ATHLETEPROFILEID.eq(sync_user_id) does not work.

Here is the code and my schema, the updateSync() function is being called at runtime when the user logs in.
Everything seems to be working with QueryPredicate.all.

Sorry for posting here, I have been stuck for a while on this.

```dart
final amplifyProvider = Provider<AmplifyNotifier>((ref) {
  return AmplifyNotifier(ref);
});

var sync_user_id = "";

Future<void> updateSync() async {
  final currentUser = await Amplify.Auth.getCurrentUser();
  sync_user_id = currentUser.userId;
  await startStore(delaySeconds: 1);
}

class AmplifyNotifier extends StateNotifier {
  AmplifyNotifier(
    this._ref,
  ) : super(null);
  final Ref _ref;

  Future<void> init() async {
    final authPlugin = AmplifyAuthCognito();
    final api = AmplifyAPI(modelProvider: ModelProvider.instance);

    final datastorePlugin = AmplifyDataStore(
        syncExpressions: [
          DataStoreSyncExpression(AthleteProfile.classType,
              () => AthleteProfile.ID.eq(sync_user_id)),
          // read the documentation and try to work out why, might have something to do with schema
          DataStoreSyncExpression(
              AthleteWorkout.classType,
              // ATHLETEPROFILEID.eq(sync_user_id) dosent work for this
              () => QueryPredicate.all),
          DataStoreSyncExpression(
              AthleteExercise.classType, () => QueryPredicate.all),
          // () => AthleteExercise.ATHLETEPROFILEID.eq(sync_user_id)),
          DataStoreSyncExpression(
              ExerciseTemplate.classType, () => QueryPredicate.all),
          DataStoreSyncExpression(
              WorkoutSection.classType, () => QueryPredicate.all),
        ],
        modelProvider: ModelProvider.instance,
        syncMaxRecords: 50000,
        syncPageSize: 10000);

    await Amplify.addPlugins([authPlugin, api, datastorePlugin]);
    await Amplify.configure(amplifyconfig);
  }

  // See https://docs.amplify.aws/lib/project-setup/upgrade-guide/q/platform/flutter/
  Future<bool> isLoggedIn() {
    /*
      This should fix devices tokens signing out and not logging out of UI
    */
    return Amplify.Auth.getPlugin(
      AmplifyAuthCognito.pluginKey,
    ).fetchAuthSession().then((session) {
      return (session.identityIdResult.valueOrNull != null);
    });
  }
}

Future<void> startStore({int delaySeconds = 1}) async {
  try {
    await Amplify.DataStore.clear();
  } catch (ex) {
    print("error clearing data store, $ex");
  }
  try {
    await Amplify.DataStore.start();
    print('DataStore is started.');
  } on DataStoreException catch (e) {
    print('Failed to start DataStore: $e');
  }
}
```

(this is the schema for the class I am actually testing)
![image](https://github.com/aws-amplify/amplify-flutter/assets/44858574/12941137-dbae-4123-bc8d-622341c6f6a7)

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Have a sync expression with a query predicate. 
and a model like
![image](https://github.com/aws-amplify/amplify-flutter/assets/44858574/cee82622-f344-4347-989c-a267f23c668b)

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.7

### Amplify Flutter Version

1.4.1

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment] 2023-10-12 18:42
Hello @Lance-Kraakman - I am going to close this as a duplicate of https://github.com/aws-amplify/amplify-flutter/issues/3703 since this sounds pretty similar. I was not able to reproduce any issues with selective sync. If you are still facing issues, please see my latest comment - https://github.com/aws-amplify/amplify-flutter/issues/3703#issuecomment-1760180869

**Closed by Jordan-Nelson** 2023-10-12 18:42 UTC
Labels: DataStore, pending-triage
