### ISSUE TITLE
[aws_common] update the "js" version in pubspec

### ISSUE THREAD

**Issue by HemantNegi** [aws-amplify/amplify-flutter#4965] opened 2024-06-04 08:41 UTC
We need to update js version of aws_common package to "^0.7.1"

Because no versions of aws_common match >0.7.0 <0.8.0 and aws_common 0.7.0 depends on js ^0.6.4, aws_common ^0.7.0 requires js ^0.6.4.
And because image_cropper >=6.0.0 depends on image_cropper_for_web ^4.0.0 which depends on js ^0.7.1, aws_common ^0.7.0 is incompatible with image_cropper >=6.0.0.
So, because presence depends on both image_cropper ^6.0.0 and aws_common ^0.7.0, version solving failed.

**Comment by Equartey** [comment] 2024-06-04 16:07
Hi @HemantNegi, thank you for reporting. We understand this is disruptive and will take a look at getting it updated for you. 

We will keep you updated with its progress.

**Comment by Equartey** [comment] 2024-06-04 20:31
Hi @HemantNegi, noticed this is a duplicate of https://github.com/aws-amplify/amplify-flutter/issues/4618. I'm going to close this issue to consolidate the discussion over there.

**Closed by Equartey** 2024-06-04 20:31 UTC
Labels: pending-triage, dependencies
