### ISSUE TITLE
Large Integers Parsed as Double with Scientific Notation

### ISSUE THREAD

**Issue by Daniel-HyunHo-Shin** [aws-amplify/amplify-flutter#4318] opened 2024-01-06 13:32 UTC
### Description

When an integer is large, it seems that GraphQL parses it into a double using scientific notation, and it causes a type problem when syncing on DataStore

```dart
type PreflopChart @model @auth(rules: [{allow: owner}]) {
  id: ID!
  createdOn: AWSDateTime
  updatedOn: AWSDateTime
  title: String!
  description: String
  chartIconColor: Int!
  chartIcon: Int!
  data: AWSJSON!
}
```

have a model like the one above and saved `int chartIconColor = 4281389400`. 
However, it caused an error when syncing, saying `GraphQLResponse.Error{message='Variable 'chartIconColor'` has an invalid value. 

When I checked the logs, I found that it's saved as `chartIconColor = 4.2813894E9.`

### Categories

- [ ] Analytics
- [X] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.18.0-0.2.pre

### Amplify Flutter Version

amplify_flutter: ^1.6.1

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type PreflopChart @model @auth(rules: [{allow: owner}]) {
  id: ID!
  createdOn: AWSDateTime
  updatedOn: AWSDateTime
  title: String!
  description: String
  chartIconColor: Int!
  chartIcon: Int!
  data: AWSJSON!
}
```

**Comment by Jordan-Nelson** [comment] 2024-01-09 17:05
@Daniel-HyunHo-Shin - Sorry you are facing this issue. We will attempt to reproduce this with the info provided.

**Comment by Jordan-Nelson** [comment] 2024-01-09 17:59
@Daniel-HyunHo-Shin - I was able to reproduce this. I will mark this as a bug and we will look into it.

**Comment by Jordan-Nelson** [comment] 2024-01-09 19:35
@Daniel-HyunHo-Shin - The GraphQL spec allows for a max integer size of 32 bit. 4281389400 exceeds this limit. You could use a different type such as string or float in this case.

I think we could improve the DX by throwing a clear error instead of waiting until the sync to fail in this way. This would unfortunately be a breaking change though. We have a related issue here: https://github.com/aws-amplify/amplify-flutter/issues/850. I'll leave a comment on that issue to note that.

I am going to close this out since this is not expected to work and we have another issue to track the DX improvement.

**Closed by Jordan-Nelson** 2024-01-09 19:35 UTC
Labels: bug, datastore
