### ISSUE TITLE
API GraphQL Subscription not working

### ISSUE THREAD

**Issue by Lorenzohidalgo** [aws-amplify/amplify-flutter#898] opened 2021-09-17 11:19 UTC
**Describe the bug**
The generated GraphQL subscriptions do not work consistently. For some models they will work every time and for other models only changes via AdminUI will be detected. Mutations triggered from that same device won't be detected. If I try using the default generated subscription it will fail saying all fields are empty.

**To Reproduce**
1. Generate a GraphQL schema
2. Add custom subscriptions
3. Generate objects and mutations to try and trigger subscriptions

**Expected behavior**
All events should be detected or an error/info message should be prompted.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[X] Android
[] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [VersiÃ³n 10.0.19043.1165], locale es-ES)
    • Flutter version 2.2.3 at C:\DEVELOPMENT\SRC\flutter
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3) 
    • Android SDK at C:\Users\Lorenzo HG\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe      

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.60.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (3 available)
    • ONEPLUS A5010 (mobile) • 9070076c • android-arm64  • Android 10 (API 29)
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)             • edge     • web-javascript • Microsoft Edge 93.0.961.38

• No issues found!
```

</details>

**Smartphone (please complete the following information):**
 - Device: OnePlus 5t
 - OS: Android 10(API 29)

**Additional context**
<details>

  <summary>Working model schema and custom subscription</summary>
  
  ```GraphQL
type Users @model @auth(rules: [{allow: private}]) 
@key(name: "usersByEmail", fields: ["email"], queryField: "usersByEmail"){
  id: ID!
  pid: ID
  email: AWSEmail!
  name: String
  cognito_uid: ID
  avatarKey: String
  phoneNumber: String
  joinDate: AWSDateTime!
  lastLogIn: AWSDateTime
  description: String
  lastSpacePID: ID
  pushIdentifiers: [String]
  pushNotifications: Boolean
  emailNotifications: Boolean
  language: String
  isPartner: Boolean
  isActive: Boolean
}

type Subscription {
  onUpdateUserByPID(id: ID!): Users @aws_subscribe(mutations: ["updateUsers"])
}
```

</details>
<details>

  <summary>Failing model schema and custom subscription</summary>
  
  ```GraphQL
type Transfers @model @auth(rules: [{allow: private}])
@key(name: "transferBySpacePID", fields: ["spacePID", "transferDateTime"], queryField: "transferBySpacePID")
@key(name: "transferByTokenPID", fields: ["tokenPID"], queryField: "transferByTokenPID")
@key(name: "transferByTypePID", fields: ["tokenTypePID"], queryField: "transferByTypePID"){
  id: ID!
  pid: ID
  spacePID: ID!
  teamPID: ID
  tokenPID: ID!
  tokenPackPID: ID
  tokenTypePID: ID
  trasferType: TransferTypeEnum!
  transferMode: TransferModeEnum!
  fromManager: Boolean!
  publicTransfer: Boolean!
  isInitialTransfer: Boolean!
  pendingValidation: Boolean!
  pendingManagerValidation: Boolean!
  transferDateTime: AWSDateTime!
  fromUserPID: ID!
  toUserPID: ID!
  body: String
  publicBody: Boolean
  mediaKey: String
  publicMedia: Boolean
  amount: Int
  likes: [ID!]
  isCanceled: Boolean
  reminderDate: AWSDateTime
  challengeEndDate: AWSDateTime
  challengeAccepted: Boolean
  challengeEnded: Boolean
}

type Subscription {
  onCreateTransferBySpaceSender(spacePID: ID!, fromUserPID: ID!): Transfers @aws_subscribe(mutations: ["createTransfers"])
  onUpdateTransferBySpaceSender(spacePID: ID!, fromUserPID: ID!): Transfers @aws_subscribe(mutations: ["updateTransfers"])
  onCreateTransferBySpaceReceiver(spacePID: ID!, toUserPID: ID!): Transfers @aws_subscribe(mutations: ["createTransfers"])
  onUpdateTransferBySpaceReceiver(spacePID: ID!, toUserPID: ID!): Transfers @aws_subscribe(mutations: ["updateTransfers"])
}
```

</details>

**Comment by Lorenzohidalgo** [comment] 2021-09-17 15:38
[Update] By updating the mutation statements to return all fields (on create and update mutations) the subscriptions are triggered. 

Example:
<details>

  <summary>Original mutation (did not trigger the subscription)</summary>

```dart
String graphQLDocument =
            '''mutation likeTransfer(\$id: ID!, \$likes: [ID!], \$_version: Int) {
                        updateTransfers(input: {id: \$id, likes: \$likes, _version: \$_version}) {
                          _deleted
                          _lastChangedAt
                          _version
                        }
                      }''';
        final operation = Amplify.API.mutate(
            request: GraphQLRequest<String>(
                document: graphQLDocument,
                variables: {
              'id': _newTransfer.pid,
              'likes': _newTransfer.likes,
              '_version': _version
            }));
```

</details>
<details>

  <summary>New mutation (triggers the subscription)</summary>

```dart
String graphQLDocument =
            '''mutation likeTransfer(\$id: ID!, \$likes: [ID!], \$_version: Int) {
                        updateTransfers(input: {id: \$id, likes: \$likes, _version: \$_version}) {
                          _deleted
                          _lastChangedAt
                          _version
                          amount
                          body
                          challengeAccepted
                          challengeEndDate
                          challengeEnded
                          fromManager
                          fromUserPID
                          id
                          isCanceled
                          isInitialTransfer
                          likes
                          mediaKey
                          pendingManagerValidation
                          pendingValidation
                          pid
                          publicBody
                          publicMedia
                          publicTransfer
                          spacePID
                          reminderDate
                          teamPID
                          toUserPID
                          tokenPackPID
                          tokenPID
                          tokenTypePID
                          transferDateTime
                          transferMode
                          trasferType
                        }
                      }''';
        final operation = Amplify.API.mutate(
            request: GraphQLRequest<String>(
                document: graphQLDocument,
                variables: {
              'id': _newTransfer.pid,
              'likes': _newTransfer.likes,
              '_version': _version
            }));
```

</details>

**Comment by HuiSF** [comment] 2021-09-17 16:15
Related issue: https://github.com/aws-amplify/amplify-flutter/issues/663

When both amplify-ios and amplify-android send GraphQL model subscription requests:
* iOS: subscription listed all fields including nested model fields
* Android: subscription listed all fields of the root model, and only `id` field of nested models

From this, I think the mutation would need to list all fields as well. I think with your original mutation, the subscription still receives events, but may contain GraphQL error similar to what I listed in above issue, and underlying DataStore sync engine ignores it.

**Comment by HuiSF** [comment] 2021-09-17 16:18
Currently the workaround is like what @Lorenzohidalgo  updated, if the mutation returns all fields, subscription should work correctly. In the meantime, I'll try to spend sometime looking into the inconsistency between iOS and Android. And possibly need to update relevant  documentation.

**Comment by fjnoyp** [comment] 2021-09-17 16:59
Hi @Lorenzohidalgo we'll take a look thanks.

**Comment by ragingsquirrel3** [comment] 2021-10-21 21:44
@Lorenzohidalgo would it be possible to also include the code you used to generate the subscription request? I see the schema (with custom subscription) and mutation request, but the subscription request might be helpful as well. The reason I ask is that I was reviewing AppSync documentation on https://docs.aws.amazon.com/appsync/latest/devguide/aws-appsync-real-time-data.html and noticed a potentially relevant detail:

"If you use the pure WebSockets client [amplify-android/amplify-flutter do], selection set filtering is done per client, as each client can define its own selection set. In this case, the subscription selection set must be a subset of the mutation selection set. For example, a subscription addedPost{author title} linked to the mutation addPost(...){id author title url version} receives only the author and title of the post. It does not receive the other fields. However, if the mutation lacked the author in its selection set, the subscriber would get a null value for the author field (or an error in case the author field is defined as required/not-null in the schema)."

This might explain why including all the fields in your mutation selection set caused the subscription to be triggered. If this is the cause, it would appear you do not need to include all the fields in the mutation selection set, just the required fields and all the fields in your subscription selection subset. Let me know if this is helpful.

**Comment by dnys1** [comment] 2021-11-16 23:47
Hi @Lorenzohidalgo - has this worked to resolve your issue? I believe you must include the fields used as arguments of the subscription in your selection set of the mutation in order for the subscription to be triggered. For example, in your subscription, `onCreateTransferBySpaceSender(spacePID: ID!, fromUserPID: ID!)`, `spacePID` and `fromUserPID` must be included in the selection set of `createTransfers` mutations.

**Comment by Lorenzohidalgo** [comment] 2021-11-18 15:06
Hi @dnys1, It works when selecting all fields on mutating calls, have not tried yet to select only the ones used as fileters.

**Comment by HuiSF** [comment] 2022-03-10 18:12
As above described workaround has resolved the original problem, I'm closing this issue. 
We will update advance use cases on using API to operate with DataStore in this feature request tracking issue: https://github.com/aws-amplify/amplify-flutter/issues/1129

**Closed by HuiSF** 2022-03-10 18:12 UTC
Labels: DataStore, GraphQL API, pending-triage

**Comment by dfourcfive** [comment] 2022-03-31 16:42
@HuiSF  i have relational models exmaple user have many pets and pet belongs to user
so if i try to return all fields i'll end up in unlimited cycle , i have tried to not do that but it doesn't work
it only works in simple use cases , please investigate more

**Comment by HuiSF** [comment] 2022-03-31 17:23
Hi @dfourcfive you mean you have to list all fields in the selection set as an infinite cycle?
In general you don't need to list nested fields for `@hasOne` and `@hasMany` nested model fields, but only `@belongsTo`.

E.g. this schema

```graphql
type Blog @model @auth(rules: [{ allow: public }]) {
  id: ID!
  name: String!
  posts: [Post] @hasMany(indexName: "byBlog", fields: ["id"])
}

type Post @model @auth(rules: [{ allow: public }]) {
  id: ID!
  title: String!
  rating: Int!
  blogID: ID @index(name: "byBlog")
  blog: Blog @belongsTo(fields: ["blogID"])
  comments: [Comment] @hasMany(indexName: "byPost", fields: ["id"])
}

type Comment @model @auth(rules: [{ allow: public }]) {
  id: ID! @primaryKey
  postID: ID! @index(name: "byPost", sortKeyFields: ["content"])
  post: Post @belongsTo(fields: ["postID"])
  content: String!
}
```

When mutate post. the selection set should be
```
createPost(input: $input) {
  id
  createdAt
  rating
  title
  updatedAt
  blog {
    id
    createdAt
    name
    updatedAt
    __typename
    _version
    _deleted
    _lastChangedAt
  }
  __typename
  _version
  _deleted
  _lastChangedAt
}
```
Note that in the `blog` section, you don't need to include `posts`.

**Comment by dfourcfive** [comment] 2022-03-31 17:37
@HuiSF [HuiSF](https://github.com/HuiSF) my mutation works but in the event gets treated as Unhandled DataStoreHubEvent

**Comment by dfourcfive** [comment] 2022-03-31 17:50
in the mobile side (flutter android) I am observing a user model  (using the observe method)
and i have a django app which trigger an update mutation , the mutation works 
when i do mutation on simple model and return all fields i get the event but now since my model have relations (hasMany and hasOne) it doesn't get received in with the observe method
```
I/amplify:flutter:datastore( 7036): Unhandled DataStoreHubEvent: subscriptionDataProcessed
I/amplify:flutter:datastore( 7036): ModelWithMetadata{model=SerializedModel{id='96385463-3ddd-4bb4-991c-c947ad70161e', serializedData={bank_verification_status=null, user_status=CONFIRMED, address_books=null, occupation=, profile=null, newsletter_subscription=true, createdAt=2022-03-05T16:25:30.828Z, global_transactions=null, kyc_level=0, profileID=0f4e9853-8637-4e60-b72a-06c378b55bbe, phone_number=+13069884048, id=96385463-3ddd-4bb4-991c-c947ad70161e, email=ibrahimbenadidou2020@gmail.com, updatedAt=2022-03-31T17:47:28.204Z}, modelName=User}, syncMetadata=ModelMetadata{id='User|96385463-3ddd-4bb4-991c-c947ad70161e', _deleted=null, _version=44, _lastChangedAt=Temporal.Timestamp{timestamp=1648748848249}}}

```

**Comment by HuiSF** [comment] 2022-03-31 18:26
You can ignore 
```
Unhandled DataStoreHubEvent: subscriptionDataProcessed
```
When this event gets emitted, it means the DataStore has received a subscription event, and correctly reconsolidate the remote data into the local DB.

Looking at the logs, you should be testing in Android? When you mutate models with associated models, you don't see `subscriptionDataProcessed` at all? Do you see any error logs?

**Comment by HuiSF** [comment] 2022-03-31 20:51
Hey @dfourcfive why don't you open a new issue attaching your model schema, code example, and description what you are trying to achieve. I have a hard time to visualize your use case. Thanks :)
