### ISSUE TITLE
java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by brunovsiqueira** [aws-amplify/amplify-flutter#340] opened 2021-02-01 18:00 UTC
I see the following crash in my crashlytics console:

Fatal Exception: java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:243)
       at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito$prepareError$1.run(AuthCognito.kt:466)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6934)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

It seems that com.amazonaws.amplify.amplify_auth_cognito.AuthCognito$prepareError$1.run(AuthCognito.kt:466) is causing the crash. Can you guys please help me?

**Comment by haverchuck** [comment] 2021-02-02 16:03
@brunovsiqueira What is the API method being invoked which leads to this?

**Comment by brunovsiqueira** [comment] 2021-02-02 19:21
Hi @haverchuck. This is the complete stack trace I can see in crashlytics.

**Comment by haverchuck** [comment] 2021-02-03 17:01
@brunovsiqueira Is there a specific amplify-flutter method you are calling when this happens, or is it at app startup?

**Comment by brunovsiqueira** [comment] 2021-02-03 19:48
I really don't know because I can only see this crash on crashlytics. If you want, I can send the device information  where this crash happened.

**Comment by haverchuck** [comment] 2021-02-16 21:47
@brunovsiqueira Is this still occurring with version 0.1.0?

**Comment by haverchuck** [comment] 2021-03-01 19:51
Closing this issue due to inactivity.

**Comment by brunovsiqueira** [comment] 2021-03-01 19:59
I see no crashs in the latest release. I let you guys know if it happens again. Thank you.

**Comment by brunovsiqueira** [comment] 2021-03-11 13:27
Hi @haverchuck @Amplifiyer.

Same crash is happening in latest release (0.1.0). Can you guys please reopen this issue? Is there any workaround?

**Comment by Ashish-Nanda** [comment] 2021-03-11 19:33
@brunovsiqueira I'm reopening the issue. Is it possible for you to try and reproduce it on a device so that we can have more information on what the issue might be?

**Comment by brunovsiqueira** [comment] 2021-03-11 19:57
Also, I see the following in the crashlytics "Keys" section: (message: You are currently signed out., recoverySuggestion: Please sign in and reattempt the operation., underlyingException: null).

So I guess it is maybe caused when SessionExpiredException is thrown.

I am going to try to reproduce it.

**Comment by brunovsiqueira** [comment] 2021-04-14 21:55
Happening again in 0.1.1 when you rerun your application without killing.

**Comment by offlineprogrammer** [comment] 2021-06-23 23:16
Hi @brunovsiqueira 

Can you please provide more details on this and how to reproduce it

Regards
Mo

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android
[] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```Paste your output of "flutter doctor -v" here```

</details>

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by offlineprogrammer** [comment] 2021-07-08 16:10
Hi @brunovsiqueira 

I am closing this issue for now as I didn't hear back from you
We can reopen it if you are still facing the issue and when you provide details

Regards
Mo

**Closed by offlineprogrammer** 2021-07-08 16:10 UTC
Labels: Auth, clarification-needed, pending-close-response-required

**Comment by Nealsoni00** [comment] 2021-08-04 04:51
Happened again for me on   `amplify_auth_cognito: ^0.2.1`

When I call:
 ```
await Amplify.Auth.signOut();
      SignInResult res = await Amplify.Auth.signIn(
        username: username.trim(),
        password: password.trim(),
      );
```
```
E/AndroidRuntime(21915): FATAL EXCEPTION: main
E/AndroidRuntime(21915): Process: com.preparedapp.preparedAndroid, PID: 21915
E/AndroidRuntime(21915): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(21915): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:155)
E/AndroidRuntime(21915): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime(21915): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito$prepareSignInResult$1.run(AuthCognito.kt:516)
E/AndroidRuntime(21915): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime(21915): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(21915): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(21915): 	at android.app.ActivityThread.main(ActivityThread.java:6145)
E/AndroidRuntime(21915): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21915): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/AndroidRuntime(21915): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
