### ISSUE TITLE
unable to define custom Graphql Query for getting a single record 

### ISSUE THREAD

**Issue by uzairleo** [aws-amplify/amplify-flutter#3903] opened 2023-10-04 20:28 UTC
### Description

Hi there Guys , we are having a serious issue with our app search functionalities i reported that but was not able to get some active response which led us to use an alternative option but now this alternative option is also not working in Amplify, as it docs are not available so assuming it's not supported or by default its not working when we fetch user by email, But Amplify.Api.Query()  do works when we fetch user record from dynamodb by ID 

Anyone know how to fix this as we do try triggering this query directly from amplify test env but getting error  But for id its working out of the box . 
```

{
  getTotemUSER(email: "test@t.com"){
    name
    id
    email
  }
}
```

Response
```

{
  "data": null,
  "errors": [
    {
      "path": null,
      "locations": [
        {
          "line": 62,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Validation error of type MissingFieldArgument: Missing field argument id @ 'getTotemUSER'"
    },
    {
      "path": null,
      "locations": [
        {
          "line": 62,
          "column": 16,
          "sourceName": null
        }
      ],
      "message": "Validation error of type UnknownArgument: Unknown field argument email @ 'getTotemUSER'"
    }
  ]
}
```

### Categories

- [ ] Analytics
- [X] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

To reproduce just define and create a simple model with (id,name,email)  graphql schmea and then run codegen model , now query on some even this below code to get user by ID and then again for USER BY EMAIL

For ID (Works ) 
 ```
final request = ModelQueries.get(  TotemUSER.classType,
        TotemUSERModelIdentifier(id: userId));
      final response = await Amplify.API.query(request: request).response;
```
For Email (Not Working) 
```

final request = ModelQueries.get(  TotemUSER.classType,
        TotemUSERModelIdentifier(id: userId));
      final response = await Amplify.API.query(request: request).response;

```

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [X] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.6

### Amplify Flutter Version

1.3.1

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type USER @model @auth(rules: [{allow: public}]) {
  id: ID! 
  name: String!
  email: String!
{
```

**Comment by uzairleo** [comment] 2023-10-04 20:55
@dnys1

**Comment by uzairleo** [comment] 2023-10-04 21:10
Also i already have checked the legacy cli docs for custom query addition feature purpose but any of the directive mentioned in the doc is not supported by flutter 

https://docs.amplify.aws/cli-legacy/graphql-transformer/resolvers/#custom-resolvers

**Comment by Equartey** [comment] 2023-10-05 15:22
Hi @uzairleo, I'm going to close this as a duplicate of https://github.com/aws-amplify/amplify-flutter/issues/3873. Lets keep the discussion there so its easier to track.

**Closed by Equartey** 2023-10-05 15:22 UTC
