### ISSUE TITLE
DataStore observeQuery not triggering when updated the nested model

### ISSUE THREAD

**Issue by afnx** [aws-amplify/amplify-flutter#3744] opened 2023-09-15 05:36 UTC
### Description

Generate some sample data to reproduce the issue:

```dart
final post = Post(
  title: 'My Post with comments',
  rating: 10,
  status: PostStatus.ACTIVE,
);
final comment = Comment(
  post: post, // associate the comment to the post
  content: 'Loving Amplify DataStore!',
);

try {
  await Amplify.DataStore.save(post);
  await Amplify.DataStore.save(comment);
} on DataStoreException catch (e) {
  safePrint('Something went wrong querying posts: ${e.message}');
}
```

Now, observe the changes of the comment you created and print the title of its post:

```dart
Amplify.DataStore.observeQuery(Comment.classType,
        where: Comment.ID.eq(comment.id))
    .where((event) => event.items.isNotEmpty)
    .map((event) => event.items.toList().first)
    .listen((Comment comment) {
  print(comment.post.title); // Prints the title value of the connected Post model
});
```

Update the title of the post:
```dart
try {
  await Amplify.DataStore.save(post.copyWith(title: 'New Title'));
} on DataStoreException catch (e) {
  safePrint('Something went wrong querying posts: ${e.message}');
}
```

The`Amplify.DataStore.observeQuery` won't be triggered immediately after there is an update to the associated post. 

If you perform a hot restart, then the updated data will be received in the stream. Is this the expected behavior?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.4

### Amplify Flutter Version

1.4.1

### Deployment Method

Amplify CLI

### Schema

```GraphQL
enum PostStatus {
  ACTIVE
  INACTIVE
}

type Post @model {
  id: ID!
  title: String!
  rating: Int!
  status: PostStatus!
  # New field with @hasMany
  comments: [Comment] @hasMany(indexName: "byPost", fields: ["id"])
}

# New model
type Comment @model {
  id: ID!
  postID: ID! @index(name: "byPost")
  post: Post! @belongsTo(fields: ["postID"])
  content: String!
}
```

**Comment by khatruong2009** [comment] 2024-02-06 21:32
Hi @afnx (and @burntblark), observeQuery is only single model targeted. Unfortunately, this means that what you're experiencing is expected behavior as a change in the Parent should not trigger the observeQuery for a Comment. I tried to reproduce what you had, using the code you provided and I was not receiving the updated data in the stream even after a hot restart. We currently have [this issue](https://github.com/aws-amplify/amplify-flutter/issues/1449) that is tracking a feature request for better support for operations on nested models. I'm going to close this issue since this use case is not supported at the moment. Feel free to create a new issue if you are experiencing another issue or to comment on the feature request issue linked above if you have any other issues. Thanks.

**Closed by khatruong2009** 2024-02-06 21:32 UTC
Labels: bug, datastore, Investigating
