### ISSUE TITLE
Bug: Breaking changes in the model can be a headache

### ISSUE THREAD

**Issue by guplem** [aws-amplify/amplify-flutter#1427] opened 2022-03-03 16:45 UTC
I just faced the same issue as #496

That is marked as closed, but I do believe that the reason is not correct. 

I sincerely do not know how to request an issue to be reopened, so I am creating a new one.

I did post comments related to the issue in the original one that might be relevant: https://github.com/aws-amplify/amplify-flutter/issues/496#issuecomment-1058223923

**Comment by dnys1** [comment] 2022-03-03 17:28
Hi @guplem - can you confirm that re-generating your models with `amplify codegen models` and calling `Amplify.DataStore.clear()` in your code does not resolve the issue?

**Comment by guplem** [comment] 2022-03-03 17:59
@dnys1 I fixed the issue (by not adding required fields) so I tried to replicate it again doing the following:

1. I deleted all the entries in the Content tab
2. In my data model, I added a new field (String) marked as mandatory
3. The content tab now showed X tabs failed to sync (like here https://github.com/aws-amplify/amplify-flutter/issues/496#issuecomment-1058223923) 
![image](https://user-images.githubusercontent.com/11029629/156620756-8f250f4e-6dad-4d30-b16e-ab418ff1f685.png)
4. I ran `amplify pull --appId dnz7d3km8a1gi --envName staging`
5. I ran `amplify codegen models` (I do not know if that makes any difference after running the previous one...?)
6. I adapted my code app to ensure the use of the new field (so no errors appeared) something like `Task newTask = Task(newfield: "DUMMY"...)`
7. I ran the app. An error appears:
![image](https://user-images.githubusercontent.com/11029629/156622993-0acf63b4-07d7-4fb2-9ddd-2b78f81dd78a.png)
8. I call `Amplify.DataStore.clear()` is called on the press of a button
9. I ran the app again. Same results.
10. I uninstalled the app
12. I ran the app again with the same results again
13. I created a new entry, manually, using amplify studio
14. I ran the app again. Same error and no entry was shown in the app.
15. I created a new entry from the app
16. I ran the app again. Same error and no entry was shown in the app (unexpected to me).

I do believe that what is basically happening is that adding a change, like a new mandatory field (even if there are no entries displayed in the content tab), breaks the app, forcing it to local storage. Probably because the old fields are not 100% deleted and are missing that field, and it causes some errors or something...

However, it is weird to me that even if I believe that it is switching to local storage, the entry that I created from within the app is not being shown (in the app) either.... I did believe it would.



P.D. While doing this testing, I had issues with the new field's name being all caps (I believe). I couldn't compile the app.

**Comment by dnys1** [comment] 2022-03-03 19:28
Thank you @guplem for that very detailed breakdown. I will try to reproduce it and see if there's a way to workaround the issue you're experiencing.

**Comment by dnys1** [comment] 2022-03-04 15:43
So, here is what I tried and it worked for me:

1. Start with schema

```graphql
type Todo @model {
  id: ID!
  name: String!
  description: String
}
```

2. Create some todos
3. Sync with iOS (everything works okay so far)
4. Update schema with new breaking field

```graphql
type Todo @model {
  id: ID!
  name: String!
  description: String
  breaking: String!
}
```

5. Update models and try to sync with iOS (receive error)

So far, this aligns with what you've experienced. At this point, I updated each of the todos that I had created and added that breaking field like this:

```graphql
mutation {
  updateTodo(
    input: { 
      id: "5e1a57fd-bf4f-4de5-8454-460eeedac1f5", 
      breaking: "123" 
    }
  ) {
    id
    name
    description
    breaking
  }
}
```

6. Without changing anything in Flutter, I restarted the app and sync worked again.

So it seems like when a new field is introduced which is breaking, you need to perform a migration of your data such that the field is present for all which you are syncing. Once that is true, everything should work as expected.

**Comment by dnys1** [comment] 2022-03-04 18:04
Great questions! And no worries. So, the Amplify API & DataStore categories are backed by [AWS AppSync](https://docs.aws.amazon.com/appsync/latest/devguide/what-is-appsync.html), which is a GraphQL service. GraphQL is very popular and not unique to AWS, and that block of code I posted for the `mutation` is a GraphQL query string which can be used with any GraphQL client (and there are a lot!)

I really like Insomnia as a general HTTP/GraphQL client because it can pull down the schema and help you write queries: https://insomnia.rest/

To your second question, yes, you should still be able to update them. When you delete a model, it marks it as deleted but doesn't actually remove the data from the database for a set period of time (called the [TTL](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html)). By default, this is 30 days. Within that time period, the `_deleted` field of the model will be true, but the data will still exist in the DynamoDB table (which is the database used by AppSync).

Hope this helps!

**Comment by guplem** [comment] 2022-03-05 11:53
> Great questions! And no worries. So, the Amplify API & DataStore categories are backed by [AWS AppSync](https://docs.aws.amazon.com/appsync/latest/devguide/what-is-appsync.html), which is a GraphQL service. GraphQL is very popular and not unique to AWS, and that block of code I posted for the `mutation` is a GraphQL query string which can be used with any GraphQL client (and there are a lot!)
> 
> I really like Insomnia as a general HTTP/GraphQL client because it can pull down the schema and help you write queries: https://insomnia.rest/
> 
> To your second question, yes, you should still be able to update them. When you delete a model, it marks it as deleted but doesn't actually remove the data from the database for a set period of time (called the [TTL](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html)). By default, this is 30 days. Within that time period, the `_deleted` field of the model will be true, but the data will still exist in the DynamoDB table (which is the database used by AppSync).
> 
> Hope this helps!

Thanks for the clear answers!

I created this issue (https://github.com/aws-amplify/amplify-adminui/issues/497) in the Amplify Admin UI (which, I believe, is the repository for Amplify Studio). 
Probably this should be fixed there... Maybe allowing the automatic application of mutations to previously existing data to fit the new model?

**Comment by dnys1** [comment] 2022-03-05 20:31
I agree - this could definitely be an enhancement of the DataStore category and the Studio UI! Thanks for creating that ticket.

I will close this one for now in favor of that one. Please feel free to re-open or create another ticket here if you continue to experience challenges.

**Closed by dnys1** 2022-03-05 20:31 UTC
Labels: clarification-needed, DataStore

**Comment by Quixotical** [comment] 2022-08-20 09:58
This might not be related but I wanted to add that my issue was that after I had updated the model with a new required field, the local datastore on my emulator was not updated even though everything else was. The solution was to clear the data on my emulator and then reload the data from dynamoDB. Then everything worked as expected.
