### ISSUE TITLE
Null-Safety Support

### ISSUE THREAD

**Issue by raywhiteside** [aws-amplify/amplify-flutter#435] opened 2021-03-09 15:07 UTC
I assume at some point null safety will be supported. I'd like to track the status and interest here.

**Comment by fjnoyp** [comment] 2021-03-10 13:23
Hi @raywhiteside thanks for creating this issue.  We don't have any set dates for delivering this, but are actively looking into it.  We can update you here.

**Comment by cto-leaps** [comment] 2021-03-16 20:43
I'm pretty sure a lot of people are looking to move to null-safety and not having all dependencies supporting it will be an issue soon. Do you guys have any idea of an ETA for this?

**Comment by 24601** [comment] 2021-03-27 00:04
I would suggest a heavy priority be put on this. Frankly, a brand-new (as opposed to new rev with old legacy code) project/library like Amplify Flutter NOT supporting this amazes me (to the point of it almost being negligent, given null safety was no surprise, been in plan for quite some time in Flutter, almost as if AWS didn't hire or engage proper Flutter architects to plan this).

Especially considering that null-safe packages are compatible for those not using it, but you're locking out those who are or at least being the delaying dependency for those who otherwise could move (e.g. people not using null-safety could still use amplify-flutter, but people using null safety cannot use amplify-flutter).

**Comment by Ashish-Nanda** [comment] 2021-03-28 18:57
@24601 I understand your frustration, but as you can see above https://github.com/aws-amplify/amplify-flutter/issues/435#issuecomment-795408009 it is clear that we are actively working on the null safety migrations and acknowledge its importance. We cannot disclose our internal roadmap or dates, **but this is one of our top priorities at this time**. 

Also this is not a surprise for us. The project is new, but was started much before migrations of a lot of community packages began. It was planned to have the migration for all packages (we have 12) after GA, and at the same time to ensure they work together as many are interdependent. Please remember null safety migrations are still happening actively across the Dart/Flutter ecosystem with [775 packages migrating just recently](https://twitter.com/dart_lang/status/1370419316324245509?s=20), and different projects will take take time based on size, complexity, dependencies, etc. 

While we encourage feedback we request that it is constructive, respectful and adheres to our [community guidelines](https://aws.github.io/code-of-conduct). I assure you we understand the importance of the null safety migration and are actively working on it. We will update this thread as soon as we have a preview version available for customers to try.

**Comment by meggamind** [comment] 2021-03-30 17:48
@Ashish-Nanda Do you need help with this? I would like to make a PR if ya'll need help

**Comment by 24601** [comment] 2021-03-30 17:58
> @24601 I understand your frustration, but as you can see above [#435 (comment)](https://github.com/aws-amplify/amplify-flutter/issues/435#issuecomment-795408009) it is clear that we are actively working on the null safety migrations and acknowledge its importance. We cannot disclose our internal roadmap or dates, **but this is one of our top priorities at this time**.
> 
> Also this is not a surprise for us. The project is new, but was started much before migrations of a lot of community packages began. It was planned to have the migration for all packages (we have 12) after GA, and at the same time to ensure they work together as many are interdependent. Please remember null safety migrations are still happening actively across the Dart/Flutter ecosystem with [775 packages migrating just recently](https://twitter.com/dart_lang/status/1370419316324245509?s=20), and different projects will take take time based on size, complexity, dependencies, etc.
> 
> While we encourage feedback we request that it is constructive, respectful and adheres to our [community guidelines](https://aws.github.io/code-of-conduct). I assure you we understand the importance of the null safety migration and are actively working on it. We will update this thread as soon as we have a preview version available for customers to try.

Thanks for the insight, and I look forward to AWS releasing the software. 

I reviewed the community guidelines, I did not find anywhere that my comment violated it. If I did, please help me understand so I can avoid doing so in the future, but being frank and upfront doesn't seem to be against the policy. On the other hand, attempting to use community guidelines designed to create a safe space for everyone to silence criticism of AWS as a company's ability to execute as compared to smaller players is actually more harmful to a "safe space" and inclusive community than anything else if you ask me.

**Comment by fjnoyp** [comment] 2021-03-31 06:08
#481 - Null Safety support for Core/Flutter and all Platform Plugin Interfaces
#482 - Null Safety support for Auth
#483 - Null Safety support for Analytics
#484 - Null Safety support for API

**Comment by fjnoyp** [comment] 2021-04-22 22:49
Hi everyone, thanks for your patience as we upgrade Amplify Flutter to support Null Safety.  

This upgrade is requiring a lot of changes throughout our entire code base so we've created a separate branch here: https://github.com/aws-amplify/amplify-flutter/tree/null-safety-master to aggregate our Null Safety changes. 

So far we've upgrade our core and flutter modules as well as all of the interfaces.  We'll now be migrating individual module plugins starting with Auth.  We'd love to get your feedback during this upgrade.  We are migrating Auth now so feel free to take a look at the what's changing here: #536

**Comment by maxim-saplin** [comment] 2021-05-02 14:26
Thanks for the effort taken to migrate to null-safety! Looking forward to pub.dev updaes, will be trying Amplify as soon as null-safe versions are rolled out.

**Comment by BesavedTech** [comment] 2021-05-05 08:06
When will these be rolling out?

**Comment by yurijdvornyk** [comment] 2021-05-19 11:44
Hi, any updates on this?

**Comment by sima-11** [comment] 2021-06-07 08:51
Understand it may take quite some efforts. But would it be possible to provide a way to generate models with null safety first? 
E.g. `amplify codegen models --null-safety`

**Comment by fjnoyp** [comment] 2021-06-11 18:46
Hi everyone the pre release version of null safety for Auth, Storage, API, and Analytics is now available.  To use it please update your pubspec.yaml to 0.2.0-nullsafety.0 as it is opt in only.  

We are currently working on upgrading Datastore to Null Safety and will share updates once that is ready.

**Comment by caravanat** [comment] 2021-06-14 15:52
The 0.2.0-nullsafety.0 branch won't compile for me. I'm getting the following error:

`e: /Users/caravath/Development/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_auth_cognito-0.2.0-nullsafety.0/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/types/FlutterFetchCognitoAuthSessionResult.kt: (45, 38): Type mismatch: inferred type is Map<String, Any> but Comparable<{Boolean & String}>? was expected
e: /Users/caravath/Development/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_auth_cognito-0.2.0-nullsafety.0/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/types/FlutterFetchCognitoAuthSessionResult.kt: (45, 38): Type mismatch: inferred type is Map<String, Any> but Serializable? was expected
e: /Users/caravath/Development/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_auth_cognito-0.2.0-nullsafety.0/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/types/FlutterFetchCognitoAuthSessionResult.kt: (45, 38): Type mismatch: inferred type is Map<String, Any> but {Comparable<{Boolean & String}>? & java.io.Serializable?} was expected
e: /Users/caravath/Development/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_auth_cognito-0.2.0-nullsafety.0/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/types/FlutterFetchCognitoAuthSessionResult.kt: (49, 33): Type mismatch: inferred type is Map<String, Any> but Comparable<{Boolean & String}>? was expected
e: /Users/caravath/Development/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_auth_cognito-0.2.0-nullsafety.0/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/types/FlutterFetchCognitoAuthSessionResult.kt: (49, 33): Type mismatch: inferred type is Map<String, Any> but Serializable? was expected
e: /Users/caravath/Development/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_auth_cognito-0.2.0-nullsafety.0/android/src/main/kotlin/com/amazonaws/amplify/amplify_auth_cognito/types/FlutterFetchCognitoAuthSessionResult.kt: (49, 33): Type mismatch: inferred type is Map<String, Any> but {Comparable<{Boolean & String}>? & java.io.Serializable?} was expected

FAILURE: Build failed with an exception.`

**Comment by jonbhanson** [comment] 2021-06-15 16:43
> Looks like the type is missing in the line 35. After changing the code to:
> 
> `var serializedMap = mutableMapOf<String, Any?>`
> 
> It worked. I'm gonna do further tests. Thanks, guys!

Thanks for this solution @caravanat, this worked for me. 👍

**Comment by Jordan-Nelson** [comment] 2021-06-15 19:48
@caravanat and @jonbhanson could you both let me know what version of flutter you are using and what other amplify packages you are using?

**Comment by jonbhanson** [comment] 2021-06-15 20:21
@Jordan-Nelson 

Flutter doctor output:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.56.2)
[✓] Connected device (3 available)
```

amplify packages in `pubspec.yaml`:
```yaml
  amplify_auth_cognito: ^0.2.0-nullsafety.0
  amplify_flutter: ^0.2.0-nullsafety.0
  amplify_analytics_pinpoint: ^0.2.0-nullsafety.0
```

**Comment by caravanat** [comment] 2021-06-15 21:04
```
macOS 11.4, Android Studio 4.2.1, flutter 2.2.2.

  amplify_flutter: ^0.2.0-nullsafety.0
  amplify_core: ^0.2.0-nullsafety.0
  amplify_auth_cognito: ^0.2.0-nullsafety.0
```

**Comment by leonardocustodio** [comment] 2021-06-18 20:43
I'm having the same problem with amplify packages. Can we release a new version with @caravanat fix?

**Comment by dnys1** [comment] 2021-06-18 21:31
It seems the issue is related to Kotlin itself. The Amplify team currently uses the default version in new Flutter packages, 1.3.50, and we're able to recreate the issue only by bumping the Kotlin version. Can those who experienced the issue confirm they are using versions of Kotlin >1.3.50?

As the team investigates how to prevent issues like this from happening in the future, we will be releasing the fix proposed by @leonardocustodio soon. Thank you for your time and patience resolving this matter.

**Comment by leonardocustodio** [comment] 2021-06-18 21:34
Yes, I'm using kotlin 1.4.32. Had to bump kotlin version because of other packages.
I appreciate the PR but the real kudos goes to @caravanat who proposed the fix :)

**Comment by caravanat** [comment] 2021-06-18 22:01
Thanks @leonardocustodio for the PR... I didn't knew if it was something local here so I just made the change locally until further investigation.

Here we use Kotlin 1.4.30 and others devs here had the same problem using the 0.2.0-nullsafety.0 branch.

**Comment by jonbhanson** [comment] 2021-06-21 13:56
@dnys1 in my case I had the problem with an app using Kotlin version 1.5.10.

**Comment by Ahmed0tdc** [comment] 2021-06-21 17:08
does anyone know when will amplify start supporting null safety?

**Comment by Ashish-Nanda** [comment] 2021-07-01 02:52
**Amplify Flutter `0.2.0` with support for null safety is now released!**

Please take a look at the docs for [instructions on how to migrate your app](https://docs.amplify.aws/lib/project-setup/null-safety/q/platform/flutter)

Do let us know if you have any questions or feedback.

**Closed by Ashish-Nanda** 2021-07-01 02:52 UTC
Labels: feature-request
