### ISSUE TITLE
 Is it possible to use both sign in and social sign in with web ui?

### ISSUE THREAD

**Issue by kimjuggang** [aws-amplify/amplify-flutter#1263] opened 2022-01-13 08:35 UTC
**Describe the bug**
When calling sign out and sign in, the web UI is displayed.

**To Reproduce**

```dart
   try {
      await Amplify.Auth.signOut();
    } on AuthException catch (e) {
      print(e);
    }

    try {
      await Amplify.Auth.signIn(
          username: usernameController.text.trim(),
          password: passwordController.text.trim());
      await _fetchUserAttributes();
      await _fetchSession();
      Navigator.pop(context, true);
    } on AuthException catch (e) {
      setState(() {
        _signUpError = e.message;
      });
    }
```

```dart
const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "myappdata",
                        "AppClientId": "myappdata",
                        "Region": "myappdata"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "myappdata",
                            "AppClientId": "myappdata",
                            "SignInRedirectURI": "myappdata",
                            "SignOutRedirectURI": "",                            
                            "Scopes": [
                                "email",
                                "openid",
                                "profile"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [
                            "GOOGLE",
                            "APPLE"
                        ],
                        "usernameAttributes": [
                            "EMAIL"
                        ],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": [
                                "REQUIRES_LOWERCASE",
                                "REQUIRES_NUMBERS"
                            ]
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}''';
```

**Expected behavior**
The web ui is not displayed and the sign in is successful.

**Screenshots**
![Screenshot_1642062492](https://user-images.githubusercontent.com/13284419/149293720-050c8c8e-1e85-4e69-8ce3-c59b1fe8d38f.png)

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[*] Android

<details>

I want to use both Apple sign in and normal sign.

</details>

**Comment by Jordan-Nelson** [comment] 2022-01-13 13:51
Hello @kimjuggang - I think this is a duplicate of https://github.com/aws-amplify/amplify-flutter/issues/401. My latest comment on that issue should answer your question.

> As of now, the Amplify-Android library, which Amplify-Flutter depends on, does not officially support social sign in and username based sign in within the same app. The [amplify-android issue](https://github.com/aws-amplify/amplify-android/issues/1180) linked above is the feature request for that in Amplify-Android. If this is a feature you are looking for, you can give that issue a 👍 to show your support.

I am going to close this issue. Please feel free to 👍 both #401 and https://github.com/aws-amplify/amplify-android/issues/1180 to show your interest in using both forms of authentication within a single app.

**Closed by Jordan-Nelson** 2022-01-13 13:51 UTC
Labels: Auth
