### ISSUE TITLE
Could not configure Amplify: AmplifyException(message: Amplify plugin AmplifyAuthCognito was not added successfully.

### ISSUE THREAD

**Issue by aqarcoSys** [aws-amplify/amplify-flutter#1237] opened 2021-12-31 14:40 UTC
**Describe the bug**
Amplify configuration not working with hot reload, when I change the code the exception is raided Amplify plugin XXXX was not added  successfully

```dart
  Future<void> _configure() async {
    try {
      
      kLogger.i("configuring Amplify", "[AmplifyService]");

      // add Amplify plugins
      await Amplify.addPlugins([
        AmplifyAuthCognito(),
        _dataStorePlugin,
        AmplifyAPI(),
        // _pinpointPlugin,
        // _storageS3Plugin
      ]);

      kLogger.i("Plugins added", "[AmplifyService]");

      if (!Amplify.isConfigured) await Amplify.configure(amplifyconfig);

    } on AmplifyAlreadyConfiguredException {

      kLogger.w("Amplify already configured !");

    } catch (e) {

      kLogger.e(e.toString(), "[AmplifyService][_configure]");
    }
  }
```

**To Reproduce**

**Expected behavior**
Amplify configure  should .work with hot reload, not with reinstall the app

**Platform**
Amplify Flutter currently supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

**pubspec.yml**

```yml
  #amplify
  amplify_flutter: ^0.2.10
  amplify_datastore: ^0.2.10
  amplify_api: ^0.2.10
  amplify_auth_cognito: ^0.2.10
  amplify_analytics_pinpoint: ^0.2.10
  amplify_storage_s3: ^0.2.10
```

**flutter doctor**
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)
```

**Comment by haverchuck** [comment] 2022-01-03 16:05
@aqarcoSys At what point in the lifecycle are you calling your _configure method?

**Comment by aqarcoSys** [comment] 2022-01-05 18:38
@haverchuck  Im calling inside `initState()`  , I have always to reinstalll the app from the simulator

**Comment by aqarcoSys** [comment] 2022-01-06 09:51
any Help here ? , we cannot use amplify with flutter

**Comment by Jordan-Nelson** [comment] 2022-04-26 14:15
@aqarcoSys - I am unable to reproduce this issue. Can you share your amplifyconfig.dart (with sensitive info masked)? This could be an issue with you config. Was the project created with the Amplify CLI? If so, what version are you using?

**Comment by Jordan-Nelson** [comment] 2022-05-10 18:42
Closing this out since I have heard back. Please open a new issue if you are still experiencing this issue.

**Closed by Jordan-Nelson** 2022-05-10 18:42 UTC
Labels: pending-close-response-required, Auth, pending-triage
