### ISSUE TITLE
Post confirmation trigger lambda does not get correct user pool id.

### ISSUE THREAD

**Issue by bprayush** [aws-amplify/amplify-flutter#901] opened 2021-09-18 03:30 UTC
**Describe the bug**
The Post confirmation lambda function to add user to group does not get correct user pool id.

**To Reproduce**
1. Add Post confirmation
2. Add "Add user to group" functionality

**Expected behavior**
The user should be added to the user group.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[X] Android
[] iOS

<details>
  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```
➜ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.0, on Pop!_OS 20.04 LTS 5.13.0-7614-generic, locale
    en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.60.1)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
```
</details>

<details>
  <summary>Exception snippet</summary>

```
AuthException{
    message=Confirm sign up failed, 
    cause=com.amazonaws.services.cognitoidentityprovider.model.UserLambdaValidationException: 
    PostConfirmation failed with error 
    User: arn:aws:sts::XXXXXXXX:assumed-role/XXXXXXXX/XXXXXXXX is not 
    authorized to perform: cognito-idp:AdminAddUserToGroup on resource: 
    arn:aws:cognito-idp:ap-southeast-2:XXXXXXXX:userpool/XXXXXXXX. 
    (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: UserLambdaValidationException; 
    Request ID: 3edd7e2c-469f-467a-b201-a2f22ff721d2), 
    recoverySuggestion=See attached exception for more details.
}
```
</details>

**Additional context**
Manually adding the correct user pool ID to the permission solves the issue but ideally, amplify CLI should add it automatically.

**Comment by fjnoyp** [comment] 2021-09-19 01:21
Hi @bprayush thanks for reaching out to us.  We'll look into the issue on Monday

**Comment by dnys1** [comment] 2021-09-21 18:53
I'm able to reproduce. Looks like it might be a CLI issue. Will verify and create a ticket with them, if that's the case.

**Comment by dnys1** [comment] 2021-09-21 22:19
Looks like it is being tracked in the CLI repo already. Closing in favor of those issues:
- Tracking Issue: https://github.com/aws-amplify/amplify-cli/issues/7582
- Current Workaround is to add the necessary permissions by hand to the Lambda function: https://github.com/aws-amplify/amplify-cli/issues/8012#issuecomment-905723746

**Closed by dnys1** 2021-09-21 22:19 UTC
Labels: bug, Auth

**Comment by cunneen** [comment] 2021-12-10 12:11
An alternative workaround is to edit the `amplify/backend/function/[....MY_AUTH_CATEGORY_NAME....]/XXXXXXPostConfirmation-cloudformation-template.json` and add the statement below to the `Resources.lambdaexecutionpolicy.Properties.PolicyDocument.Statement` array  (which grants the lambda full access to all user pools).

The advantage of this approach is it's reusable e.g. if a new environment is created.

```json
{
  "Effect": "Allow",
  "Action": [
    "cognito-idp:CreateGroup",
    "cognito-idp:AdminAddUserToGroup",
    "cognito-idp:GetGroup"
  ],
  "Resource": {
    "Fn::Sub": [
      "arn:aws:cognito-idp:${region}:${account}:userpool/*",
      {
        "region": {
          "Ref": "AWS::Region"
        },
        "account": {
          "Ref": "AWS::AccountId"
        },
        "lambda": {
          "Ref": "LambdaFunction"
        }
      }
    ]
  }
}
```
