### ISSUE TITLE
gradle build failing due to robolectric version

### ISSUE THREAD

**Issue by raywhiteside** [aws-amplify/amplify-flutter#826] opened 2021-08-22 21:21 UTC
**Describe the bug**
`./gradlew build` failing due to robolectric version

**To Reproduce**
```
> cd $flutter_project_with_amplify
> cd android
> ./gradlew -v
------------------------------------------------------------
Gradle 5.6.2
------------------------------------------------------------

Build time:   2019-09-05 16:13:54 UTC
Revision:     55a5e53d855db8fc7b0e494412fc624051a8e781

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          11.0.12 (Oracle Corporation 11.0.12+7)
OS:           Linux 5.13.12-arch1-1 amd64

> ./gradlew build
...
Execution failed for task ':amplify_auth_cognito:testDebugUnitTest'.
> There were failing tests. See the report at: 
$flutter_project_with_amplify/build/amplify_auth_cognito/reports/tests/testDebugUnitTest/index.html
```
If you look at the failing report, this is the error:

```
Unable to resolve artifact: Missing:
----------
1) org.robolectric:android-all:jar:10-robolectric-5803371
...
  Path to dependency: 
  	1) org.apache.maven:super-pom:pom:2.0
  	2) org.robolectric:android-all:jar:10-robolectric-5803371

----------
1 required artifact is missing.

for artifact: 
  org.apache.maven:super-pom:pom:2.0

from the specified remote repositories:
  central (http://repo1.maven.org/maven2),
  sonatype (https://repo1.maven.org/maven2)
```

The problem is the URL for maven is http not https, you can see for yourself the difference clicking on these links:

http://repo1.maven.org/maven2
https://repo1.maven.org/maven2

```
501 HTTPS Required. 
Use https://repo1.maven.org/maven2/
More information at https://links.sonatype.com/central/501-https-required
```

Similar issues:

https://github.com/flutter/flutter/issues/48943
https://github.com/robolectric/robolectric/issues/5456

Key is Amplify packages are using 4.3.1 which was released before the non-SSL URL was deprecated, so it needs to be updated to a newer version.

**Expected behavior**
`./gradlew build` should complete without error

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[X] Android
[] iOS

Using Amplify 2.2

```
❯ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /opt/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /opt/android-sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android_sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 12.0.1
    • cmake version 3.21.1
    • ninja version 1.10.2
    • pkg-config version 1.7.3

[✓] Android Studio (version 2020.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 59.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```

**Comment by HuiSF** [comment] 2021-08-23 19:11
Thanks for reporting this issue and the detailed explanation. It looks like the Android packages in the codebase could use a upgrade. Will look into it.

**Comment by Jordan-Nelson** [comment] 2022-04-27 18:29
I'm going to mark this as a bug until we update to 4.4 or higher. I think we can update to 4.5.1 to match Amplify-Android ([reference](https://github.com/aws-amplify/amplify-android/blob/650c8ee7e2a673b358c126f50d696ba7c7fa59d8/build.gradle#L128)).

**Comment by dnys1** [comment] 2023-06-06 00:11
Closing as this is no longer reproducible. Please reopen if you continue to experience issues on the latest version of Amplify Flutter.

**Closed by dnys1** 2023-06-06 00:11 UTC
Labels: bug, Android, Build
