### ISSUE TITLE
Timing out awaiting device token

### ISSUE THREAD

**Issue by 94Sip** [aws-amplify/amplify-flutter#3737] opened 2023-09-12 23:23 UTC
### Description

I am not able to complete Amplify.configure() as I keep reaching timeout of 5s with the push notification plugin (see screen capture of error below)

I am getting this error using the iOS Simulator. I would get this error when I first implemented the push notification plugin, and then would need to simply restart the simulator and the error would go away. Now, I am getting this error all the time and I can't resolve it. And I am using Simulator of iPhone 14 Pro with iOS 16.4.

I can connect my iPhone 13 Pro to my macbook, via USB, and I do NOT get this error.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Notifications (Push)
- [ ] Storage

### Screenshots

<img width="1322" alt="image" src="https://github.com/aws-amplify/amplify-flutter/assets/60077534/da92a4ec-2e16-498f-aff7-8cdc12dbc051">

Screenshot of configure Amplify function:
<img width="1035" alt="image" src="https://github.com/aws-amplify/amplify-flutter/assets/60077534/1db97608-ac3c-4b59-8385-837627e5dcf6">

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.3

### Amplify Flutter Version

1.4

### Deployment Method

Amplify CLI

**Comment by HuiSF** [comment] 2023-09-13 18:18
Hi @94Sip When you receive the exception "Timed out awaiting device token", it implies the simulator is not able to generate a device token for your app.

Testing remote push notifications was impossible with the iOS simulator, but Apple has recently provided support with limitations. Please refer to https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/flutter/#prerequisites for the details.

>Testing with APNs on the iOS simulator requires an Apple Silicon Mac running macOS 13+, Xcode 14+, and the iOS simulator 16+. If your development environment does not meet all these requirements, then you must run on a real device to get an APN token.

If you don't have this environment available, please test PN with a physical device (as you mentioned, this wasn't an issue on your iPhone 13 Pro).

**Comment by 94Sip** [comment] 2023-09-13 19:48
Hi and thank you for the response @HuiSF 

Yes, I saw those environment constraints in the documentation and I DO meet those requirements (Apple Silicon Mac running macOS 13+, Xcode 14+, and iOS simulator 16+). And as I mentioned I used to be able to get a token, but something has changed and now it doesn't work at all. Meaning, I could get a token if I restarted the simulator, but now, no matter what I try the token times out.

I saw in a previous Issue that we are supposed to call identifyUser with a '' for the userId to clear the endpoint? Could this be causing the problem? This token timeout has occurred with Fluter 3.13.1 and 3.13.3. 

From an environment perspective, I am also using the Authenticator component, and I have upgraded all of these to the latest of 1.4.x.

**Comment by HuiSF** [comment] 2023-09-14 00:52
Thanks for the clarification @94Sip 

>I saw in a previous Issue that we are supposed to call identifyUser with a '' for the userId to clear the endpoint?

I don't think this is relevant; the timeout exception is particularly useful for waiting for the native implementation to return the token. This is a precondition for reaching any Pinpoint related business logic. 

https://github.com/aws-amplify/amplify-flutter/blob/46ca8dbed81e361ae09f27c32a04c418ee7f452d/packages/notifications/push/amplify_push_notifications/lib/src/amplify_push_notifications_impl.dart#L347-L349

>I used to be able to get a token, but something has changed and now it doesn't work at all. Meaning, I could get a token if I restarted the simulator, but now, no matter what I try the token times out.

Still, this sounds like an Xcode/iOS simulator-specific environment issue. The plugin doesn't have any control over the system issuing a device token.

It could be worth nothing, but try to reset your simulator, Xcode etc. Also you can try to run the iOS app using Xcode directly, which gives more native logs that may give a hint what's going on.

**Comment by 94Sip** [comment] 2023-09-18 13:44
None of the recommendations for resetting xcode or the simulator worked.

As a workaround I created environment variables in VS Code to indicate if I will be debugging in a simulator or not, and when using simulator I do NOT load the PushNotification plugin, and any code that uses that plugin. 

Its obviously a workaround but allows me to use the simulator for all the things I need the simulator for (e.g. responsive design).

**Comment by Jordan-Nelson** [comment] 2023-10-10 19:27
Hello @94Sip - Do you know what changed between the period of time that this was working and when it stopped working?

**Comment by Jordan-Nelson** [comment] 2023-10-11 17:50
@94Sip - I think we can make an update to not throw in this scenario and instead log an error. That way you are able to develop when the token cannot be retrieved.

**Comment by 94Sip** [comment] 2023-10-14 16:12
@Jordan-Nelson  ok, that can work, thank you.

As to your question about "what changed", I really don't understand that. The only thing I can think of was using a different simulator - I have been testing iOS 13 and iOS 14 Pro.

**Comment by BradVidler** [comment] 2023-10-18 19:48
In case it matters, I don't believe this is just an ios/emulator issue. We are having quite a few Android users getting stuck on our native splash screen on app launch. In the ANR in Crashlytics we see PushNotificationException { "message": "Timed out awaiting for device token." on most of them. Additionally, we have lots of non-fatal crashes for the same error.

Unfortunately I am unable to reproduce the error in debug or release, or on a real device or emulator.

**Comment by zilaiyedaren** [comment] 2023-10-24 13:43
flutter: An error occurred configuring Amplify: PushNotificationException {
flutter:   "message": "Timed out awaiting for device token.",
flutter:   "recoverySuggestion": "This may happen when the native apps have not been correctly configured for push notifications, review push notification configurations of the native iOS and Android apps of your Flutter project.",
flutter:   "underlyingException": "TimeoutException after 0:00:05.000000: Future not completed"
flutter: }

**Comment by Jordan-Nelson** [comment] 2023-11-10 17:00
We will use https://github.com/aws-amplify/amplify-flutter/issues/3997 to track issues around tokens not being received on physical devices. I am going to close this issue out.

**Closed by Jordan-Nelson** 2023-11-10 17:00 UTC
Labels: bug, push notifications
