### ISSUE TITLE
Get Issue when changing the configuration amplify

### ISSUE THREAD

**Issue by manhtran-itr** [aws-amplify/amplify-flutter#2867] opened 2023-04-14 04:58 UTC
### Description

- At first, our app sets the Amplify.configure(alphaAwsConfig) for the alpha environment, 
- Our app wants to switch to another environment ex.delta by killing the app and setting the delta environment Amplify.configure(deltaAwsConfig). The configuration is successful
==> We try to sign out from the old account. The next step we sign in to the new account successfully.
==>  But when getting the access token to authenticate with the server, we get the invalid access token.  However if we uninstall the app and reconfigure Amplify.configure, and All things work fine. 

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.2.1 22D68 darwin-arm64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.77.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

### Dependencies

```bash
amplify_flutter
amplify_auth_cognito
```

### Device

iphone xs, Samsung

### OS

iOS 15.2, Android 12

### CLI Version

7.6.21

**Comment by Jordan-Nelson** [comment] 2023-04-14 10:46
@manhtran-itr - what version of amplify_flutter are you using?

**Comment by manhtran-itr** [comment] 2023-04-17 02:06
@Jordan-Nelson My versions: 
  amplify_core: 0.6.5
  amplify_flutter: 0.6.5
  amplify_auth_cognito: 0.6.5
  amplify_storage_s3: 0.6.5

**Comment by dnys1** [comment] 2023-04-17 19:02
Would you be able to try again with v1.0.0 of Amplify Flutter?

**Comment by manhtran-itr** [comment] 2023-04-18 07:28
@dnys1 We cannot update to v1.0.0 because it isn't compatible with other dependencies. The highest version we can upgrade to is v0.6.13

**Comment by Jordan-Nelson** [comment] 2023-04-18 10:17
@manhtran-itr - what dependencies does it conflict with?

**Comment by manhtran-itr** [comment] 2023-04-18 11:32
@Jordan-Nelson  these dependencies: 
amplify_core: 0.6.5
amplify_flutter: 0.6.5
amplify_auth_cognito: 0.6.5
amplify_storage_s3: 0.6.5

Conflict with: 
  device_info_plus: 4.0.0 --> required 8.0.0
  drift: 2.6.0 --> required <2.6.0
  flutter_svg: 1.0.3 --> ..
  printing

When updating to the newest version, it required other dependencies must update too. I solved those, Because of the newest versions, some codes are out of date or get predicated like storage... we need to change those too, it get risks to do that.

Notes: I tried to update to 0.6.13 and get the same error, I just wonder, the Amplify_flutter only allows configuring the AWS one time and keep until the app unintalls?

**Comment by Jordan-Nelson** [comment] 2023-04-18 13:37
Switching configs isn't officially supported, but I believe this would work in the latest version depending on what your expectations are when changing the config.

Let me know if you are willing to upgrade the latest version. If some of those dependencies are transitive dependencies, I would reach out to the maintainers of your direct dependencies to see if they would release a new version support the latest version.

Note: There is a feature request to support calling configure() multiple times at runtime (https://github.com/aws-amplify/amplify-flutter/issues/1902). It sounds like you are fine with stopping the app between calls. However, this would still be a good place to add info about your use case and what your expectations are when switching configs.

**Comment by manhtran-itr** [comment] 2023-04-19 02:32
@Jordan-Nelson  Thanks for your response. We just want to kill the app and reconfigure the new one. 
If Amplify_flutter can support calling configure multiple times at runtime, it will be better.  In react native codes, we can do it multiple times. 

Thanks.

**Comment by Jordan-Nelson** [comment] 2023-04-20 19:57
Hi @manhtran-itr - As noted above, I believe this would work in v1 but it is not something we officially support. I am going to close this as a duplicate of https://github.com/aws-amplify/amplify-flutter/issues/1902. Can you add some info about your use case to that feature request?

**Closed by Jordan-Nelson** 2023-04-20 19:57 UTC
Labels: Auth, pending-response
