### ISSUE TITLE
DataStore Realtime Sync not working. Error in IncomingAsyncSubscriptionEventToAnyModelMapper

### ISSUE THREAD

**Issue by alrashedf** [aws-amplify/amplify-flutter#1390] opened 2022-02-23 07:11 UTC
### Description

When DataStore is used and I subscribe to a `Amplify.DataStore.observeQuery(Orders.classType).listen`. It works fine on Android but I get the following error on iOS:
`[IncomingAsyncSubscriptionEventToAnyModelMapper] The operation couldn’t be completed. (Amplify.GraphQLResponseError<AWSPluginsCore.MutationSync<AWSPluginsCore.AnyModel>> error 1.)`

In screenshots below, the iOS App is receiving an update with `branch` being `null`. But in DynamoDB, `ordersBranchId` is not `null`. Could it be that there is a mapping issue between `branch` table name and internal backend naming `ordersBranchId`?

### Categories

- [ ] Analytics
- [ ] API
- [ ] Auth
- [X] DataStore
- [ ] Storage

### Steps to Reproduce

1. Configure amplify to use Auth (using cognito), DataStore, and API. 
2. Use the following `schema.graphql` and push it to Amplify.
```
enum OrderState {
  PLACED
  ACCEPTED
  READY
  COMPLETED
  REJECTED
}

type Orders @model @key(name: "ordersByUserID", fields: ["userID", "placed"], queryField: "ordersByUserID") @auth(rules: [{allow: public}, {allow: private}]) {
  id: ID!
  placed: AWSDateTime
  details: AWSJSON
  state: OrderState
  branch: Branch @connection
  subTotal: Float
  tax: Float
  total: Float
  userID: String
}

type Branch @model @key(name: "byBrand", fields: ["brandID"]) @auth(rules: [{allow: public}, {allow: private, operations: [read]}]) {
  id: ID!
  brandID: ID
  name: String!
  tagline: String
  menu: AWSJSON
  arabicMenu: AWSJSON
  location: AWSJSON!
}
```
 
2. Listen to Order changes in the code `Amplify.DataStore.observeQuery(Orders.classType,
   where: AsUsualOrders.USERID.eq(userID)).listen(listener);`
3. Add an order to Amplify Studio content tab
4. See error in the iOS log
```
[StarscreamAdapter] websocketDidReceiveMessage: - {"id":"656FD38E-226F-449C-97CC-C398DD823A54","type":"data","payload":{"data":{"onUpdateOrders":{"id":"8336807e-557f-4777-b866-093badffa43e","accepted":"2022-02-21T21:35:20.020Z","completed":null,"details":"{\"delivery\":{\"requested\":false},\"details\":[{\"instructions\":null,\"quantity\":1,\"price\":15,\"name\":\"Cortado\",\"description\":\"Cortado Description \",\"tax\":2.25,\"attributes\":[]}]}","placed":"2022-02-21T18:35:03.637477000Z","readied":"2022-02-22T10:26:07.007Z","receiptentInfo":"XXX/XXX/XXX","rejected":null,"state":"READY","subTotal":15.0,"tax":2.25,"total":17.25,"userID":"XXX","branch":null,"__typename":"Orders","_version":3,"_deleted":null,"_lastChangedAt":1645514767852}},"errors":[{"message":"Cannot return null for non-nullable type: 'AWSJSON' within parent 'Branch' (/onUpdateOrders/branch/location)","path":["onUpdateOrders","branch","location"]},{"message":"Cannot return null for non-nullable type: 'String' within parent 'Branch' (/onUpdateOrders/branch/name)","path":["onUpdateOrders","branch","name"]},{"message":"Cannot return null for non-nullable type: 'Int' within parent 'Branch' (/onUpdateOrders/branch/_version)","path":["onUpdateOrders","branch","_version"]},{"message":"Cannot return null for non-nullable type: 'AWSTimestamp' within parent 'Branch' (/onUpdateOrders/branch/_lastChangedAt)","path":["onUpdateOrders","branch","_lastChangedAt"]}]}}
[RealtimeConnectionProvider] Resetting stale connection timer
[AppSyncSubscriptionConnection] handleDataEvent(response:): A7E29E99-0524-4BA7-AEA2-02CE42EB5593. Ignoring data event for 656FD38E-226F-449C-97CC-C398DD823A54
[AppSyncSubscriptionConnection] handleDataEvent(response:): DA856C5D-766D-4B47-A3E3-6D7BB51C44EA. Ignoring data event for 656FD38E-226F-449C-97CC-C398DD823A54
[AppSyncSubscriptionConnection] handleDataEvent(response:): A754C29E-D8B5-49E0-B450-57AA5FBAF858. Ignoring data event for 656FD38E-226F-449C-97CC-C398DD823A54
[AppSyncSubscriptionConnection] handleDataEvent(response:): 7F4220DE-4084-4D94-AABF-DA91BD809C14. Ignoring data event for 656FD38E-226F-449C-97CC-C398DD823A54
[AppSyncSubscriptionConnection] handleDataEvent(response:): 9863BDAB-7871-4919-81CE-C14D96F38850. Ignoring data event for 656FD38E-226F-449C-97CC-C398DD823A54
[AppSyncSubscriptionConnection] handleDataEvent(response:): 32E3C185-208E-4027-8C76-3C0553FFC031. Ignoring data event for 656FD38E-226F-449C-97CC-C398DD823A54
[AppSyncSubscriptionConnection] handleDataEvent(response:): 42966AD8-162B-4400-A877-00A5B233526B. Ignoring data event for 656FD38E-226F-449C-97CC-C398DD823A54
[AppSyncSubscriptionConnection] handleDataEvent(response:): A4638555-54B0-463F-A7BF-31ADD271B65B. Ignoring data event for 656FD38E-226F-449C-97CC-C398DD823A54
[AppSyncSubscriptionConnection] handleDataEvent(response:): 88CD4465-4606-4734-80EE-0A1CBF899B41. Ignoring data event for 656FD38E-226F-449C-97CC-C398DD823A54
[AppSyncSubscriptionConnection] handleDataEvent(response:): 326549DB-73AC-4DCE-A57D-B8D1DD64B0E2. Ignoring data event for 656FD38E-226F-449C-97CC-C398DD823A54
[AppSyncSubscriptionConnection] handleDataEvent(response:): 21491BE1-D24B-4F51-AD62-DEE4E1E89606. Ignoring data event for 656FD38E-226F-449C-97CC-C398DD823A54
[IncomingAsyncSubscriptionEventToAnyModelMapper] The operation couldn’t be completed. (Amplify.GraphQLResponseError<AWSPluginsCore.MutationSync<AWSPluginsCore.AnyModel>> error 1.)
```

### Screenshots

This is the formatted JSON from iOS logs:
```
{
  "id": "18B47289-5B78-4C64-9E8B-64609DD31218",
  "type": "data",
  "payload": {
    "data": {
      "onUpdateOrders": {
        "id": "8336807e-557f-4777-b866-093badffa43e",
        "accepted": "2022-02-21T21:35:20.020Z",
        "completed": null,
        "details": "{\"delivery\":{\"requested\":false},\"details\":[{\"instructions\":null,\"quantity\":1,\"price\":15,\"name\":\"Cortado\",\"description\":\"Cortado Description \",\"tax\":2.25,\"attributes\":[]}]}",
        "placed": "2022-02-21T18:35:03.637477000Z",
        "readied": null,
        "receiptentInfo": "XXX/XXX/XXX",
        "rejected": null,
        "state": "ACCEPTED",
        "subTotal": 15.0,
        "tax": 2.25,
        "total": 17.25,
        "userID": "XXX",
        "branch": null,   <------ this is wrong, branch ID is not null in Amplify Studio or DynamoDB
        "__typename": "Orders",
        "_version": 2,
        "_deleted": null,
        "_lastChangedAt": 1645468522815
      }
    },
    "errors": [
      {
        "message": "Cannot return null for non-nullable type: 'AWSJSON' within parent 'Branch' (/onUpdateOrders/branch/location)",
        "path": [
          "onUpdateOrders",
          "branch",
          "location"
        ]
      },
      {
        "message": "Cannot return null for non-nullable type: 'String' within parent 'Branch' (/onUpdateOrders/branch/name)",
        "path": [
          "onUpdateOrders",
          "branch",
          "name"
        ]
      },
      {
        "message": "Cannot return null for non-nullable type: 'Int' within parent 'Branch' (/onUpdateOrders/branch/_version)",
        "path": [
          "onUpdateOrders",
          "branch",
          "_version"
        ]
      },
      {
        "message": "Cannot return null for non-nullable type: 'AWSTimestamp' within parent 'Branch' (/onUpdateOrders/branch/_lastChangedAt)",
        "path": [
          "onUpdateOrders",
          "branch",
          "_lastChangedAt"
        ]
      }
    ]
  }
}
```

This is the JSON of the DynamoDB item:
```
{
 "id": "8336807e-557f-4777-b866-093badffa43e",
 "__typename": "Orders",
 "completed": null,
 "rejected": null,
 "_lastChangedAt": 1645514767852,
 "receiptentInfo": "XXX/XXX/XXX",
 "ordersBranchId": "b1ccf2cb-e15b-4eaa-9ca9-407ce3226aa5", <---- This is not being translated to 'branch' properly. 
 "tax": 2.25,
 "total": 17.25,
 "createdAt": "2022-02-21T18:35:04.516Z",
 "state": "READY",
 "_version": 3,
 "subTotal": 15,
 "updatedAt": "2022-02-22T07:26:07.833Z",
 "userID": "XXX",
 "readied": "2022-02-22T10:26:07.007Z",
 "placed": "2022-02-21T18:35:03.637477000Z",
 "accepted": "2022-02-21T21:35:20.020Z",
 "details": {
  "delivery": {
   "requested": false
  },
  "details": [
   {
    "instructions": null,
    "quantity": 1,
    "price": 15,
    "name": "Cortado",
    "description": "Cortado Description ",
    "tax": 2.25,
    "attributes": []
   }
  ]
 }
}
```
This is the `Branch` id `b1ccf2cb-e15b-4eaa-9ca9-407ce3226aa5`
```
{
 "id": "b1ccf2cb-e15b-4eaa-9ca9-407ce3226aa5",
 "__typename": "Branch",
 "_lastChangedAt": 1638602786000,
 "location": {
  "lat": 16.34483,
  "long": 10.15325
 },
 "_version": 1,
 "updatedAt": "2021-12-03T07:26:46.728Z",
 "brandID": "ac9f0425-e880-467b-bcf4-c23e4d334e11",
 "createdAt": "2021-12-02T06:42:38.358Z",
 "name": "XXX BRANCH"
}
```

### Platforms

- [X] iOS
- [ ] Android

### Environment

```bash
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2.1 21D62 darwin-x64, locale en-US)
    • Flutter version 2.10.2 at /Users/alrashedf/software/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (3 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/alrashedf/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/alrashedf/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554             • android-x86    • Android 11 (API 30) (emulator)
    • iPhone (mobile)         • 00008030-00061D1E26C0802E • ios            • iOS 15.3.1 19D52
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 98.0.4758.102
    ! Error: Man is busy: Fetching debug symbols for Man. Xcode will continue when Man is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Dependencies

```bash
Dart SDK 2.16.1
Flutter SDK 2.10.2
my_app 1.0.27+27

dependencies:
- amplify_api 0.4.0 [amplify_api_plugin_interface amplify_core collection flutter meta plugin_platform_interface]
- amplify_auth_cognito 0.4.0 [flutter amplify_auth_plugin_interface amplify_core collection plugin_platform_interface]
- amplify_auth_plugin_interface 0.4.0 [flutter meta amplify_core]
- amplify_datastore 0.4.0 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.4.0 [amplify_analytics_plugin_interface amplify_api_plugin_interface amplify_auth_plugin_interface amplify_core amplify_datastore_plugin_interface amplify_storage_plugin_interface collection flutter json_annotation meta plugin_platform_interface]
- animation_wrappers 0.0.5 [flutter]
- awesome_notifications 0.6.21 [flutter platform intl]
- background_locator 1.6.12 [flutter]
- cached_network_image 3.2.0 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- connectivity_plus 2.2.1 [flutter connectivity_plus_platform_interface connectivity_plus_linux connectivity_plus_macos connectivity_plus_web connectivity_plus_windows]
- country_code_picker 2.0.2 [flutter modal_bottom_sheet collection universal_platform]
- cupertino_icons 1.0.4
- equatable 2.0.3 [collection meta]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutter_bloc 7.3.3 [flutter bloc provider]
- flutter_form_builder 6.2.0 [flutter flutter_localizations intl collection]
- flutter_icons 1.1.1-nullsafety.0 [flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path typed_data vector_math]
- flutter_phoenix 1.0.0 [flutter]
- flutter_polyline_points 1.0.0 [flutter http]
- flutter_rating_bar 4.0.0 [flutter]
- geolocator 7.7.1 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web]
- google_fonts 2.3.1 [flutter http path_provider crypto]
- google_maps_flutter 2.1.1 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- http 0.13.4 [async http_parser meta path]
- intl 0.17.0 [clock path]
- introduction_screen 2.1.0 [flutter dots_indicator]
- path_provider 2.0.9 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- percent_indicator 3.4.0 [flutter]
- shared_preferences 2.0.13 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- synchronized 3.0.0
- uuid 3.0.6 [crypto]
- visibility_detector 0.2.2 [flutter]

dev dependencies:
- build_runner 2.1.7 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_launcher_icons 0.9.2 [args image path yaml]
- flutter_lints 1.0.4 [lints]
- flutter_native_splash 1.3.3 [args image meta path xml yaml universal_io]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- _fe_analyzer_shared 34.0.0 [meta]
- amplify_analytics_plugin_interface 0.4.0 [amplify_core flutter meta]
- amplify_api_plugin_interface 0.4.0 [amplify_core collection flutter json_annotation meta]
- amplify_core 0.4.0 [flutter plugin_platform_interface collection date_time_format meta uuid]
- amplify_datastore_plugin_interface 0.4.0 [flutter meta collection amplify_core]
- amplify_storage_plugin_interface 0.4.0 [flutter meta amplify_core]
- analyzer 3.2.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.2.1 [crypto path]
- args 2.3.0
- async 2.8.2 [collection meta]
- bloc 7.2.1 [meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.2.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.1 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.6 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.1.4 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.2.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.5 [meta path]
- clock 1.1.0
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- connectivity_plus_linux 1.3.0 [flutter connectivity_plus_platform_interface meta nm]
- connectivity_plus_macos 1.2.1 [connectivity_plus_platform_interface flutter]
- connectivity_plus_platform_interface 1.2.0 [flutter meta plugin_platform_interface]
- connectivity_plus_web 1.2.0 [connectivity_plus_platform_interface flutter_web_plugins flutter]
- connectivity_plus_windows 1.2.0 [connectivity_plus_platform_interface flutter]
- convert 3.0.1 [typed_data]
- crypto 3.0.1 [collection typed_data]
- dart_style 2.2.1 [analyzer args path pub_semver source_span]
- date_time_format 2.0.1
- dbus 0.7.1 [args ffi meta xml]
- dots_indicator 2.1.0 [flutter]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- fixnum 1.0.0
- flutter_blurhash 0.6.4 [flutter]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_plugin_android_lifecycle 2.0.5 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- frontend_server_client 2.1.2 [async path]
- geolocator_android 2.1.0 [flutter geolocator_platform_interface]
- geolocator_apple 1.2.2 [flutter geolocator_platform_interface]
- geolocator_platform_interface 2.3.6 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.0.6 [flutter flutter_web_plugins geolocator_platform_interface]
- glob 2.0.2 [async collection file path string_scanner]
- google_maps_flutter_platform_interface 2.1.5 [collection flutter plugin_platform_interface stream_transform]
- graphs 2.1.0 [collection]
- http_multi_server 3.2.0 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.1.3 [archive meta xml]
- io 1.0.3 [meta path string_scanner]
- js 0.6.3
- json_annotation 4.4.0 [meta]
- lints 1.0.1
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- mime 1.0.1
- modal_bottom_sheet 2.0.0 [flutter]
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- octo_image 1.0.1 [flutter flutter_blurhash]
- package_config 2.0.2 [path]
- path 1.8.0
- path_provider_android 2.0.11 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.7 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.5 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.5 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.3 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.5 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- petitparser 4.4.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.4 [file path platform]
- provider 6.0.2 [collection flutter nested]
- pub_semver 2.1.0 [collection meta]
- pubspec_parse 1.2.0 [checked_yaml collection json_annotation pub_semver yaml]
- rxdart 0.27.3
- shared_preferences_android 2.0.11 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.0 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.3 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.3 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.2.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.2 [flutter sqflite_common path]
- sqflite_common 2.2.0 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.8 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- universal_io 2.0.4 [collection crypto meta typed_data]
- universal_platform 1.0.0+1
- vector_math 2.1.1
- watcher 1.0.1 [async path]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- win32 2.4.1 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

### Device

iPhones

### OS

iOS 15.3.1

### Additional Context

**Android behavior**
To compare, the Android app logs the following and updates the screen properly:
```
I/flutter ( 5543): subscribeToOrders: Received event of type EventType.update
I/flutter ( 5543): subscribeToOrders: Received order Orders {id=8336807e-557f-4777-b866-093badffa43e, placed=2022-02-21T18:35:03.637477000Z, readied=2022-02-22T10:26:07.007000000Z, completed=null, rejected=null, accepted=2022-02-21T21:35:20.020000000Z, details={"delivery":{"requested":false},"details":[{"instructions":null,"quantity":1,"price":15,"name":"Cortado","description":"Cortado Description ","tax":2.25,"attributes":[]}]}, state=READY, branch=Branch {id=b1ccf2cb-e15b-4eaa-9ca9-407ce3226aa5, brandID=null, name=null, tagline=null, menu=null, arabicMenu=null, location=null}, receiptentInfo=XXX/XXX/XXX, subTotal=15.0, tax=2.25, total=17.25, userID=XXX}
I/amplify:aws-datastore( 5543): Orchestrator lock acquired.
I/amplify:aws-datastore( 5543): Orchestrator lock released.
```

**Comment by dnys1** [comment] 2022-02-23 15:33
@alrashedf - Thank for this extremely detailed issue, I really appreciate it. I will look into finding the root cause.

 Is this a new project, or was this working on previous Amplify Flutter versions (e.g. it was working on 0.2.x or 0.3.x)?

**Comment by dnys1** [comment] 2022-02-23 16:41
There appears to be a discrepancy between the mutation which Amplify Studio is performing and the iOS subscription. The mutation is structured like this:

```graphql
mutation operation($input: CreateOrdersInput!) {
  createOrders(input: $input) {
    id
    placed
    details
    state
    subTotal
    tax
    total
    userID
    createdAt
    updatedAt
    _version
    _lastChangedAt
    _deleted
    branch {
      id
      _deleted
    }
  }
}
```

iOS expects all non-null fields in the `branch` selection set, but Android is able to decode a partial model. I'm working to figure out where the change needs to be made to resolve this. In the meantime, your subscription should work outside Amplify Studio if the full selection set of `branch` is included like this:

```graphql
mutation operation($input: CreateOrdersInput!) {
  createOrders(input: $input) {
    id
    placed
    details
    state
    subTotal
    tax
    total
    userID
    createdAt
    updatedAt
    _version
    _lastChangedAt
    _deleted
    branch {
        id
        brandID
        name
        location
        createdAt
        updatedAt
        _lastChangedAt
        _version
        _deleted
    }
  }
}
```

**Comment by dnys1** [comment] 2022-02-23 17:29
Thanks @HuiSF

**Comment by alrashedf** [comment] 2022-02-23 21:28
> @alrashedf - Thank you for this extremely detailed issue, I really appreciate it. I will look into finding the root cause.
> 
> Is this a new project, or was this working on previous Amplify Flutter versions (e.g. it was working on 0.2.x or 0.3.x)?

I'm not sure. I remember realtime updates were generally working previously. This is the first time updates consistently didn't work (hence the bug report)

**Comment by dnys1** [comment] 2022-02-23 22:00
Thanks, @alrashedf. It sounds like it's a been an issue for a while and that the different teams are investigating it right now. We'll keep this ticket up-to-date with the latest info.

**Comment by HuiSF** [comment] 2022-03-10 18:52
Hi @alrashedf a quick follow up

>the iOS App is receiving an update with branch being null. But in DynamoDB, ordersBranchId is not null

Was the updated triggered by a mutation made by using the `API` category, or `DataStore` category?

**Comment by alrashedf** [comment] 2022-03-11 07:12
> Was the updated triggered by a mutation made by using the `API` category, or `DataStore` category?

It is triggered by calling `Amplify.DataStore.Save()`. So, `DataStore` category.

**Comment by HuiSF** [comment] 2022-05-03 17:48
Closing this issue as a duplicate as it's caused by the same root cause of #663 .

**Closed by HuiSF** 2022-05-03 17:48 UTC
Labels: bug, duplicate, requires-android-fix, requires-ios-fix, DataStore, platform-discrepancy
