### ISSUE TITLE
Error handling Maps as nested Serialized Custom Types in Android

### ISSUE THREAD

**Issue by kryptx** [aws-amplify/amplify-flutter#5457] opened 2024-09-15 22:26 UTC
### Description

During synchronization on Android, my app produces the following error:
```
E/amplify:flutter:datastore( 8093): Received an error
E/amplify:flutter:datastore( 8093): DataStoreException{message=Failed to observe items in storage adapter., cause=java.lang.ClassCastException: java.util.Collections$UnmodifiableMap cannot be cast to com.amplifyframework.core.model.SerializedCustomType, recoverySuggestion=Inspect the failure details.}
E/amplify:flutter:datastore( 8093): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$observe$10(SQLiteStorageAdapter.java:762)
E/amplify:flutter:datastore( 8093): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter$$ExternalSyntheticLambda14.accept(Unknown Source:4)
E/amplify:flutter:datastore( 8093): 	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
E/amplify:flutter:datastore( 8093): 	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
E/amplify:flutter:datastore( 8093): 	at io.reactivex.rxjava3.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:310)
E/amplify:flutter:datastore( 8093): 	at io.reactivex.rxjava3.subjects.PublishSubject.onNext(PublishSubject.java:226)
E/amplify:flutter:datastore( 8093): 	at io.reactivex.rxjava3.subjects.SerializedSubject.onNext(SerializedSubject.java:104)
E/amplify:flutter:datastore( 8093): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.saveInternal(SQLiteStorageAdapter.java:487)
E/amplify:flutter:datastore( 8093): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$batchSyncOperations$3$com-amplifyframework-datastore-storage-sqlite-SQLiteStorageAdapter(SQLiteStorageAdapter.java:339)
E/amplify:flutter:datastore( 8093): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/amplify:flutter:datastore( 8093): 	at com.amplifyframework.datastore.storage.sqlite.SQLCommandProcessor.lambda$runInTransactionAndSucceedOnDatastoreException$0$com-amplifyframework-datastore-storage-sqlite-SQLCommandProcessor(SQLCommandProcessor.java:145)
E/amplify:flutter:datastore( 8093): 	at com.amplifyframework.datastore.storage.sqlite.SQLCommandProcessor$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/amplify:flutter:datastore( 8093): 	at com.amplifyframework.datastore.storage.sqlite.SQLCommandProcessor.runInTransaction(SQLCommandProcessor.java:163)
E/amplify:flutter:datastore( 8093): 	at com.amplifyframework.datastore.storage.sqlite.SQLCommandProcessor.runInTransactionAndSucceedOnDatastoreException(SQLCommandProcessor.java:143)
E/amplify:flutter:datastore( 8093): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$batchSyncOperations$4$com-amplifyframework-datastore-storage-sqlite-SQLiteStorageAdapter(SQLiteStorageAdapter.java:399)
E/amplify:flutter:datastore( 8093): 	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter$$ExternalSyntheticLambda8.run(Unknown Source:8)
E/amplify:flutter:datastore( 8093): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
E/amplify:flutter:datastore( 8093): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
E/amplify:flutter:datastore( 8093): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/amplify:flutter:datastore( 8093): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/amplify:flutter:datastore( 8093): 	at java.lang.Thread.run(Thread.java:1012)
E/amplify:flutter:datastore( 8093): Caused by: java.lang.ClassCastException: java.util.Collections$UnmodifiableMap cannot be cast to com.amplifyframework.core.model.SerializedCustomType
E/amplify:flutter:datastore( 8093): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.parseSerializedDataMap(FlutterSerializedModel.kt:104)
E/amplify:flutter:datastore( 8093): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.<init>(FlutterSerializedModel.kt:15)
E/amplify:flutter:datastore( 8093): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.parseSerializedDataMap(FlutterSerializedModel.kt:60)
E/amplify:flutter:datastore( 8093): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSerializedModel.<init>(FlutterSerializedModel.kt:15)
E/amplify:flutter:datastore( 8093): 	at com.amazonaws.amplify.amplify_datastore.types.model.FlutterSubscriptionEvent.<init>(FlutterSubscriptionEvent.kt:10)
E/amplify:flutter:datastore( 8093): 	at com.amazonaws.amplify.amplify_datastore.AmplifyDataStorePlugin.onSetUpObserve$lambda$26(AmplifyDataStorePlugin.kt:522)
E/amplify:flutter:datastore( 8093): 	at com.amazonaws.amplify.amplify_datastore.AmplifyDataStorePlugin.$r8$lambda$W8b09unHd0AjID_kblCPn89Ob84(Unknown Source:0)
E/amplify:flutter:datastore( 8093): 	at com.amazonaws.amplify.amplify_datastore.AmplifyDataStorePlugin$$ExternalSyntheticLambda2.accept(Unknown Source:4)
E/amplify:flutter:datastore( 8093): 	at com.amplifyframework.datastore.AWSDataStorePlugin.lambda$observe$25(AWSDataStorePlugin.java:549)
E/amplify:flutter:datastore( 8093): 	at com.amplifyframework.datastore.AWSDataStorePlugin$$ExternalSyntheticLambda37.accept(Unknown Source:6)
E/amplify:flutter:datastore( 8093): 	at com.amplifyframework.datastore.storage.sqlite.ObserveQueryExecutor$$ExternalSyntheticLambda1.accept(Unknown Source:4)
E/amplify:flutter:datastore( 8093): 	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
E/amplify:flutter:datastore( 8093): 	... 17 more
```

After this, the DataStore sync process must be restarted or records will not be synchronized.

On iOS, this issue does not occur, however I'm **not** 100% certain that this issue has no impact on iOS. I can confirm only that I'm unable to reproduce the error log output and sync stopping except on Android.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce
In my app, the error occurs when a `FlightSearch` is deleted in the app, or when a `FlightSearchResult` is received from the platform (they are created with IAM, and the app receives them via synchronization).

1. Create a FlightItineraryOffer containing at least 1 trip leg with at least 1 flight record
1. Create a FlightSearch owned by the OIDC user
1. Create a FlightSearchResult associating the two records, owned by the OIDC user
1. Synchronize the data to the app

I've dug into this stack trace and found that we seem to be receiving a `Map` when we use a certain data structure in our schema. I believe it is when we define a property as containing an array of objects, and those objects are not themselves "models" (annotated with `@model`). In the schema, this property is `tripLegs`.

Additionally, I've created a draft PR in my own space that resolves this issue for me locally. I have little confidence that this is how you would want the problem solved, but hopefully this will make clear what part of the logic is failing for me: https://github.com/kryptx/amplify-flutter/pull/1/files

I'm willing to take this PR further if you confirm you would accept it (once tests are included along with any other contributing guidelines), but my goal with it was just to prove and clearly illustrate the problem I'm having.

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.22.0

### Amplify Flutter Version

3.4.1

### Deployment Method

Amplify Gen 2

### Schema

```GraphQL
enum CabinType {
  MAIN,
  BUSINESS,
  FIRST
}

enum FlexibilityType {
  NONE,
  DATE,
  AIRPORT
}

enum SearchMode {
  ROUND_TRIP,
  ONE_WAY
}

enum SearchStatus {
  QUEUED,
  IN_PROGRESS,
  COMPLETED,
  ERROR
}

type FlightSearch @model @auth(rules: [
  { allow: owner, provider: oidc, identityClaim: "sub" }
  { allow: private, provider: iam, operations: [read, update]}
]){
  id: ID!
  airportSequence: [String!]!
  departureDates: [String!]!
  cabinTypes: [CabinType!]!
  passengerCount: Int!
  flexibilityType: FlexibilityType!
  status: SearchStatus!
  results: [FlightSearchResult] @hasMany(indexName: "bySearch", fields: ["id"])
}

type Flight {
  departureDate: AWSDateTime!
  arrivalDate: AWSDateTime!
  departureAirport: String!
  arrivalAirport: String!
  cabinType: CabinType!
  flightNumber: String!
  carrierCode: String!
  operatorNumber: String!
  operatorCode: String!
  duration: String!
  distanceMiles: Int!
  aircraftType: String!
}

type TripLeg {
  flights: [Flight!]!
}

type FlightPrice {
  points: Int!
  cash: Float!
  currency: String!
}

type FlightItineraryOffer @model @auth(rules: [
  { allow: private, provider: oidc, identityClaim: "sub", operations: [read]},
  { allow: private, provider: iam, operations: [create, read, update, delete]}
]) {
  id: ID!
  searchMode: SearchMode!
  airline: String!
  cost: FlightPrice!
  departureDate: AWSDateTime!
  returnDate: AWSDateTime
  tripLegs: [TripLeg!]!
  duration: String!
  availableSeats: Int!
  searchKey: String! @index(name: "bySearchKey", sortKeyFields: ["offerKey"])
  offerKey: String!
  searchResults: [FlightSearchResult] @hasMany(indexName: "byOffer", fields: ["id"])
}

type FlightSearchResult @model @auth(rules: [
  { allow: owner, provider: oidc, identityClaim: "sub" },
  { allow: private, provider: iam, operations: [create, read, update, delete]}
]) {
  id: ID!
  searchId: ID! @index(name: "bySearch")
  search: FlightSearch! @belongsTo(fields: ["searchId"])
  offerId: ID! @index(name: "byOffer")
  offer: FlightItineraryOffer! @belongsTo(fields: ["offerId"])
  owner: String!
  legIndex: Int
}
```

**Comment by Equartey** [comment] 2024-09-16 14:52
Hi @kryptx, thank you for taking the time to open this issue. 

We'll need to take some time to reproduce the error to verify if your change is valid. 

We will provide updates here when we have them.

**Comment by kryptx** [comment] 2024-09-20 03:57
To follow up, I made the following changes in my project:

* removed the many-to-many association table (I'm now only using sync expressions)
* updated to the latest flutter
* fixed a bug (I had two separate `DataStorePluginInterface` instances, and was treating them as one)

Since those changes, I don't have this problem anymore, on version 2.4.1, flutter 3.24.3. I'm comfortable if you want to close this, in the absence of somebody else having the same problem.

**Comment by khatruong2009** [comment] 2024-09-23 21:51
@kryptx do you know which of those changes in your project fixed the issue for you or did you make all those changes around the same time and it seemed to fix on its own?

**Comment by kryptx** [comment] 2024-09-23 23:11
Hi @khatruong2009, thanks for your reply.

Unfortunately I had set this issue aside and proceeded with development using my forked plugin, and also mostly testing on iOS. I have however tested downgrading to flutter 3.22.0 and confirmed that I'm still unable to reproduce the issue. My app does also still have a `@belongsTo`/ `@hasMany` association. So it's either specific to the many-to-many association table, or self-inflicted somehow. I'd note though that even if I had a bug, it was still definitely working on iOS.

**Comment by khatruong2009** [comment] 2024-09-24 16:40
Hi @kryptx, since you're not having the issue anymore, I'll close it for now. If you, or anyone else, has this issue or another one, please feel free to reopen this issue or create a new one, thanks.

**Closed by khatruong2009** 2024-09-24 16:40 UTC
Labels: to-be-reproduced, datastore, pending-triage, pending-maintainer-response
