### ISSUE TITLE
iOS Simulator Fails on Startup

### ISSUE THREAD

**Issue by ianfmc** [aws-amplify/amplify-flutter#2108] opened 2022-09-09 21:58 UTC
### Description

On startup, the iOS simulator fails with the error: 

```
Launching lib/main.dart on iPhone 12 in debug mode...
Running Xcode build...
Xcode build done.                                           19.8s
Debug service listening on ws://127.0.0.1:49189/gfJ0j2P_-ZY=/ws
Syncing files to device iPhone 12...
Amplify/ModelPrimaryKey.swift:60: Fatal error: Primary key field named (id) not found in schema fields.
Lost connection to device.
```

This error occurs for all emulated iOS devices

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [X] DataStore
- [X] Storage

### Steps to Reproduce

1. Select iOS device (in this case iPhone 12)
2. Tap 'Run' or 'Debug'
3. Startup fails with above error

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Android Device/Emulator API Level

API 32+

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.5.1 21G83 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.71.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
[peter:~/Development/elys_mobile/ios] ianmccal% flutter doctor -v
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.5.1 21G83 darwin-x64, locale en-US)
    • Flutter version 3.0.3 at /Users/ianmccal/Development/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (3 months ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/ianmccal/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
[peter:~/Development/elys_mobile/ios] ianmccal%
```

### Dependencies

```bash
[peter:~/Development/elys_mobile] ianmccal% flutter pub deps --no-dev --style=compact
Dart SDK 2.17.5
Flutter SDK 3.0.3
elys_mobile 1.0.002+73

dependencies:
- amplify_api 0.6.6 [amplify_api_android amplify_api_ios amplify_core amplify_flutter aws_common collection flutter meta plugin_platform_interface]
- amplify_auth_cognito 0.6.6 [amplify_auth_cognito_android amplify_auth_cognito_ios amplify_core aws_common collection flutter meta plugin_platform_interface]
- amplify_core 0.6.6 [aws_common collection flutter intl json_annotation meta plugin_platform_interface uuid]
- amplify_datastore 0.6.6 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.6.6 [amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios aws_common collection flutter meta plugin_platform_interface]
- amplify_storage_s3 0.6.6 [amplify_storage_s3_android amplify_storage_s3_ios amplify_core aws_common flutter meta plugin_platform_interface]
- camera 0.10.0+1 [camera_android camera_avfoundation camera_platform_interface camera_web flutter flutter_plugin_android_lifecycle quiver]
- cupertino_icons 1.0.5
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_libphonenumber 1.2.4 [flutter]
- flutter_slidable 2.0.0 [flutter]
- flutter_spinkit 5.1.0 [flutter]
- google_fonts 3.0.1 [flutter http path_provider crypto]
- image_picker 0.8.5+3 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
- intl 0.17.0 [clock path]
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- permission_handler 10.0.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- sentry_flutter 6.9.1 [flutter flutter_web_plugins sentry package_info_plus meta]
- url_launcher 6.1.5 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- video_player 2.4.7 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]

transitive dependencies:
- amplify_api_android 0.6.6 [flutter]
- amplify_api_ios 0.6.6 [amplify_core flutter]
- amplify_auth_cognito_android 0.6.6 [flutter]
- amplify_auth_cognito_ios 0.6.6 [amplify_core flutter]
- amplify_datastore_plugin_interface 0.6.6 [amplify_core collection flutter meta]
- amplify_flutter_android 0.6.6 [flutter]
- amplify_flutter_ios 0.6.6 [amplify_core flutter]
- amplify_storage_s3_android 0.6.6 [flutter]
- amplify_storage_s3_ios 0.6.6 [flutter]
- async 2.8.2 [collection meta]
- aws_common 0.1.1 [async collection http meta stream_transform uuid]
- camera_android 0.10.0+2 [camera_platform_interface flutter flutter_plugin_android_lifecycle stream_transform]
- camera_avfoundation 0.9.8+5 [camera_platform_interface flutter stream_transform]
- camera_platform_interface 2.2.0 [cross_file flutter plugin_platform_interface stream_transform]
- camera_web 0.3.0 [camera_platform_interface flutter flutter_web_plugins stream_transform]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.16.0
- cross_file 0.3.3+1 [js meta]
- crypto 3.0.2 [typed_data]
- csslib 0.17.2 [source_span]
- ffi 2.0.1
- file 6.1.4 [meta path]
- flutter_plugin_android_lifecycle 2.0.7 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- html 0.15.0 [csslib source_span]
- http 0.13.5 [async http_parser meta path]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- image_picker_android 0.8.5+2 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.8 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.6 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.6.1 [cross_file flutter http plugin_platform_interface]
- js 0.6.4
- json_annotation 4.6.0 [meta]
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- package_info_plus 1.4.3+1 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- package_info_plus_linux 1.0.5 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.5 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 2.1.0 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.1
- path_provider_android 2.0.20 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.3 [ffi flutter path path_provider_platform_interface win32]
- permission_handler_android 10.0.0 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.0.4 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.0 [flutter permission_handler_platform_interface]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- quiver 3.1.0 [matcher]
- sentry 6.9.1 [http meta stack_trace uuid]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- typed_data 1.3.1 [collection]
- url_launcher_android 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.0 [flutter plugin_platform_interface]
- url_launcher_web 2.0.13 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
- video_player_android 2.3.9 [flutter video_player_platform_interface]
- video_player_avfoundation 2.3.5 [flutter video_player_platform_interface]
- video_player_platform_interface 5.1.4 [flutter plugin_platform_interface]
- video_player_web 2.0.12 [flutter flutter_web_plugins video_player_platform_interface]
- win32 3.0.0 [ffi]
- xdg_directories 0.2.0+2 [meta path process]
[peter:~/Development/elys_mobile] ianmccal%
```

### Device

all iOS Devices

### OS

iOS 14.5

### Deployment Method

Amplify CLI

### CLI Version

9.0.0

### Additional Context

This emulation worked as of 3 September.

### Amplify Config

please be more specific -- I am unsure what is needed here.

**Comment by ianfmc** [comment] 2022-09-12 19:43
Hi Hui! I did upgrade, and performed a flutter clean, too.

**Comment by HuiSF** [comment] 2022-09-12 21:49
Hi @ianfmc can you provide your model schema? I will try to repro locally.
Also can you paste the content of the `cli.json` (Located in `<your-project>/amplify/`).

**Comment by ianfmc** [comment] 2022-09-12 22:27
```
type Account @model @auth(rules: [{allow: owner}, {allow: groups, groups: ["Admin"]}]) @key(name: "byUserName", fields: ["userName"], queryField: "accountByUserName") {
  id: ID!
  userName: String!
  userEmail: String
  userPhone: String
  executorName: String! 
  executorEmail: String
  executorId: String 
  customerId: String!
  subscriptionId: String
  customerStatus: String
  subscriptionLeve: String
}

type Content @model @auth(rules: [{allow: owner}]) {
  id: ID!
  description: String!
  name: String!
  type: String!
  bucket: String!
  region: String!
  key: String!
}

type Event @model @auth(rules: [{allow: owner}, {allow: groups, groups: ["Admin"]}]) {
  id: ID!
  contactEmail: String!
  contactId: ID
  ownerName: ID
  contentId: ID!
  name: String!
  eventDate: String!
  eventMonth: String!
  eventYear: String!
  description: String
  sent: Boolean
}

type SpecialEvent @model @auth(rules: [{allow: owner}, {allow: groups, groups: ["Admin"]}]) {
  id: ID!
  bucket: String
  region: String
  fileKey: String
  ownEmail: String
  ownPhone: String
  emergencyName: String
  emergencyNumber: String
  timeSubmitted: String
  timeZone: String
  warned48: Boolean
  warned24: Boolean
  warned: Boolean
  sent: Boolean
}

enum GroupNames {
  Family, 
  Friends, 
  Other
}

type Contact @model @auth(rules: [{allow: owner}]) @key(fields: ["email"], name: "contactByEmail", queryField: "contactByEmail") {
  id: ID!
  name: String!
  email: String!
  relationship: String
  community: String
}

type StripeSubscription {
  subscriptionId: String
  clientSecret: String
}

type StripeInvoices {
  date: String!
  amount_paid: String!
  invoice_number: String!
}

type Mutation {
  cancelSubscription(subscriptionId: String!): String @function(name: "cancelSubscription-${env}")
  changeSubscription(subscriptionId: String!, newPriceId: String!): String @function(name: "changeSubscription-${env}")
  createCustomer(email: String!): String @function(name: "createCustomer-${env}")
  createSubscription(customerId: String!, paymentMethodId: String!, couponId: String, priceId: String!): StripeSubscription @function(name: "createSubscription-${env}")
  deleteCustomer(customerId: String!): String @function(name: "deleteCustomer-${env}")
  getCurrentPrice(subscriptionId: String): String @function(name: "getCurrentPrice-${env}")
  getInvoices(customerId: String): [StripeInvoices]! @function(name: "getInvoices-${env}")
  getNextInvoice(customerId: String): StripeInvoices! @function(name: "getNextInvoice-${env}")
  getSubscriptionStatus(customerId: String!): String @function(name: "getSubscriptionStatus-${env}")
  newCard(customerId: String!, paymentMethodId: String!): String @function(name: "newCard-${env}")
  sendDesigneeEmail(toAddresses: [String]!, designeeName: String!, clientName: String!): String @function(name: "sendDesigneeEmail-${env}")
  sendSpecialEventText(emergencyName: String!, emergencyNumber: String!): String @function(name: "sendSpecialEventText-${env}")
}
```

**Comment by HuiSF** [comment] 2022-09-13 21:32
Thanks @ianfmc I noticed that you are still using GraphQL transformer v1 syntax, e.g. using `@key` directive to create index. I'm not sure if that may cause something wrong for the new custom primary key implementation in amplify-ios. I need to test. (hopefully on Wed)

Any specific reason that you have to stay with Transformer v1 instead of [migrating to Transformer v2](https://docs.amplify.aws/cli/migration/transformer-migration/)?

**Comment by ianfmc** [comment] 2022-09-13 22:15
No trouble! I am using Transformer v1 because I am trying to Go-Live (date was actually 11 September) and didn't want to change what had been tested (completely). I guess I can change the directives to see if that helps. Would you suggest that, or wait until you are finished testing?

**Comment by ianfmc** [comment] 2022-09-13 22:19
TBH, I was also unaware of the change!

**Comment by ianfmc** [comment] 2022-09-13 23:19
Hi @HuiSF: I am just wondering -- if I push these changes this it will create new tables, correct? I have some Step Functions that use the tables (and so the names are embedded). Please LMK. Thanks...Ian.

**Comment by HuiSF** [comment] 2022-09-13 23:39
Hi @ianfmc per my understanding, the migration should still use the same data source meaning it won't create new tables unless you change model names.

It's great to be precautious about migration. I'd recommend you test out the migration in a different environment before applying to your production environment. [This document](https://docs.amplify.aws/cli/migration/transformer-migration/) really explains the steps well.

**Comment by ianfmc** [comment] 2022-09-14 01:08
Haha. I just did (:

I can validate that it does not change the tables! 

I'm working on updating the v2 environment to my mobile application to see what happens. I will report soon.

**Comment by ianfmc** [comment] 2022-09-14 17:56
Unfortunately, after I converted the schema to be compatible with the v2 Transformer, there is no change (same error exactly). The new schema is below. Please advise (our Go-Live is waiting on this one issue :)

```
type Account @model @auth(rules: [{allow: owner}, {allow: groups, groups: ["Admin"]}]) {
  id: ID!
  userName: String! @index(name: "byUserName", queryField: "accountByUserName")
  userEmail: String
  userPhone: String
  executorName: String!
  executorEmail: String
  executorId: String
  customerId: String!
  subscriptionId: String
  customerStatus: String
  subscriptionLeve: String
}

type Content @model @auth(rules: [{allow: owner}]) {
  id: ID!
  description: String!
  name: String!
  type: String!
  bucket: String!
  region: String!
  key: String!
}

type Event @model @auth(rules: [{allow: owner}, {allow: groups, groups: ["Admin"]}]) {
  id: ID!
  contactEmail: String!
  contactId: ID
  ownerName: ID
  contentId: ID!
  name: String!
  eventDate: String!
  eventMonth: String!
  eventYear: String!
  description: String
  sent: Boolean
}

type SpecialEvent @model @auth(rules: [{allow: owner}, {allow: groups, groups: ["Admin"]}]) {
  id: ID!
  bucket: String
  region: String
  fileKey: String
  ownEmail: String
  ownPhone: String
  emergencyName: String
  emergencyNumber: String
  timeSubmitted: String
  timeZone: String
  warned48: Boolean
  warned24: Boolean
  warned: Boolean
  sent: Boolean
}

enum GroupNames {
  Family
  Friends
  Other
}

type Contact @model @auth(rules: [{allow: owner}]) {
  id: ID!
  name: String!
  email: String! @index(name: "contactByEmail", queryField: "contactByEmail")
  relationship: String
  community: String
}

type StripeSubscription {
  subscriptionId: String
  clientSecret: String
}

type StripeInvoices {
  date: String!
  amount_paid: String!
  invoice_number: String!
}

type Mutation {
  cancelSubscription(subscriptionId: String!): String @function(name: "cancelSubscription-${env}")
  changeSubscription(subscriptionId: String!, newPriceId: String!): String @function(name: "changeSubscription-${env}")
  createCustomer(email: String!): String @function(name: "createCustomer-${env}")
  createSubscription(customerId: String!, paymentMethodId: String!, couponId: String, priceId: String!): StripeSubscription @function(name: "createSubscription-${env}")
  deleteCustomer(customerId: String!): String @function(name: "deleteCustomer-${env}")
  getCurrentPrice(subscriptionId: String): String @function(name: "getCurrentPrice-${env}")
  getInvoices(customerId: String): [StripeInvoices]! @function(name: "getInvoices-${env}")
  getNextInvoice(customerId: String): StripeInvoices! @function(name: "getNextInvoice-${env}")
  getSubscriptionStatus(customerId: String!): String @function(name: "getSubscriptionStatus-${env}")
  newCard(customerId: String!, paymentMethodId: String!): String @function(name: "newCard-${env}")
  sendDesigneeEmail(toAddresses: [String]!, designeeName: String!, clientName: String!): String @function(name: "sendDesigneeEmail-${env}")
  sendSpecialEventText(emergencyName: String!, emergencyNumber: String!): String @function(name: "sendSpecialEventText-${env}")
}
```

**Comment by ianfmc** [comment] 2022-09-15 00:55
How did the testing go @HuiSF?

**Comment by ianfmc** [comment] 2022-09-16 15:26
[bump] Hi @HuiSF: do you need anything from me?

**Comment by ianfmc** [comment] 2022-09-18 20:35
Hello @HuiSF: I updated to 0.6.7 **but the result is the same error**.

**Comment by ianfmc** [comment] 2022-09-18 20:36
BTW: here is the cli.json

```
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": true,
      "enableiterativegsiupdates": true,
      "securityEnhancementNotification": false,
      "showfieldauthnotification": false,
      "transformerversion": 2,
      "suppressschemamigrationprompt": true
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "enableDartNullSafety": true
    },
    "project": {
      "overrides": true
    }
  },
  "debug": {
    "shareProjectConfig": false
  }
}
```

**Comment by Crhis35** [comment] 2022-09-18 23:59
Same issue here

**Comment by HuiSF** [comment] 2022-09-19 16:15
Hello @Crhis35 are you using transformer v1 schema as well?

**Comment by HuiSF** [comment] 2022-09-19 16:19
> BTW: here is the cli.json
> 
> ```
> {
>   "features": {
>     "graphqltransformer": {
>       "addmissingownerfields": true,
>       "validatetypenamereservedwords": true,
>       "useexperimentalpipelinedtransformer": true,
>       "enableiterativegsiupdates": true,
>       "securityEnhancementNotification": false,
>       "showfieldauthnotification": false,
>       "transformerversion": 2,
>       "suppressschemamigrationprompt": true
>     },
>     "frontend-ios": {
>       "enablexcodeintegration": true
>     },
>     "auth": {
>       "enablecaseinsensitivity": true
>     },
>     "codegen": {
>       "useappsyncmodelgenplugin": true,
>       "enableDartNullSafety": true
>     },
>     "project": {
>       "overrides": true
>     }
>   },
>   "debug": {
>     "shareProjectConfig": false
>   }
> }
> ```

Hi @ianfmc have you migrated to transformer v2? Looking at your `cli.json` that you are on transformer v2, as `"transformerversion": 2` and `"useexperimentalpipelinedtransformer": true`. If so the issue persists for you?

**Comment by HuiSF** [comment] 2022-09-19 17:01
I think I found the cause, fixing.

**Comment by ianfmc** [comment] 2022-09-19 17:11
So awesome...standing by.

**Comment by ianfmc** [comment] 2022-09-19 17:18
Hi @HuiSF: should I take a look at that incident?

**Comment by HuiSF** [comment] 2022-09-19 17:50
Hi @ianfmc you mean testing out the PR? That'd be helpful!

You should be able to use git url to get the fix from the PR. e.g. in `pubspec.yaml`

```yaml
  amplify_datastore:
    git:
      url: https://github.com/HuiSF/amplify-flutter.git
      ref: fix/cpk-custom-type
      path: packages/amplify_datastore
```

**Comment by ianfmc** [comment] 2022-09-19 17:54
Yes: I am using transformer v2, and the issue persists.

**Comment by ianfmc** [comment] 2022-09-19 18:38
Hi @HuiSF: not sure what a PR is (: I'm happy to try out the update. I am not sure how to add the line you suggest. Do I substitute what you've written for the line in current pubspec.yaml?

**Comment by ianfmc** [comment] 2022-09-19 19:22
Hi @HuiSF: here's what happened

```
[peter:~/Development/elys_mobile/ios] ianmccal% flutter pub get
Because every version of amplify_datastore from git depends on amplify_core 0.6.4-rc.1 and elys_mobile depends on amplify_core ^0.6.7, amplify_datastore from git is forbidden.
So, because elys_mobile depends on amplify_datastore from git, version solving failed.
Running "flutter pub get" in elys_mobile...                             
pub get failed (1; So, because elys_mobile depends on amplify_datastore from git, version solving failed.)
[peter:~/Development/elys_mobile/ios] ianmccal% 
```

**Comment by HuiSF** [comment] 2022-09-19 19:32
To clarify this issue is caused by a recent change for supporting custom primary key, with which the logic tries to parse primary key information from a `CustomType`, but a `CustomType` doesn't have a primary key. 

@ianfmc yea I think need to replace all dependencies with git resource, you can ignore it for now. The fix will be released soon. Thanks!

**Comment by ianfmc** [comment] 2022-09-19 19:36
ok! please let me know (or will it be obvious on pub.dev)?

**Comment by HuiSF** [comment] 2022-09-19 21:18
Hello @ianfmc [amplify-flutter 0.6.8](https://github.com/aws-amplify/amplify-flutter/releases/tag/v0.6.8) has been release, please upgrade and test with your App. The issue should've been fixed. Please feel free to follow up if anything. Thanks again for reporting this issue.

**Comment by ianfmc** [comment] 2022-09-19 22:52
Worked. TY @HuiSF

**Comment by Crhis35** [comment] 2022-09-19 23:46
For me too Thanks!

**Comment by HuiSF** [comment] 2022-09-20 00:20
Issue has been fixed. :)

**Closed by HuiSF** 2022-09-20 00:20 UTC
Labels: bug, pending-close-response-required, DataStore
