### ISSUE TITLE
 S3 Upload Fails with "S3 access denied when making the API call"  (V2.1.0 with Amplify Gen 2)

### ISSUE THREAD

**Issue by pepie** [aws-amplify/amplify-flutter#5065] opened 2024-06-25 03:23 UTC
### Description

Hello! I'm unable to upload to S3 with ampllify_storage_s3 v2.1.0 + Amplify Gen2.
This happens for guest and authenticated users, public or secured buckets.

Error:
"S3 access denied when making the API call"

```yaml
// Libraries
amplify_api: *amplify_version
amplify_authenticator: ^2.0.1
amplify_auth_cognito: *amplify_version
amplify_datastore: *amplify_version
amplify_flutter: *amplify_version
amplify_storage_s3: *amplify_version
```

Tutorial Reference:
https://docs.amplify.aws/flutter/build-a-backend/storage/upload-files/

```ts
// backend.ts
const backend = defineBackend({ auth, data, storage });

// data/resources.ts
export const data = defineData({
  schema,
  authorizationModes: {
    defaultAuthorizationMode: "iam",
    apiKeyAuthorizationMode: { expiresInDays: 7 },
  },
});


// storage/resource.ts
export const storage = defineStorage({
  name: "mediafiles",
  access: (allow) => ({
    "media/public/{entity_id}/": [
      allow.guest.to(["read]"]),
      allow.entity("identity").to(["read", "write", "delete"]),
      allow.groups(["Admins"]).to(["read", "write", "delete"]),
    ],
    "media/protected/{entity_id}/": [
      allow.authenticated.to(["read"]),
      allow.entity("identity").to(["read", "write", "delete"]),
    ],
    "media/private/{entity_id}/*": [
      allow.entity("identity").to(["read", "write", "delete"]),
    ],
  }),
});

```

```dart
// upload methods

final result = await Amplify.Storage.uploadFile(
  localFile: AWSFile.fromStream( imageFile.openRead(), size: 0 ),
  path: StoragePath.fromString("media/public/test.jpg",
  options: options,
  onProgress: onProgress ?? (progress) {
    safePrint('upload progress ${progress.fractionCompleted}');
  },
).result;
```

Please review.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Steps to Reproduce

1. Follow guide https://docs.amplify.aws/flutter/build-a-backend/storage/upload-files/
2. Use amplify_storage_v2 here https://pub.dev/packages/amplify_storage_s3
3. Use libraries
  amplify_api: 2.1.0
  amplify_authenticator: ^2.0.1
  amplify_auth_cognito: 2.10
  amplify_datastore: 2.10
  amplify_flutter: 2.10
  amplify_storage_s3: 2.10

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.22.2

### Amplify Flutter Version

2.1.0

### Deployment Method

Amplify CLI

### Schema

```ts
export const storage = defineStorage({
  name: 'gallery',
  access: (allow) => ({
      'media/public/*': [
         allow.guest.to( ['read'] ),
         allow.entity('identity').to(['read', 'write', 'delete']),
      ],
  }),
});
```

**Comment by Jordan-Nelson** [comment] 2024-06-25 14:28
Hello @pepie - Your storage backend allows identities to write to `media/public/*`, but there is no identityId in the path. Paths that have access set for an identity should have an identity Id in the path. You can see an example of this under the "Owners" tab here:  https://docs.amplify.aws/flutter/build-a-backend/storage/authorization/#access-definition-rules

One option is to update the backend to the following:

```ts
export const storage = defineStorage({
  name: 'gallery',
  access: (allow) => ({
      'media/public/{entity_id}/*': [
         allow.guest.to( ['read'] ),
         allow.entity('identity').to(['read', 'write', 'delete']),
      ],
  }),
});
```

And then update the upload function to the following.

```dart
final result = await Amplify.Storage.uploadFile(
  localFile: AWSFile.fromStream( imageFile.openRead(), size: 0 ),
  path: StoragePath.fromIdentityId((id) => "media/public/$id/test.jpg"),
  options: options,
  onProgress: onProgress ?? (progress) {
    safePrint('upload progress ${progress.fractionCompleted}');
  },
).result;
```

Let me know if you have other questions.

**Comment by pepie** [comment] 2024-06-25 23:46
Thanks @Jordan-Nelson , 

That's what my actual code looks like. I simplified it for the sake of the ticket, because I get the same error regardless of my configuration. Upload fails for both authenticated and non-authenticated users.

I even called Amplify.Auth.getCurrentUser() right before the upload function, to make sure the user was still logged in.

Here's the full code:

//(backend): amplify/storage/resource.ts

export const storage = defineStorage({
  name: 'gallery',
  access: (allow) => ({
      'media/public/{entity_id}/*': [
         allow.guest.to( ['read'] ),
         allow.entity('identity').to(['read', 'write', 'delete']),
         allow.groups(['Admins','Staff','SystemAdmins']).to( ['read','write','delete'] )
      ],
      'media/protected/{entity_id}/*': [
         allow.authenticated.to(['read']),
         allow.entity('identity').to(['read', 'write', 'delete']),
         allow.groups(['Admins','Staff','SystemAdmins']).to( ['read','write','delete'] )
      ],
      'media/private/{entity_id}/*': [
         allow.entity('identity').to(['read', 'write', 'delete']),
         allow.groups(['Admins','Staff','SystemAdmins']).to( ['read','write','delete'] )
     ]
  }),
});


// calling function

AuthUser authUser = await Amplify.Auth.getCurrentUser();  // TESTING ONLY - Just to double check user is still signed-in. 
print(authUser); //this works - so the user credentials is not the issue


final result = await Amplify.Storage.uploadFile(
            localFile: AWSFile.fromStream( imageFile.openRead(), size: 0 ),
            path: StoragePath.fromIdentityId( (id)=> "media/public/${id}/test.jpg"),
            options: options,
            onProgress: onProgress ?? (progress) {
               safePrint('upload progress ${progress.fractionCompleted}');
             },
).result;

**Comment by Jordan-Nelson** [comment] 2024-06-26 15:22
@pepie I am not able to reproduce that behavior. I have created a storage backend with your definition above and used the code snippet you are using to upload the file and the file uploads successfully. Below are the full details for my app.

Backend defintion
<details>

```ts
// backend.ts
import { defineBackend } from "@aws-amplify/backend";
import { auth } from "./auth/resource";
import { storage } from "./storage/resource";

defineBackend({
  auth,
  storage,
});

// amplify/auth/resource.ts
import { defineAuth } from "@aws-amplify/backend";

export const auth = defineAuth({
  loginWith: {
    email: true,
  },
  groups: ["Admins", "Staff", "SystemAdmins"],
});

// amplify/storage/resource.ts
import { defineStorage } from "@aws-amplify/backend";

export const storage = defineStorage({
  name: "gallery",
  access: (allow) => ({
    "media/public/{entity_id}/*": [
      allow.guest.to(["read"]),
      allow.entity("identity").to(["read", "write", "delete"]),
      allow
        .groups(["Admins", "Staff", "SystemAdmins"])
        .to(["read", "write", "delete"]),
    ],
    "media/protected/{entity_id}/*": [
      allow.authenticated.to(["read"]),
      allow.entity("identity").to(["read", "write", "delete"]),
      allow
        .groups(["Admins", "Staff", "SystemAdmins"])
        .to(["read", "write", "delete"]),
    ],
    "media/private/{entity_id}/*": [
      allow.entity("identity").to(["read", "write", "delete"]),
      allow
        .groups(["Admins", "Staff", "SystemAdmins"])
        .to(["read", "write", "delete"]),
    ],
  }),
});
```

</details>

Flutter app code

<details>

```dart
import 'package:amplify_auth_cognito/amplify_auth_cognito.dart';
import 'package:amplify_authenticator/amplify_authenticator.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:amplify_storage_s3/amplify_storage_s3.dart';
import 'package:flutter/material.dart';

import 'amplifyconfiguration.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
    _configureAmplify();
  }

  void _configureAmplify() async {
    try {
      await Amplify.addPlugin(AmplifyAuthCognito());
      await Amplify.addPlugin(AmplifyStorageS3());
      await Amplify.configure(amplifyConfig);
      safePrint('Successfully configured');
    } on Exception catch (e) {
      safePrint('Error configuring Amplify: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Authenticator(
      child: MaterialApp(
        builder: Authenticator.builder(),
        home: Scaffold(
          appBar: AppBar(),
          body: Center(
            child: Column(
              children: [
                ElevatedButton(
                  onPressed: () async {
                    AuthUser authUser = await Amplify.Auth.getCurrentUser();
                    safePrint(authUser);
                    final result = await Amplify.Storage.uploadFile(
                      localFile: AWSFile.fromStream(
                        Stream.value([1, 2, 3]),
                        size: 3,
                      ),
                      path: StoragePath.fromIdentityId(
                        (id) => "media/public/$id/test.jpg",
                      ),
                      onProgress: (progress) {
                        safePrint(
                          'upload progress ${progress.fractionCompleted}',
                        );
                      },
                    ).result;
                    safePrint(result.uploadedItem);
                  },
                  child: const Text('Upload'),
                ),
                const SignOutButton()
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

Can you share the IAM policy definition for your Authenticated role on your S3 bucket? It should look similar to the one below. You can find it my navigating to IAM -> Roles in the AWS Console and then searching for your app name. There will be several roles listed. The one you should look at is for authenticated users and will be named something like "<app_name>-amplifyAuthenticated-<id>". Once you find that you can click on the link and then click on the link for the first permissions policy listed.

```json
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Action": "s3:GetObject",
			"Resource": [
				"arn:aws:s3:::<app_name>/media/public/${cognito-identity.amazonaws.com:sub}/*",
				"arn:aws:s3:::<app_name>/media/protected/*/*",
				"arn:aws:s3:::<app_name>/media/protected/${cognito-identity.amazonaws.com:sub}/*",
				"arn:aws:s3:::<app_name>/media/private/${cognito-identity.amazonaws.com:sub}/*"
			],
			"Effect": "Allow"
		},
		{
			"Condition": {
				"StringLike": {
					"s3:prefix": [
						"media/public/${cognito-identity.amazonaws.com:sub}/*",
						"media/public/${cognito-identity.amazonaws.com:sub}/",
						"media/protected/*/*",
						"media/protected/*/",
						"media/protected/${cognito-identity.amazonaws.com:sub}/*",
						"media/protected/${cognito-identity.amazonaws.com:sub}/",
						"media/private/${cognito-identity.amazonaws.com:sub}/*",
						"media/private/${cognito-identity.amazonaws.com:sub}/"
					]
				}
			},
			"Action": "s3:ListBucket",
			"Resource": "arn:aws:s3:::<app_name>",
			"Effect": "Allow"
		},
		{
			"Action": "s3:PutObject",
			"Resource": [
				"arn:aws:s3:::<app_name>/media/public/${cognito-identity.amazonaws.com:sub}/*",
				"arn:aws:s3:::<app_name>/media/protected/${cognito-identity.amazonaws.com:sub}/*",
				"arn:aws:s3:::<app_name>/media/private/${cognito-identity.amazonaws.com:sub}/*"
			],
			"Effect": "Allow"
		},
		{
			"Action": "s3:DeleteObject",
			"Resource": [
				"arn:aws:s3:::<app_name>/media/public/${cognito-identity.amazonaws.com:sub}/*",
				"arn:aws:s3:::<app_name>/media/protected/${cognito-identity.amazonaws.com:sub}/*",
				"arn:aws:s3:::<app_name>/media/private/${cognito-identity.amazonaws.com:sub}/*"
			],
			"Effect": "Allow"
		}
	]
}
```

**Comment by Jordan-Nelson** [comment] 2024-07-01 15:11
@pepie if you are still facing this issue please share the IAM policy. Thanks.

**Comment by pepie** [comment] 2024-07-02 01:20
Thanks for your patience, @Jordan-Nelson .

I had four policies created. The first three were had a type of 'Customer Managed' and followed this naming convention
`amplify-<app name>-sandbox-< ID > - amplifyDataAuthRolePolicy< ID >` with type 'Customer Managed'

Each had one attached entity.

The last one, which I think is the one you're interested in, was is named 'storageAccess< ID >' and has a type of 'Customer Inline' with zero attached entities.

Here's the content of that policy

`
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "s3:GetObject",
            "Resource": [
                "arn:aws:s3:::amplify-backend-kio-sandbox-kiomediabucket<*ID*>/kio-media/public/${cognito-identity.amazonaws.com:sub}/*",
                "arn:aws:s3:::amplify-backend-kio-sandbox-kiomediabucket<*ID*>/kio-media/protected/*/*",
                "arn:aws:s3:::amplify-backend-kio-sandbox-kiomediabucket<*ID*>/kio-media/protected/${cognito-identity.amazonaws.com:sub}/*",
                "arn:aws:s3:::amplify-backend-kio-sandbox-kiomediabucket<*ID*>/kio-media/private/${cognito-identity.amazonaws.com:sub}/*"
            ],
            "Effect": "Allow"
        },
        {
            "Condition": {
                "StringLike": {
                    "s3:prefix": [
                        "kio-media/public/${cognito-identity.amazonaws.com:sub}/*",
                        "kio-media/public/${cognito-identity.amazonaws.com:sub}/",
                        "kio-media/protected/*/*",
                        "kio-media/protected/*/",
                        "kio-media/protected/${cognito-identity.amazonaws.com:sub}/*",
                        "kio-media/protected/${cognito-identity.amazonaws.com:sub}/",
                        "kio-media/private/${cognito-identity.amazonaws.com:sub}/*",
                        "kio-media/private/${cognito-identity.amazonaws.com:sub}/"
                    ]
                }
            },
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::amplify-backend-kio-sandbox-kiomediabucket<*ID*>",
            "Effect": "Allow"
        },
        {
            "Action": "s3:PutObject",
            "Resource": [
                "arn:aws:s3:::amplify-backend-kio-sandbox-kiomediabucket<*ID*>/kio-media/public/${cognito-identity.amazonaws.com:sub}/*",
                "arn:aws:s3:::amplify-backend-kio-sandbox-kiomediabucket<*ID*>/kio-media/protected/${cognito-identity.amazonaws.com:sub}/*",
                "arn:aws:s3:::amplify-backend-kio-sandbox-kiomediabucket<*ID*>/kio-media/private/${cognito-identity.amazonaws.com:sub}/*"
            ],
            "Effect": "Allow"
        },
        {
            "Action": "s3:DeleteObject",
            "Resource": [
                "arn:aws:s3:::amplify-backend-kio-sandbox-kiomediabucket<*ID*>/kio-media/public/${cognito-identity.amazonaws.com:sub}/*",
                "arn:aws:s3:::amplify-backend-kio-sandbox-kiomediabucket<*ID*>/kio-media/protected/${cognito-identity.amazonaws.com:sub}/*",
                "arn:aws:s3:::amplify-backend-kio-sandbox-kiomediabucket<*ID*>/kio-media/private/${cognito-identity.amazonaws.com:sub}/*"
            ],
            "Effect": "Allow"
        }
    ]
}
`

Note:
* The official bucket name is kio-media, this was truncated in earlier messages as 'media'. This change was only made for the public forum. All configurations use 'kio-media' for the bucket name.

I also get a few warnings when launching the sandbox
`current credentials could not be used to assume 'arn:aws:iam::< ID >:role/cdk-hnb659fds-deploy-role-< ID >-us-east-1', but are for the right account. Proceeding anyway.
`

**Comment by pepie** [comment] 2024-07-02 01:24
Here's the bucket policy that was generated

```{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Deny",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::amplify-backend-kio-sandbox-kiomediabucket< ID >",
                "arn:aws:s3:::amplify-backend-kio-sandbox-kiomediabucket< ID >/*"
            ],
            "Condition": {
                "Bool": {
                    "aws:SecureTransport": "false"
                }
            }
        },
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::< ID >:role/amplify-backend-kio-sandb-CustomS3AutoDeleteObjects-< ID >"
            },
            "Action": [
                "s3:PutBucketPolicy",
                "s3:GetBucket*",
                "s3:List*",
                "s3:DeleteObject*"
            ],
            "Resource": [
                "arn:aws:s3:::amplify-backend-kio-sandbox-kiomediabucket< ID >",
                "arn:aws:s3:::amplify-backend-kio-sandbox-kiomediabucket< ID >/*"
            ]
        }
    ]
}```

**Comment by Jordan-Nelson** [comment] 2024-07-02 14:21
@pepie - In the IAM policy it looks like the root folder name is `kio-media`. The resource.ts file snippet you shared and the Amplify Flutter code snippets showed `media` as the root folder.

Can you confirm the resource.ts file you shared is accurate? Have you made changes since your last deployed? If your resource.ts file is accurate and you have successfully deployed recently, can you open an issue at https://github.com/aws-amplify/amplify-backend for this?

With the given IAM policies you should be able to update the Amplify Flutter code snippet to use `kio-media` in place of `media`. For example:

```dart
final result = await Amplify.Storage.uploadFile(
    localFile: AWSFile.fromStream( imageFile.openRead(), size: 0 ),
    path: StoragePath.fromIdentityId( (id)=> "kio-media/public/${id}/test.jpg"),
    options: options,
    onProgress: onProgress ?? (progress) {
       safePrint('upload progress ${progress.fractionCompleted}');
     },
).result;
```

Let me know if you have other questions. Thanks.

**Comment by pepie** [comment] 2024-07-02 17:33
Yes, I mentioned this in the post.
I changed "kio-media" to "media" to simplify the GitHub post, but all the paths configurations are set to 'kio-media'.

I also noticed that your sample backend.js code did not include a config for data
```// backend.ts
import { defineBackend } from "@aws-amplify/backend";
import { auth } from "./auth/resource";
import { storage } from "./storage/resource";

defineBackend({
  auth,
  storage,
});```

I don't know if this has any impact, but I have defaultAuthorizationMode set to 'userPool' in data/resource.ts.

```export const data = defineData({
  schema,
  authorizationModes: {
    defaultAuthorizationMode: 'userPool',
     apiKeyAuthorizationMode: {
          expiresInDays: 360
    }
  },
});```

The only other difference  I have is a post-confirmation resource.

I'll try your code again in a clean project and open a ticket if it fails.

**Comment by pepie** [comment] 2024-07-02 17:36
Also, can you confirm your flutter amplify library version?

I am using the latest version (2.2.0) for all, except for amplify_authenticator.

  
```  
variables:
  amplify_version: &amplify_version 2.2.0
amplify_api: *amplify_version
  amplify_authenticator: ^2.1.0
  amplify_auth_cognito: *amplify_version
  amplify_datastore: *amplify_version
  amplify_flutter: *amplify_version
  amplify_storage_s3: *amplify_version```

**Comment by Jordan-Nelson** [comment] 2024-07-02 17:38
@pepie Okay, let me know if you still face issues after redeploying.

I has used amplify flutter v2.1.0 as that was the latest available at the time. v2.2.0 was released on Thursday.

**Comment by pepie** [comment] 2024-07-02 17:39
Lastly, the Sandbox deployment is successful. However, I do get the following warnings:

```current credentials could not be used to assume 'arn:aws:iam::<-ID->:role/cdk-<ID>-deploy-role-<-ID->-us-east-1', but are for the right account. Proceeding anyway.
```

**Comment by pepie** [comment] 2024-07-02 17:40
> @pepie Okay, let me know if you still face issues after redeploying.
> 
> I had used amplify flutter v2.1.0 as that was the latest available at the time. v2.2.0 was released on Thursday.

Yes, I started with v2.1.0 and upgraded to 2.2.0, but I still get the same error.
I'll try with a clean flutter project and see if the problem persists.

**Comment by Jordan-Nelson** [comment] 2024-07-02 17:59
> Lastly, the Sandbox deployment is successful. However, I do get the following warnings:

I am not seeing any warnings in the comment.

**Comment by pepie** [comment] 2024-07-02 18:19
Hey @Jordan-Nelson, 
I created a cleaned project and was able to upload an image successfully.
I'll have to review my project to see the differences. But it seems this issue is on my side.

Thank you for your help!

**Comment by Jordan-Nelson** [comment] 2024-07-02 19:31
@pepie I am glad it is working now. I will close this issue out.

**Closed by Jordan-Nelson** 2024-07-02 19:31 UTC
Labels: question, pending-close-response-required, storage, not-reproducible, pending-response

**Comment by pepie** [comment] 2024-07-03 05:38
I finally figured out the issue, so adding some notes here in case others face similar issues.

Summary: Uploads worked for unauthenticated users, but failed for authenticated users. The is was with my authenticated users, belonging to a group. So, allow.authenticated().to([....]) is not enough, when your user belong to a group.

Example:
Uploads failed for the following configuration - for all buckets and all users

```// amplify/storage/resource.ts
import { defineStorage } from "@aws-amplify/backend";

export const storage = defineStorage({
  name: "gallery",
  access: (allow) => ({
    "media/public/{entity_id}/*": [
      allow.guest.to(["read"]),
      
      // This is NOT enough to grant access to the authenticated user, if the user belongs to a group
      // You must grant access to the group for this to be effective
      allow.entity("identity").to(["read", "write", "delete"]),  
      
      // this works. But my test user belonged to the "Users" group, which was not included here.
      allow.groups(["Admins", "Staff", "SystemAdmins"]).to(["read", "write", "delete"]),  
    ],
    "media/protected/{entity_id}/*": [
      allow.authenticated.to(["read"]),         //this doesn't work by itself when users are in groups
      allow.entity("identity").to(["read", "write", "delete"]),
      allow.groups(["Admins", "Staff", "SystemAdmins"]).to(["read", "write", "delete"]),
    ],
    "media/private/{entity_id}/*": [
      //this fails. Add allow.groups([])... or allow.authenticated() if users are not in groups
      allow.entity("identity").to(["read", "write", "delete"]),
      allow
        .groups(["Admins", "Staff", "SystemAdmins"])
        .to(["read", "write", "delete"]),
    ],
  }),
});```

I hope this helps.

**Comment by mausic** [comment] 2024-07-22 13:53
Thanks @pepie it really works!

However, it creates a breach that allows other users to access files they must not have access to. Do you have any ideas on how to avoid this or solve the problem another way?

**Comment by pepie** [comment] 2024-07-23 04:10
> Thanks @pepie it really works!
> 
> However, it creates a breach that allows other users to access files they must not have access to. Do you have any ideas on how to avoid this or solve the problem another way?

Hi @mausic! 
I fixed the typos in my last post to make it clearer.  In short, if a user belong to a group then the group must be able to take action on the bucket first.  You can then add additional restrictions to lock down the file.  AWS will apply the strictest access rule, so that should prevent unauthorized access. 

So, if 'UserA' belong to group 'Staff', then:

1. The 'Staff' group must have read/write access to the bucket.
2. You can then add  more restrictions to limit read access to 'Authenticated' users and/or 'Owner' only.

The strictest access rule should apply. 

The following example should let the Staff group upload files, but restrict read access only to the file owner.

//the group must be able to write to upload
allow.groups(["Staff"]).to(["write"]),

// only owner can read and delete (the write entry may be redundant, but it doesn't hurt)
allow.entity("identity").to(["read", "write", "delete"]),

Try granting Staff read and write if reading fails.

**Comment by rhys-daniel** [comment] 2024-08-26 09:08
> Thanks @pepie it really works!
> 
> However, it creates a breach that allows other users to access files they must not have access to. Do you have any ideas on how to avoid this or solve the problem another way?

I agree @mausic. This will grant certain users access to areas I don't want them to have access. Did you figure this out? I had the same problem as @pepie whose work around works...albeit giving access to areas I don't want to.

**Comment by Spockinnator** [comment] 2024-10-05 10:22
@pepie this was very helpful! Thanks for sharing. I've dI also just went through the documentation and it doesn't say anything about setting up the IAM policies that you showed. @Jordan-Nelson showed in your examples. I've read and re-read these instructions. It appears from the instructions that setting up IAM policies for each sandbox and each production environment manually is a step backward from what Amplify Gen 2 with CDK level 3 is doing, so I'm really hoping that wasn't the case. 

Were those generated dynamically with something else explicitely shown in your backend.ts. If so, would you mind sharing?

**Comment by charlieforward9** [comment] 2024-10-11 23:56
For anyone who falls here in a confused daze, remember to check the path youre trying to save to. You may be messing it up.

**Comment by pepie** [comment] 2024-10-12 00:25
> @pepie this was very helpful! Thanks for sharing. I've dI also just went through the documentation and it doesn't say anything about setting up the IAM policies that you showed. @Jordan-Nelson showed in your examples. I've read and re-read these instructions. It appears from the instructions that setting up IAM policies for each sandbox and each production environment manually is a step backward from what Amplify Gen 2 with CDK level 3 is doing, so I'm really hoping that wasn't the case.
> 
> Were those generated dynamically with something else explicitely shown in your backend.ts. If so, would you mind sharing?

Please excuse the delay, here is how the groups are generated.
`export const auth = defineAuth({
  loginWith: {
    email: true,
  },
  name: "<user_pool_name_here>",
  groups: ["Admins","Users","...and so on..."],
  userAttributes: {
      givenName: {
        mutable: true,
        required: true,
      },
      familyName: {
        mutable: true,
        required: true,
      },
      phoneNumber: {
        mutable: true,
        required: false,
      },
      profilePicture: {
        mutable: true,
        required: false,

      },
      gender: {
        mutable: true,
        required: false,
      },
      middleName: {
        mutable: true,
        required: false,
      }
  },
  triggers: {
     postConfirmation
  },
  access: ( allow ) => [
     allow.resource( postConfirmation ).to( ["addUserToGroup"] )
  ]

});`
