### ISSUE TITLE
[Web] ModelSubscriptions.onUpdate callback not fired when GraphQL mutation update occurs

### ISSUE THREAD

**Issue by fvisticot** [aws-amplify/amplify-flutter#2499] opened 2022-12-18 21:30 UTC
### Description

- I subscribe to a model update like in the code bellow.
- When update occurs from an update in the Flutter App, callback is called successfully
- When I try to update the data from AppSync AWS console with a mutation, the callback is not fired.

Any idea why it does not work ?

```
final subscriptionRequest = ModelSubscriptions.onUpdate(Device.classType);
    _subscription = Amplify.API
        .subscribe(
          subscriptionRequest,
          onEstablished: () => print('Subscription established'),
        )
        .take(5)
        .handleError((error) {
      print(error);
    }).listen((event) {
      print(event);
    });
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment

```bash
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6.1 21G217 darwin-arm, locale fr-FR)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

### Dependencies

```bash
dependencies:
- ai_barcode 3.2.4 [flutter ai_barcode_platform_interface ai_barcode_web]
- amplify_analytics_pinpoint 1.0.0-next.2 [amplify_analytics_pinpoint_dart amplify_core amplify_db_common amplify_secure_storage aws_common device_info_plus flutter meta package_info_plus path_provider]
- amplify_api 1.0.0-next.2+1 [amplify_api_android amplify_api_ios amplify_core amplify_flutter async aws_common collection connectivity_plus flutter json_annotation meta plugin_platform_interface stream_transform web_socket_channel]
- amplify_auth_cognito 1.0.0-next.2+1 [amplify_auth_cognito_android amplify_auth_cognito_dart amplify_auth_cognito_ios amplify_core amplify_flutter amplify_secure_storage async flutter flutter_web_plugins meta path plugin_platform_interface]
- amplify_authenticator 1.0.0-next.1+3 [amplify_auth_cognito amplify_core amplify_flutter async aws_common collection flutter flutter_localizations intl meta smithy stream_transform]
- amplify_flutter 1.0.0-next.2 [amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios amplify_secure_storage aws_common collection flutter meta plugin_platform_interface]
- built_value 8.4.2 [built_collection collection fixnum meta]
- cupertino_icons 1.0.5
- dio 4.0.6 [http_parser path]
- dots_indicator 2.1.0 [flutter]
- equatable 2.0.5 [collection meta]
- fl_chart 0.55.2 [flutter equatable]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_bloc 8.1.1 [flutter bloc provider]
- flutter_launcher_icons 0.11.0 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_map 3.0.0 [async collection flutter http latlong2 meta polylabel positioned_tap_detector_2 proj4dart tuple vector_math]
- flutter_rating_bar 4.0.1 [flutter]
- flutter_slidable 2.0.0 [flutter]
- flutter_spinkit 5.1.0 [flutter]
- geolocator 9.0.2 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- go_router 5.2.4 [collection flutter flutter_web_plugins logging meta]
- intl 0.17.0 [clock path]
- latlong2 0.8.1 [intl]
- logging 1.1.0
- package_info_plus 3.0.2 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- permission_handler 10.2.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- rating 1.0.0-dev.1 [flutter flutter_bloc flutter_spinkit]
- shimmer 2.0.0 [flutter]
- snapping_sheet 3.1.0 [flutter]

dependency overrides:
- package_info_plus 3.0.2 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]

transitive dependencies:
- ai_barcode_platform_interface 3.0.1 [flutter]
- ai_barcode_web 3.0.1 [flutter flutter_web_plugins ai_barcode_platform_interface qr_flutter universal_html]
- amplify_analytics_pinpoint_dart 0.1.2 [amplify_core amplify_db_common_dart amplify_secure_storage_dart aws_common aws_signature_v4 built_collection built_value drift intl meta path smithy smithy_aws uuid]
- amplify_api_android 1.0.0-next.2 [flutter]
- amplify_api_ios 1.0.0-next.2 [amplify_core flutter]
- amplify_auth_cognito_android 1.0.0-next.2 [flutter]
- amplify_auth_cognito_dart 0.3.1 [amplify_core amplify_secure_storage_dart async aws_common aws_signature_v4 built_collection built_value collection convert crypto fixnum http intl js json_annotation meta oauth2 path smithy smithy_aws stream_transform uuid worker_bee]
- amplify_auth_cognito_ios 1.0.0-next.2 [amplify_core flutter]
- amplify_core 1.0.0-next.2+1 [async aws_common aws_signature_v4 collection intl json_annotation logging meta retry uuid]
- amplify_datastore_plugin_interface 1.0.0-next.2 [amplify_core collection flutter meta]
- amplify_db_common 0.1.2 [amplify_db_common_dart drift flutter path path_provider]
- amplify_db_common_dart 0.1.3 [amplify_core async aws_common drift meta path sqlite3]
- amplify_flutter_android 1.0.0-next.2 [flutter]
- amplify_flutter_ios 1.0.0-next.2 [amplify_core flutter]
- amplify_secure_storage 0.1.4 [amplify_secure_storage_dart async file flutter meta path path_provider]
- amplify_secure_storage_dart 0.1.4 [async aws_common built_collection built_value ffi file js meta path win32 worker_bee]
- archive 3.3.5 [crypto path pointycastle]
- args 2.3.1
- async 2.9.0 [collection meta]
- aws_common 0.3.5 [async built_collection built_value collection http2 js json_annotation logging meta mime os_detect path stream_transform uuid]
- aws_signature_v4 0.3.1 [async aws_common collection convert crypto json_annotation meta path]
- bloc 8.1.0 [meta]
- built_collection 5.1.1
- characters 1.2.1
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.5 [meta path]
- clock 1.1.1
- collection 1.16.0
- connectivity_plus 3.0.2 [flutter flutter_web_plugins connectivity_plus_platform_interface js meta nm]
- connectivity_plus_platform_interface 1.2.3 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- crclib 3.0.0 [meta tuple]
- crypto 3.0.2 [typed_data]
- csslib 0.17.2 [source_span]
- dbus 0.7.8 [args ffi meta xml]
- device_info_plus 6.0.0 [flutter device_info_plus_platform_interface device_info_plus_macos device_info_plus_linux device_info_plus_web device_info_plus_windows]
- device_info_plus_linux 5.0.0 [device_info_plus_platform_interface file flutter meta]
- device_info_plus_macos 5.0.0 [device_info_plus_platform_interface flutter]
- device_info_plus_platform_interface 5.0.0 [flutter meta plugin_platform_interface]
- device_info_plus_web 5.0.0 [device_info_plus_platform_interface flutter_web_plugins flutter]
- device_info_plus_windows 6.0.0 [device_info_plus_platform_interface ffi flutter win32 meta]
- drift 2.3.0 [async convert collection js meta stream_channel sqlite3]
- ffi 2.0.1
- file 6.1.4 [meta path]
- fixnum 1.0.1
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- geolocator_android 4.1.4 [flutter geolocator_platform_interface]
- geolocator_apple 2.2.3 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.0.7 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.1.6 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.1.1 [flutter geolocator_platform_interface]
- html 0.15.1 [csslib source_span]
- http 0.13.5 [async http_parser meta path]
- http2 2.0.1
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 3.2.2 [archive meta xml]
- js 0.6.4
- json_annotation 4.7.0 [meta]
- lists 1.0.1 [meta]
- material_color_utilities 0.1.5
- meta 1.8.0
- mgrs_dart 2.0.0 [unicode]
- mime 1.0.3
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- oauth2 2.0.1 [collection crypto http http_parser]
- os_detect 2.0.1
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.8.2
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.22 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.5 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.3 [ffi flutter path path_provider_platform_interface win32]
- permission_handler_android 10.2.0 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.0.7 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.9.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.2 [flutter permission_handler_platform_interface]
- petitparser 5.1.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.3 [meta]
- pointycastle 3.6.2 [collection convert js]
- polylabel 1.0.1 [collection]
- positioned_tap_detector_2 1.0.4 [flutter]
- process 4.2.4 [file path platform]
- proj4dart 2.1.0 [mgrs_dart wkt_parser meta]
- provider 6.0.5 [collection flutter nested]
- qr 2.1.0 [meta]
- qr_flutter 4.0.0 [flutter qr]
- retry 3.1.0
- shelf 1.4.0 [async collection http_parser path stack_trace stream_channel]
- sky_engine 0.0.99
- smithy 0.3.2 [async aws_common built_collection built_value collection convert crypto fixnum http_parser intl json_annotation meta path retry shelf typed_data xml]
- smithy_aws 0.3.2 [aws_common aws_signature_v4 built_collection built_value collection convert crclib crypto intl json_annotation meta path smithy xml]
- source_span 1.9.0 [collection path term_glyph]
- sqlite3 1.9.1 [collection ffi js meta path]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.1.0
- string_scanner 1.1.1 [source_span]
- term_glyph 1.2.1
- tuple 2.0.1
- typed_data 1.3.1 [collection]
- unicode 0.3.1 [lists]
- universal_html 2.0.8 [async csslib charcode collection html meta source_span typed_data universal_io]
- universal_io 2.0.4 [collection crypto meta typed_data]
- uuid 3.0.7 [crypto]
- vector_math 2.1.2
- web_socket_channel 2.2.0 [async crypto stream_channel]
- win32 3.1.3 [ffi]
- wkt_parser 2.0.0
- worker_bee 0.1.3 [async aws_common built_collection built_value collection js meta path stack_trace stream_channel stream_transform]
- xdg_directories 0.2.0+2 [meta path process]
- xml 6.1.0 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]
```

### Device

WEB

### OS

WEB

### Deployment Method

Amplify CLI

### CLI Version

10.5.2

### Amplify Config

NA

**Comment by ragingsquirrel3** [comment] 2022-12-19 20:15
@fvisticot thanks for filing this issue and sorry it's not working as expected. When you establish the subscription, do you get the 'Subscription established' output from the `onEstablished` callback you passed? Would it be possible to also include a copy of the request you are making from the console as well as your GraphQL schema? This will help us try to reproduce this issue.

**Comment by fvisticot** [comment] 2022-12-19 20:49
The onEstablished callback is OK (I get the trace from the callback).
The request I made from the console: 

mutation MyMutation {
  updateDevice(input: {description: "coucou", id: "69002"}) {
    id
  }
}

The GraphQL schema (from appSync schema export)
[schema.txt](https://github.com/aws-amplify/amplify-flutter/files/10262609/schema.txt)

For your information, if I update the description attribute from the app and subscribe to the onUpdateDevice on the appSync console, the callback is successfully received on the console.

**Comment by ragingsquirrel3** [comment] 2022-12-22 13:27
I discussed this with OP offline, will post resolution here in case anyone has similar error/question. I was able to repro this Here are the issues per my current understanding:
* root cause is that subscription selection set is not a subset of the mutation selection set. This is a [requirement from AppSync](https://docs.aws.amazon.com/appsync/latest/devguide/aws-appsync-real-time-data.html). In AppSync AWS console, you should just be able to add all the fields to the mutation selection set and it should work (example only has ID). This fixed the issue for OP.
* Without step 1, expected behavior is that you get a GQL response with an error. There is a known issue with subscription error parsing that is causing the failure from step 1 to not get parsed correctly. There is [a fix for this pending release](https://github.com/aws-amplify/amplify-flutter/pull/2483).
* While debugging this I noticed some other issues with how this error was ignored and the websocket doesn't recover well. I will [get a PR out ](https://github.com/aws-amplify/amplify-flutter/pull/2507)to fix that to improve visibility of similar errors in the future.

I'm going to close this issue.

**Closed by ragingsquirrel3** 2022-12-22 13:27 UTC
Labels: GraphQL API, pending-response, pending-triage
