### ISSUE TITLE
With msix pakcage  install to windows 10, 11, When sign in cognito, Got an error "request failed due to a network error"

### ISSUE THREAD

**Issue by minganp** [aws-amplify/amplify-flutter#5186] opened 2024-07-20 09:46 UTC
### Description

My application is deveploed for windows. I package it for redistrubution with msix, after installed on a new machine which is not install Android stuido with flutter or visual stuido, when I sign in cognito, it raised an error "request failed due to a network error". but after I install Android stuido with flutter and visual stuido, it works normally.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. create flutter app for windows
2. flutter build windows to create applicate exe
3. copy msvcp140.dll, vcruntime140.dll, vcruntime140_1.dll into runner\release directory
4. create msix config in yaml
5. run dart run msix:create to create msix file in runner\release
6. the msix defined as: 
    msix_config: 
      display_name: MY PROJECT
      publisher_display_name: xxxxxx
      identity_name: xxxxxx
     msix_version: "1.0.0.0"
     logo_path: xxxxx
     capabilities: internetClient, location, webcam
     debug: false
     certificate_path: C:\xxxx\xxxx\xxxx\xxxx\xxxx\CERTIFICATE.pfx
     certificate_password: xxxxxx
7. the x64\runner\release directory include amplify_db.common_plugin.dll, camera_windows_plugin.dll, connectivity_plus_plugin.dll, file_selector_windows_plugin.dll, flutter_windows.dll, sqlite3.dll, url_launcher_windows.plugin.dll, webview_win_floating_plugin.dll, webview2loader.dll

### Screenshots

/
![Screenshot 2024-07-20 174408](https://github.com/user-attachments/assets/2f271fab-eeac-44e0-8022-3a3d2c65645f)

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [X] Windows
- [ ] Linux

### Flutter Version

3.19.6

### Amplify Flutter Version

2.0.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment] 2024-07-22 17:43
Hello @minganp - Have you added the `internetClient` capability? This would be required when packaging the app with msix that uses internet. See https://pub.dev/packages/msix#-configuring-your-installer for more info.

I will mark this as a documentation issue since this should be noted in the Amplify docs.

**Comment by minganp** [comment] 2024-07-23 01:23
msix_config:
display_name: MY PROJECT
publisher_display_name: xxxxxx
identity_name: xxxxxx
msix_version: "1.0.0.0"
logo_path: xxxxx
capabilities: internetClient, location, webcam
debug: false
certificate_path: C:\xxxx\xxxx\xxxx\xxxx\xxxx\CERTIFICATE.pfx
certificate_password: xxxxxx
**capabilities: internetClient, location, webcam** already include

**Comment by minganp** [comment] 2024-07-25 02:00
> Apologies, I missed that. Do you have a stack trace or full exception?

Hellow Jordan Nelson, thanks a lot. Because I deploy it on a new machine without development enviroment, so I can not get the stack trace or full exception. I try to print it to log file or display on the screen. But I I got nothing. I do it like this:
Authenticator(
      onException: (authException) async{
        await showDialog(
            context: context,
            builder: (BuildContext context){
              return AlertDialog(
                title: Text(authException.toString()),
                actions: [
                  TextButton(
                    child:const Text("OK"),
                    onPressed: (){
                      Navigator.of(context).pop();
                    },
                  )
                ],
              );
            });
      },
      child: ProviderScope(
        child:MaterialApp(
        locale: _locale,
        debugShowCheckedModeBanner: false,
        supportedLocales: const [
          Locale('en'),
          Locale('lo'),
          Locale('zh')
        ],
        localizationsDelegates: const [
          S.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate
        ],
        builder: Authenticator.builder(),
        theme: ThemeData(
          primarySwatch: Colors.blue,
          cardTheme: const CardTheme(
            color: Colors.transparent,
          ),
          popupMenuTheme: PopupMenuThemeData(
            color: DefaultTheme.containerMediumColor
          )
        ),
        home: MyHomePage(
            setLocale: setLocale,
          ),
            ))
      ), but the dialog havn't show. And with Future<String> _configureAmplify({required Logger logger}) async {
  AmplifyAPI api;
  // To be filled in
  try {
    api = AmplifyAPI();
    await Amplify.addPlugins([AmplifyAuthCognito(), api]);
    await Amplify.configure(amplifyconfig);
    //logger.i('Successfully configured Amplify 🎉');
    return "Successfully configured Amplify 🎉";
  } on Exception catch (e) {
    //logger.e('Could not configure Amplify ☠️,$e');
    return e.toString();
  }
}, I can see the  "Successfully configured Amplify 🎉" displayed on the screen. 
Because I the error message "The request failed due to a network error" raised by the flutter amplify "Authenticator", How can I catch more information about the error? Thanks again

**Comment by Jordan-Nelson** [comment] 2024-07-25 14:46
`Authenticator()` accepts a `onException` callback. You can use this to print/log the exception.

```dart
onException: (exception) {
  print('[ERROR]: ${exception.toJson()}');
},
```

**Comment by minganp** [comment] 2024-07-26 02:13
I already have this: 

onException: (authException) async{
        await showDialog(
            context: context,
            builder: (BuildContext context){
              return AlertDialog(
                title: Text(authException.toString()),
                actions: [
                  TextButton(
                    child:const Text("OK"),
                    onPressed: (){
                      Navigator.of(context).pop();
                    },
                  )
                ],
              );
            });
      }, 

but the dialog not show

**Comment by minganp** [comment] 2024-08-01 08:59
Meaby I have find the root cause of it. Actually it's the same as the issue [#4714](https://github.com/aws-amplify/amplify-flutter/issues/4714). When I switch to another internet connection, it get normally.

**Comment by Jordan-Nelson** [comment] 2024-08-07 17:07
@minganp thanks for the update. We will continue to use #4714 to track that issue. I think we can close this issue out as a duplicate then. Let me know if you disagree.

If you would like, we can keep this issue open until the documentation is updated to add the `internetClient` capability, but it sounds like the missing documentation wasn't related to your issue as you had already added that.

**Comment by Jordan-Nelson** [comment] 2024-08-28 01:49
Closing as duplicate of #4714

**Closed by Jordan-Nelson** 2024-08-28 01:49 UTC
Labels: Documentation, feature-request, pending-close-response-required, auth, windows
