### ISSUE TITLE
Hard Crash Exception On fetchAuthSession With Android Release Build

### ISSUE THREAD

**Issue by doug-mrowl** [aws-amplify/amplify-flutter#675] opened 2021-06-25 01:50 UTC
I'm getting a strange crash exception, but only on Android release builds. iOS completely works, and the problem does not occur with Android debug builds. For me, this is reproducible every time, but only on Android release builds. Upon calling Amplify.Auth.fetchAuthSession(options:), I get the following exception:

Console log:
```
Launching lib/main.dart on SM G960U in release mode...
Installing build/app/outputs/flutter-apk/app.apk...
I/flutter (20547): **** configureAmplify
I/flutter (20547): **** configureAmplify Setup Done
I/flutter (20547): **** configureAmplify Done
I/flutter (20547): **** _awsSdkinitialize
I/flutter (20547): **** amplify service getUserState: fetch auth session
E/AndroidRuntime(20547): FATAL EXCEPTION: main
E/AndroidRuntime(20547): Process: com.mycompany.myapp, PID: 20547
E/AndroidRuntime(20547): java.lang.RuntimeException: Missing type parameter.
E/AndroidRuntime(20547): 	at e.d.c.P.a.getSuperclassTypeParameter(Unknown Source:26)
E/AndroidRuntime(20547): 	at e.d.c.P.a.<init>(Unknown Source:7)
E/AndroidRuntime(20547): 	at com.amazonaws.amplify.amplify_auth_cognito.types.FlutterFetchCognitoAuthSessionResult$serializeToMap$$inlined$convert$1.<init>(Unknown Source:0)
E/AndroidRuntime(20547): 	at com.amazonaws.amplify.amplify_auth_cognito.types.FlutterFetchCognitoAuthSessionResult.serializeToMap(Unknown Source:14)
E/AndroidRuntime(20547): 	at com.amazonaws.amplify.amplify_auth_cognito.types.FlutterFetchCognitoAuthSessionResult.serializeCredentials(Unknown Source:0)
E/AndroidRuntime(20547): 	at com.amazonaws.amplify.amplify_auth_cognito.types.FlutterFetchCognitoAuthSessionResult.toValueMap(:6)
E/AndroidRuntime(20547): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.prepareCognitoSessionResult$lambda-42(Unknown Source:14)
E/AndroidRuntime(20547): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.a(Unknown Source:0)
E/AndroidRuntime(20547): 	at com.amazonaws.amplify.amplify_auth_cognito.a.run(Unknown Source:4)
E/AndroidRuntime(20547): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(20547): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(20547): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(20547): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
E/AndroidRuntime(20547): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20547): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/AndroidRuntime(20547): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```
I just updated to Flutter 2.2.2, and updated the Amplify Flutter packages all to 0.1.6.

Thanks for any insight!

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
    • Flutter version 2.2.2 at /Users/dplanford/Desktop/Develop/flutter
    • Framework revision d79295af24 (13 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/dplanford/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • SM G960U (mobile) • 32514f4842413098 • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

</details>

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9
 - OS: Android 10 (API 29)

**Additional context**
Relevant Flutter code attached below (showing my print comments shown in the console log):
 ```
static Future<void> configureAmplify() async {
  print('**** configureAmplify');
  AmplifyAuthCognito authPlugin = AmplifyAuthCognito();
  AmplifyStorageS3 storagePlugin = AmplifyStorageS3();
  Amplify.addPlugins([
    authPlugin,
    storagePlugin,
  ]);
  print('**** configureAmplify Setup Done');

  try {
    await Amplify.configure(amplifyconfig);
  } on AmplifyAlreadyConfiguredException {
    print(
        "Tried to reconfigure Amplify; this can occur when your app restarts on Android.");
  }
  print('**** configureAmplify Done');
}

Future<void> _awsSdkinitialize() async {
  print('**** _awsSdkinitialize');
  final bool status = await amplifyService.getUserState();
  print('**** _awsSdkinitialize got user state');
  if (status == false) {
    signOut();
  } else {
  print('**** _awsSdkinitialize handle Cognito SignIn');
    await handleCognitoSignIn();
  }
}

class AmplifyService {
  Future<bool> getUserState() async {
    print('**** amplify service getUserState: fetch auth session');
    try {
      AuthSession authSession = await Amplify.Auth.fetchAuthSession(
          options: CognitoSessionOptions(getAWSCredentials: true));
      print('**** amplify service fetch auth session done');
      return authSession.isSignedIn;
    } on AuthException catch (e) {
      print('**** ${e.message}');
      return false;
    } catch (e) {
      print('**** ${e.message}');
      return false;
    }
  }
}
```

**Comment by Jordan-Nelson** [comment] 2021-06-25 12:03
Hello @doug-mrowl - Thanks for taking the time to open an issue. I will see if I can reproduce this with the info you have provided.

**Comment by Jordan-Nelson** [comment] 2021-06-25 15:51
@doug-mrowl can you provide the contents of /android/app/build.gradle?

**Comment by doug-mrowl** [comment] 2021-06-25 15:58
Thanks for the help... here is my /android/app/build.gradle file. Note that I am mostly an iOS coder... still learning the Android side of things for Flutter development ;-)

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "com.gonstead_nm.mrowlcommunitygroup"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
        debug {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
```

**Comment by Jordan-Nelson** [comment] 2021-06-25 18:19
Thanks @doug-mrowl - I was able to reproduce this. I am going to look into a fix.

**Comment by Jordan-Nelson** [comment] 2021-06-25 19:09
I think this is related to https://github.com/flutter/flutter/issues/78625

**Comment by doug-mrowl** [comment] 2021-06-25 22:06
Thanks for the info... I'll look at the related issue and see if the fix works!

**Comment by Jordan-Nelson** [comment] 2021-06-28 14:18
I have been able to reproduce this with apps created with flutter v2.2.0 and up (v2.0.6 and earlier seems fine). I believe it is an issue with all versions of amplify-flutter. I have only attempted to reproduce it with version 0.1.6 and 0.2.0-nullsafety.1, but the code that is causing the crash was not added recently.

I don't think it is the same issue as I have linked above. It seems similar just reading the description, but the issue I linked appears to have started in v2.0.0. I can only reproduce this with apps created with flutter v2.2.0 and up. I did try a handful of the workarounds in that issue but non of them resolved this.

**Comment by Jordan-Nelson** [comment] 2021-06-28 14:28
@doug-mrowl can you confirm if you are seeing this on a physical device or an emulator?

**Comment by doug-mrowl** [comment] 2021-06-28 16:40
I'm seeing this on a physical device, a Samsung Galaxy S9. I'm also seeing it on my older Android test device, a Moto G4. I also agree that this appears to not be related to the above linked similar issues... I tried the fixes mentioned and they did not work to fix this problem. Thanks for the continued look at this... I'm still researching the problem and I'll post here if I find anything!

**Comment by Jordan-Nelson** [comment] 2021-07-01 18:00
@doug-mrowl a fix for this was included in the latest release of amplify-flutter (0.2.0). 0.2.0 was also the first stable release that supports null safety. One option is to upgrade to 0.2.0 to resolve this.

Since this is the first release that supports null safety, you may want to look at [the documentation for null safety in amplify-flutter](https://docs.amplify.aws/lib/project-setup/null-safety/q/platform/flutter) before you upgrade, in particular if you are using datastore. I also want to callout that this release included some breaking changes. All breaking changes are listed in the change log for the packages on pub.

**Comment by doug-mrowl** [comment] 2021-07-01 21:59
Thanks for the information... I'll take a look at updating to 0.2.0 tomorrow.

**Comment by doug-mrowl** [comment] 2021-07-14 09:23
I can confirm that our Android release build now works perfectly under Amplify 0.2.0. Sorry it took so long... I work from home and a random tree branch fell in my backyard and took out our power (and thus wifi) for a few days. But I just tested the updated Flutter Amplify on both iOS and Android, and everything works great.

Thanks for all the help and support!

**Comment by ragingsquirrel3** [comment] 2021-07-20 21:15
I'm going to close this as it seems the issue has been addressed.

**Closed by ragingsquirrel3** 2021-07-20 21:15 UTC
Labels: Android, Auth, bug, pending-close-response-required
