### ISSUE TITLE
Guidance on Integrating Flutter App Authentication with Next.js API using AWS Amplify

### ISSUE THREAD

**Issue by egyangel** [aws-amplify/amplify-flutter#4632] opened 2024-03-30 15:12 UTC
### Environment information

```plain text
System:
  OS: macOS 14.3.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 209.67 MB / 64.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.11.1 - /opt/homebrew/opt/node@20/bin/node
  Yarn: 1.22.21 - ~/.npm-global/bin/yarn
  npm: 10.2.4 - /opt/homebrew/opt/node@20/bin/npm
  pnpm: 8.15.4 - ~/.npm-global/bin/pnpm
NPM Packages:
  @aws-amplify/backend: 0.13.0-beta.13
  @aws-amplify/backend-cli: 0.12.0-beta.15
  aws-amplify: Not Found
  aws-cdk: Not Found
  aws-cdk-lib: Not Found
  typescript: 5.4.3
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
```

### Description

Hello,

I am currently developing a Flutter application that needs to interact securely with a Next.js API. The authentication for the API is handled through AWS Amplify, and I am seeking guidance on the best practices to authenticate my Flutter app users against the Next.js API using Amplify.

Background:
Frontend: Flutter App
Backend: Next.js API
Authentication: Managed through AWS Amplify (Cognito)
Objective:
My main goal is to securely call the Next.js API from my Flutter application. I need to ensure that the API requests are authenticated, leveraging the capabilities of AWS Amplify.

What I've Tried:
I have successfully integrated AWS Amplify for authentication within the Next.js application. However, I am unsure of the steps required to authenticate API requests from the Flutter app.
I've put 'breer idToken' in Authorization header with no success. 

Once authenticated, how do I use these tokens from flutter to make authenticated API calls to my Next.js backend?

Thank you for your assistance and for the great work on AWS Amplify!

**Comment by Jordan-Nelson** [comment] 2024-04-01 20:06
Hello @egyangel - You can use Auth.fetchAuthSession to fetch the credentials including the Access and ID tokens in the front end app ([see docs](https://docs.amplify.aws/flutter/build-a-backend/auth/accessing-credentials/) for more info). Cognito has documentation on how to then verify the tokens on the backend - https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html

Let me know if you have further questions. Thanks.

**Comment by Jordan-Nelson** [comment] 2024-04-04 17:43
@egyangel - Let me know if you have any other questions.

**Comment by NikaHsn** [comment] 2024-04-15 23:47
I'm closing this issue as we did not hear back. please feel free to re-open it if the issue is not resolved.

**Closed by NikaHsn** 2024-04-15 23:47 UTC
Labels: question, pending-close-response-required, auth, transferred
