### ISSUE TITLE
Amplify.configure() hangs on first launch and hot restart when using AmplifyPushNotificationsPinpoint

### ISSUE THREAD

**Issue by zilaiyedaren** [aws-amplify/amplify-flutter#3313] opened 2023-06-27 02:49 UTC
### Description

when invoke flutter run in ios device:
Amplify.configure() hangs on first launch and hot restart when using AmplifyPushNotificationsPinpoint.
remove AmplifyPushNotificationsPinpoint plugin is ok.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3

### Amplify Flutter Version

1.0.1

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment] 2023-06-27 03:01
It looks like this is a duplicate of https://github.com/aws-amplify/amplify-flutter/issues/2989, which is resolved. Please let us know if upgrading to the latest version does not resolve the issue.

**Closed** 2023-06-27 03:02 UTC
Labels: duplicate, Analytics

**Comment by zilaiyedaren** [comment] 2023-10-24 02:54
**error message:**
flutter: An error occurred configuring Amplify: PushNotificationException {
flutter:   "message": "Error occurred awaiting for device token to register device with Pinpoint",
flutter:   "recoverySuggestion": "Please review the underlying exception",
flutter:   "underlyingException": "UnknownException {\n  \"message\": \"Forbidden from accessing the Pinpoint resource.\",\n  \"recoverySuggestion\": \"Please ensure Analytics is properly configured in your amplifyconfiguration.dart file and that unauthenticated guest access is allowed or an authorized user is signed in.\",\n  \"underlyingException\": \"ForbiddenException {\\n}\"\n}"
flutter: }
