### ISSUE TITLE
Instance of 'UnknownSmithyHttpException' on adding amplify_analytics_pinpoint: ^2.2.0

### ISSUE THREAD

**Issue by vipinkashyap** [aws-amplify/amplify-flutter#5356] opened 2024-08-22 15:29 UTC
### Description

Note: This project has not be created using amplify cli. I used an existing pinpoint project with my flutter app. I have provided the input configuration through amplifyconfiguration.dart providing the app id and the region under pinpointAnalytics 

I see the error being thrown here 
![Screenshot 2024-08-22 at 8 14 58 AM](https://github.com/user-attachments/assets/752abfba-2e00-42bc-bb27-c0f54c79c628)

This line to be specific 
![Screenshot 2024-08-22 at 8 12 05 AM](https://github.com/user-attachments/assets/5118481a-77d3-4ddd-98e6-852049e965c3)

This is how the error is being logged and there is no useful recovery suggestion

![Screenshot 2024-08-22 at 8 02 27 AM](https://github.com/user-attachments/assets/292e8863-b9bf-4de7-960e-b7f7a3b023d9)

Flutter doctor

![Screenshot 2024-08-22 at 8 18 07 AM](https://github.com/user-attachments/assets/7d49d880-5b43-4ab5-ad39-0141eedeae9f)

Please let me know if I can provide more information. I need amplify pinpoint analytics to track events and would really appreciate help with this

### Categories

- [X] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Add a valid amplifyconfiguration.dart file to a flutter project make sure to include the awsPinpointAnalyticsPlugin configuration
2. Configure amplify as shown in the image above (the graphql config is optional its relevant to my application)
3.  Run the app

### Screenshots

![Screenshot 2024-08-22 at 8 02 27 AM](https://github.com/user-attachments/assets/22714160-3e2f-4a08-8929-4144e4732b22)
![Screenshot 2024-08-22 at 8 12 05 AM](https://github.com/user-attachments/assets/e2e6ef82-40dd-4850-bcfa-3e0fae987e9a)
![Screenshot 2024-08-22 at 8 14 58 AM](https://github.com/user-attachments/assets/906ffc58-a373-4461-89fe-08cef3e98af4)

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [X] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.22.0

### Amplify Flutter Version

2.2.0

### Deployment Method

Custom Pipeline

**Comment by NikaHsn** [comment] 2024-08-22 16:05
Sorry that you are facing this issue and thanks for reporting it. We will look into this and get back to you when we have updates.

**Comment by tyllark** [comment] 2024-08-22 21:26
Hello @vipinkashyap can you please verify that your IAM Policy has been updated to as described [here](https://docs.amplify.aws/gen1/react-native/build-a-backend/more-features/analytics/existing-resources/#update-your-iam-policy). This will need to be done for both your Guest role and Authenticated role which can be found here:

`AWS Console -> Cognito -> Identity pools -> Identity pool name -> User access `

In the meantime I'll look into why this documentation is excluded in Flutter.

**Comment by vipinkashyap** [comment] 2024-08-23 01:17
I can confirm that the steps you've detailed work . I am able to now use pinpoint analytics. Thank you!

**Comment by NikaHsn** [comment] 2024-08-23 16:31
@vipinkashyap thanks for confirming and gald that the issue is resolved. I will leave this issue open to update the documentation and close it after that.

**Comment by NikaHsn** [comment] 2024-09-03 20:45
I'm going to close this issue as the documentation is updated. please feel free to open a new issue if you have any other questions.

**Closed by NikaHsn** 2024-09-03 20:45 UTC
Labels: Documentation, feature-request, question, analytics
