### ISSUE TITLE
Amplify.Auth.signOut() stuck and Amplify.Auth.fetchAuthSession( ) error

### ISSUE THREAD

**Issue by betobe1898Bullground** [aws-amplify/amplify-flutter#2746] opened 2023-03-13 19:52 UTC
### Description

When running Amplify.Auth.fetchAuthSession( options: CognitoSessionOptions(getAWSCredentials: true), the following error is returned :

 "[AuthErrorHandler] The operation couldn’t be completed. (Amplify.AuthError error 2.)
flutter: UnknownException(message: Unexpected error occurred with message: User is not signed in to Cognito User Pool, please sign in to use this API., recoverySuggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Users/user/Developer/bullground/bullground_mobile/ios/Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 80, underlyingException: null)"

When running Amplify.Auth.signOut(), nothing happens
`await Amplify.Auth.signOut(); 
print('done');`

print('done') never executes and no exception is caught.

Amplify.Auth.signIn() and Amplify.Auth.signInWithWebUI() with any providers does the same behaviour 

The problem occured in IOS simulator and Physical device, but, after "Erasing All Content and Settings" in simulator, the issue no longer occurs in the simulator and everything works as expected, but this is not a good solution for production.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.0

### Amplify Flutter Version

0.6.12

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment] 2023-03-13 20:27
Hi @betobe1898Bullground - Do you know what steps you took prior to the device being in this state?

**Comment by betobe1898Bullground** [comment] 2023-03-13 21:25
Hello, these are the steps that i remember before the issue happened

-App start

`await Amplify.addPlugin(AmplifyAuthCognito());`
`await Amplify.configure(amplifyconfig);`

` final awsUser = await Amplify.Auth.fetchAuthSession(
        options: CognitoSessionOptions(getAWSCredentials: true),
      );`

-if the "user" is logged in
the user logs out using `await Amplify.Auth.signOut(
        options: const SignOutOptions(globalSignOut: true),
      );`

-else

log in: 
`await Amplify.Auth.signOut(
        options: const SignOutOptions(globalSignOut: true),`
then
 `await Amplify.Auth.signIn(
        username: username,
        password: password,
      );` or ` await Amplify.Auth.signInWithWebUI(provider: AuthProvider.facebook);`  or ` await Amplify.Auth.signInWithWebUI(provider: AuthProvider.google);` or ` await Amplify.Auth.signInWithWebUI(provider: AuthProvider.apple);` 

signUp:
`await Amplify.Auth.signUp(
        username: username,
        password: password,
      );`
``await Amplify.Auth.signOut(
        options: const SignOutOptions(globalSignOut: true),``
`await _authenticationRepository.logIn(
        username: state.email.value,
        password: state.password.value,
      );`

resetPassword
` await Amplify.Auth.resetPassword(
        username: username,
      );`
`await Amplify.Auth.confirmResetPassword(
        username: username,
        newPassword: newPassword,
        confirmationCode: confirmationCode,
      );`

**Comment by fjnoyp** [comment] 2023-03-14 15:09
Hi @betobe1898Bullground 

Thanks for sharing that.  Have you setup Social sign in for `facebook` `google` and `apple` or were you just testing those calls to see if your app would work? 

Before you encountered this error, did you modify your auth setup using the Amplify CLI or AWS?

**Comment by betobe1898Bullground** [comment] 2023-03-14 15:48
Hello,
The social sign in is already setup for facebook, google and apple, and working as they should.
And, no changes have been made to the auth setup.

**Comment by fjnoyp** [comment] 2023-03-15 00:01
Hi @betobe1898Bullground have you been able to reproduce this issue again after wiping your device and simulator?

**Comment by betobe1898Bullground** [comment] 2023-03-16 16:44
Hello, I have not been able to reproduce the issue.

**Comment by Jordan-Nelson** [comment] 2023-03-30 19:48
@betobe1898Bullground - Let us know if you see this issue again. Otherwise, since we don't have reproduction steps and it seems to be working at the moment, we will close it out and we can reopen if needed.

**Comment by Jordan-Nelson** [comment] 2023-04-10 14:51
@betobe1898Bullground - I am going to close this out. If you see this again, please let us know and try to include as much detail as possible about what steps were taken to get the device in this state.

**Closed by Jordan-Nelson** 2023-04-10 14:51 UTC
Labels: Auth, to-be-reproduced, pending-triage
