### ISSUE TITLE
signInWithWebUI issue

### ISSUE THREAD

**Issue by divyanshu2345** [aws-amplify/amplify-flutter#3123] opened 2023-05-30 14:31 UTC
### Description

Getting nonce issue 

ERROR | HostedUiStateMachine | Emitted error: InvalidStateException {
 "message": "Missing nonce"
}

### Categories

- [ ] Analytics
- [X] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1: Upgrade version
    amplify_authenticator: ^0.6.3 ==> amplify_authenticator: ^1.1.0
  amplify_flutter:^0.6.3 ==>amplify_flutter: ^1.1.0
  amplify_api: ^0.6.3 ==>   amplify_api: ^1.1.0
  amplify_auth_cognito: ^0.6.3 ==>  amplify_auth_cognito: ^1.1.0

2: final idTokenNonce = idToken.nonce;   ///////idToken.nonce getting null
    if (nonce == null || idTokenNonce == null) {
      throw const InvalidStateException('Missing nonce');
    }
    if (nonce != idTokenNonce) {
      throw const InvalidStateException('Nonce values do not match');
    }

3: getting nonce missing :
HostedUiStateMachine | Emitted error: InvalidStateException {

"message": "Missing nonce"
}

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

1.1.0

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment] 2023-05-30 20:34
Hi @divyanshu2345, sorry you are facing this issue.

Can you provide a bit more information? 
1. Which social provider are you using to login?
2. Can you share a redacted version of your `amplifyconfiguration.dart` file?
3. Does this only happen during the upgrade from 0.x -> 1.x? That is, are you able to sign in if you log out and back in?

**Comment by divyanshu2345** [comment] 2023-05-31 05:10
Hi @dnys1 ,
1:We are not using any social provider for signInWithWebUI.
2: ```
const amplifyConfig = ''' {
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "api": {
    "plugins": {
      "awsAPIPlugin": {
        "api": {
          "endpointType": "REST",
          "endpoint": "xxxxxxxxxx-xxxxxxxxxx-xxxxxxxxxx",
          "region": "xxxxxxxxxx",
          "authorizationType": "AMAZON_COGNITO_USER_POOLS"
        },
        "local": {
          "endpointType": "REST",
          "endpoint": "xxxxxxxxxx-xxxxxxxxxx-xxxxxxxxxx",
          "region": "xxxxxxxxxx",
          "authorizationType": "AMAZON_COGNITO_USER_POOLS"
        }
      }
    }
  },
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "IdentityManager": {
          "Default": {}
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "xxxxxxxxxx_XXXXXXXXX",
            "AppClientId": "xxxxxxxxxx",
            "Region": "xxxxxxxxxx"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_SRP_AUTH",
            "socialProviders": [],
            "usernameAttributes": [],
            "signupAttributes": [
              "EMAIL"
            ],
            "passwordProtectionSettings": {
            
            },
            "OAuth": {
              "WebDomain": "xxxxxxxxxx",
              "AppClientId": "xxxxxxxxxx",
              "SignInRedirectURI": "app://",
              "SignOutRedirectURI": "app://",
              "Scopes": [
                "phone",
                "email",
                "openid",
                "profile",
                "aws.cognito.signin.user.admin"
              ]
            }
          }
        }
      }
    }
  }
}''';
```
3: Yes, In version 0.6.3 to version 1.1.0. And We are able to login again but after login we are facing InvalidStateException('Missing nonce'). And we are not able to redirect to another screen.

**Comment by dnys1** [comment] 2023-05-31 15:58
Thanks for the additional information. Can I ask why you're using `signInWithWebUI` instead of `signIn`?

I will look into why `nonce` could be `null` for you as this should not happen.

**Comment by divyanshu2345** [comment] 2023-06-01 04:38
Yes, I am using signInWithWebUI instead of signIn because of development requirements.
  Thanks for quick response.

**Comment by dnys1** [comment] 2023-06-01 17:26
Hi @divyanshu2345, are you using the same identity broker mentioned in [this issue](https://github.com/aws-amplify/amplify-flutter/issues/3129) (https://github.com/awslabs/aws-amplify-identity-broker/)?

**Comment by Jordan-Nelson** [comment] 2023-06-09 17:57
@divyanshu2345 - I am going to close this as a duplicate of https://github.com/aws-amplify/amplify-flutter/issues/3129. Please let us know if you think the issue you are facing is substantially different. Thanks.

**Closed by Jordan-Nelson** 2023-06-09 17:57 UTC
Labels: Auth, pending-response, Investigating
