### ISSUE TITLE
Query never completes if it starts and then connection is lost

### ISSUE THREAD

**Issue by seanhamstra** [aws-amplify/amplify-flutter#4004] opened 2023-10-25 17:31 UTC
### Description

Seem to be able to replicate fairly easily if you have a query that takes a few seconds. Found that once it is called, after waiting a second or so, disabling connection it never seems to complete.

eg, trigger a long call:
```final response = await Amplify.API.query(request: request).response```
Wait a moment, then disable internet. Nothing is thrown and the await never completes.

When we have connection, it returns normally. If you are offline **before** firing, it correctly throws for being offline.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Setup a graphql query that takes a long time to complete (eg 3-6 seconds)
2. Await the query response
3. Wait 1-2 seconds, then disable internet
4. Future never throws nor completes.

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.7

### Amplify Flutter Version

1.4.1

### Deployment Method

Amplify CLI

**Comment by khatruong2009** [comment] 2023-11-22 20:13
Hi @seanhamstra, I was working to reproduce this issue and found that this was also happening on Android. Have you tested it on Android or have you found that you've only had this issue with iOS?

**Comment by khatruong2009** [comment] 2024-03-18 21:51
Hi @seanhamstra, I want to follow up on this issue and was wondering if you were still encountering it or if you were able to resolve it.

**Comment by khatruong2009** [comment] 2024-04-01 16:56
Hi @seanhamstra, I haven't been able to consistently reproduce this issue since November. I'm going to close this issue now since I have not been able to follow up on this issue. If you have any other issues or this issue reoccurs, please feel free to submit a new issue or reopen this one, thanks.

**Closed by khatruong2009** 2024-04-01 16:56 UTC
Labels: pending-close-response-required, to-be-reproduced, GraphQL API, Investigating
