### ISSUE TITLE
Datastore cloud don't sync with app.

### ISSUE THREAD

**Issue by willianmascimiano** [aws-amplify/amplify-flutter#1322] opened 2022-01-31 14:34 UTC
**Describe the bug**
When I delete something from APPSYNC console, why the data still on my phone?

**To Reproduce**
1) Create a data in flutter with datastore, and allow SYNC.
2) Check on AppSync if the data exists.
3) After check the existence, I DELETED from APPSYNC the data.
4) The data still stored on device, don't deleted.

**Expected behavior**
I Would like if when I delete something from AppSync / dynabodb , this modification replies to connected mobile apps.
 
**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android - MOTOG9
[x] iOS - simulator

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
    ```
MacBook-Air-de-Willian:agroeti-mobile willian$ flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-x64, locale pt-BR)
    • Flutter version 2.8.1 at /Users/willian/developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/willian/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Users/willian/Downloads/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.63.2)
    • VS Code at /Users/willian/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • moto g 9 play (mobile) • ZF5238QBLM                           • android-arm64  • Android 11 (API 30)
    • iPhone 13 (mobile)     • AF3A68CD-2EB5-43DD-85EF-7F2E271E3C07 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2
      (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 97.0.4692.99

• No issues found!
  ```
</details>

<details>

  <summary>Dependencies (<code>pubspec.lock</code>)</summary>
  
  ```
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  advance_pdf_viewer:
    dependency: "direct main"
    description:
      name: advance_pdf_viewer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  amplify_analytics_plugin_interface:
    dependency: transitive
    description:
      name: amplify_analytics_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_api:
    dependency: "direct main"
    description:
      name: amplify_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_api_plugin_interface:
    dependency: transitive
    description:
      name: amplify_api_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_auth_cognito:
    dependency: "direct main"
    description:
      name: amplify_auth_cognito
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_auth_plugin_interface:
    dependency: transitive
    description:
      name: amplify_auth_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_authenticator:
    dependency: "direct main"
    description:
      name: amplify_authenticator
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.0-rc.3"
  amplify_core:
    dependency: transitive
    description:
      name: amplify_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_datastore:
    dependency: "direct main"
    description:
      name: amplify_datastore
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_datastore_plugin_interface:
    dependency: transitive
    description:
      name: amplify_datastore_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_flutter:
    dependency: "direct main"
    description:
      name: amplify_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_storage_plugin_interface:
    dependency: transitive
    description:
      name: amplify_storage_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.8.2"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  characters:
    dependency: transitive
    description:
      name: characters
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.1"
  clock:
    dependency: transitive
    description:
      name: clock
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.15.0"
  crypto:
    dependency: transitive
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.1"
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.4"
  date_time_format:
    dependency: transitive
    description:
      name: date_time_format
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  fake_async:
    dependency: transitive
    description:
      name: fake_async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  ffi:
    dependency: transitive
    description:
      name: ffi
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.2"
  file:
    dependency: transitive
    description:
      name: file
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.1.2"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_cache_manager:
    dependency: transitive
    description:
      name: flutter_cache_manager
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.3.0"
  flutter_lints:
    dependency: "direct dev"
    description:
      name: flutter_lints
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.4"
  flutter_localizations:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  http:
    dependency: transitive
    description:
      name: http
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.13.4"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.0"
  infinite_listview:
    dependency: transitive
    description:
      name: infinite_listview
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  intl:
    dependency: "direct main"
    description:
      name: intl
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.17.0"
  json_annotation:
    dependency: transitive
    description:
      name: json_annotation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.4.0"
  lints:
    dependency: transitive
    description:
      name: lints
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  matcher:
    dependency: transitive
    description:
      name: matcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.11"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.0"
  numberpicker:
    dependency: transitive
    description:
      name: numberpicker
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.1"
  path:
    dependency: transitive
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.0"
  path_provider:
    dependency: transitive
    description:
      name: path_provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.8"
  path_provider_android:
    dependency: transitive
    description:
      name: path_provider_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.11"
  path_provider_ios:
    dependency: transitive
    description:
      name: path_provider_ios
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.7"
  path_provider_linux:
    dependency: transitive
    description:
      name: path_provider_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.4"
  path_provider_macos:
    dependency: transitive
    description:
      name: path_provider_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.4"
  path_provider_platform_interface:
    dependency: transitive
    description:
      name: path_provider_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  path_provider_windows:
    dependency: transitive
    description:
      name: path_provider_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.4"
  pedantic:
    dependency: transitive
    description:
      name: pedantic
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.11.1"
  platform:
    dependency: transitive
    description:
      name: platform
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.0"
  plugin_platform_interface:
    dependency: transitive
    description:
      name: plugin_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  process:
    dependency: transitive
    description:
      name: process
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.2.4"
  rxdart:
    dependency: transitive
    description:
      name: rxdart
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.27.3"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.1"
  sqflite:
    dependency: transitive
    description:
      name: sqflite
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  sqflite_common:
    dependency: transitive
    description:
      name: sqflite_common
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1+1"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.10.0"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  synchronized:
    dependency: transitive
    description:
      name: synchronized
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.0"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  test_api:
    dependency: transitive
    description:
      name: test_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.3"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0"
  uuid:
    dependency: transitive
    description:
      name: uuid
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.5"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.1"
  win32:
    dependency: transitive
    description:
      name: win32
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.3.3"
  xdg_directories:
    dependency: transitive
    description:
      name: xdg_directories
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0"
sdks:
  dart: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"
  ```

</details>

**Comment by HuiSF** [comment] 2022-01-31 16:13
Hi @willianmascimiano thanks for opening this issues.

>I DELETED from APPSYNC the data.

How did you delete the data? Directly delete the record from DynamoDB? Using AppSync generated delete mutation on this record model? 

**Context**

DataStore syncing is performed by:
1. Initial Sync/Delta Sync on App cold start - on every App cold start where you initiate DataStore, it will use AppSync generated "sync" API to sync new data from cloud, and delete local records that marked as deleted in the cloud
2. AppSync GraphQL subscription while App is running, realtime data sync relies on GraphQL subscription, this require a GraphQL subscription event can be properly triggered.

From your description, it sounds like you were not using AppSync generated mutation API to delete data, hence, the `onDelete` subscription event were not triggered, and end devices are not able to receive the update to delete local data.

**Comment by willianmascimiano** [comment] 2022-01-31 17:37
This is where I deleted the data.
Its has 7 data, then I deleted all. Even if I close the app and open again, the data still there. 

I will study the onDelete event, but for now, even the clean after restart could resolve for the feature I need To do.

Thanks.

![image](https://user-images.githubusercontent.com/19466705/151843820-12fbfd47-ad4f-4ad3-bbe2-6e7386643227.png)

**Comment by HuiSF** [comment] 2022-02-02 17:07
If you delete the records directly from DynamoDB, device data won't be able to sync and react, therefore the outdated data will remain in the end device.

I've explained above, here's some more details - 

DataStore relies on AppSync with Conflict Detection, which adds meta data fields into DynamoDB record, including `_deleted`, `_version` and `_lastChangedAt`.

On each initial sync (when user starts App), or `onDelete` GraphQL events are triggered, DataStore will check each records `_deleted` value, if it's true, it will remove the record from the device. 

Therefore, if you are going to **manually** delete records from DynamoDB, DataStore won't able to delete the records from end devices.

If you want to delete records from everywhere you will need to:

1. Using `Amplify.DataStore.delete` API in a device to delete the record
2. Using generate delete mutation API in AppSync

**Comment by willianmascimiano** [comment] 2022-02-04 01:04
Thanks 👍👍

**Comment by djsjr** [comment] 2022-02-06 20:44
@HuiSF I am deleting and adding content from the Admin UI. I notice that after I make a change from there, an in-app query will not reflect that change for some time. Even if I set the 'syncInterval' to something like '20' on configuration, it still does not update until I cold start the simulator. Is this the intended functionality? How often to the local database take to reflect the cloud?

**Comment by djsjr** [comment] 2022-02-08 18:45
@HuiSF For some reason, the the model I created was only syncing on cold start of the app - `query` and `observeQuery` did return most recent items. Other models were syncing. Deleting model and recreating it in my schema fixed the problem. 

Wish I had reproducible steps for you. If I encounter again I'll create an issue.

**Comment by HuiSF** [comment] 2022-02-08 18:56
Hi @djsjr sorry missed your previous comment.

>Even if I set the syncInterval to something like 20 on configuration

This `syncInterval` doesn't mean after a period of time, it will automatically sync. DataStore sync has two types under the hood, initial (full) async and delta sync. After an initial sync, within the `syncInterval` specified period of time, DataStore will only perform delta sync to accelerate and the syncing.

>Deleting model and recreating it in my schema fixed the problem.

This could be that the model schema were out of sync between cloud (AppSync) and App device. Realtime syncing depends on GraphQL subscription, when a subscription event delivered from cloud, if the data doesn't conform App device model schema, the data won't be merged into local DB.

Please feel free to reach out if encounter other issues.

**Comment by HuiSF** [comment] 2022-02-08 18:57
Hi @willianmascimiano 

> Thanks 👍👍

It looks your original issue has been resolved, I will close this issue. Please feel free to follow up and reopen if you have more question around this topic. Thanks!

**Closed by HuiSF** 2022-02-08 18:57 UTC
Labels: question, DataStore
