### ISSUE TITLE
API build failure after upgrade

### ISSUE THREAD

**Issue by alokjkumar** [aws-amplify/amplify-flutter#635] opened 2021-06-11 15:47 UTC
**Describe the bug**
After updating flutter and all other packages I get the following build error:

```
BUILD FAILED in 41s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
Building plugin amplify_api...

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/alok/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_api-0.1.5/android/build.gradle' line: 55

* What went wrong:
A problem occurred evaluating root project 'amplify_api'.
> Cannot convert a null value to an object of type Dependency.
  The following types/formats are supported:
    - Instances of Dependency.
    - String or CharSequence values, for example 'org.gradle:gradle-core:1.0'.
    - Maps, for example [group: 'org.gradle', name: 'gradle-core', version: '1.0'].
    - FileCollections, for example files('some.jar', 'someOther.jar').
    - Projects, for example project(':some:project:path').
    - ClassPathNotation, for example gradleApi().

  Comprehensive documentation on dependency notations is available in DSL reference for DependencyHandler type.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
2

Exception: The plugin amplify_api could not be built due to the issue above.
```

Flutter doctor output:

```
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.3.1 20E241 darwin-arm, locale en-GB)
    • Flutter version 2.2.1 at /Users/alok/Dev/flutter
    • Framework revision 02c026b03c (2 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/alok/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 91.0.4472.101

• No issues found!
```

**To Reproduce**
1. Run flutter upgrade
2. Run flutter pub upgrade
3. Run app

**Expected behavior**
Application should build

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[X] Android
[] iOS

**Additional context**
Running on Mac OS with M1 chip - has been problematic in the past...

**Comment by dnys1** [comment] 2021-06-18 20:46
Hi @alokjkumar - thank you for taking the time to file a bug report, and sorry you are experiencing this issue. As of now, the team has been unable to reproduce this issue given the steps provided. Would you be able to provide the project files that are leading to this issue, or are you able to create an example project which showcases the issue?

**Comment by dnys1** [comment] 2021-06-18 22:29
Hi @alokjkumar - I was able to reproduce this issue by opening the `amplify_api/android` (plugin) folder in Android Studio. Could you confirm you are working with an app of your own or the `amplify_api/example/android` (app) folder?

**Comment by alokjkumar** [comment] 2021-06-18 22:33
@dnys1 Hi, the issue is occurring with my own app only when I run flutter pub upgrade

**Comment by dnys1** [comment] 2021-06-18 22:37
Thank you for confirming, @alokjkumar. Are you able to share you `build.gradle` and `settings.gradle` files? And can you confirm there is a file called `.flutter-plugins-dependencies` in the root of your project?

**Comment by alokjkumar** [comment] 2021-06-18 22:40
@dnys1 - added you to the repo

**Comment by dnys1** [comment] 2021-06-18 22:46
You're the man - thanks. I will have a look and get back to you shortly.

**Comment by dnys1** [comment] 2021-06-18 23:11
Hi @alokjkumar  - thank you again for sharing your code. I was able to run `flutter pub upgrade` and build the app successfully via the command line and Android Studio. Could you try a few things for me?
1. Run `flutter clean && flutter pub get`
2. Confirm that a file named `.flutter-plugins-dependencies` exists in the root of your project.
3. Confirm that `android/local.properties` has a `flutter.sdk` property which points to your Flutter installation.
4. Try running the project again.

Thanks for your patience working through this issue.

**Comment by epomeranz** [comment] 2021-07-22 16:20
Hi @dnys1 I'm trying to run the example app and I have the exact same issue. I checked all your suggestions and I still have the same issue.

Any ideas?

Thanks :)

**Comment by dnys1** [comment] 2021-07-29 00:25
Hi @epomeranz - sorry for the late response. Are you using the `melos bs` command by chance before running the app? I believe this may be an issue with melos. Can you try running the app using the `flutter run` command before running it in an IDE like Android Studio?

**Comment by alamo88** [comment] 2021-08-02 17:45
I too am facing this issue. It was able to run previously and all of a sudden i get the same error. I am using VS code to run in MacOS.

**Comment by yukitaka13-1110** [comment] 2021-08-09 06:22
Any update?

**Comment by djsjr** [comment] 2021-09-01 21:22
Receiving same error message using android studio. Tried steps suggested above to no avail. #432 seems to be similar, but with auth instead of api being the issue.

**Comment by abdallahshaban557** [comment] 2021-11-09 17:08
Is there anyone still facing this issue?

**Comment by dnys1** [comment] 2021-11-17 18:48
This should be fixed now when running `melos bs` in the package repository. If anyone is still experiencing this issue, please reopen with the setup you're using so that we may try to reproduce.

**Closed by dnys1** 2021-11-17 18:48 UTC
Labels: Android, API
