### ISSUE TITLE
Application on Android Device Fails

### ISSUE THREAD

**Issue by ianfmc** [aws-amplify/amplify-flutter#1688] opened 2022-06-04 21:59 UTC
### Description

Application functions normally on Android and iOS emulator. Application functions normally when tethered via USB or WiFi on Android, and then tethered on iOS. Application functions normally on iOS device (iPhone). Application fails after during authentication and connection to datastore on actual Android device (TCL A509DL). Running Android version 11, security patch level of April 5, 2022.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [X] Auth
- [X] Authenticator
- [X] DataStore
- [ ] Storage

### Steps to Reproduce

See screenshots below. There are two files: one showing the application running while in Wireless debugging mode (and working) and the other on the actual device (failing).

https://user-images.githubusercontent.com/5844059/172026670-23073329-ac33-42a5-916d-3cf512cd8a12.mp4

https://user-images.githubusercontent.com/5844059/172026675-373e1685-c7d7-415e-9418-02456fdb3d40.mp4

.

### Platforms

- [ ] iOS
- [X] Android

### Environment

```bash
/Users/ianmccal/Development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.4 21F79 darwin-x64, locale en-US)
    • Flutter version 2.10.5 at /Users/ianmccal/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (7 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/ianmccal/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
Process finished with exit code 0
```

### Dependencies

```bash
flutter pub deps --no-dev --style=compact
Changing current working directory to: /Users/ianmccal/Development/elys_mobile
Dart SDK 2.16.2
Flutter SDK 2.10.5
elys_mobile 0.8.11+32

dependencies:
- amplify_api 0.5.1 [amplify_api_plugin_interface amplify_core amplify_api_android amplify_api_ios collection flutter meta plugin_platform_interface]
- amplify_auth_cognito 0.5.1 [amplify_auth_cognito_android amplify_auth_cognito_ios amplify_auth_plugin_interface amplify_core collection flutter plugin_platform_interface]
- amplify_core 0.5.1 [collection date_time_format flutter meta plugin_platform_interface uuid]
- amplify_datastore 0.5.1 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.5.1 [amplify_analytics_plugin_interface amplify_api_plugin_interface amplify_auth_plugin_interface amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios amplify_storage_plugin_interface collection flutter json_annotation meta plugin_platform_interface]
- amplify_storage_s3 0.5.1 [flutter amplify_storage_plugin_interface plugin_platform_interface amplify_storage_s3_android amplify_storage_s3_ios amplify_core]
- camera 0.9.7+1 [camera_platform_interface camera_web flutter flutter_plugin_android_lifecycle quiver]
- cupertino_icons 1.0.4
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutter_libphonenumber 1.2.4 [flutter]
- flutter_spinkit 5.1.0 [flutter]
- google_fonts 3.0.1 [flutter http path_provider crypto]
- image_picker 0.8.5+3 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
- intl 0.17.0 [clock path]
- path_provider 2.0.10 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- permission_handler 9.2.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- url_launcher 6.1.2 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- video_player 2.4.2 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]

transitive dependencies:
- amplify_analytics_plugin_interface 0.5.1 [amplify_core flutter meta]
- amplify_api_android 0.5.1 [flutter]
- amplify_api_ios 0.5.1 [amplify_core flutter]
- amplify_api_plugin_interface 0.5.1 [amplify_core collection flutter json_annotation meta]
- amplify_auth_cognito_android 0.5.1 [flutter]
- amplify_auth_cognito_ios 0.5.1 [amplify_core flutter]
- amplify_auth_plugin_interface 0.5.1 [amplify_core flutter meta]
- amplify_datastore_plugin_interface 0.5.1 [flutter meta collection amplify_core]
- amplify_flutter_android 0.5.1 [flutter]
- amplify_flutter_ios 0.5.1 [amplify_core flutter]
- amplify_storage_plugin_interface 0.5.1 [flutter meta amplify_core]
- amplify_storage_s3_android 0.5.1 [flutter]
- amplify_storage_s3_ios 0.5.1 [flutter]
- async 2.8.2 [collection meta]
- camera_platform_interface 2.2.0 [cross_file flutter plugin_platform_interface stream_transform]
- camera_web 0.2.1+6 [camera_platform_interface flutter flutter_web_plugins stream_transform]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.15.0
- cross_file 0.3.3+1 [js meta]
- crypto 3.0.2 [typed_data]
- csslib 0.17.2 [source_span]
- date_time_format 2.0.1
- ffi 1.2.1
- file 6.1.2 [meta path]
- flutter_plugin_android_lifecycle 2.0.6 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- html 0.15.0 [csslib source_span]
- http 0.13.4 [async http_parser meta path]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- image_picker_android 0.8.4+13 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.8 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.5+5 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.5.0 [cross_file flutter http plugin_platform_interface]
- js 0.6.3
- json_annotation 4.5.0 [meta]
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- path 1.8.0
- path_provider_android 2.0.14 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.9 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.6 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.6 [ffi flutter path path_provider_platform_interface win32]
- permission_handler_android 9.0.2+1 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.0.4 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.0 [flutter permission_handler_platform_interface]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- quiver 3.1.0 [matcher]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- typed_data 1.3.0 [collection]
- url_launcher_android 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.0.5 [flutter plugin_platform_interface]
- url_launcher_web 2.0.11 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- uuid 3.0.6 [crypto]
- vector_math 2.1.1
- video_player_android 2.3.4 [flutter video_player_platform_interface]
- video_player_avfoundation 2.3.4 [flutter video_player_platform_interface]
- video_player_platform_interface 5.1.2 [flutter plugin_platform_interface]
- video_player_web 2.0.10 [flutter flutter_web_plugins video_player_platform_interface]
- win32 2.5.2 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
```

### Device

TCL A509DL

### OS

Android 11

### CLI Version

8.3.1

### Additional Context

From the build.gradle

```
compileSdkVersion 31

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "com.desertdigital.elysmobile"
        minSdkVersion 30
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

```

**Comment by Jordan-Nelson** [comment] 2022-06-06 14:07
Hi @ianfmc - Thanks for taking the time to open the issue. I have a few follow up questions based on the info you have provided.

1. When you are testing on Android tethered via USB, are you testing in release mode? If not, can you attempt in release mode?
2. In the first screen capture, does the app crash after login? I can see that the app closes, but it is hard to tell from the screen recording if the app crashes for if it is manually closed.
3. Are you capturing any logs? It would help to capture any exceptions that are being thrown as well as crash reports.
4. Have you tested this on other Android devices? It would be helpful to know if this is specific to certain devices.

**Comment by ianfmc** [comment] 2022-06-06 15:51
Hi Jordan: 

Thanks so much for the very detailed response. 

1. I hadn't, but I will this morning.
2. It does crash right after the login (not manually closed)
3. Not sure how to do that -- can you recommend good documentation on how to generate the logs and crash reports? I definitely want to set that up
4. Unfortunately, the only actual android device I have is the TCL...I will check with one of my testers to see what happens on their device (which I am reasonably sure is not the TCL).

Please let know about 3 and I'll follow up on 1 and 4. 

Thanks!!

**Comment by ianfmc** [comment] 2022-06-06 18:10
Hi again Jordan:

1. Yes: release mode (please see attached codemagic screenshot).
2. N/A
3. Please let me know
4. Same result (crashes after login page) on a Galaxy 6
<img width="1440" alt="Screen Shot 2022-06-06 at 11 08 37" src="https://user-images.githubusercontent.com/5844059/172220199-0deca73e-2f4b-4b89-b95a-cc233dff10bd.png">
.

**Comment by Jordan-Nelson** [comment] 2022-06-06 19:43
If you are able to reproduce this when your device is tethered via USB, can you run `flutter run --release -d=<your_device_id>` and then capture the logs while you reproduce it? I believe you will get some output when the app crashes. That would be a good starting point.

**Comment by ianfmc** [comment] 2022-06-06 20:34
When I try to run I get the following errors

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':image_picker_android:debugUnitTestRuntimeClasspath'.
   > Failed to transform bcprov-jdk15on-1.68.jar (org.bouncycastle:bcprov-jdk15on:1.68) to match attributes {artifactType=processed-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: /Users/ianmccal/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.68/46a080368d38b428d237a59458f9bc915222894d/bcprov-jdk15on-1.68.jar.
         > Failed to transform '/Users/ianmccal/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.68/46a080368d38b428d237a59458f9bc915222894d/bcprov-jdk15on-1.68.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 59. (Run with --stacktrace for more details.)
           Suggestions:
            - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&s=modified_time:desc, it's possible that this issue has already been filed there.
            - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 48s
Running Gradle task 'assembleRelease'...                          169.8s
Exception: Gradle task assembleRelease failed with exit code 1
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:406:9)
<asynchronous suspension>
#2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:184:5)
<asynchronous suspension>
#3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:577:7)
<asynchronous suspension>
#4      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:505:33)
<asynchronous suspension>
#5      ColdRunner.run (package:flutter_tools/src/run_cold.dart:71:28)
<asynchronous suspension>
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:692:26)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>


```

When I build, I get the following result: 

```
Changing current working directory to: /Users/ianmccal/Development/elys_mobile

💪 Building with sound null safety 💪

Removed unused resources: Binary resource data reduced from 788KB to 715KB: Removed 9%
Running Gradle task 'bundleRelease'...                            129.3s
✓ Built build/app/outputs/bundle/release/app-release.aab (27.5MB).
```

**Comment by ianfmc** [comment] 2022-06-06 20:50
I added Sentry. Here's what the error is:

```

IllegalAccessError: Illegal class access: 'com.amplifyframework.datastore.syncengine.SubscriptionProcessor' attempting to access 'f.b.a.e.e.e.d$a' (declaration of 'com.amplifyframework.datastore.syncengine.SubscriptionProcessor' appears in /data/app/~~ki45KIZ9gDtGqIRw2UnBCg==/com.desertdigital.elysmobile-SoTH5Dnnon2OD8bFFuIIlw==/base.apk)
```

**Comment by ianfmc** [comment] 2022-06-07 13:37
Hi Jordan: so build with '--no-shrink' and run again? Thanks, Ian.

**Comment by Jordan-Nelson** [comment] 2022-06-07 17:21
> Hi Jordan: so build with '--no-shrink' and run again? Thanks, Ian.

Correct

**Comment by ianfmc** [comment] 2022-06-07 19:05
I built with --no-shrink and got the following results.

```

IllegalAccessError: Illegal class access: 'com.amplifyframework.datastore.syncengine.SubscriptionProcessor' attempting to access 'f.b.a.e.e.e.d$a' (declaration of 'com.amplifyframework.datastore.syncengine.SubscriptionProcessor' appears in /data/app/~~F1V5vDERjtG8XRP6fUR2Ag==/com.desertdigital.elysmobile--zX9SWQxVFOUB6pgEUFUjA==/base.apk)
```

Doesn't appear to be any change. How can I be sure the build was really --no-shrink? I'm using sentry to find this error.

**Comment by Jordan-Nelson** [comment] 2022-06-07 19:38
> I assume you're trying to figure out exactly where in the datastore library there is an issue, right?

Yes, sort of. It would be great if we could reveal the source of the issue. Although I suspect that minification and/or obfuscation is removing something that is needed.

I remembered that there was [an issue](https://github.com/aws-amplify/amplify-flutter/issues/828) opened a while back that was very similar to this. It was resolved, but possibly a similar issue has been reintroduced.

Can you share your `android/app/build.gradle` file? In particular I am interested in the `buildTypes` section and wether or not you have minification and/or shrinking enabled.

Others were able to work around the previous issue by following [this comment](https://github.com/aws-amplify/amplify-flutter/issues/828#issuecomment-905963525). If you want you can attempt to build/test the app with those changes, although if you don't have minification and/or shrinking enabled, I believe it is off by default.

**Comment by ianfmc** [comment] 2022-06-07 20:56
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
  keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 31

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "com.desertdigital.elysmobile"
        minSdkVersion 30
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    signingConfigs {
      release {
        if (System.getenv()["CI"]) { // CI=true is exported by Codemagic
            storeFile file(System.getenv()["CM_KEYSTORE_PATH"])
            storePassword System.getenv()["CM_KEYSTORE_PASSWORD"]
            keyAlias System.getenv()["CM_KEY_ALIAS"]
            keyPassword System.getenv()["CM_KEY_PASSWORD"]
        } else {
          keyAlias keystoreProperties['keyAlias']
          keyPassword keystoreProperties['keyPassword']
          storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
          storePassword keystoreProperties['storePassword']
        }
      }
    }
    buildTypes {
      release {
        signingConfig signingConfigs.release
      }
    }

}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "com.google.android.material:material:1.5.0"
}

```

**Comment by ianfmc** [comment] 2022-06-07 21:22
I'm trying a new build with the suggested changes from #828.

**Comment by ianfmc** [comment] 2022-06-07 21:47
Seems to have worked. What exactly did I do? (:

**Comment by Jordan-Nelson** [comment] 2022-06-09 22:09
@ianfmc My initial attempt to reproduce this was unsuccessful. I was able to build and app using API & DataStore in release mode and run it. I tested on a Pixel 3a. Have you had a chance to reproduce this on any other devices?

**Comment by ianfmc** [comment] 2022-06-10 01:05
Hi Jordan: I don’t have any other physical devices, but it is running on the Galaxy and the TCL A509DL.    

I will try it again, but I’m in the middle of testing for a July release…recommendations?

**Comment by ianfmc** [comment] 2022-06-10 23:47
Hey Jordan: the Galaxy is using version 11. I’m using 1.6.1. See below. Thanks, Ian

**Comment by ianfmc** [comment] 2022-06-10 23:51
Sorry: 1.6.21

```
buildscript {
    ext.kotlin_version = '1.6.21'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

**Comment by Jordan-Nelson** [comment] 2022-06-13 16:52
@ianfmc - Can you try to upgrade the version of gradle to 6.2+. Projects created with the latest version of flutter use 7.1.4 I believe, so you can likely upgrade to that version if you are using the latest version of flutter.

We had removed a temporary fix that was only needed for gradle version lower than 6.2 in the 0.5.0 release. It looks like this was not clearly called out in the release notes/docs. Apologies for that.

**Comment by ianfmc** [comment] 2022-06-14 23:23
Hi Jordan: I upgraded. Should I now try to run w/o the workaround? Thanks.

**Comment by Jordan-Nelson** [comment] 2022-06-15 11:31
Yes. See if you can run it in release mode without the workaround now.

**Comment by Jordan-Nelson** [comment] 2022-06-30 19:17
@ianfmc were you able to test that out?

**Comment by ragingsquirrel3** [comment] 2022-07-21 16:32
Glad it's working! closing this

**Closed by ragingsquirrel3** 2022-07-21 16:32 UTC
Labels: Build, pending-response, pending-triage
