### ISSUE TITLE
[api] Model helpers should not pass `null` fields

### ISSUE THREAD

**Issue by dnys1** [aws-amplify/amplify-flutter#2492] opened 2022-12-15 17:55 UTC
### Description

AppSync interprets explicit `null` values different than implicit ones in the `variables` map of a request. Model helpers explicitly setting these values can lead to unexpected errors when these fields are read-only or otherwise protected.

For example, consider the schema:

```graphql
type Todo @model @auth(rules: [{ allow: public }, { allow: owner, ownerField: "owners" }]) {
  id: ID!
  name: String!
  owners: [String]
  private: String @auth(rules: [{ allow: owner, ownerField: "owners" }])
}
```

And a mutation to create a `Todo`:

```graphql
mutation CreateTodo($input: CreateTodoInput!) {
  createTodo(input: $input) {
    id
    name
    owners
    private
    createdAt
    updatedAt
  }
}
```

The following input allows creation with no issues: 

```json
{
  "input": {
    "name": "test",
    "private": "secret"
  }
}
```

However, model helpers generates the following input (notice the inclusion of `owners` which cannot be written to):

```json
{
  "input": {
    "name": "test",
    "owners": null,
    "private": "secret"
  }
}
```

This leads to the following error:

```json
{
  "data": {
    "createTodo": null
  },
  "errors": [
    {
      "path": [
        "createTodo"
      ],
      "data": null,
      "errorType": "Unauthorized",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Not Authorized to access createTodo on type Todo"
    }
  ]
}
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment

```bash
N/A
```

### Dependencies

```bash
vNext
```

### Device

N/A

### OS

N/A

### Deployment Method

Amplify CLI

### Amplify Config

N/A

**Comment by ragingsquirrel3** [comment] 2022-12-21 16:16
I made a PR for this. Noted in the PR description but IMO we should not remove all null values from mutation input (plenty of valid use cases for doing that), only null values when they are owner fields.

**Comment by okhomin** [comment] 2022-12-24 15:30
I faced the same issue for my model:
```
type UserInfo @model @auth(rules: [{allow: owner}]) {
  id: ID!
  owner: String @auth(rules: [{ allow: owner, operations: [read, delete] }]) # prevent reassigning of user
  nickname: String
  firstLineAddress: String
  secondLineAddress: String
}
```
And `amplify codegen models` generates this code:
```
  Map<String, dynamic> toJson() => {
    'id': id, 'owner': _owner, 'nickname': _nickname, 'firstLineAddress': _firstLineAddress, 'secondLineAddress': _secondLineAddress, 'createdAt': _createdAt?.format(), 'updatedAt': _updatedAt?.format()
  };
  ```
  So instead of a json without the `owner` field it sends a json with `"owner": null`, which leads to the `Unauthorized` error.

**Comment by okhomin** [comment] 2022-12-24 15:32
@ragingsquirrel3 Is there a workaround before your fix?
Currently I have to manually fix the generated models.

**Comment by ragingsquirrel3** [comment] 2022-12-27 16:08
@okhomin yes there is a workaround. You basically have to remove the unwanted keys from the request input variables and copy to a new request like this:

```dart
final Blog blog = Blog(id: id, name: name);
final GraphQLRequest<Blog> req = ModelMutations.create<Blog>(blog);
final modifiedInputVariables =
    req.variables['input'] as Map<String, dynamic>;
modifiedInputVariables.remove('owners');
final modifiedVariables = {'input': modifiedInputVariables};
final modifiedRequest = GraphQLRequest<Blog>(
  document: req.document,
  decodePath: req.decodePath,
  modelType: req.modelType,
  variables: modifiedVariables,
);
final operation = Amplify.API.query(request: modifiedRequest);
```

**Comment by theartofnonso** [comment] 2023-02-10 00:11
Update as of today, I was experiencing this issue with the stable release (v0.6.12). However I switched to the developer preview version (v1.0.0-next.4).

I can confirm that the issue is still happening in the stable release but the dev preview is fine.

I guess I will be sticking to the working version.

**Comment by Jordan-Nelson** [comment] 2023-04-17 19:00
This issue has been addressed in v1.0.0 of Amplify Flutter, which is now stable. This release also includes web and desktop support for Auth, API, Analytics, and Storage. You can see the list of new features and bug fixes in the [release notes](https://github.com/aws-amplify/amplify-flutter/releases/tag/v1.0.0), and see more details on how to migrate in the [upgrade guide](https://docs.amplify.aws/lib/project-setup/upgrade-guide/q/platform/flutter/).

**Closed by Jordan-Nelson** 2023-04-17 19:00 UTC
Labels: bug, GraphQL API, fixed-in-release-candidate

**Comment by maziarzamani** [comment] 2023-08-21 19:55
I have the same problem with amplify_flutter=1.3.1. Is this is a bug?

**Comment by dnys1** [comment] 2023-08-21 20:02
Hi @maziarzamani. Would you be able to create a new issue with details about your schema and the issue you're facing?

**Comment by maziarzamani** [comment] 2023-08-22 06:49
Long story short, it seems to be a bug in the SDK, if any AWS personnel needs a reference to the case ID, please let me know. I'd really love if this bug was fixed as I have many read-only field permission in my GraphQL schema.
