### ISSUE TITLE
observeQuery does not return complete objects.

### ISSUE THREAD

**Issue by bibaswan-bhawal** [aws-amplify/amplify-flutter#2048] opened 2022-08-18 17:06 UTC
### Description

My team is working on a chat application where we open a observeQuery stream to observe for changes in a Room model. We have a three models, a User Model containing information about a user, Room Model which just contains an Id and last message sent. We also have a Message model which holds the string message and a User object with a belongsTo relationship. The observeQuery correctly returns the list of messages for a given room however, when we send a message the message gets saved using Amplify.Datastore.save(message) and the observeQuery returns message however the message it returns contains a User object with only an ID and all other fields are null. If we restart the screen (navigate away from the widget and back) then the observeQuery returns the full message object with the complete user object. 

The bug - Message object returned with User object with null fields.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Screenshots

printing in build method of widget:
message after calling Datastore.save(message)
![2022-08-18 10_03_18-Run - socale](https://user-images.githubusercontent.com/67685395/185453641-a6370db5-b1d9-444f-b951-7a5bbe68ca33.png)

message after reloading widget
![2022-08-18 10_03_33-Run - socale](https://user-images.githubusercontent.com/67685395/185453656-0a319302-7960-4f57-bdf0-51194a40ad64.png)

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Android Device/Emulator API Level

API 32+

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.3, on Microsoft Windows [Version 10.0.22621.382], locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.16)
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.70.1)
[✓] Connected device (5 available)
[✓] HTTP Host Availability
```

### Dependencies

```bash
Dart SDK 2.17.5
Flutter SDK 3.0.3
socale 1.0.0+1

dependencies:
- amplify_analytics_pinpoint 1.0.0-next.0 [amplify_analytics_pinpoint_android amplify_analytics_pinpoint_ios amplify_core aws_common flutter meta]
- amplify_api 1.0.0-next.0+1 [amplify_api_android amplify_api_ios amplify_core amplify_flutter aws_common collection flutter meta plugin_platform_interface]
- amplify_auth_cognito 1.0.0-next.0+4 [amplify_auth_cognito_android amplify_auth_cognito_dart amplify_auth_cognito_ios amplify_core amplify_flutter amplify_secure_storage async flutter flutter_web_plugins meta path plugin_platform_interface]
- amplify_datastore 1.0.0-next.0 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 1.0.0-next.0+1 [amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios amplify_secure_storage aws_common collection flutter meta plugin_platform_interface]
- amplify_secure_storage 0.1.0 [amplify_secure_storage_dart flutter]
- amplify_storage_s3 1.0.0-next.0 [amplify_storage_s3_android amplify_storage_s3_ios amplify_core aws_common flutter meta plugin_platform_interface]
- animations 2.0.3 [flutter]
- aws_common 0.2.2 [async collection http logging meta stream_transform uuid]
- aws_signature_v4 0.2.1 [async aws_common collection convert crypto http json_annotation meta path]
- cupertino_icons 1.0.5
- encrypt 5.0.1 [args asn1lib clock collection crypto pointycastle]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_chat_types 3.4.5 [equatable json_annotation meta]
- flutter_chat_ui 1.5.8 [flutter diffutil_dart equatable flutter_chat_types flutter_link_previewer flutter_parsed_text intl meta photo_view url_launcher visibility_detector]
- flutter_dotenv 5.0.2 [flutter]
- flutter_image_compress 1.1.1 [flutter]
- flutter_riverpod 2.0.0-dev.9 [collection flutter meta riverpod state_notifier]
- flutter_svg 1.1.4 [flutter meta path_drawing vector_math xml]
- get 4.6.5 [flutter]
- get_it 7.2.0 [async collection]
- google_fonts 3.0.1 [flutter http path_provider crypto]
- hive 2.2.3 [meta crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- image_picker 0.8.5+3 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
- injectable 1.5.3 [get_it]
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- pin_code_fields 7.4.0 [flutter]
- provider 6.0.3 [collection flutter nested]

transitive dependencies:
- amplify_analytics_pinpoint_android 1.0.0-next.0 [flutter]
- amplify_analytics_pinpoint_ios 1.0.0-next.0 [flutter]
- amplify_api_android 1.0.0-next.0 [flutter]
- amplify_api_ios 1.0.0-next.0 [amplify_core flutter]
- amplify_auth_cognito_android 1.0.0-next.0+1 [flutter]
- amplify_auth_cognito_dart 0.1.5 [amplify_core amplify_secure_storage_dart async aws_common aws_signature_v4 built_collection built_value collection convert crypto fixnum http intl js json_annotation meta oauth2 path smithy smithy_aws stream_transform uuid worker_bee]
- amplify_auth_cognito_ios 1.0.0-next.0+1 [amplify_core flutter]
- amplify_core 1.0.0-next.0 [async aws_common aws_signature_v4 collection http intl json_annotation logging meta uuid]
- amplify_datastore_plugin_interface 1.0.0-next.0 [amplify_core collection flutter meta]
- amplify_flutter_android 1.0.0-next.0 [flutter]
- amplify_flutter_ios 1.0.0-next.0 [amplify_core flutter]
- amplify_secure_storage_dart 0.1.0 [aws_common built_collection built_value ffi js meta win32 worker_bee]
- amplify_storage_s3_android 1.0.0-next.0 [flutter]
- amplify_storage_s3_ios 1.0.0-next.0 [flutter]
- args 2.3.1
- asn1lib 1.1.0
- async 2.8.2 [collection meta]
- built_collection 5.1.1
- built_value 8.4.0 [built_collection collection fixnum meta]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.16.0
- convert 3.0.2 [typed_data]
- crclib 3.0.0 [meta tuple]
- cross_file 0.3.3+1 [js meta]
- crypto 3.0.2 [typed_data]
- csslib 0.17.2 [source_span]
- diffutil_dart 3.0.0
- equatable 2.0.3 [collection meta]
- ffi 2.0.1
- file 6.1.3 [meta path]
- fixnum 1.0.1
- flutter_link_previewer 2.6.6 [flutter flutter_chat_types flutter_linkify html http linkify meta url_launcher]
- flutter_linkify 5.0.2 [flutter linkify]
- flutter_parsed_text 2.2.1 [flutter]
- flutter_plugin_android_lifecycle 2.0.7 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- html 0.15.0 [csslib source_span]
- http 0.13.5 [async http_parser meta path]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- image_picker_android 0.8.5+2 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.8 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.5+6 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.6.1 [cross_file flutter http plugin_platform_interface]
- intl 0.17.0 [clock path]
- js 0.6.4
- json_annotation 4.6.0 [meta]
- linkify 4.1.0
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- nested 1.0.0 [flutter]
- oauth2 2.0.0 [collection crypto http http_parser]
- path 1.8.1
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.0.19 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.2 [ffi flutter path path_provider_platform_interface win32]
- petitparser 5.0.0 [meta]
- photo_view 0.13.0 [flutter]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- pointycastle 3.6.1 [collection convert js]
- process 4.2.4 [file path platform]
- quiver 3.1.0 [matcher]
- retry 3.1.0
- riverpod 2.0.0-dev.9 [collection meta stack_trace state_notifier]
- shelf 1.3.2 [async collection http_parser path stack_trace stream_channel]
- sky_engine 0.0.99
- smithy 0.1.0 [aws_common built_collection built_value collection convert crypto fixnum http http_parser intl json_annotation meta path retry shelf typed_data xml]
- smithy_aws 0.1.1 [aws_common aws_signature_v4 built_collection built_value collection crclib http intl json_annotation meta path smithy xml]
- source_span 1.8.2 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- state_notifier 0.7.2+1 [meta]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- tuple 2.0.0 [quiver]
- typed_data 1.3.1 [collection]
- url_launcher 6.1.5 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_launcher_android 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.0 [flutter plugin_platform_interface]
- url_launcher_web 2.0.13 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
- visibility_detector 0.3.3 [flutter]
- win32 2.7.0 [ffi]
- worker_bee 0.1.0 [async aws_common built_collection built_value collection js meta path stack_trace stream_channel stream_transform]
- xdg_directories 0.2.0+1 [meta path process]
- xml 6.1.0 [collection meta petitparser]
```

### Device

Pixel 5 - API 33

### OS

Android Api 33

### Deployment Method

Amplify CLI

### CLI Version

9.2.1

### Amplify Config

```
const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "socale": {
                    "endpointType": "GraphQL",
                    "endpoint":  -----------------------,
                    "region":  -----------------------,
                    "authorizationType": "API_KEY",
                    "apiKey": -----------------------
                }
            }
        }
    },
    "analytics": {
        "plugins": {
            "awsPinpointAnalyticsPlugin": {
                "pinpointAnalytics": {
                    "appId":  ----------------------,
                    "region":  -----------------------
                },
                "pinpointTargeting": {
                    "region":  -----------------------
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl":  -----------------------,
                        "Region":  -----------------------,
                        "AuthMode":  -----------------------,
                        "ApiKey":  -----------------------,
                        "ClientDatabasePrefix":  -----------------------
                    },
                    "socale_AWS_IAM": {
                        "ApiUrl":  -----------------------,
                        "Region":  -----------------------,
                        "AuthMode": "AWS_IAM",
                        "ClientDatabasePrefix":  -----------------------
                    }
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId":  -----------------------,
                            "Region":  -----------------------
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId":  -----------------------,
                        "AppClientId":  -----------------------,
                        "Region":  -----------------------
                    }
                },
                "GoogleSignIn": {
                    "Permissions":  -----------------------,
                    "ClientId-WebApp":  -----------------------
                },
                "FacebookSignIn": {
                    "AppId":  -----------------------
                    "Permissions":  -----------------------
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain":  -----------------------,
                            "AppClientId": -----------------------,
                            "SignInRedirectURI":  -----------------------,
                            "SignOutRedirectURI":  -----------------------,
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [
                            "FACEBOOK",
                            "GOOGLE",
                            "APPLE"
                        ],
                        "usernameAttributes": [
                            "EMAIL"
                        ],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                },
                "PinpointAnalytics": {
                    "Default": {
                        "AppId":  -----------------------,
                        "Region":  -----------------------
                    }
                },
                "PinpointTargeting": {
                    "Default": {
                        "Region":  -----------------------
                    }
                },
                "S3TransferUtility": {
                    "Default": {
                        "Bucket":  -----------------------,
                        "Region": " -----------------------
                    }
                }
            }
        }
    },
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket":  -----------------------,
                "region":  -----------------------,
                "defaultAccessLevel": "guest"
            }
        }
    }
}''';
```

**Comment by HuiSF** [comment] 2022-08-18 17:09
Does this happen in iOS?

May be related to https://github.com/aws-amplify/amplify-flutter/issues/1355

**Comment by bibaswan-bhawal** [comment] 2022-08-18 17:11
I'm not sure, I don't have the ability to test on IOS however, I am pretty user it is related to the same issue.

**Comment by Jordan-Nelson** [comment] 2022-08-18 19:25
@bibaswan-bhawal - Can you share you schema (schema.graphql)?

**Comment by Jordan-Nelson** [comment] 2022-08-18 19:32
Might be related to https://github.com/aws-amplify/amplify-flutter/issues/943

@bibaswan-bhawal - Are you testing this across two devices? That is, are you calling DataStore.observeQuery() on device A and DataStore.save() on device B, or is this all within a single device?

It should work either way, but knowing if you are testing across devices will help us reproduce this and determine the root cause.

**Comment by bibaswan-bhawal** [comment] 2022-08-18 21:07
Hi @Jordan-Nelson I am testing this on two devices the data is synced fine when data saving on device A and viewing on device B but on device A itself the model isn’t being saved correctly

**Comment by Jordan-Nelson** [comment] 2022-08-19 00:11
Okay thanks. Would you be able to share your schema so that we can try to reproduce it with the same schema?

**Comment by bibaswan-bhawal** [comment] 2022-08-19 01:31
also this is how we open the stream 

```
_stream = Amplify.DataStore.observeQuery(
      Message.classType,
      where: Message.ROOM.eq(widget.room.id)
    ).listen((QuerySnapshot<Message> snapshot) {
      if (snapshot.isSynced) {
        setState(() {
          _messages = snapshot.items;
        });
      }
    });
```

 and this is how we save the model 

```

    final message = Message(
      encryptedText: text,
      author: user,
      room: currentRoom,
      createdAt: TemporalDateTime.now(),
    );

    await Amplify.DataStore.save(message);

```

**Comment by fjnoyp** [comment] 2022-08-19 12:34
Thanks for providing the schema.  Will look to reproduce your issue later today.

**Comment by bibaswan-bhawal** [comment] 2022-08-20 19:29
any updates? 

For anymore else facing this issue the nested object that is returned does contain the id field so we just run another query to get the full object itself. This is a work around though and has resulted in many more queries to the database than would be required if the object returned was complete.

**Comment by Jordan-Nelson** [comment] 2022-08-21 14:11
@bibaswan-bhawal - Is the stream returned by observeQuery emitting more than 1 snapshot when using the query predicate in the code snippet you shared above?

There is a know issue with query predicates on nested models (https://github.com/aws-amplify/amplify-flutter/issues/2039). This issue prevents anything other than the initial snapshot from being returned.

**Comment by bibaswan-bhawal** [comment] 2022-08-21 16:00
@Jordan-Nelson Well observeQuery doesn't even work with queryPredicates (i never got any snapshots back) I actually used your draft pull request to get it working.

**Comment by bibaswan-bhawal** [comment] 2022-08-21 16:03
also the query predicate isn't causing the problem since it still happens even you take out the query predicate. From a little more investigation what I found was that when enqueuing the mutation Datastore only saves the ids of nested objects so I suspect the snapshot returned is using the object enqueued for mutation instead of the actual object. You can see this behaviour if you try to save a message object with a room and user and look at the logs when the save method is called.

**Comment by Jordan-Nelson** [comment] 2022-08-22 15:45
> Well observeQuery doesn't even work with queryPredicates (i never got any snapshots back) I actually used your draft pull request to get it working.

Yes, there is a known issue when using a predicate with a nested model (filtering Messages by the User ID). If you are seeing issue with other predicates (for example, filtering Messages by `createdAt`) please let me know.

I am trying to create a minimal reproduction of this issue via an integration test. So far I haven't been able to do that. I have created an integration test in a new app using the same schema as you provided, and I am seeing nested data return from observeQuery. Would you be able to run the following integration test within your app? If this is failing for you, then I will need to determine what is different about set up (device, OS, etc.)

This will require adding an `integration_test` dir if you do not have one, and adding the dependency `integration_test` as a dev dependency as follows. 

Dev dependency update:
```yaml
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
```

Integ test file: `integration_test/main_test.dart`
```dart
import 'package:amplify_datastore/amplify_datastore.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import 'package:<app_name>/amplifyconfiguration.dart';
import 'package:<app_name>/models/ModelProvider.dart';

Future<void> configureDataStore() async {
  final dataStorePlugin = AmplifyDataStore(
    modelProvider: ModelProvider.instance,
  );
  final apiPlugin = AmplifyAPI();
  await Amplify.addPlugins([apiPlugin, dataStorePlugin]);
  await Amplify.configure(amplifyconfig);
}

main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  setUp(() async {
    await configureDataStore();
    await Amplify.DataStore.clear();
  });

  testWidgets(
    'should emit events with nested data',
    (WidgetTester tester) async {
      // Nested data (message.author.firstName)
      final nameStream = Amplify.DataStore.observeQuery(Message.classType).map(
        (event) => event.items.map((item) => item.author.firstName),
      );

      expectLater(
        nameStream,
        emitsInOrder([
          orderedEquals([]),
          orderedEquals(['user 1']),
        ]),
      );

      final user1 = User(
        firstName: 'user 1',
        academicInclination: 0,
        academicInterests: const [],
        careerGoals: const [],
        college: '',
        dateOfBirth: TemporalDate.now(),
        email: '',
        graduationMonth: TemporalDate.now(),
        idealFriendDescription: '',
        leisureInterests: const [],
        major: const [],
        matches: const [],
        minor: const [],
        privateKey: const [],
        publicKey: '',
        schoolEmail: '',
        selfDescription: const [],
        situationalDecisions: const [],
        skills: const [],
      );

      final message1 = Message(
        author: user1,
        createdAt: TemporalDateTime.now(),
        encryptedText: 'text 1',
      );

      await Amplify.DataStore.save(user1);
      await Amplify.DataStore.save(message1);
    },
  );
}

```

**Comment by fjnoyp** [comment] 2022-08-22 17:40
Hi @bibaswan-bhawal thanks for your patience here.  I also attempted to reproduce your problem in a small sample app using a simplified version of your schema.  Like Jordan did above I run observeQuery:

```
 Amplify.DataStore.observeQuery(
      Message.classType,
    ).listen((QuerySnapshot<Message> snapshot) {
      setState(() {
        _messages = snapshot.items;
      });
    });
  }
```

When I call await Amplify.DataStore.save(message); the observeQuery result is shown and the message has its parent room and user information shown.  

Please run Jordan's above test.  If you prefer running an example app instead I can also provide what I wrote to you instead (I can share it via github).

**Comment by bibaswan-bhawal** [comment] 2022-08-22 19:00
@Jordan-Nelson I tried running the integration test but  I'm getting the following error:
![2022-08-22 11_56_29-Run - socale](https://user-images.githubusercontent.com/67685395/185997982-ce739caf-9567-469e-96d6-c104ad47da26.png)

I ran the integration test you provided with a few modifications to align more with the db structure.
```
import 'package:amplify_api/amplify_api.dart';
import 'package:amplify_datastore/amplify_datastore.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import 'package:socale/amplifyconfiguration.dart';
import 'package:socale/models/ModelProvider.dart';

Future<void> configureDataStore() async {
  final dataStorePlugin = AmplifyDataStore(
    modelProvider: ModelProvider.instance,
  );
  final apiPlugin = AmplifyAPI(modelProvider: ModelProvider.instance);
  await Amplify.addPlugins([apiPlugin, dataStorePlugin]);
  await Amplify.configure(amplifyconfig);
}

main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  setUp(() async {
    await configureDataStore();
    await Amplify.DataStore.clear();
  });

  testWidgets(
    'should emit events with nested data',
    (WidgetTester tester) async {
      // Nested data (message.author.firstName)
      final nameStream = Amplify.DataStore.observeQuery(Message.classType).map(
        (event) => event.items.map((item) => item.author.firstName),
      );

      expectLater(
        nameStream,
        emitsInOrder([
          orderedEquals([]),
          orderedEquals(['user 1']),
        ]),
      );

      final user1 = User(
        firstName: 'user 1',
        academicInclination: 0,
        academicInterests: const [],
        careerGoals: const [],
        college: '',
        dateOfBirth: TemporalDate.now(),
        email: '',
        graduationMonth: TemporalDate.now(),
        idealFriendDescription: '',
        leisureInterests: const [],
        major: const [],
        matches: const [],
        minor: const [],
        privateKey: const [],
        publicKey: '',
        schoolEmail: '',
        selfDescription: const [],
        situationalDecisions: const [],
        skills: const [],
      );

      final user2 = User(
        firstName: 'user 2',
        academicInclination: 0,
        academicInterests: const [],
        careerGoals: const [],
        college: '',
        dateOfBirth: TemporalDate.now(),
        email: '',
        graduationMonth: TemporalDate.now(),
        idealFriendDescription: '',
        leisureInterests: const [],
        major: const [],
        matches: const [],
        minor: const [],
        privateKey: const [],
        publicKey: '',
        schoolEmail: '',
        selfDescription: const [],
        situationalDecisions: const [],
        skills: const [],
      );

      final room1 = Room();

      final userRoom1 = UserRoom(
        user: user1,
        room: room1,
      );
      final userRoom2 = UserRoom(
        user: user2,
        room: room1,
      );

      final message1 = Message(
        author: user1,
        room: room1,
        createdAt: TemporalDateTime.now(),
        encryptedText: 'text 1',
      );

      // create users
      await Amplify.DataStore.save(user1);
      await Amplify.DataStore.save(user2);

      //create room
      await Amplify.DataStore.save(room1);

      // create userRooms
      await Amplify.DataStore.save(userRoom1);
      await Amplify.DataStore.save(userRoom2);

      // Create message
      await Amplify.DataStore.save(message1);
    },
  );
}
```

**Comment by bibaswan-bhawal** [comment] 2022-08-22 19:12
Also here are the logs for when I am actually calling the save function in app
![2022-08-22 12_09_03-Run - socale](https://user-images.githubusercontent.com/67685395/186000059-59527039-2e61-42f0-b808-928ab0745bb0.png)
![2022-08-22 12_09_23-Run - socale](https://user-images.githubusercontent.com/67685395/186000076-7d93f469-4c2b-43d5-94f5-119edddfc7e1.png)

from what I understand that it is saving the Message object with the complete object, but when it enqueues that mutation is only keeps the id. and this is the object that the observeQuery is picking up.

**Comment by Jordan-Nelson** [comment] 2022-08-22 19:44
> I tried running the integration test but I'm getting the following error:

You see this while running them on Android?

**Comment by bibaswan-bhawal** [comment] 2022-08-22 23:34
yes

**Comment by Jordan-Nelson** [comment] 2022-08-22 23:53
@bibaswan-bhawal were you able to run the modified version that you shared? If not, can you try again and confirm that your are targeting Android? That exception that you posted is what I would expect if you used API on a platform other than iOS or Android

**Comment by bibaswan-bhawal** [comment] 2022-08-22 23:55
I was not able to run the modified version either and I can confirm it is running on android

**Comment by Jordan-Nelson** [comment] 2022-08-23 15:08
The exception you are seeing is wrapped in a condition that would prevent it from being thrown on platforms other than Web, Window, MacOS, and Linux.

https://github.com/aws-amplify/amplify-flutter/blob/319f9ee368f3d0934f69b3541a8a1320e4ed9029/packages/api/amplify_api/lib/amplify_api.dart#L39-L41

How are you trying to run the integration test? Are you running it from your IDE or are you using `flutter test`?

**Comment by bibaswan-bhawal** [comment] 2022-08-23 19:11
I’m running it from my ide

**Comment by bibaswan-bhawal** [comment] 2022-08-23 19:12
I’ll think it’s because my ide isn’t running it on my device so I’ll look into that and get back to you

**Comment by Jordan-Nelson** [comment] 2022-08-23 19:14
Okay, thanks. Let me know what you find.

**Comment by bibaswan-bhawal** [comment] 2022-08-29 01:33
Sorry for the late reply, but I finally got around to testing this again and using the integration test the correct result is produced. I will create a minimum test app to see if this is a problem with the library or something wrong with my code.

**Comment by Jordan-Nelson** [comment] 2022-09-19 20:18
@bibaswan-bhawal - have you had a chance to create a minimal reproduction?

**Comment by Jordan-Nelson** [comment] 2022-09-26 14:15
Hi @bibaswan-bhawal - I am going to close this out since we were unable to reproduce it. If you are able to create a reproduction of this, please open a new issue. Thanks.

**Closed by Jordan-Nelson** 2022-09-26 14:15 UTC
Labels: pending-close-response-required, DataStore, not-reproducible, pending-triage
