### ISSUE TITLE
Google Login UI is always in Arabic [Flutter]

### ISSUE THREAD

**Issue by mufayed** [aws-amplify/amplify-flutter#2045] opened 2022-08-18 13:10 UTC
I got a problem, The users that are trying to log in via google, the google page is always in Arabic for them,
so is there any way to change the language and make it default to English?

```
Amplify.Auth.signInWithWebUI(
      provider: AuthProvider.google,
          options: const CognitoSignInWithWebUIOptions(
              isPreferPrivateSession: true));
```

**Comment by Jordan-Nelson** [comment] 2022-08-18 19:41
Hi @mufayed - Can you please fill out the info in the [bug report template](https://github.com/aws-amplify/amplify-flutter/issues/new?assignees=&labels=&template=BUG-REPORT.yaml)? It helps us reproduce and triage the issue.

Is the user's language on their device set to Arabic?

**Comment by mufayed** [comment] 2022-08-19 05:19
> 

Hi @Jordan-Nelson , 
Thank you for your fast reply, I have filled the bug report template.

And No, The language is English and I also tested that in different android emulators and ios simulators, I made sure the language and the region were in English and English country but still.

The project supports localization and the default language is English

**Comment by fjnoyp** [comment] 2022-08-19 12:35
Hi looks like you created another one.  I will close this and mark as duplicate. 

New Issue: https://github.com/aws-amplify/amplify-flutter/issues/2052

**Closed by fjnoyp** 2022-08-19 12:35 UTC
Labels: duplicate, Auth, pending-response, pending-triage
