### ISSUE TITLE
.fromJson() in all auto-generated models is fundamentally flawed

### ISSUE THREAD

**Issue by sjdoneape** [aws-amplify/amplify-flutter#3492] opened 2023-07-31 22:19 UTC
### Description

When creating a model that has either a 1:n or an m:n relationship with any other model, the autogenerated code for ModelA.fromJson(jsonData) will not generate a complete model. the GraphQL query looks something like this:
query GetModelA {
  getModelA(id: "modelA_ID") {
    ModelBs {
      items {
        id
      }
    }
  }
}
and the response would be something like this:
{
  "data": {
    "getModelA": {
      "ModelBs": {
        "items": [
          {
            "id": "modelB_ID1"
          },
          {
            "id": "modelB_ID2"
          },
          {
            "id": "modelB_ID3"
          }
        ]
      }
    }
  }
}
the list is in jsonRequest.data['getModelA']['ModelBs']['items'] but the ModelA.fromJson(jsonRequest.data['getModelA']) looks for a list in jsonRequest.data['getModelA']['ModelBs'], sees that it is not a list, but a map with one key-value pair (associating 'items' to the list). this can be fixed by replacing the parts of the code that say "json['ModelBs'] is List ?" to say "json['ModelBs']?['items'] is List ?, and replacing the next line that says "(json['ModelBs'] as List)" with "(json['ModelBs']['items'] as List)" 

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Create a model with two types, and either a 1:n or an m:n relationship between them
2. Use the API to add at least one of each model, with the associated relationship between them
3. amplify pull the backend to flutter, including amplify codegen models and run a query that retrieves the data including the relationship as described above
4. Gasp in horror!

### Platforms

- [X] iOS
- [X] Android
- [X] Web
- [X] macOS
- [X] Windows
- [X] Linux

### Flutter Version

3.10.6

### Amplify Flutter Version

1.0.0

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type ModelA @model @auth(rules: [{allow: private}]) {
  id: ID!
  ModelBs: [ModelB] @hasMany(indexName: "byModelA", fields: ["id"])
}

type ModelB @model @auth(rules: [{allow: private}]) {
  id: ID!
  ModelAID: ID! @index(name: "byModelA")
}
```

**Comment by Jordan-Nelson** [comment] 2023-07-31 23:31
Hello @sjdoneape - I am going to close this as a duplicate of https://github.com/aws-amplify/amplify-flutter/issues/816. If you believe this is a different issue, please let me know.

This is something we are looking into and would like to fix. You can follow the issue linked above for updates.

**Closed by Jordan-Nelson** 2023-07-31 23:31 UTC
