### ISSUE TITLE
Pinpoint push notification campaign events are not being recorded. 

### ISSUE THREAD

**Issue by naveenthontepu** [aws-amplify/amplify-flutter#5122] opened 2024-07-08 08:24 UTC
### Description

We are unable to track pinpoint push notification campaign and journey events as they are not being recorded from the flutter SDK.

### Categories

- [X] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [X] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Create a push notification campaign in pinpoint.
2. Run the campaign.
3. Go to the campaign metrics section and only messages delivered is visible, the app open metric is not available.  

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.2

### Amplify Flutter Version

2.2.0

### Deployment Method

Custom Pipeline

**Comment by khatruong2009** [comment] 2024-07-08 15:47
Hi @naveenthontepu, thank you for submitting this issue. We will take a look and get back to you with any updates.

**Comment by tyllark** [comment] 2024-07-18 15:49
Hello @naveenthontepu, I was able to reproduce the issue and determined that the root cause is that the [Push Notification Campaign Events](https://docs.aws.amazon.com/pinpoint/latest/developerguide/event-streams-data-campaign.html#event-streams-data-campaign-attributes) are being cached in memory, but are never being sent to PinPoint. I'm marking this issue as a bug and we will get back to you when we have a fix.

**Comment by NikaHsn** [comment] 2024-08-21 00:02
I'm going to close this issue as the fix has been released in [2.4.0](https://github.com/aws-amplify/amplify-flutter/releases/tag/v2.4.0) version. If you see otherwise or have additional questions, please open a new issue.

**Closed by NikaHsn** 2024-08-21 00:02 UTC
Labels: bug, pending-release, push notifications
