### ISSUE TITLE
Datastor and API (GraphQL) for App and WebApp combination not working

### ISSUE THREAD

**Issue by thomasklaush** [aws-amplify/amplify-flutter#3325] opened 2023-06-30 04:41 UTC
### Description

If mobile App is used, Datastore is preferred. 
For Web Applications, Datastore is not usable, so API (GraphQL) is necessary. 

1. Conflict detection: Since _version is not aces sable, conflict detection is not working with API (GraphQL) 
2. Deletion: Since _deleted flag is not aces sable from API and not usable in queries, all not expired ttl objects ar still visible 
3. @manyToMany Auth (@manyToMany(relationName: "RelationClass") ): For this, no groups (@model @auth(rules: [{ allow: private, operations: [read] },{ allow: groups, groupsField: "groups" }) field are constructed for RelationClass and so cannot be used.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [X] iOS
- [X] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.5

### Amplify Flutter Version

1.2.0

### Deployment Method

Amplify CLI

**Comment by NikaHsn** [comment] 2023-06-30 19:24
Thanks @thomasklaush for opening this. It seems these issues are captured in #1945. 
There is a workaround mentioned in #1434  for using GraphQL API w conflict detection enabled backend which may be helpful.
Regarding `If mobile App is used, Datastore is preferred` would you please give more detail about your use case and how/why is it true for you?

**Comment by thomasklaush** [comment] 2023-06-30 19:34
Especially https://github.com/aws-amplify/amplify-flutter/issues/1945 meets my issues best.
I use an App for training Data mobile and a web portal for the exercise and training creation and maintenance.
So Exercises and trainings have to be edited on a web app (w/o) Datastore.
On the user side, so the mobile application, I want to leverage the possibilities of Datastore.
On the web app side, I'm running in these problems.

**Comment by NikaHsn** [comment] 2023-07-05 20:21
@thomasklaush thanks for confirming. I will mark this as duplicate. Please follow #1945 for progress update.
Specific to your use case,`for the mobile application, I want to leverage the possibilities of Datastore`: Are you refering to Datastore offline support or do you use other functionalities of Datastore which are not provided by API (GraphQL) category?

**Comment by NikaHsn** [comment] 2023-07-14 19:06
Duplicate of #1945

**Comment by NikaHsn** [comment] 2023-07-14 19:11
@thomasklaush I will close this as duplicate. please comment on #1945 to let us know about your specific use case.
Duplicate of #1945

**Closed** 2023-07-14 19:12 UTC
Labels: duplicate, feature-request, DataStore, GraphQL API
