### ISSUE TITLE
Unable to Access Protected Level Bucket Objects when Authenticated with Google Provider

### ISSUE THREAD

**Issue by oyatrides** [aws-amplify/amplify-flutter#4108] opened 2023-11-11 17:24 UTC
### Description

Hello,

I recently transitioned from using the Amplify CLI to create backend resources using CDK (coupled with Amplify hooks and environments). However, I'm still utilizing amplify-flutter to access these resources from my app.

I've successfully connected my resources in amplifyconfiguration.dart, following the tutorials. Everything works fine, except for one issue: I can't retrieve an object created by another user on the protected level in my bucket when connected with the Google provider. Interestingly, it works fine when connected through email/userpool. The front-end code remains unchanged from when I was using the Amplify-generated resources.

This problem appears to be closely related to the following issue: https://github.com/aws-amplify/amplify-flutter/issues/2946. @dnys1 resolved a similar issue by pushing some code into the Cognito auth state machines. However, I'm having difficulty understanding the changes made, and I'm unsure how to address this problem.

Does anyone have any insights or ideas on how to resolve this issue? Your assistance is greatly appreciated. Thank you, and have a great day!

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Screenshots

![377150837_1054557825568609_7758350202582455988_n](https://github.com/aws-amplify/amplify-flutter/assets/74047573/8dce441d-f80d-474b-b8a3-5283f958d5a2)

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.9

### Amplify Flutter Version

1.6.0

### Deployment Method

Amplify CLI + Custom Pipeline

**Comment by oyatrides** [comment] 2023-11-12 15:58
Upon further investigation, it has become apparent that the error is not exclusively tied to Google Sign-In but rather exhibits a more nuanced nature.

Specifically, when a user endeavors to retrieve a non-existent S3 key using the S3 Amplify API, it leads to the storage error as illustrated in the shared screenshot. In our prior utilization of Amplify resources, the error message from Amplify would typically contain "storageException: couldn't find the key" (although the exact phrasing escapes me).

It appears that the Amplify library is encountering difficulty pinpointing the correct error to display. Do you have any insights into the root cause of this issue?

**Comment by Equartey** [comment] 2023-11-16 19:15
@oyatrides sorry you ran into this issue.

To be clear, you were able to reproduce this error with users not signed in with Google? 

Also, does the object exist in the S3 bucket?

Could you provide more concrete reproduction steps so we can investigate further?

**Comment by oyatrides** [comment] 2023-11-20 07:24
Hello and thank you for your answer,

This problem isn't exclusive to Google sign-in; it also occurs when users are connected via email using Cognito User Pool.

The issue arises when attempting to retrieve an object in S3 using a non-existent key. In our case, it is when attempting to display a user's avatar that hasn't been added yet. 

Steps to reproduce:

- Create a backend using CDK, consisting of a bucket, Cognito User Pool, Identity Pool, and Google Identity Provider (although the bug doesn't seem directly related to Google, this configuration reflects the current state of my backend and the 'amplifyconfiguration.dart' file).
- Connect to Cognito.
- Attempt to retrieve a non-existent key in S3 --> This triggers the bug.

In case it helps, here's my amplifyconfiguration.dart code : 

```const amplifyconfig = '''{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
      "api": {
       "plugins": {
           "awsAPIPlugin": {
               "XXXApi": {
                   "endpointType": "GraphQL",
                   "endpoint": "XXXXX/graphql",
                   "region": "eu-west-3",
                   "authorizationType": "AMAZON_COGNITO_USER_POOLS"
               }
           }
       }
    },
    "analytics": {
        "plugins": {
            "awsPinpointAnalyticsPlugin": {
                "pinpointAnalytics": {
                    "appId": "XXXX",
                    "region": "eu-west-1"
                },
                "pinpointTargeting": {
                    "region": "eu-west-1"
                }
            }
        }
    },
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "XXXXX",
                "region": "eu-west-3"
          }
    }
  },
      "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "XXXXX",
                            "Region": "eu-west-3"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "XXXX",
                        "AppClientId": "XXXX",
                        "Region": "eu-west-3"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "OAuth": {
                            "WebDomain": "XXXX",
                            "AppClientId": "XXXX",
                            "SignInRedirectURI": "myapp://",
                            "SignOutRedirectURI": "myapp://",
                            "Scopes": [ 
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        }
                    }
                }
            }
        }
    }
  }''';
  ```
 
  The flutter code accessing the avatar : 
  
  ```
  List<Query$GetFriends$getFriends$friends> friends =
          await gqlApiProvider.queryFriends(
        gqlClient: gqlClient,
        username: event.username,
      );
      for (final friend in friends) {
        late final Uint8List? avatarImage;
        try {
          avatarImage = await storageProvider.downloadAvatarBytes(
              storageID: friend.storageID!);
        } on AvatarDoesNotExists {
          avatarImage = null;
        }
        ```
I hope this will help, thank you for your time :)

**Comment by NikaHsn** [comment] 2023-11-30 19:24
@oyatrides thanks for the detailed info. we marked it as a bug and will investigate the options to fix it.

**Comment by Jordan-Nelson** [comment] 2024-03-19 20:54
Hello @oyatrides - Are. you still facing this issue? I attempted to reproduce this today prior to looking into a fix but was unable to reproduce it. In my reproduction I am using a user pool where users sign up with their email as a username. I attempted to call downloadFile and downloadData with a non existent key with both guest and protected access level.

If you are still able to reproduce this can you please share the code that invokes the Amplify storage APIs. The code sample you shared looks like it invokes an API that may be wrapping Amplify APIs so I am unsure which APIs you are calling.

Thanks

**Comment by Jordan-Nelson** [comment] 2024-04-01 16:50
I am going to close this out since I was not able to reproduce this and we have not heard back. If you are still facing this issue please let us know.

**Closed by Jordan-Nelson** 2024-04-01 16:50 UTC
Labels: bug, pending-close-response-required, storage
