### ISSUE TITLE
Unable to handle exception

### ISSUE THREAD

**Issue by PriyaranjanEuphotic** [aws-amplify/amplify-flutter#3226] opened 2023-06-15 09:19 UTC
### Description

I am not able to handle exception, on sign up when user already exist

error:I/flutter (11943): ERROR | SignUpStateMachine | Emitted error: UsernameExistsException {
I/flutter (11943):   "message": "An account with the given phone_number already exists.",
I/flutter (11943):   "underlyingException": "UsernameExistsException {\n  message=An account with the given phone_number already exists.,\n}"
I/flutter (11943): }
I/flutter (11943): package:smithy/src/http/http_operation.dart 316:7                                HttpOperation.deserializeOutput
I/flutter (11943): package:async/src/cancelable_operation.dart 425:16                               CancelableCompleter.complete.<fn>
I/flutter (11943): ===== asynchronous gap ===========================
I/flutter (11943): package:amplify_core/src/state_machine/event.dart 43:47                          new EventCompleter
I/flutter (11943): package:amplify_core/src/state_machine/state_machine.dart 150:23                 StateMachineManager.accept
I/flutter (11943): package:amplify_core/src/state_machine/state_machine.dart 162:23                 StateMachineManager.acceptAndComplete
I/flutter (11943): package:amplify_auth_cognito_dart/src/auth_plugin_impl.dart 411:40               AmplifyAuthCognitoDart.signUp
I/flutter (11943): package:amplify_auth_cognito/src/auth_pl

my code:

  Future<Result<bool, CustomException>> signUp({
    required String phoneNumber,
  }) async {
    final userAttributes = <AuthUserAttributeKey, String>{
      AuthUserAttributeKey.phoneNumber: phoneNumber,
    };

    final signUpOptions = SignUpOptions(
      userAttributes: userAttributes,
    );

    try {
      await Amplify.Auth.signUp(
        username: phoneNumber,
        password: "Password@1234",
        options: signUpOptions,
      );

      return const Success(true);
    } on UsernameExistsException catch (e) {
      return Error(
        CustomException(message: "User already exist"),
      );
    } on AuthException catch (e) {
      return Error(
        CustomException(message: "Auth error"),
      );
    } catch (e) {
      return Error(
        CustomException(message: "Unable to signup"),
      );
    }
  }

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [ ] iOS
- [X] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.5

### Amplify Flutter Version

1.1.0

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment] 2023-06-15 15:42
Hi @PriyaranjanEuphotic, I'm not able to reproduce the issue. Are you saying this code never gets executed? Can you set a breakpoint and let me know that's the case?

```dart
} on UsernameExistsException catch (e) {
  return Error(
    CustomException(message: "User already exist"),
  );
}
```

Or are you wondering why the error message is still printed even though you are handling the exception?

**Comment by dnys1** [comment] 2023-06-20 15:39
Hi @PriyaranjanEuphotic, please let me know if you're still facing this issue. I'll be closing the ticket if we don't hear back from you.

**Comment by PriyaranjanEuphotic** [comment] 2023-06-20 15:44
Yes I am wondering why the error message is still printed even though I am handling the exception.

**Comment by dnys1** [comment] 2023-06-20 15:49
Understood. I think we can adjust the log level of the error so that it's not printed by default.

I've opened https://github.com/aws-amplify/amplify-flutter/pull/3248 to resolve this.

**Comment by dnys1** [comment] 2023-06-21 00:14
The fix for this has been released.

**Closed by dnys1** 2023-06-21 00:14 UTC
Labels: Auth, pending-release
