### ISSUE TITLE
NotAuthorizedException exception message are different on android and iOS

### ISSUE THREAD

**Issue by kmvignesh** [aws-amplify/amplify-flutter#2231] opened 2022-10-11 11:59 UTC
### Description

When user is not authorised getting exception as 'NotAuthorizedException' but the underlyingException is giving proper message on android and null on iOS. Due to this we are not able to identify wether the user is inactive or entered wrong password.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

Login with invalid credential on android as well as iOS

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Android Device/Emulator API Level

API 32+

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.6 21G115 darwin-arm, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.71.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

### Dependencies

```bash
Flutter SDK 2.10.5
fdgv2 1.21.3+27

dependencies:
- amplify_api 0.6.2 [amplify_api_android amplify_api_ios amplify_core amplify_flutter aws_common collection flutter meta plugin_platform_interface]
- amplify_auth_cognito 0.6.2 [amplify_auth_cognito_android amplify_auth_cognito_ios amplify_core aws_common collection flutter meta plugin_platform_interface]
- amplify_flutter 0.6.2 [amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios aws_common collection flutter meta plugin_platform_interface]
- firebase_core 1.20.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.8.5 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 12.0.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]

transitive dependencies:
- amplify_api_android 0.6.2 [flutter]
- amplify_api_ios 0.6.2 [amplify_core flutter]
- amplify_auth_cognito_android 0.6.2 [flutter]
- amplify_auth_cognito_ios 0.6.2 [amplify_core flutter]
- amplify_core 0.6.2 [aws_common collection flutter intl json_annotation meta plugin_platform_interface uuid]
- amplify_datastore_plugin_interface 0.6.2 [amplify_core collection flutter meta]
- amplify_flutter_android 0.6.2 [flutter]
- amplify_flutter_ios 0.6.2 [amplify_core flutter]
- archive 3.3.1 [crypto path]
- args 2.3.1
- aws_common 0.1.1 [async collection http meta stream_transform uuid]
- ffi 1.2.1
- file 6.1.2 [meta path]
- firebase_core_platform_interface 4.5.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.2.11 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.1.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.1.0 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flat_buffers 2.0.5
- flutter_blurhash 0.7.0 [flutter]
- flutter_isolate 2.0.2 [flutter uuid]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_local_notifications_linux 0.4.2 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.7 [flutter]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph typed_data]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
```

### Device

iPhone XR

### OS

iOS 16

### Deployment Method

Amplify CLI

### Amplify Config

```
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify/cli",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
              "CognitoUserPool": {
                    "Default": {
                        "PoolId": "abc",
                        "AppClientId": "abcd",
                        "AppClientSecret": "abcde",
                        "Region": "abcde"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    },
     "api": {
      "plugins": {
        "awsAPIPlugin": {
          "api": {
            "endpointType": "GraphQL",
            "endpoint": "https://abcd.amazonaws.com/graphql",
            "region": "abcd",
            "authorizationType": "OPENID_CONNECT"
          }
        }
      }
    }
}
```

**Comment by NewLand-Ju** [comment] 2022-10-14 04:16
me too...

**Comment by Jordan-Nelson** [comment] 2022-11-08 22:15
Hi @kmvignesh - I was able to reproduce this and have labeled this as a bug. It looks like Amplify-iOS and Amplify-Android, which Amplify Flutter depend on, have different error messages when a incorrect password is entered.

We are re-writing the Amplify Flutter libraries to remove the dependencies on Amplify-iOS and Amplify-Android, and expand support to other platforms. The Auth re-write is available in developer preview. The latest dev-preview version is [1.0.0-next.0+4](https://pub.dev/packages/amplify_flutter/versions/1.0.0-next.0+4). This issue should be resolved in that version.

**Closed** 2023-04-17 18:45 UTC
Labels: bug, Auth, platform-discrepancy, fixed-in-release-candidate, Authenticator
