### ISSUE TITLE
Schema with field containing @connection not showing in generated model

### ISSUE THREAD

**Issue by EmmanuelOgbewe** [aws-amplify/amplify-flutter#616] opened 2021-06-06 23:15 UTC
**Describe the bug**
When creating a model in schema.graphql and assigning a field with @connection this field is **not** generated after running `amplify codegen models`

**To Reproduce**
1. Go to schema.graphql create two models.
2. One having a @connection to the other model 
3. Run `amplify codegen models` see if the @connected field is viewable in the file generated under models

**Expected behavior**
After creating my schemas I'm expecting to see the @connection fields in their corresponding files under models.

**Screenshots**
1. User and friend model created 
![Screen Shot 2021-06-06 at 7 01 10 PM](https://user-images.githubusercontent.com/29666179/120942918-e66d2100-c6f9-11eb-95eb-98761fbc6f46.png)
2. Warnings outputted from running `amplify codegen models` although @connection was used.
![Screen Shot 2021-06-06 at 7 02 28 PM](https://user-images.githubusercontent.com/29666179/120942990-406de680-c6fa-11eb-8661-8c887e0c6969.png)
3.The generated 'Friend' model, with missing requester and recipient fields
![Screen Shot 2021-06-06 at 7 07 55 PM](https://user-images.githubusercontent.com/29666179/120943073-b8d4a780-c6fa-11eb-82d0-ca3cf05d24fb.png)
4. The generated 'User' model, with missing friends field.
![Screen Shot 2021-06-06 at 7 10 56 PM](https://user-images.githubusercontent.com/29666179/120943128-081ad800-c6fb-11eb-87fe-18588e34e23f.png)

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[x] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.4 19E266
    darwin-x64, locale en-US)
    • Flutter version 2.0.6 at /Users/emmanuelogbewe/flutter
    • Framework revision 1d9032c7e1 (5 weeks ago), 2021-04-29 17:37:58
      -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version
    29.0.3)
    • Android SDK at /Users/emmanuelogbewe/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • 2A493D3E-54BB-43AA-94CE-B0148EC28830 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Chrome (web)       • chrome                               •
      web-javascript • Google Chrome 91.0.4472.77

• No issues found!``

</details>

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] simulator, iphone 11
 - OS: [e.g. iOS8.1] ios 12
 - Browser [e.g. stock browser, safari] safari
 - Version [e.g. 22]

**Additional context**
I'm running latest version of the amplify-cli

**Comment by HuiSF** [comment] 2021-06-08 01:16
Hi @EmmanuelOgbewe , thanks for opening this issue.

From the attached screenshots, it looks like that you are trying to create a many-to-many relationship between `User` model and `Friend` model. According to Amplify [API (GraphQL) documentation](https://docs.amplify.aws/cli/graphql-transformer/connection#many-to-many-connections), a joining model is required to correctly create a many-to-many relationship.

**Comment by EmmanuelOgbewe** [comment] 2021-06-10 05:15
Hi @HuiSF, thank you! 

 So when modifying my schema with a joining model like the example from the documentation, I still have missing fields. Specifically, when running amplify codegen models, the recipientID and requesterID are missing, but I still have the requester and recipient fields. If I remove the @connection from recipient and requester,  all fields remain. 

I ideally would want to create a bidirectional relationship as shown in the documentation. My goal is for a Friend model to keep a connection to a requester and a recipient and a User can have many friends.

**Comment by HuiSF** [comment] 2021-06-11 16:59
>My goal is for a Friend model to keep a connection to a requester and a recipient and a User can have many friends.

Looking at this use case, the `Friend` model is actually a joining model of two `User`'s. From the perspective of `Friend`, the `requester` to `User` and `recipient` to `User` is "_has one_" relationship respectively, isn't it? Using your example above, the schema could be defined as below:

```graphql
type User @model {
  id: ID!
  name: String!
  email: String!
  """a User can have many friends"""
  friends: [Friend] @connection
}

type Friend @model {
  id: ID!
  status: FriendStatus!
  requesterID: ID!
  recipientID: ID!
  """each friend links to two users"""
  requester: User @connection
  recipient: User @connection
}

enum FriendStatus {
  REQUESTED
  FRIENDS
}
```

Generated models containing fields:

```dart

class User extends Model {
  static const classType = const _UserModelType();
  final String id;
  final String name;
  final String email;
  final List<Friend> friends;
}

class Friend extends Model {
  static const classType = const _FriendModelType();
  final String id;
  final FriendStatus status;
  final String requesterID;
  final String recipientID;
  final User requester;
  final User recipient;
  final String userFriendsId;
}
```

**Comment by HuiSF** [comment] 2021-06-11 17:03
This thread is more like a GraphQL schema defining question :)
The original warning mentioned in the issue was not a library bug but expected behavior. Marking the issue as pending close.

**Comment by EmmanuelOgbewe** [comment] 2021-06-12 13:16
Thanks, I should've been more specific with my issue. For this schema, since there is a one-to-many relation between a user having many friends wouldn't I need to define a @key for Friend, or is that only if I want to specify fields? In addition, if I wanted a users friends field to be populated by querying the Friend table with a user's ID matching a requesterID or recipientID, then I would provide a @key like in my screenshot above?

> > My goal is for a Friend model to keep a connection to a requester and a recipient and a User can have many friends.
> 
> Looking at this use case, the `Friend` model is actually a joining model of two `User`'s. From the perspective of `Friend`, the `requester` to `User` and `recipient` to `User` is "_has one_" relationship respectively, isn't it? Using your example above, the schema could be defined as below:
> 
> ```graphql
> type User @model {
>   id: ID!
>   name: String!
>   email: String!
>   """
>   a User can have many friends
>   """
>   friends: [Friend] @connection
> }
> 
> type Friend @model {
>   id: ID!
>   status: FriendStatus!
>   requesterID: ID!
>   recipientID: ID!
>   """
>   each friend links to two users
>   """
>   requester: User @connection(fields: ["requesterID"])
>   recipient: User @connection(fields: ["recipientID"])
> }
> 
> enum FriendStatus {
>   REQUESTED
>   FRIENDS
> }
> ```
> 
> Generated models containing fields:
> 
> ```dart
> class User extends Model {
>   static const classType = const _UserModelType();
>   final String id;
>   final String name;
>   final String email;
>   final List<Friend> friends;
> }
> 
> class Friend extends Model {
>   static const classType = const _FriendModelType();
>   final String id;
>   final FriendStatus status;
>   final String requesterID;
>   final String recipientID;
>   final User requester;
>   final User recipient;
>   final String userFriendsId;
> }
> ```

**Comment by HuiSF** [comment] 2021-06-14 16:57
You sure can add `@key` directive to `Friend` model to create your secondary index. My example is minimum :D 

When you need to populate the `requester` and `recipient` fields of `Friend`, if you are only going to use `User.id`, then you don't need create secondary index by using `@key` on `User` as by default it creates index on `id` field. 

The schema could be

```graphql
type User @model {
  id: ID!
  name: String!
  email: String!
  """
  a User can have many friends
  """
  friends: [Friend] @connection
}

type Friend @model 
  @key(name: "byRequester", fields: ["requesterID"])
  @key(name: "byRecipient", fields: ["recipientID"]) {
  id: ID!
  status: FriendStatus!
  requesterID: ID!
  recipientID: ID!
  """
  each friend links to two users
  """
  requester: User @connection(fields: ["requesterID"])
  recipient: User @connection(fields: ["recipientID"])
}
```

I kept `byRequester` and `byRecipient` separate as I presume -
* A `User` cannot be the requester and recipient of a `Friend` at the same time
* Each combination of 2 different `User`s can only create 2 unique `Friend`s 
  * User1 as requester - User2 as recipient
  * User2 as requester - User1 as recipient

I would recommend you to take a look at [Amplify GraphQL data access patterns documentation](https://docs.amplify.aws/cli/graphql-transformer/dataaccess). You can find better example there.

**Comment by EmmanuelOgbewe** [comment] 2021-06-18 05:05
So when running the schema you provided I get the intended model output. Though when specifying a keyName to the friend's field like below after running `amplify codegen models` I no longer have the `requesterID` and `recipientID` field. This is the issue I am having, when I provide a keyName to a connection where there is a bidirectional relationship as shown in the documentation, some fields become missing.

![Screen Shot 2021-06-17 at 11 19 13 PM](https://user-images.githubusercontent.com/29666179/122502707-27501a00-cfc5-11eb-8b2b-08040143c52e.png)


![Screen Shot 2021-06-17 at 11 29 47 PM](https://user-images.githubusercontent.com/29666179/122507155-b103e580-cfcd-11eb-89a4-dbea03ff3492.png)

**Comment by HuiSF** [comment] 2021-06-18 16:04
That is expected behavior, as `requesterID` and `recipientID` now serve as secondary indexes.
If you look into the generated model `Friend`, it should have a `belongsTo` model schema definition defined, which describe the relationship between `requesterID`, `recipientID` and `User` model.

If you looking to the the amplify build directory

```
amplify/backend/<api name>/build/schema.graphql
```

You can check all generated types, if you look `CreateFriendInput`, `requesterID` and `recipientID` should be required fields. Therefore the generated models should work correctly.

**Comment by EmmanuelOgbewe** [comment] 2021-06-24 06:48
Ah I see , however when creating a Friend without passing a requesterID and recipientID given those fields are not available,  but yet passing the requester and recipient, when querying the Friend table I see the model contains a requester and recipient but all values for both User model connected are null except for the ID attribute. Likewise, the User whose ID matches the recipient from the created Friend model,  attribute friends is an empty list.

**Comment by HuiSF** [comment] 2021-06-24 18:42
That's an expected behavior, at least at this moment.

* When saving a new object that associates with other models (Friend with recipient and requester in your use case), it would need to provide complete nested models (this is different from directly using GraphQL API providing only ids)
* Currently in amplify-flutter, it returns only id field for nested models.

We are currently working on return fully populated nested models. iOS PR #658 Android PR is in progress.

**Comment by ragingsquirrel3** [comment] 2021-07-20 21:11
I'm going to close this issue as it was marked "pending close ..." and it seems the original issue/question has been answered.

**Closed by ragingsquirrel3** 2021-07-20 21:11 UTC
Labels: pending-close-response-required
