### ISSUE TITLE
Unexpected behavior when resending verification code when updating user attribute

### ISSUE THREAD

**Issue by jamilsaadeh97** [aws-amplify/amplify-flutter#3756] opened 2023-09-18 14:36 UTC
### Description

I found a bug when resending a verification code used for `updateUserAttribute`.

Let's say I have "123" as a phone number registered and verified by SMS in Cognito.
If I want to update the phone number to "456" with: 
```dart
await Amplify.Auth.updateUserAttribute(
  userAttributeKey: AuthUserAttributeKey.phoneNumber,
  value: "456"
);
```
I receive the verification code to "456". Until now everything is expected.

The issue is when I resend the code with:
```dart
await Amplify.Auth.resendUserAttributeConfirmationCode(
  userAttributeKey: AuthUserAttributeKey.phoneNumber,
);
```
This code is sent to my old phone number (in this example, to "123")

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Update the phone number with `updateUserAttribute`
2. New phone number receives the verification code.
3. Resend verification code.
4. Old phone number receives the code.

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.0

### Amplify Flutter Version

1.4.1

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment] 2023-09-18 16:54
@jamilsaadeh97 Can you share you amplifyconfiguration.dart file (with any sensitive or app specific info removed)?

**Comment by Jordan-Nelson** [comment] 2023-09-18 16:59
@jamilsaadeh97 I was not able to reproduce this with an Amplify app created with the CLI using Phone Number to log in. In addition to the config, can you let me know if you app was created with the Amplify CLI? Are there any other steps you are taking to reproduce this?

**Comment by jamilsaadeh97** [comment] 2023-09-18 17:13
Hi @Jordan-Nelson , 

This is my amplifyconfiguration.dart:
```json
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "analytics": {
        "plugins": {
            "awsPinpointAnalyticsPlugin": {
                "pinpointAnalytics": {
                    "appId": "xxx",
                    "region": "us-east-1"
                },
                "pinpointTargeting": {
                    "region": "us-east-1"
                }
            }
        }
    },
    "notifications": {
        "plugins": {
            "awsPinpointPushNotificationsPlugin": {
                "appId": "xxx",
                "region": "us-east-1"
            }
        }
    },
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "Api": {
                    "endpointType": "GraphQL",
                    "endpoint": "xxx.amazonaws.com/graphql",
                    "region": "us-east-1",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "PinpointAnalytics": {
                    "Default": {
                        "AppId": "xxx",
                        "Region": "us-east-1"
                    }
                },
                "PinpointTargeting": {
                    "Default": {
                        "Region": "us-east-1"
                    }
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "xxx.amazonaws.com/graphql",
                        "Region": "us-east-1",
                        "AuthMode": "AMAZON_COGNITO_USER_POOLS",
                        "ClientDatabasePrefix": "xxx"
                    },
                    "xxApi_AWS_IAM": {
                        "ApiUrl": "xxx.amazonaws.com/graphql",
                        "Region": "us-east-1",
                        "AuthMode": "AWS_IAM",
                        "ClientDatabasePrefix": "xxx"
                    }
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-1:xxx",
                            "Region": "us-east-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-1_xxx",
                        "AppClientId": "xxx",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": [
                                "REQUIRES_LOWERCASE",
                                "REQUIRES_UPPERCASE"
                            ]
                        },
                        "signupAttributes": [
                            "BIRTHDATE",
                            "EMAIL",
                            "FAMILY_NAME",
                            "GIVEN_NAME",
                            "PHONE_NUMBER"
                        ],
                        "socialProviders": [],
                        "usernameAttributes": [
                            "EMAIL",
                            "PHONE_NUMBER"
                        ],
                        "verificationMechanisms": [
                            "PHONE_NUMBER"
                        ]
                    }
                }
            }
        }
    }
}
```

And yes I created the app using the CLI.

I want to mention that a few days ago, I ran `amplify update auth` and for the email verification prompt I selected "Disabled, (SMS will be used instead)" something like that. I wanted to make the OTP through SMS instead of email.
I also want to add that this logged in user that I am testing on is registered and confirmed by email previously. (The username used when signing up and on log in is the email)

Thank you!

**Comment by Jordan-Nelson** [comment] 2023-09-18 18:28
@jamilsaadeh97 - Apologies, I made a mistake in my initial attempt to reproduce it. I am able to reproduce this experience.

I think the issue here is that the API name is confusing and the existing documentation is misleading.

`resendUserAttributeConfirmationCode` will send the a code to confirm the *current* value for that attribute. For example, if the user set phone number as "123" during sign up, but never confirmed their phone number, the API can be used to send them a verification code. The code will be sent to their existing phone number ("123").

 If an attribute is in the _middle_ of an update (update requested, but not yet confirmed), this API will send the code to the *current* attribute. The *current* attribute in this case is still considered to be the original phone number (123) since the new phone number (456) is not yet confirmed.

If you want to resend the code in the middle of the update flow, you should re-invoke `updateUserAttribute()` with the value. This is not what is show in some of the existing documentation. I will mark this as a docs issue until we have updated the documentation for this.

We are also discussing renaming this API as the existing name does not reflect the behavior.

**Comment by jamilsaadeh97** [comment] 2023-09-18 20:16
Thank you for taking the time digging into this @Jordan-Nelson .

Just to make sure I understood correctly, `resendUserAttributeConfirmationCode` is used to confirm the attribute that was not confirmed during signup. 
In my case, if I want to update an already confirmed attribute I should use `updateUserAttribute()` and if I want to resend the verification code for that "unverified updated attribute" I should re-invoke `updateUserAttribute()`, is that correct?

**Comment by Jordan-Nelson** [comment] 2023-09-18 21:01
That is correct

**Comment by jamilsaadeh97** [comment] 2023-09-18 21:47
Thank you for the clarification!

**Comment by Jordan-Nelson** [comment] 2024-05-01 17:40
This API has been renamed from `resendUserAttributeConfirmationCode` to `sendUserAttributeVerificationCode()`. The docs update is still pending. I will close out this issue once the docs has been updated.

**Comment by Jordan-Nelson** [comment] 2024-05-29 14:06
The docs update has been made. I will close this out now.

**Closed by Jordan-Nelson** 2024-05-29 14:06 UTC
Labels: Documentation, auth
