### ISSUE TITLE
DataStore - App crash when lost internet connection

### ISSUE THREAD

**Issue by vuchau** [aws-amplify/amplify-flutter#252] opened 2020-12-14 11:54 UTC
**Describe the bug**
When I have established a connection to the cloud, if I disable internet connection then the application crashes. 

**To Reproduce**
1. Make sure internet is connected
2. Make established  a connection to the cloud
3. Disable internet connection.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS
**Additional context**
Error log

`W/amplify:aws-api(  929): Websocket connection failed.
W/amplify:aws-api(  929): javax.net.ssl.SSLException: Read error: ssl=0xec550b88: I/O error during system call, Software caused connection abort
W/amplify:aws-api(  929): 	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
W/amplify:aws-api(  929): 	at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:399)
W/amplify:aws-api(  929): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:546)
W/amplify:aws-api(  929): 	at okio.InputStreamSource.read(JvmOkio.kt:90)
W/amplify:aws-api(  929): 	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
W/amplify:aws-api(  929): 	at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
W/amplify:aws-api(  929): 	at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
W/amplify:aws-api(  929): 	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:209)
W/amplify:aws-api(  929): 	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
W/amplify:aws-api(  929): 	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
W/amplify:aws-api(  929): 	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
W/amplify:aws-api(  929): 	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
W/amplify:aws-api(  929): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
W/amplify:aws-api(  929): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/amplify:aws-api(  929): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/amplify:aws-api(  929): 	at java.lang.Thread.run(Thread.java:764)
.....
Lost connection to device.
`

**Comment by Amplifiyer** [comment] 2020-12-14 21:22
Duplicate of https://github.com/aws-amplify/amplify-android/issues/541 and https://github.com/aws-amplify/amplify-android/issues/1022

**Comment by Amplifiyer** [comment] 2021-02-04 00:51
The fix for this is released. Let us know if you are still facing issues.

**Closed by Amplifiyer** 2021-02-04 00:51 UTC
Labels: Android, DataStore, requires-android-fix

**Comment by rommank** [comment] 2021-04-07 08:21
@Amplifiyer Can you reopen the issue, please?

I am having the same issue I guess.

aws-datastore:1.17.2

```
io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | DataStoreException{message=Failure during mutation., cause=ApiException{message=OkHttp client request failed., cause=java.net.SocketTimeoutException: timeout, recoverySuggestion=See attached exception for more details.}, recoverySuggestion=Check details.}
     at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
     at io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:82)
     at com.amplifyframework.datastore.syncengine.-$$Lambda$H2kP2N9w3X0gYQg1QzSwv0s9uXc.accept(Unknown Source:4)
     at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$mutation$5(AppSyncClient.java:328)
     at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$FfgHx1XvivjmTcZhtf9BjbrAq_M.accept(Unknown Source:4)
     at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onFailure(AppSyncGraphQLOperation.java:156)
     at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
     at java.lang.Thread.run(Thread.java:764)
  Caused by: DataStoreException{message=Failure during mutation., cause=ApiException{message=OkHttp client request failed., cause=java.net.SocketTimeoutException: timeout, recoverySuggestion=See attached exception for more details.}, recoverySuggestion=Check details.}
     at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$mutation$5(AppSyncClient.java:328) 
     at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$FfgHx1XvivjmTcZhtf9BjbrAq_M.accept(Unknown Source:4) 
     at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onFailure(AppSyncGraphQLOperation.java:156) 
     at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525) 
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
     at java.lang.Thread.run(Thread.java:764) 
  Caused by: ApiException{message=OkHttp client request failed., cause=java.net.SocketTimeoutException: timeout, recoverySuggestion=See attached exception for more details.}
     at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onFailure(AppSyncGraphQLOperation.java:156) 
     at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525) 
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
     at java.lang.Thread.run(Thread.java:764) 
  Caused by: java.net.SocketTimeoutException: timeout
     at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:677)
     at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:686)
     at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
     at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
     at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
     at com.amplifyframework.api.aws.UserAgentInterceptor.intercept(UserAgentInterceptor.java:56)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
     at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
     at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
     at java.lang.Thread.run(Thread.java:764) 
```

**Comment by Amplifiyer** [comment] 2021-04-08 17:01
@rommank this looks like a different bug than the one originally discussed in this issue. Can you please open another bug report and add as detailed reproduction steps as possible for us to replicate?

**Comment by rommank** [comment] 2021-04-08 17:08
> @rommank this looks like a different bug than the one originally discussed in this issue. Can you please open another bug report and add as detailed reproduction steps as possible for us to replicate?

 https://github.com/aws-amplify/amplify-android/issues/1273
Thanks for your reply.
