### ISSUE TITLE
AWS Amplify can't configure in the unit test function

### ISSUE THREAD

**Issue by draxexx** [aws-amplify/amplify-flutter#1334] opened 2022-02-04 08:25 UTC
I try to write unit tests for the Amplify Auth SignIn, but I can't configure the Amplify in the unit test functions. I got an error like "Amplify plugin AmplifyAuthCognito was not added successfully."

Here is my configuration code (by the way it is working well in my application):

```
AmplifyAuthCognito authPlugin = AmplifyAuthCognito();
AmplifyAPI apiPlugin = AmplifyAPI();
Amplify.addPlugins([authPlugin, apiPlugin]);

// Once Plugins are added, configure Amplify
// Note: Amplify can only be configured once.
try {
  await Amplify.configure(amplifyconfigDEV);
  print('Amplify configured');
} on AmplifyAlreadyConfiguredException {
  print(
      "Tried to reconfigure Amplify; this can occur when your app restarts on Android.");
}
```

Here is the error:

**AmplifyException(message: Amplify plugin AmplifyAuthCognito was not added successfully., recoverySuggestion: We currently don't have a recovery suggestion for this exception., underlyingException: Null check operator used on a null value)**

**Comment by cshfang** [comment] 2022-02-05 00:13
Hiya @draxexx, thanks for sharing this with us. Generally speaking, you should probably be mocking out third party dependencies when writing unit tests for you application. The configuration will attempt to step through its normal production steps otherwise - this includes trying to configure plugins over the Flutter method channel (which Amplify Flutter uses to configure plugins at the native layer).

I would suggest taking a look at the Flutter docs around mocking out dependencies for unit tests:
https://docs.flutter.dev/cookbook/testing/unit/mocking

Additionally, check out https://github.com/aws-amplify/amplify-flutter/issues/1255 for a more in depth discussion for integration testing (which you would need if you wish to actually test end-to-end flow of your application).

**Comment by cshfang** [comment] 2022-02-05 00:14
Duplicate of #1255

**Closed by cshfang** 2022-02-05 00:14 UTC
Labels: duplicate

**Comment by draxexx** [comment] 2022-02-07 07:04
Thank you @cshfang, integration testing fixed that problem.
