### ISSUE TITLE
uploading issue

### ISSUE THREAD

**Issue by Ghazanfaru** [aws-amplify/amplify-flutter#3968] opened 2023-10-19 11:21 UTC
### Description

when i upload file on aws s3 bucket sometimes it works great and file gets uploaded and when i try to upload same file more than one time then it get stuck after 2nd or 3rd try if size is small and if size is large then it get stucks in 2nd try and if size is much larger then it get stucks in first try. why would this be happening? 

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.0.0

### Amplify Flutter Version

1.4.1

### Deployment Method

Amplify CLI

**Comment by Equartey** [comment] 2023-10-19 18:49
Hey @Ghazanfaru, sorry you are facing this issue.

Can you please provide file size example from when you have observed the issue?

Can you also provide sample code and reproduction steps for the issue?

**Comment by Ghazanfaru** [comment] 2023-10-19 18:58
Hey,
yes, when i upload more than 100 mb file it get stuck at 90% sometime 98%
sometimes 78% and the code that im using is that one which is in example on
aws page i will share the code in the morning, if you really need to see
that and thanks for the response.

**Comment by Ghazanfaru** [comment] 2023-10-20 05:45
Future<void> uploadImage() async {
    // Select a file from the device
    final result = await FilePicker.platform.pickFiles(
      type: FileType.any,
      withData: false,
      // Ensure to get file stream for better performance
      withReadStream: true,
    );

    if (result == null) {
      safePrint('No file selected');
      return;
    }

    // Upload file with its filename as the key
    final platformFile = result.files.single;
    try {
      final result = await Amplify.Storage.uploadFile(
        localFile: AWSFile.fromStream(
          platformFile.readStream!,
          size: platformFile.size,
        ),
        key: platformFile.name,
        onProgress: (progress) {
          safePrint('Uploaded: ${progress.fractionCompleted*100} %');
          safePrint("${progress.transferredBytes/ (1024 * 1024)} out of ${progress.totalBytes/ (1024 * 1024)}");
        },
      ).result;
      safePrint('Successfully uploaded file: ${result.uploadedItem.key}');
    } on StorageException catch (e) {
      safePrint('Error uploading file: $e');
      rethrow;
    }
  }
  //This is the code what im using.

**Comment by khatruong2009** [comment] 2023-11-02 22:36
Hi @Ghazanfaru, I was able to reproduce the issue and have marked it as a bug. We will investigate it further, thanks.

**Comment by khatruong2009** [comment] 2024-02-14 00:35
Hi @Ghazanfaru, I started working on this issue again and was not able to reproduce the issue. Are you still encountering this issue? Also, what is the use case for uploading the same file multiple times?

**Comment by Equartey** [comment] 2024-03-05 21:52
Closing due to lack of activity. Please comment here or open an issue if you experience this issue again.

**Closed by Equartey** 2024-03-05 21:52 UTC
Labels: pending-close-response-required, storage, Investigating
