### ISSUE TITLE
Feature Request: specify folder to upload file to

### ISSUE THREAD

**Issue by sirwes** [aws-amplify/amplify-flutter#1863] opened 2022-07-09 16:33 UTC
I'd like to specify which folder a file is uploaded to in my s3 bucket. If the folder doesn't already exist, it should create it automatically.

**Comment by HuiSF** [comment] 2022-07-09 20:00
Hello @sirwes thanks for opening this issue.

I think Amplify-flutter Storage plug-in is capable to achieve what you are asking. 

When you invoke `Amplify.Storage.uploadFile()` API you'll provide a value for the `key` parameter. This value doesn't only present the name of the object, but can also present prefix of the object which is an equivalent to the idea of "folder".

E.g.
```dart
final UploadFileResult result = await Amplify.Storage.uploadFile(
  local: exampleFile,
  key: 'album/pop/a.mp4',
);
```

This call will create the object under the "folder" `pop` inside the "folder" `album`.

Please note Amplify Storage plugin will also automatically add prefix for auth purposes. I.e.

* AccessLevel.guest: all objects will be created under `public` prefix
* AccessLevel.protected: under prefix `protected/<user-identity-id>`
* AccessLevel.private: under prefix `private/<user-identity-id>`


If you are trying to use an existing bucket, with existing "folder" structure, you may not be able to access objects directly without migration to above mentioned prefix structures.

Hope this helps.

**Comment by ragingsquirrel3** [comment] 2022-07-21 16:45
I believe this is a duplicate of https://github.com/aws-amplify/amplify-flutter/issues/416 so I'm going to close this one in favor of that one.

**Closed by ragingsquirrel3** 2022-07-21 16:45 UTC
Labels: Question, Storage, pending-response
