### ISSUE TITLE
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDevDebugJavaWithJavac'

### ISSUE THREAD

**Issue by dgagnon** [aws-amplify/amplify-flutter#3726] opened 2023-09-11 17:16 UTC
### Description

Whenever a new amplify version is released, a local upgrade of depencies is required: `fvm dart pub upgrade`  

doing so breaks the the build ( see screenshots below ).  The only method to reliably fix it has been:
1. gradle.properties: `org.gradle.caching=false`
2. `fvm flutter clean` 
3. `fvm dart pub get` 
4. `fvm dart pub upgrade`
5. `fvm dart pub cache repair` 
6. `fvm flutter -v build apk --debug --dart-define env=dev`
6.1. This step is needed in our case, but I believe it is a bug on our side. see note 1.
7. gradle.properties: `org.gradle.caching=true`

Note 1: Without this step, we get the following error.
```
[  +15 ms] package identifier or launch activity not found.
[   +1 ms] Please check E:\Dan\Code\Project Pipeline\flutter-demo-with-docs\android\app\src\main\AndroidManifest.xml for errors.
[   +1 ms] No application found for TargetPlatform.android_x64.
           Is your project missing an android\app\src\main\AndroidManifest.xml?
           Consider running "flutter create ." to create one.
```

### Categories

- [X] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Setup an old version of the app.
2. Setup the datastore.
3. Upgrade to a newer amplify library.

### Screenshots

```dart
[   +1 ms] E:\Dan\Code\Project Pipeline\flutter-demo-with-docs\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:19: error: cannot find symbol
[   +2 ms]       flutterEngine.getPlugins().add(new com.amazonaws.amplify.amplify_analytics_pinpoint.AmplifyAnalyticsPinpointPlugin());
[        ]                                                                                          ^
[        ]   symbol:   class AmplifyAnalyticsPinpointPlugin
[        ]   location: package com.amazonaws.amplify.amplify_analytics_pinpoint
[        ] E:\Dan\Code\Project Pipeline\flutter-demo-with-docs\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:29: error: cannot find symbol
[        ]       flutterEngine.getPlugins().add(new com.amazonaws.amplify.amplify_datastore.AmplifyDataStorePlugin());
[        ]                                                                                 ^
[        ]   symbol:   class AmplifyDataStorePlugin
[        ]   location: package com.amazonaws.amplify.amplify_datastore
[        ] 2 errors
```

[full debug log.txt](https://github.com/aws-amplify/amplify-flutter/files/12578761/full.debug.log.txt)

```powershell
PS E:\Dan\Code\Project Pipeline\flutter-demo-with-docs> fvm flutter --version
Flutter 3.13.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2524052335 (5 days ago) • 2023-09-06 14:32:31 -0700
Engine • revision b8d35810e9                                            
Tools • Dart 3.1.1 • DevTools 2.25.0                                    
PS E:\Dan\Code\Project Pipeline\flutter-demo-with-docs> fvm flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.3, on Microsoft Windows [Version 10.0.19045.3393], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web                                                
[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.1.6)
[√] Android Studio (version 2022.2)                                             
[√] IntelliJ IDEA Ultimate Edition (version 2023.2)                             
[√] VS Code (version 1.79.2)                                                    
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.3

### Amplify Flutter Version

1.4.1

### Deployment Method

Amplify CLI

### Schema

```GraphQL
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
enum Status {
    ACTIVE
    COMPLETED
    DELETED
}

enum UserStatus {
    ACTIVE
    SUSPENDED
    DELETED
}

type User @model @auth(rules: [{ allow: owner, ownerField: "owner"}, {allow: private, provider: iam}, { allow: groups, groups: ["admin"] }]) {
    id: ID! @auth(rules: [{ allow: owner, ownerField: "owner" }, {allow: private, provider: iam}, { allow: groups, groups: ["admin"] }])
    username: String! @auth(rules: [{ allow: owner, ownerField: "owner" }, {allow: private, provider: iam}, { allow: groups, groups: ["admin"] }])
    data: AWSJSON @auth(rules: [{ allow: owner, ownerField: "owner" }, {allow: private, provider: iam}, { allow: groups, groups: ["admin"] }])
    attributes: AWSJSON @auth(rules: [{ allow: owner, ownerField: "owner" }, {allow: private, provider: iam}, { allow: groups, groups: ["admin"] }])
    # https://docs.amplify.aws/lib/datastore/sync/q/platform/flutter/#advanced-use-case---query-instead-of-scan
    status: UserStatus @default(value: "ACTIVE" ) @index(name: "byStatus") @auth(rules: [{ allow: owner, ownerField: "owner" }, {allow: private, provider: iam}, { allow: groups, groups: ["admin"] }])
    owner: String @index(name: "byOwner") @auth(rules: [{ allow: owner, ownerField: "owner", operations: [read, create, delete] }, { allow: private, provider: iam }, { allow: groups, groups: ["admin"] }])
    tasks: [Task] @hasMany(indexName: "byUser", fields: ["id"])
    sharedWith: [String] @auth(rules: [{ allow: owner, ownerField: "owner" }, { allow: private, provider: iam }, { allow: groups, groups: ["admin"] }])
}
type Project @model @auth(rules: [{ allow: owner, ownerField: "owner"}, {allow: private, operations: [read]}, {allow: private, provider: iam}]) {
    id: ID! @auth(rules: [{ allow: owner, ownerField: "owner" }, {allow: private, provider: iam}, {allow: private, operations: [read]}, { allow: groups, groups: ["admin"] }])
    title: String! @auth(rules: [{ allow: owner, ownerField: "owner" }, {allow: private, provider: iam}, {allow: private, operations: [read]}, { allow: groups, groups: ["admin"] }])
    description: String @auth(rules: [{ allow: owner, ownerField: "owner" }, {allow: private, provider: iam}, {allow: private, operations: [read]}, { allow: groups, groups: ["admin"] }])
    data: AWSJSON @auth(rules: [{ allow: owner, ownerField: "owner" }, {allow: private, provider: iam}, {allow: private, operations: [read]}, { allow: groups, groups: ["admin"] }])
    status: Status @default(value: "ACTIVE" ) @index(name: "byStatus") @auth(rules: [{ allow: owner, ownerField: "owner" }, {allow: private, provider: iam}, {allow: private, operations: [read]}, { allow: groups, groups: ["admin"] }])
    dueAt: AWSDateTime! @auth(rules: [{ allow: owner, ownerField: "owner"}, { allow: private, provider: iam }, {allow: private, operations: [read]}, { allow: groups, groups: ["admin"] }])
    owner: String @index(name: "byOwner") @auth(rules: [{ allow: owner, ownerField: "owner", operations: [read, create, delete] }, { allow: private, provider: iam }, {allow: private, operations: [read]},{ allow: groups, groups: ["admin"] }])
    tasks: [Task] @hasMany(indexName: "byProject", fields: ["id"]) #https://docs.amplify.aws/cli/graphql/data-modeling/#belongs-to-relationship
}
type Task @model @auth(rules: [{ allow: owner, ownerField: "owner"}, {allow: private, provider: iam}, { allow: groups, groups: ["admin"], operations: [read] }]) {
    id: ID @auth(rules: [{ allow: owner, ownerField: "owner" }, {allow: private, provider: iam}, { allow: groups, groups: ["admin"], operations: [read] }])
    title: String! @auth(rules: [{ allow: owner, ownerField: "owner" }, {allow: private, provider: iam}, { allow: groups, groups: ["admin"], operations: [read] }])
    description: String @auth(rules: [{ allow: owner, ownerField: "owner" }, {allow: private, provider: iam}, { allow: groups, groups: ["admin"], operations: [read] }])
    data: AWSJSON @auth(rules: [{ allow: owner, ownerField: "owner" }, {allow: private, provider: iam}, { allow: groups, groups: ["admin"], operations: [read] }])
    status: Status @default(value: "ACTIVE" ) @index(name: "byStatus") @auth(rules: [{ allow: owner, ownerField: "owner" }, {allow: private, provider: iam}, { allow: groups, groups: ["admin"] }])
    dueAt: AWSDateTime! @auth(rules: [{ allow: owner, ownerField: "owner" }, { allow: private, provider: iam }, { allow: groups, groups: ["admin"], operations: [read] }])
    # https://docs.amplify.aws/cli/graphql/authorization-rules/#multi-user-data-access
    #    owners: [String]
    # BUG: https://github.com/aws-amplify/amplify-flutter/issues/1566
    owner: String @index(name: "byOwner") @auth(rules: [{ allow: owner, ownerField: "owner", operations: [read, create, delete] }, { allow: private, provider: iam }, { allow: groups, groups: ["admin"], operations: [read] }])
    projectID: ID! @index(name: "byProject") #https://docs.amplify.aws/cli/graphql/data-modeling/#belongs-to-relationship
    project: Project! @belongsTo(fields: ["projectID"])
    sharedWith: [String] @auth(rules: [{ allow: owner, ownerField: "owner" }, { allow: private, provider: iam }, { allow: groups, groups: ["admin"], operations: [read] }])
    userID: ID @index(name: "byUser") #https://docs.amplify.aws/cli/graphql/data-modeling/#belongs-to-relationship
    user: User @belongsTo(fields: ["userID"])
}
```

**Comment by dnys1** [comment] 2023-09-11 23:23
Hi @dgagnon, sorry you are facing this issue. I will work on getting access to a Windows machine to try and reproduce this. I'm not able to reproduce it on my mac so far.

Which version of Flutter are you using with `fvm`?

**Comment by dgagnon** [comment] 2023-09-11 23:25
@dnys1 stable.  Here is the fvm config.  I am using prod flavor with flutter 3.13.3.

```json
{
  "flutterSdkVersion": "stable",
  "flavors": {
    "prod": "stable",
    "dev": "beta",
    "update": "3.10.4"
  }
}
```

**Comment by dnys1** [comment] 2023-09-12 01:20
@dgagnon I was not able to reproduce this on my Windows machine, unfortunately. I did try using `fvm`, and with/without the caching property but all were successful.

**Comment by dgagnon** [comment] 2023-09-12 01:35
@dnys1 I am most likely missing some reproduction steps, as I never get this on a new setup, only on upgrading an ongoing project.

Here are my gradle and manifest file, maybe that makes a difference:
[build.gradle.txt](https://github.com/aws-amplify/amplify-flutter/files/12581481/build.gradle.txt)
[app_build.gradle.txt](https://github.com/aws-amplify/amplify-flutter/files/12581488/app_build.gradle.txt)
[debugAndroidManifest.txt](https://github.com/aws-amplify/amplify-flutter/files/12581497/debugAndroidManifest.txt)
[mainAndroidManifest.txt](https://github.com/aws-amplify/amplify-flutter/files/12581499/mainAndroidManifest.txt)

**Comment by amrogad** [comment] 2023-09-12 12:39
Hi! I'm getting the same issue, here's my logs:
```
C:\GitHub\flutter-demo-with-docs\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:19: error: cannot find symbol
      flutterEngine.getPlugins().add(new com.amazonaws.amplify.amplify_analytics_pinpoint.AmplifyAnalyticsPinpointPlugin());
                                                                                         ^
  symbol:   class AmplifyAnalyticsPinpointPlugin
  location: package com.amazonaws.amplify.amplify_analytics_pinpoint
C:\GitHub\flutter-demo-with-docs\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:29: error: cannot find symbol
      flutterEngine.getPlugins().add(new com.amazonaws.amplify.amplify_datastore.AmplifyDataStorePlugin());
                                                                                ^
  symbol:   class AmplifyDataStorePlugin
  location: package com.amazonaws.amplify.amplify_datastore
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDevDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 50s
Exception: Gradle task assembleDevDebug failed with exit code 1
```

**Comment by dgagnon** [comment] 2023-09-12 20:43
@dnys1 I've given you access to our (soon to be open-source) repo: https://github.com/projectpipeline/flutter-demo-with-docs/

**Comment by dnys1** [comment] 2023-09-13 16:35
Thanks, @dgagnon. I pulled the repo and ran the above commands and was able to successfully compile it on my Windows machine :/ 

I also tried several variations in a new app of upgrading dependencies, matching your `build.gradle` settings, etc. and could not reproduce the issue.

I'm honestly not sure what could be the problem here. I would recommend trying to [invalidate your caches](https://www.jetbrains.com/help/idea/invalidate-caches.html), and/or deleting your `android` folder and running `flutter create` again (copying back the relevant parts of the old `android` dir).

**Comment by dgagnon** [comment] 2023-09-13 16:49
We were not able to replicate it at all on MacOS (android and ios builds).

@dnys1 thank you for looking into it.  I was never able to reproduce it on purpose either.  If you have not deleted the test env yet, can you keep it and try the next release on it ? 

We suspect it may be related to GRADLE_USER_HOME and/or PUB_CACHE environments variables because I had this before I switched to using fvm.  What tends to point me toward this direction is my gradle does not work from intelij:
```
could not create task ':amplify_auth_cognito:compileDebugUnitTestSources'.
this and base files have different roots: E:\Dan\Code\Project Pipeline\flutter-demo-with-docs\build\amplify_auth_cognito and D:\Code\pubcache\hosted\pub.dev\amplify_auth_cognito-1.4.1\android.
```  
But the app builds and runs fine.   Normally I would not have opened an issue since it looks like it is a local issue with my workstation, it only happens with the amplify plugins and never with any other package.  Are there some special tasks that get run only on upgrade ?  

@amrogad also has the issue and his workstation is not build like mine and does not have gradle/pubcache env vars.  So far, the commands provided above are the only reliable way we have found to get the code building again, without resorting to recreating the flutter app as you suggest.

Since you are unable to replicate, I guess we may as well close this issue.   At least the behavior and solutions can be found now.  If other members of the community encounter the issue, we can revisit it.

**Comment by dnys1** [comment] 2023-09-13 17:10
> Are there some special tasks that get run only on upgrade ?

The Amplify packages don't do anything special. They are pretty vanilla Flutter plugins.

I will close this issue for now. If you do find a reliable way to reproduce it, I'll be more than happy to assist you in debugging it.

**Closed by dnys1** 2023-09-13 17:10 UTC
Labels: Build, not-reproducible, pending-response
