### ISSUE TITLE
signalTokensNotAvailable, waitForSignIn: userState:SIGNED_OUT_USER_POOLS_TOKENS_INVALID

### ISSUE THREAD

**Issue by thomasaab** [aws-amplify/amplify-flutter#546] opened 2021-04-28 17:21 UTC
**Describe the bug**
Trying to get User Attributes with Amplify.Auth.fetchUserAttributes() it throws me these errors: 

Inspecting user state details
W/AWSMobileClient(13803): signalTokensNotAvailable
W/AWSMobileClient(13803): Tokens are invalid, please sign-in again.
W/AWSMobileClient(13803): java.lang.Exception: No cached session.
W/AWSMobileClient(13803): 	at com.amazonaws.mobile.client.AWSMobileClient$11$1.signalTokensNotAvailable(AWSMobileClient.java:1873)
W/AWSMobileClient(13803): 	at com.amazonaws.mobile.client.AWSMobileClient$11$1.getAuthenticationDetails(AWSMobileClient.java:1853)
W/AWSMobileClient(13803): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:1032)
W/AWSMobileClient(13803): 	at com.amazonaws.mobile.client.AWSMobileClient$11.run(AWSMobileClient.java:1834)
W/AWSMobileClient(13803): 	at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
W/AWSMobileClient(13803): 	at com.amazonaws.mobile.client.AWSMobileClient.getTokens(AWSMobileClient.java:1800)
W/AWSMobileClient(13803): 	at com.amazonaws.mobile.client.AWSMobileClient.getUserStateDetails(AWSMobileClient.java:1046)
W/AWSMobileClient(13803): 	at com.amazonaws.mobile.client.AWSMobileClient.waitForSignIn(AWSMobileClient.java:925)
W/AWSMobileClient(13803): 	at com.amazonaws.mobile.client.AWSMobileClient$19.run(AWSMobileClient.java:2500)
W/AWSMobileClient(13803): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
W/AWSMobileClient(13803): 	at java.lang.Thread.run(Thread.java:919)
D/AWSMobileClient(13803): waitForSignIn: userState:SIGNED_OUT_USER_POOLS_TOKENS_INVALID
W/AWSMobileClient(13803): signalTokensNotAvailable
E/amplify:flutter:auth_cognito( 7709): AuthException{message=Failed to fetch user attributes, cause=java.lang.Exception: Operation requires a signed-in state, recoverySuggestion=Ensure that you are logged in and online}

This problem occurs when trying to sign in with Amplify.Auth.signIn after having made a sign out (it doesn't always happen). It should be noted that I also have an authentication configured with providers (google and apple) but when I authenticate with them, this error does not happen.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  [√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.4 at C:\src\flutter
    • Framework revision b1395592de (4 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\thoma\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\thoma\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (3 available)
    • Redmi Note 8 Pro (mobile) • 6hlbaupfvk4t9pyt • android-arm64  • Android 10 (API 29)
    • Chrome (web)              • chrome           • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)                • edge             • web-javascript • Microsoft Edge 90.0.818.49

• No issues found!

</details>

**Smartphone (please complete the following information):**
 - Device: [Redmi Note 8 Pro 
 - OS: Android 10 (API 29)

**Additional context**
 - amplify_flutter: "<1.0.0"
 - amplify_auth_cognito: "<1.0.0"
 - environment:
     sdk: ">=2.7.0 <3.0.0"

**Comment by thomasaab** [comment] 2021-04-29 22:41
**UPDATE**

I discovered that to replicate the error you have to do the following:



1.  Login with social: `await Amplify.Auth.signInWithWebUI (provider: AuthProvider.apple)`
2.  logout: `await Amplify.Auth.signOut ();`
3. Login with email and pw: `await Amplify.Auth.signIn (username: email.trim (), password: password.trim (),)`
4. logout:  `await Amplify.Auth.signOut ();`
5. Login with email and pw: `await Amplify.Auth.signIn (username: email.trim (), password: password.trim (),)`

In that second login, isSignedIn = true is returned, as if you do `fetchAuthSession()` it returns true, but when doing a `fetchUserAttributes()` it returns the error.

The only way to stop giving the error is by deleting the app data (just clearing the cache does not work).

**Comment by samuelchanx** [comment] 2021-06-15 04:24
Getting the same error here. In my case, when I tried to sign out a few times, and tried to sign in with the same account, the error pops up. 

Please help.

**Comment by ken-ng-esotec** [comment] 2021-06-27 14:01
I'm also getting this issue - i need to test across multiple users and therefore need to keep signing in and out

**Comment by eyeledML** [comment] 2021-09-02 08:52
Hello,
we are currently facing the same issue. We're using Cognito for authentication. Auth was configured using Amplify CLI including Google/FB social login integration. If we switch between user accounts this problem occurs occasionally. Any updates on this?

**Comment by wattanakorn495** [comment] 2021-11-07 09:38
+1

**Comment by Jordan-Nelson** [comment] 2021-11-26 16:41
I have been unable to reproduce this issue with recent versions of amplify-flutter (later than 0.2.6). There was a known issue with  sign out after signing in via web UI in earlier versions of amplify-flutter (prior to 0.1.6). This issue may still be present with versions later than 0.1.6 if you are still using the older Android Platform setup. If you are experiencing this issue with a version of amplify-flutter 0.1.6 or later, please take a look at the [Android Platform Setup](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/flutter/#android-platform-setup) docs v0.16.0+.

**Comment by abdallahshaban557** [comment] 2022-02-23 21:24
@thomasaab @wattanakorn495 @ken-ng-esotec  - are you still facing this issue?

**Comment by Jordan-Nelson** [comment] 2022-03-11 15:41
@thomasaab @wattanakorn495 @ken-ng-esotec - Please let us know if you are still facing this issue.

**Comment by Jordan-Nelson** [comment] 2022-03-21 19:07
Closing out the issue. Feel free to open a new issue if you are still facing this.

**Closed by Jordan-Nelson** 2022-03-21 19:07 UTC
Labels: pending-close-response-required, Auth
