### ISSUE TITLE
Can't get the event from the Amplify.Hub.listen

### ISSUE THREAD

**Issue by quirkeer** [aws-amplify/amplify-flutter#1290] opened 2022-01-21 14:23 UTC
I'm wondering that what is the right way to get the events from amplify hub, I just received nothing from the subscriber after `addPlugins` then `configure`

![image](https://user-images.githubusercontent.com/91845391/150542934-c54db023-f895-4c34-9051-216e4a78761c.png)

**Comment by Jordan-Nelson** [comment] 2022-01-21 14:50
Hello @quirkeer - Auth will emit events for sign in, sign out, and session expired. See [auth events here](https://docs.amplify.aws/lib/auth/auth-events/q/platform/flutter/).

Most of the DataStore events (modelSync, subscriptionEstablished) are related to cloud sync. Do you have [cloud sync](https://docs.amplify.aws/lib/datastore/sync/q/platform/flutter/) enabled? If so, you can call [DataStore.start()](https://docs.amplify.aws/lib/datastore/other-methods/q/platform/flutter/) to start cloud sync. I would have to confirm if any of the DataStore events will emit if you do not have cloud sync enabled. You can see the [DataStore hub events here](https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/flutter/).

If you are not seeing events emit after sign in, or if you have cloud sync enabled and have called DataStore.start() (or other DataStore methods that should trigger a sync) and you are still not seeing events, please let me know.

**Comment by quirkeer** [comment] 2022-01-22 10:13
cool got it~ Another question is that if I've already sign in previously and when I quit then reopen app, will the auth events be triggered again? If yes, then which event will be trigger firstly, the datastore `ready` event or the auth `signed-in` event?

**Comment by quirkeer** [comment] 2022-01-22 10:14
If no then how could I get a way to trigger this event manually?

**Comment by Jordan-Nelson** [comment] 2022-01-22 13:36
I would have to confirm this, but I don't believe you will get a sign in event after relaunching the app. I believe it is only fired when you go from a signed out state to a signed in state. You could call either getCurrentUser or fetchAuthSession if you are trying to determine authentication status when the app launches. From another issue you opened, it looks like you may be using the Authenticator widget, which will determine authentication status for you when the app launches, and will listen to sign out events.

The ready event is DataStore specific. It will emit when datastore has finished syncing with the cloud (assuming you have cloud sync enabled). You can still query/save data before that, but all datastore queries run against the local/offline DB so until the ready event has emitted the local/offline DB may not have all the data from the cloud. It should emit after closing and relaunching the app. If there is a lot of data to sync from the cloud on app launch, you may see a noticeable delay between app launch and the event being emitted.

**Comment by quirkeer** [comment] 2022-01-22 18:24
Thank you dude, I've tried too and currently I'm using `fetchAuthSession` to get whether the user is signed. 

For the Datastore I have a question, is it possible to only sync specific model to local? 

Since I'm using a data model called `User` to save some user's information like avatar url, nickname, etc. But you know that it's bad to sync other user's profile to local. So I'm supposed to call API to fetch user's profile instead of syncing all user's data. But for the other models, I want them to be synced.

**Comment by Jordan-Nelson** [comment] 2022-01-24 14:54
Yes, you use [selective sync](https://docs.amplify.aws/lib/datastore/sync/q/platform/flutter/#selectively-syncing-a-subset-of-your-data) to choose which data you would like to sync to the local DB. This allows you to write a query that will be used to determine which data is synced. In this case you could query for Users where the userID is equal to a certain ID.

In order to sync the current user's info, you would need to re-evaluate the sync expression after the user logs in (so that you can use the user ID in the query). I know Amplify-iOS and Amplify-Android support re-evaluating the sync expression at runtime (see example in [Amplify-Android docs](https://docs.amplify.aws/lib/datastore/sync/q/platform/android/#reevaluate-expressions-at-runtime)). I don't believe Amplify-Flutter supports this currently. I think the sync expression will only get evaluated at configuration time. Let me confirm that, and if that is the case we can open a feature request for re-evaluating the sync expressions at runtime.

If re-evaluating the sync expression at runtime is not yet supported, you could write a query that prevents any user data from being synced, and then you would have to make network request to get any user's data (even the current user).

I also want to note that authorization rules will also determine which data is synced, but I don't think that is what you are looking for. It sounds like you want every user to have read access to the data, but you do not want it to sync locally.

**Comment by quirkeer** [comment] 2022-01-27 05:50
thank you very much bro it's really helpful for me! really expect for the re-evaluating feature~

**Comment by quirkeer** [comment] 2022-01-27 05:53
yep currently there is no need for syncing data via specific authorization rule~ but it's pretty good if the datastore provides the functionality like this.

**Comment by Jordan-Nelson** [comment] 2022-01-28 02:53
@quirkeer I was able to confirm that re-evaluating sync expressions is supported. If you call `DataStore.clear()` and then `DataStore.start()` OR `DataStore.stop()` and then `DataStore.start()`, the sync expressions will be re-evaluated.

This is a gap in our documentation. I have opened a [separate issue](https://github.com/aws-amplify/amplify-flutter/issues/1315) to track that.

Let me know if you have any other questions before I close out this issue.

**Comment by HuiSF** [comment] 2022-03-10 18:45
Confirmed that amplify-flutter supports sync expression re-evaluate. Corresponding [documentation](https://docs.amplify.aws/lib/datastore/sync/q/platform/flutter/#reevaluate-expressions-at-runtime) has been updated.

I'm closing this issue. Please feel free to follow up if anything. Thanks!

**Closed by HuiSF** 2022-03-10 18:45 UTC
Labels: Question, Auth, DataStore

**Comment by charlieforward9** [comment] 2023-08-24 18:32
> [I don't believe you will get a sign in event after relaunching the app](https://github.com/aws-amplify/amplify-flutter/issues/1290#issuecomment-1019268931) 

@Jordan-Nelson I am trying to set up an event handler that listens to the Auth Hub Channel. It would be extremely helpful if the HubChannel emitted `AuthHubEventType.signedIn` on app launch if a user was signed in. 

```dart
switch (data.type) {
  case AuthHubEventType.signedIn:
    //Show home screen
    break;
  case AuthHubEventType.sessionExpired:
  case AuthHubEventType.signedOut:
  case AuthHubEventType.userDeleted:
    //Show auth screen
}
```

Is this a complicated feature request or is there a design choice that specifically avoids this functionality?

**Comment by Jordan-Nelson** [comment] 2023-08-28 15:04
@charlieforward9 - The auth hub only emits an event when the auth state changes. The auth state does not change when the app is relaunched. You could use `fetchAuthSession` on relaunch to check the session status.

I think your request is similar to https://github.com/aws-amplify/amplify-flutter/issues/2654. Feel free to comment on that issue with your use case.
