### ISSUE TITLE
Issue with Model Deserialization for Nested Objects in GraphQL Response - Amplify - Flutter

### ISSUE THREAD

**Issue by iamvalenciia** [aws-amplify/amplify-flutter#4286] opened 2023-12-23 05:55 UTC
**Description**
We've encountered an issue where our models are not correctly deserializing nested objects when fetching data via GraphQL. This specifically occurs with nested comments within posts. The current model structure seems to be unable to parse the nested comments correctly, leading to incomplete or incorrect data representation in the app.

**Steps to Reproduce**
    1. Execute a GraphQL query to fetch posts, which includes nested comments.
    2. Observe the deserialization process of the response in the Post.fromJson method.
    3. Notice that the nested comments are either not parsed correctly or result in an error.

**Expected Behavior**
The Post model should correctly deserialize the nested Comment objects, representing the complete post data, including its comments, as defined in the GraphQL query.

**Actual Behavior**
The Post model fails to correctly deserialize the nested Comment objects. This results in either missing comments in the post object or an error during the parsing process.

**Possible Solution**
Adjust the Post.fromJson method to handle the nested structure of comments properly. Ensure that the method iterates through the nested comments.items list and correctly parses each comment using the Comment.fromJson method.

> ### **Use the following as reference**

**GraphQL Schema:**
```
type Post
  @model
  @auth(
    rules: [
      { allow: public, provider: apiKey, operations: [read] }
      { allow: owner }
    ]
  ) {
  id: ID!
  category: String!
  text: String
  latitude: Float!
  longitude: Float!
  comments: [Comment]
    @hasMany(indexName: "byPost", fields: ["id"])
    @auth(
      rules: [
        { allow: owner }
        { allow: public, provider: apiKey, operations: [read] }
        { allow: private, operations: [create] }
      ]
    )
}

type Comment
  @model
  @auth(
    rules: [
      { allow: public, provider: apiKey, operations: [read] }
      { allow: owner } # Allows any signed-in user to create a comment
    ]
  ) {
  id: ID!
  postID: ID! @index(name: "byPost", sortKeyFields: ["content"])
  post: Post! @belongsTo(fields: ["postID"])
  content: String!
}
```

**GraphQL Query Used for fetching data:**
```
query ListPosts {
  listPosts {
    items {
      id
      category
      text
      latitude
      longitude
      comments {
        items {
          id
          postID
          content
        }
      }
      createdAt
      updatedAt
      userPostsId
    }
  }
}
```
**Post.fromJson - Before**
```
  Post.fromJson(Map<String, dynamic> json)
      : id = json['id'],
        _category = json['category'],
        _text = json['text'],
        _latitude = (json['latitude'] as num?)?.toDouble(),
        _longitude = (json['longitude'] as num?)?.toDouble(),
        _comments = json['comments'] is List
            ? (json['comments'] as List)
                .where((e) => e?['serializedData'] != null)
                .map((e) => Comment.fromJson(
                    new Map<String, dynamic>.from(e['serializedData'])))
                .toList()
            : null,
        _createdAt = json['createdAt'] != null
            ? amplify_core.TemporalDateTime.fromString(json['createdAt'])
            : null,
        _updatedAt = json['updatedAt'] != null
            ? amplify_core.TemporalDateTime.fromString(json['updatedAt'])
            : null,
        _userPostsId = json['userPostsId'];
```

**Post.fromJson - After**
```
  Post.fromJson(Map<String, dynamic> json)
      : id = json['id'],
        _category = json['category'],
        _text = json['text'],
        _latitude = (json['latitude'] as num?)?.toDouble(),
        _longitude = (json['longitude'] as num?)?.toDouble(),
        _comments = (json['comments']['items'] as List)
            .map((e) => Comment.fromJson(e as Map<String, dynamic>))
            .toList(),
        _createdAt = json['createdAt'] != null
            ? amplify_core.TemporalDateTime.fromString(json['createdAt'])
            : null,
        _updatedAt = json['updatedAt'] != null
            ? amplify_core.TemporalDateTime.fromString(json['updatedAt'])
            : null,
        _userPostsId = json['userPostsId'];
```
**Functions show use:**
```
  Future<List<Post>> _fetchPosts() async {
    try {
      String graphQLDocument = '''
        query ListPosts {
          listPosts {
            items {
              id
              category
              text
              latitude
              longitude
              comments {
                items {
                  id
                  postID
                  content
                }
              }
              createdAt
              updatedAt
              userPostsId
            }
          }
        }
      ''';

      // Create a GraphQLRequest object
      final request = GraphQLRequest<String>(
          document: graphQLDocument, apiName: 'ministrar3ApiKey');

      // Execute the query
      final operation = Amplify.API.query(request: request);
      final response = await operation.response;

      if (response.hasErrors) {
        safePrint('errors: ${response.errors}');
        return [];
      }
      safePrint("Fetched RESPONSEEE: ${response.data}");

      // Decode the response data
      final Map<String, dynamic> decodedData = jsonDecode(response.data ?? '');

      // Parse the response data into Post objects
      final postItems = (decodedData['listPosts']['items'] as List)
          .map((item) => Post.fromJson(item as Map<String, dynamic>))
          .toList();

      safePrint("Fetched Posts: $postItems");
      
      // save the post lis in a provider
      _providerPostList.setPostList(postItems);
      return postItems;
    } on ApiException catch (e) {
      safePrint('Query failed: $e');
      return [];
    }
  }
```

_This was my solution but please I want to receive feedback to know if there is a better approach to anything pulished here, thank you._

**Comment by timngyn** [comment] 2023-12-26 17:52
Hi @iamvalenciia, I'm transferring this issue over to https://github.com/aws-amplify/amplify-flutter, based on the "flutter" in your title as they might be able to help you here. If this is correct then let me know and we can figure out where to transfer this issue so that you can get the help you need.

**Comment by fjnoyp** [comment] 2023-12-28 19:25
Hi @iamvalenciia thanks for sharing your issue, can you please provide the full error stack trace you are receiving including line number it fails at?  This will help us debug whether this is happening in native or Dart code and what exactly failed.  Thank you!

**Comment by Equartey** [comment] 2024-01-04 16:47
Hi @iamvalenciia,  I am going to close this as a duplicate of - https://github.com/aws-amplify/amplify-flutter/issues/816. 

This is something we are looking into and would like to fix. You can follow the issue linked above for updates.

> This was my solution but please I want to receive feedback to know if there is a better approach to anything pulished here, thank you.

Meanwhile, this approach is a good work around until we natively support a solution.

**Closed by Equartey** 2024-01-04 16:47 UTC
Labels: GraphQL API
