### ISSUE TITLE
"An unknown error occurred" for Amplify.Auth.signUp process when exceeding daily email limit for Amazon SES to deliver verification email to new users

### ISSUE THREAD

**Issue by szymondobrzanski** [aws-amplify/amplify-flutter#4003] opened 2023-10-25 13:02 UTC
### Description

Im getting following exception: 

```
flutter: Error: UnknownServiceException {
  "message": "An unknown error occurred",
  "underlyingException": "Instance of 'UnknownSmithyHttpException'"
}
```

while trying to register user by email and password.
```
final userAttributes = <CognitoUserAttributeKey, String>{
        CognitoUserAttributeKey.email: emailAddress
      };
      await Amplify.Auth.signUp(
        username: emailAddress,
        password: password,
        options: SignUpOptions(userAttributes: userAttributes),
      );
```

It also occurred to me yesterday, today's morning everything was fine until around 2pm cest. I didn't make any changes to my amplify config.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Try to register user with email and password

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.8

### Amplify Flutter Version

12.5.2

### Deployment Method

Amplify CLI

**Comment by szymondobrzanski** [comment] 2023-10-26 07:45
Update: same error for social auth (google, Facebook, apple). This morning it started to work again

**Comment by marcschny** [comment] 2023-10-26 11:11
Same problem... but for me it didn't start working again this morning

**Comment by marcschny** [comment] 2023-10-26 11:37
@szymondobrzanski I found the underlying problem, in my case it was: 
"LimitExceededException: Exceeded daily email limit for the operation or the account. If a higher limit is required, please configure your user pool to use your own Amazon SES configuration for sending email."

The email limit is reset daily, that's why it worked for you again this morning

**Comment by szymondobrzanski** [comment] 2023-10-27 07:49
Thanks for the tip @marcschny ! it's the same issue in my case. I think it would be worth to improve error message so that it's not so general.

**Comment by cwomack** [comment] 2023-10-27 17:17
@szymondobrzanski and @marcschny, we appreciate you both confirming the root cause of the issue here.  We've marked this as a bug for now with the action to improve the error handling when this happen.  Thank you!

**Closed** 2024-05-21 18:51 UTC
Labels: bug, auth, pending-release
