### ISSUE TITLE
GraphQL query not working with CUSTOM_AUTH

### ISSUE THREAD

**Issue by Vingtoft** [aws-amplify/amplify-flutter#1160] opened 2021-12-01 17:13 UTC
**Describe the bug**
This error only appears on Android.

Creating a GraphQL query results in the following exception:

```
D/AWSMobileClient(17792): Inspecting user state details
D/AWSMobileClient(17792): hasFederatedToken: false provider: cognito-idp.eu-central-1.amazonaws.com/eu-central-1_U8aaDh09v
D/AWSMobileClient(17792): waitForSignIn: userState:SIGNED_IN
2 I/System.out(17792): (HTTPLog)-Static: isSBSettingEnabled false

E/amplify:flutter:api(11333): GraphQL mutate operation failed
E/amplify:flutter:api(11333): NonRetryableException{message=OkHttp client request failed., cause=null, recoverySuggestion=Irrecoverable error}
E/amplify:flutter:api(11333): 	at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:147)
E/amplify:flutter:api(11333): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
E/amplify:flutter:api(11333): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/amplify:flutter:api(11333): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/amplify:flutter:api(11333): 	at java.lang.Thread.run(Thread.java:923)
```

Prior to version `0.2.8` the entire app crashed, after upgrading to `0.2.8` the exception is still thrown but the app does not crash.

**To Reproduce**
Use configuration similar to the below (please note i use CUSTOM_AUTH)

```
{
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "CognitoUserPool": {
          "Default": {
            "PoolId": "eu-central-1_xxyy",
            "AppClientId": "xxyy",
            "IdentityPoolId": "eu-central-1:xxyy",
            "Region": "eu-central-1"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "CUSTOM_AUTH"
          }
        }
      }
    }
  },
  "api": {
    "plugins": {
      "awsAPIPlugin": {
        "pluto": {
          "endpointType": "GraphQL",
          "endpoint": "https://xxyy.appsync-api.eu-central-1.amazonaws.com/graphql",
          "region": "eu-central-1",
          "authorizationType": "AMAZON_COGNITO_USER_POOLS"
        }
      }
    }
  }
}
```

Create an GraphQL operation:

```
var operation = Amplify.API.query( // <-- Exception happens somewhere between here
        request: GraphQLRequest(
          document: Queries.getUser,
          variables: {
            'id': '123',
          },
        ),
      );

      var response = await operation.response; // <--- ... and here
```

**Expected behavior**
Expected to not crash (works perfectly on iOS)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8 and Samsung Galaxy A41
 - OS: Crash happens on Android 9 and Android 11 (only tested on 9 & 11)

**Additional context**
I suspect this issue may be related to this: 

https://github.com/aws-amplify/amplify-flutter/issues/1022

**Comment by dnys1** [comment] 2021-12-01 18:06
Hi @Vingtoft - has this worked before 0.2.8? Also, out of curiosity, how are you able to perform `CUSTOM_AUTH` since it is not supported by Flutter? If you're able to provide a full log file that would help as well. Thanks!

**Comment by Vingtoft** [comment] 2021-12-01 19:33
@dnys1, thank you for your quick reply, much appreciated! 

_Also, out of curiosity, how are you able to perform CUSTOM_AUTH since it is not supported by Flutter?_

First of all, the reason why we have CUSTOM_AUTH is because we have implemented passwordless authentication (user signs up / signs in using phone number and verification code).
This is achieved using Cognito with custom Lambda triggers. It works perfectly and UX is supreme 😎

It is true Amplify Flutter does not support this out-of-the-box (as Amplify for Angular/nodejs does), so we did a little hack:

Step one (submitting phone number, for signing up *or* signing in):

```
Future<void> _signUpOrSignIn() async {
    final String number = '+45$phonenumber';
    try {
      await Amplify.Auth.signIn(username: number, password: 'not-needed'); //hacky hack 😳😂
    } on UserNotFoundException {
      await Amplify.Auth.signUp(
        username: number,
        password: 'not-needed',
        options: CognitoSignUpOptions(
          userAttributes: {
            'phone_number': number,
          },
        ),
      );
      await Amplify.Auth.signIn(username: number, password: 'not-needed'); // sign in after user signed up
    } catch (e) {
       // Doing some stuff here
    }
  }
```
Step two (Submit verification code (MFA)) is completed normally using `Amplify.Auth.confirmSignIn(confirmationValue: code)`


_ If you're able to provide a full log file that would help as well_

Please see below:

```
W/uto.markets.de(20042): Long monitor contention with owner Thread-8 (27434) at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserSession com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getCachedSession()(CognitoUser.java:1304) waiters=0 in com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserSession com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getCachedSession() for 449ms
D/AWSMobileClient(20042): hasFederatedToken: false provider: cognito-idp.eu-central-1.amazonaws.com/eu-central-1_U8aaDh09v
D/AWSMobileClient(20042): waitForSignIn: userState:SIGNED_IN
2
I/System.out(20042): (HTTPLog)-Static: isSBSettingEnabled false
I/flutter (20042): Er det fucking her vi crasher??
D/AWSMobileClient(20042): Inspecting user state details
D/AWSMobileClient(20042): hasFederatedToken: false provider: cognito-idp.eu-central-1.amazonaws.com/eu-central-1_U8aaDh09v
D/AWSMobileClient(20042): waitForSignIn: userState:SIGNED_IN
2
I/System.out(20042): (HTTPLog)-Static: isSBSettingEnabled false
I/flutter (20042): Before!
E/amplify:flutter:api(20042): GraphQL mutate operation failed
E/amplify:flutter:api(20042): NonRetryableException{message=OkHttp client request failed., cause=null, recoverySuggestion=Irrecoverable error}
E/amplify:flutter:api(20042): 	at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:147)
E/amplify:flutter:api(20042): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
E/amplify:flutter:api(20042): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/amplify:flutter:api(20042): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/amplify:flutter:api(20042): 	at java.lang.Thread.run(Thread.java:923)
W/AtomicResult(query)(20042):                     Attempted to send error value after initial reply:
W/AtomicResult(query)(20042):  PlatformException{code=ApiException, message=Translating platform exception failed. Please take a look at
W/AtomicResult(query)(20042): https://github.com/aws-amplify/amplify-flutter/issues to see if there are any existing issues that
W/AtomicResult(query)(20042): match your scenario, and file an issue with the details of the bug if there isn't., details={recoverySuggestion=Irrecoverable error, message=OkHttp client request failed.}}

```

**Comment by dnys1** [comment] 2021-12-01 20:51
Thanks, @Vingtoft - super cool you've been able to achieve that flow! 😃 

I see the error now and will try to reproduce it - no idea what could be causing it, but it will be different from #1022. 0.2.8 included a fix for a crash which happens when the platform channel result is submitted twice from the platform side. That seems to be the case here.

I'll keep you posted!

**Comment by Vingtoft** [comment] 2021-12-01 21:21
@dnys1, I've been doing some research on my end, and something did not make sense: I was able to execute other queries without getting an error, but the query in question failed on Android. I destructed the query and build it up, part by part, in order to know when the error happened, and I have now re-constructed the query and *it works*.

I have no idea why one query does not work, but the other one does (and both of them works on iOS)

It might have been an illegal invisible character that puts a stick in the Android wheel but is ignored by iOS. 

Been a long time since I've experienced such a random bug. 

Thanks for your help!

**Comment by matthewfx** [comment] 2021-12-02 04:01
hey, I have a similar issue on Android. When the user is not yet authenticated and makes a query requiring authentication it crashes the Android app. On iOS it returns Unauthorised or 401 and the app can handle it gracefully. On Android it crashes before the `on Exception catch` :( However, I'm on 0.2.6 so will try 0.2.8 and let you know if it crashes there too.

**Comment by ragingsquirrel3** [comment] 2021-12-02 17:27
> @dnys1, I've been doing some research on my end, and something did not make sense: I was able to execute other queries without getting an error, but the query in question failed on Android. I destructed the query and build it up, part by part, in order to know when the error happened, and I have now re-constructed the query and _it works_.
> 
> I have no idea why one query does not work, but the other one does (and both of them works on iOS)
> 
> It might have been an illegal invisible character that puts a stick in the Android wheel but is ignored by iOS.
> 
> Been a long time since I've experienced such a random bug.
> 
> Thanks for your help!

I wonder if perchance the failing query had a tab to indent the graphql document string? I have noticed this causes a similar error in android (not ios) which resolved when changing to space.

**Comment by matthewfx** [comment] 2021-12-02 22:03
I checked the 0.2.10 and it is no longer crashing for me when the app makes a query and is no authorised.

**Comment by Vingtoft** [comment] 2021-12-03 06:43
@ragingsquirrel3 I cannot confirm or dismiss your theory, since I do not know why the query only worked when it was rewritten (the working query is exactly the same as the query that did not work).

It might have been a issue with tabs/spaces (I copied the query into VS Code from WebStorm), I sounds plausible.

**Comment by ragingsquirrel3** [comment] 2021-12-03 17:52
added https://github.com/aws-amplify/amplify-flutter/issues/1175 for tab issue

**Comment by ragingsquirrel3** [comment] 2021-12-03 17:56
I'm going to close this issue as graphql query seems to be working w custom auth. I open separate issue for tabbed whitespace in graphql document string. Thanks for all the info.

**Closed by ragingsquirrel3** 2021-12-03 17:56 UTC
Labels: Android, to-be-reproduced, API
