### ISSUE TITLE
Crash when calling updateUserAttribute

### ISSUE THREAD

**Issue by itsJoKr** [aws-amplify/amplify-flutter#2740] opened 2023-03-09 07:53 UTC
### Description

Calling `updateUserAttribute` will crash the native app. Test on my iOS simulator.

I'm using following packages:
```
  amplify_flutter: ^1.0.0-next.0
  amplify_auth_cognito: ^1.0.0-next.0
```
Because there was issue during verficiation so I was forced to bump `1.0.0-next.0`.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Call something like:
```
    await _auth.updateUserAttribute(userAttributeKey: CognitoUserAttributeKey.preferredUsername, value: 'JohnDoe');
```
2. Observe the crash with the following logs:

```
[+28553 ms] version=2.19.0 (stable) (Mon Jan 23 11:29:09 2023 -0800) on "ios_arm64"
[        ] pid=5303, thread=23811, isolate_group=main(0x14f03d400), isolate=main(0x14f02c400)
[        ] os=ios, arch=arm64, comp=no, sim=no
[        ] isolate_instructions=10c7c1e80, vm_instructions=10c7c1e80
[   +1 ms]   pc 0x000000010c8e3538 fp 0x000000016b4c6480 dart::Profiler::DumpStackTrace(void*)+0x68
[        ]   pc 0x000000010c7c2048 fp 0x000000016b4c64a0 dart::Assert::Fail(char const*, ...) const+0x28
[        ]   pc 0x000000010c966c58 fp 0x000000016b4c64d0 dart::compiler::Assembler::EmitUnconditionalBranch(dart::UnconditionalBranchOp, dart::compiler::Label*)+0x0
[        ]   pc 0x000000010c992998 fp 0x000000016b4c6550 dart::compiler::Assembler::ldr(dart::Register, dart::compiler::Address, dart::compiler::OperandSize)+0x144
[        ]   pc 0x000000010c9a356c fp 0x000000016b4c6570 dart::compiler::Assembler::LoadCompressedField(dart::Register, dart::compiler::FieldAddress const&)+0x28
[        ]   pc 0x000000010c9bfcb0 fp 0x000000016b4c65c0 dart::FlowGraphCompiler::GenerateCallerChecksForAssertAssignable(dart::CompileType*, dart::AbstractType const&, dart::compiler::Label*)+0x264
[        ]   pc 0x000000010c9bf9e0 fp 0x000000016b4c6640 dart::FlowGraphCompiler::GenerateAssertAssignable(dart::CompileType*, dart::InstructionSource const&, long, dart::Environment*, dart::String const&, dart::LocationSummary*)+0xf8
[   +5 ms]   pc 0x000000010c9d64a4 fp 0x000000016b4c6680 dart::AssertAssignableInstr::EmitNativeCode(dart::FlowGraphCompiler*)+0x70
[        ]   pc 0x000000010c9ba834 fp 0x000000016b4c6840 dart::FlowGraphCompiler::VisitBlocks()+0x71c
[        ]   pc 0x000000010c9ba0bc fp 0x000000016b4c6870 dart::FlowGraphCompiler::CompileGraph()+0x90
[  +22 ms]   pc 0x000000010ca6b788 fp 0x000000016b4c6880 dart::CompilerPass_GenerateCode::DoBody(dart::CompilerPassState*) const+0x10
[        ]   pc 0x000000010ca6a758 fp 0x000000016b4c6970 dart::CompilerPass::Run(dart::CompilerPassState*) const+0x1b0
[        ]   pc 0x000000010c96bf08 fp 0x000000016b4c7150 dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)+0x6ec
[        ]   pc 0x000000010c96c654 fp 0x000000016b4c7850 dart::CompileFunctionHelper(dart::CompilationPipeline*, dart::Function const&, bool, long)+0x324
[        ]   pc 0x000000010c96c308 fp 0x000000016b4c78e0 dart::Compiler::CompileFunction(dart::Thread*, dart::Function const&)+0x100
[        ]   pc 0x000000010c888d3c fp 0x000000016b4c7930 dart::Function::EnsureHasCode() const+0x4c
[        ]   pc 0x000000010c96b03c fp 0x000000016b4c7eb0 dart::DRT_CompileFunction(dart::NativeArguments)+0x17c
[        ]   pc 0x0000000119f02f8c fp 0x000000016b4c7ef8 Unknown symbol
[        ]   pc 0x0000000119f03010 fp 0x000000016b4c7f28 Unknown symbol
[        ]   pc 0x000000012f89a38c fp 0x000000016b4c7f80 Unknown symbol
[        ]   pc 0x000000012f89a0ec fp 0x000000016b4c7fc8 Unknown symbol
[        ]   pc 0x000000012f899ec0 fp 0x000000016b4c8000 Unknown symbol
[        ]   pc 0x000000012f8985bc fp 0x000000016b4c80a8 Unknown symbol
[        ]   pc 0x000000012f897efc fp 0x000000016b4c80e8 Unknown symbol
[        ]   pc 0x0000000131dbeb5c fp 0x000000016b4c8150 Unknown symbol
[        ]   pc 0x000000012b6acb10 fp 0x000000016b4c81a0 Unknown symbol
[        ]   pc 0x000000012b6ac7a0 fp 0x000000016b4c8220 Unknown symbol
[        ]   pc 0x000000012b6ac5ac fp 0x000000016b4c8288 Unknown symbol
[        ]   pc 0x000000012b6ac2f4 fp 0x000000016b4c8320 Unknown symbol
[        ]   pc 0x000000012b6ada24 fp 0x000000016b4c8370 Unknown symbol
[        ]   pc 0x000000012b6ad62c fp 0x000000016b4c83d0 Unknown symbol
[        ]   pc 0x000000012b6ab030 fp 0x000000016b4c8450 Unknown symbol
[        ]   pc 0x000000012b6a9758 fp 0x000000016b4c8498 Unknown symbol
[        ]   pc 0x000000012b6b2e18 fp 0x000000016b4c84e0 Unknown symbol
[        ]   pc 0x0000000119f07de0 fp 0x000000016b4c8510 Unknown symbol
[        ]   pc 0x000000012b6acb10 fp 0x000000016b4c8560 Unknown symbol
[        ]   pc 0x000000012b6ac7a0 fp 0x000000016b4c85e0 Unknown symbol
[        ]   pc 0x000000012b6ac5ac fp 0x000000016b4c8648 Unknown symbol
[        ]   pc 0x000000012b6ac2f4 fp 0x000000016b4c86e0 Unknown symbol
[        ]   pc 0x000000012b6ada24 fp 0x000000016b4c8730 Unknown symbol
[        ]   pc 0x000000012b6ad62c fp 0x000000016b4c8790 Unknown symbol
[        ]   pc 0x000000012b6ab030 fp 0x000000016b4c8810 Unknown symbol
[        ]   pc 0x000000012b6a9758 fp 0x000000016b4c8858 Unknown symbol
[        ]   pc 0x000000012b6c04e4 fp 0x000000016b4c8898 Unknown symbol
[        ]   pc 0x0000000123c4af70 fp 0x000000016b4c8910 Unknown symbol
[        ]   pc 0x0000000123c4abe4 fp 0x000000016b4c8970 Unknown symbol
[        ]   pc 0x0000000123c4a2ec fp 0x000000016b4c8a00 Unknown symbol
[        ]   pc 0x000000012b6a3598 fp 0x000000016b4c8a70 Unknown symbol
[        ]   pc 0x000000012b6a3444 fp 0x000000016b4c8ab0 Unknown symbol
[        ]   pc 0x000000012b6a3124 fp 0x000000016b4c8af8 Unknown symbol
[        ]   pc 0x000000012b6a2cb4 fp 0x000000016b4c8b38 Unknown symbol
[        ]   pc 0x000000012b6a2bac fp 0x000000016b4c8b60 Unknown symbol
[        ]   pc 0x0000000119f03518 fp 0x000000016b4c8c30 Unknown symbol
[        ]   pc 0x000000010c806598 fp 0x000000016b4c8cd0 dart::DartEntry::InvokeCode(dart::Code const&, unsigned long, dart::Array const&, dart::Array const&, dart::Thread*)+0x138
[        ]   pc 0x000000010c80640c fp 0x000000016b4c8d30 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)+0x128
[        ]   pc 0x000000010c806bd0 fp 0x000000016b4c8d80 dart::DartEntry::InvokeCallable(dart::Thread*, dart::Function const&, dart::Array const&, dart::Array const&)+0x174
[        ]   pc 0x000000010cb2c204 fp 0x000000016b4c8e90 Dart_InvokeClosure+0x438
[   +9 ms]   pc 0x000000010c60c42c fp 0x000000016b4c8f20 tonic::DartMicrotaskQueue::RunMicrotasks()+0x84
[        ]   pc 0x000000010c4e6770 fp 0x000000016b4c8fb0 fml::MessageLoopImpl::FlushTasks(fml::FlushType)+0xc8
[        ]   pc 0x000000010c4ecd94 fp 0x000000016b4c8fd0 fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*)+0x20
[        ]   pc 0x000000018037383c fp 0x000000016b4c8fe0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__+0x1c
[        ]   pc 0x00000001803734f8 fp 0x000000016b4ca0b0 __CFRunLoopDoTimer+0x364
[        ]   pc 0x0000000180372be4 fp 0x000000016b4ca110 __CFRunLoopDoTimers+0x11c
[        ]   pc 0x000000018036d2d4 fp 0x000000016b4cae80 __CFRunLoopRun+0x718
[        ]   pc 0x000000018036c7a4 fp 0x000000016b4caf30 CFRunLoopRunSpecific+0x248
[        ]   pc 0x000000010c4ecec4 fp 0x000000016b4caf70 fml::MessageLoopDarwin::Run()+0x58
[        ]   pc 0x000000010c4e6658 fp 0x000000016b4caf90 fml::MessageLoopImpl::DoRun()+0x28
[        ]   pc 0x000000010c4ebcc4 fp 0x000000016b4cafc0 void* std::_LIBCPP_ABI_NAMESPACE::__thread_proxy[abi:v15000]<std::_LIBCPP_ABI_NAMESPACE::tuple<std::_LIBCPP_ABI_NAMESPACE::unique_ptr<std::_LIBCPP_ABI_NAMESPACE::__thread_struct, std::_LIBCPP_ABI_NAMESPACE::default_delete<std::_LIBCPP_ABI_NAMESPACE::__thread_struct>>, fml::Thread::Thread(std::_LIBCPP_ABI_NAMESPACE::function<void (fml::Thread::ThreadConfig const&)> const&, fml::Thread::ThreadConfig const&)::$_0>>(void*)+0xd0
[        ]   pc 0x00000001b059e4e4 fp 0x000000016b4cafe0 _pthread_start+0x74
[        ] -- End of DumpStackTrace
[        ]   pc 0x0000000000000000 fp 0x000000016b4c7ef8 sp 0x0000000000000000 [Stub] CallToRuntime
[        ]   pc 0x0000000119f03010 fp 0x000000016b4c7f28 sp 0x000000016b4c7f08 [Stub] LazyCompile
[        ]   pc 0x000000012f89a38c fp 0x000000016b4c7f80 sp 0x000000016b4c7f38 [Unoptimized] AuthRepositoryImpl.deleteAccount
[        ]   pc 0x000000012f89a0ec fp 0x000000016b4c7fc8 sp 0x000000016b4c7f90 [Unoptimized] DeleteAccountInteractor.deleteAccount
[        ]   pc 0x000000012f899ec0 fp 0x000000016b4c8000 sp 0x000000016b4c7fd8 [Unoptimized] DeleteAccountRequestNotifier.deleteAccount.<anonymous closure>
[        ]   pc 0x000000012f8985bc fp 0x000000016b4c80a8 sp 0x000000016b4c8010 [Unoptimized] RequestNotifier.executeRequest
[        ]   pc 0x000000012f897efc fp 0x000000016b4c80e8 sp 0x000000016b4c80b8 [Unoptimized] DeleteAccountRequestNotifier.deleteAccount
[        ]   pc 0x0000000131dbeb5c fp 0x000000016b4c8150 sp 0x000000016b4c80f8 [Unoptimized] ProfileDeleteAccountRow._onAccountDeletePressed@121350347
[        ]   pc 0x000000012b6acb10 fp 0x000000016b4c81a0 sp 0x000000016b4c8160 [Unoptimized] _SuspendState@4048458._createAsyncCallbacks@4048458.thenCallback
[        ]   pc 0x000000012b6ac7a0 fp 0x000000016b4c8220 sp 0x000000016b4c81b0 [Unoptimized] _rootRunUnary@4048458
[        ]   pc 0x000000012b6ac5ac fp 0x000000016b4c8288 sp 0x000000016b4c8230 [Unoptimized] _rootRunUnary@4048458
[        ]   pc 0x000000012b6ac2f4 fp 0x000000016b4c8320 sp 0x000000016b4c8298 [Unoptimized] _CustomZone@4048458.runUnary
[        ]   pc 0x000000012b6ada24 fp 0x000000016b4c8370 sp 0x000000016b4c8330 [Unoptimized] _FutureListener@4048458.handleValue
[        ]   pc 0x000000012b6ad62c fp 0x000000016b4c83d0 sp 0x000000016b4c8380 [Unoptimized] _Future@4048458._propagateToListeners@4048458.handleValueCallback
[        ]   pc 0x000000012b6ab030 fp 0x000000016b4c8450 sp 0x000000016b4c83e0 [Unoptimized] _Future@4048458._propagateToListeners@4048458
[        ]   pc 0x000000012b6a9758 fp 0x000000016b4c8498 sp 0x000000016b4c8460 [Unoptimized] _Future@4048458._completeWithValue@4048458
[        ]   pc 0x000000012b6b2e18 fp 0x000000016b4c84e0 sp 0x000000016b4c84a8 [Unoptimized] _SuspendState@4048458._returnAsync@4048458
[        ]   pc 0x0000000119f07de0 fp 0x000000016b4c8510 sp 0x000000016b4c84f0 [Stub] ReturnAsync
[        ]   pc 0x000000012b6acb10 fp 0x000000016b4c8560 sp 0x000000016b4c8520 [Unoptimized] _SuspendState@4048458._createAsyncCallbacks@4048458.thenCallback
[        ]   pc 0x000000012b6ac7a0 fp 0x000000016b4c85e0 sp 0x000000016b4c8570 [Unoptimized] _rootRunUnary@4048458
[        ]   pc 0x000000012b6ac5ac fp 0x000000016b4c8648 sp 0x000000016b4c85f0 [Unoptimized] _rootRunUnary@4048458
[        ]   pc 0x000000012b6ac2f4 fp 0x000000016b4c86e0 sp 0x000000016b4c8658 [Unoptimized] _CustomZone@4048458.runUnary
[        ]   pc 0x000000012b6ada24 fp 0x000000016b4c8730 sp 0x000000016b4c86f0 [Unoptimized] _FutureListener@4048458.handleValue
[        ]   pc 0x000000012b6ad62c fp 0x000000016b4c8790 sp 0x000000016b4c8740 [Unoptimized] _Future@4048458._propagateToListeners@4048458.handleValueCallback
[        ]   pc 0x000000012b6ab030 fp 0x000000016b4c8810 sp 0x000000016b4c87a0 [Unoptimized] _Future@4048458._propagateToListeners@4048458
[        ]   pc 0x000000012b6a9758 fp 0x000000016b4c8858 sp 0x000000016b4c8820 [Unoptimized] _Future@4048458._completeWithValue@4048458
[        ]   pc 0x000000012b6c04e4 fp 0x000000016b4c8898 sp 0x000000016b4c8868 [Unoptimized] _Future@4048458._asyncCompleteWithValue@4048458.<anonymous closure>
[        ]   pc 0x0000000123c4af70 fp 0x000000016b4c8910 sp 0x000000016b4c88a8 [Unoptimized] _rootRun@4048458
[        ]   pc 0x0000000123c4abe4 fp 0x000000016b4c8970 sp 0x000000016b4c8920 [Unoptimized] _rootRun@4048458
[        ]   pc 0x0000000123c4a2ec fp 0x000000016b4c8a00 sp 0x000000016b4c8980 [Unoptimized] _CustomZone@4048458.run
[        ]   pc 0x000000012b6a3598 fp 0x000000016b4c8a70 sp 0x000000016b4c8a10 [Unoptimized] _CustomZone@4048458.runGuarded
[        ]   pc 0x000000012b6a3444 fp 0x000000016b4c8ab0 sp 0x000000016b4c8a80 [Unoptimized] _CustomZone@4048458.bindCallbackGuarded.<anonymous closure>
[        ]   pc 0x000000012b6a3124 fp 0x000000016b4c8af8 sp 0x000000016b4c8ac0 [Unoptimized] _microtaskLoop@4048458
[        ]   pc 0x000000012b6a2cb4 fp 0x000000016b4c8b38 sp 0x000000016b4c8b08 [Unoptimized] _startMicrotaskLoop@4048458
[        ]   pc 0x000000012b6a2bac fp 0x000000016b4c8b60 sp 0x000000016b4c8b48 [Unoptimized] _startMicrotaskLoop@4048458
[        ]   pc 0x0000000119f03518 fp 0x000000016b4c8c30 sp 0x000000016b4c8b70 [Stub] InvokeDartCode
[   +1 ms] === Crash occurred when compiling package:amplify_core/src/category/amplify_auth_category.dart_AuthCategory_updateUserAttribute in unoptimized JIT mode in GenerateCode pass
[        ] === When compiling block B9[target]:80
[        ] === When compiling instruction t0 <- AssertAssignable:56(t0, t1, 'options', instantiator_type_args(t2), function_type_args(t3))
[        ] *** BEGIN CFG
           GenerateCode
           ==== package:amplify_core/src/category/amplify_auth_category.dart_AuthCategory_updateUserAttribute (RegularFunction)
           B0[graph]:0
           B1[function entry]:2
               t0 <- Constant(#0)
               StoreLocal(:entry_points_temp @-7, t0)
               goto:68 B6
           B7[function entry]:70
               t0 <- Constant(#2)
               StoreLocal(:entry_points_temp @-7, t0)
               goto:72 B6
           B6[join]:66 pred(B1, B7)
               t0 <- LoadLocal(:arg_desc @-4)
               t0 <- LoadField(t0 . ArgumentsDescriptor.positional_count {final})
               t1 <- LoadLocal(:arg_desc @-4)
               t1 <- LoadField(t1 . ArgumentsDescriptor.count {final})
               t2 <- LoadLocal(:t1 @-9)
               t3 <- Constant(#1)
               t2 <- BinarySmiOp:4(- [tr], t2, t3)
               t3 <- LoadLocal(:t2 @-10)
               t3 <- LoadIndexedUnsafe(fp[t3 + 16]) T{*?}
               StoreLocal(this @0, t3)
               t3 <- Constant(#0)
               StoreLocal(:expr_temp @-6, t3)
               t3 <- Constant(#2)
               t4 <- LoadLocal(:expr_temp @-6)
               t3 <- BinarySmiOp:6(* [tr], t3, t4)
               t4 <- LoadLocal(:arg_desc @-4) T{*?}
               t5 <- Constant(#4)
               t6 <- <…>
[  +98 ms] Service protocol connection closed.
[        ] Lost connection to device.
[        ] DevFS: Deleting filesystem on the device (file:///Users/josipkrnjic/Library/Developer/CoreSimulator/Devices/C7B8FF1E-D7B1-487B-91EC-CDA674B7DBC1/data/Containers/Data/Application/22EADBAD-0CE4-4C69-B337-774E3F64F1E0/tmp/flutter-ludusSo0tEi/flutter-ludus/)
[   +4 ms] executing: /usr/bin/arch -arm64e xcrun simctl terminate C7B8FF1E-D7B1-487B-91EC-CDA674B7DBC1 com.ludus.app.ludus
[  +82 ms] An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
           The operation couldn’t be completed. found nothing to terminate
           found nothing to terminate
Exception: Unable to terminate com.********** on C7B8FF1E-D7B1-487B-91EC-CDA674B7DBC1:
ProcessException: Process exited abnormally:
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
The operation couldn’t be completed. found nothing to terminate
```

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.0

### Amplify Flutter Version

1.0.0-next.0

### Deployment Method

Custom Pipeline

**Comment by fjnoyp** [comment] 2023-03-09 13:23
Hi @itsJoKr 

Do you get this error when trying to compile and run the app or is the error triggered when you call that method as the app is already running?

Based on the error message it sounds like you cannot even compile: 

`[   +1 ms] === Crash occurred when compiling package:amplify_core/src/category/amplify_auth_category.dart_AuthCategory_updateUserAttribute in unoptimized JIT mode in GenerateCode pass`

I assume you are able to run other auth methods like sign up and sign in but can you confirm that you have?

**Comment by itsJoKr** [comment] 2023-03-09 14:04
@fjnoyp It does compile, the crash happens when I call the method.

After further testing:
- In release mode, everything seems to work
- In debug mode, the app crashes

I call other methods like signIn, signUp, verifySignUp, delete, logout, they all work.

**Comment by dnys1** [comment] 2023-03-09 15:33
Duplicate of https://github.com/aws-amplify/amplify-flutter/issues/2361.

Unfortunately, this is an issue with the Dart compiler. It has been resolved but has not made it to Flutter stable yet. We are working on internal improvements which should help resolve this too which should be available over the next few weeks.

**Closed by dnys1** 2023-03-09 15:33 UTC
Labels: iOS, Auth

**Comment by itsJoKr** [comment] 2023-03-09 15:35
👍 Thanks. Somehow missed that opened issue.
