### ISSUE TITLE
Retrieving data from graphql

### ISSUE THREAD

**Issue by lebe24** [aws-amplify/amplify-flutter#3457] opened 2023-07-22 21:19 UTC
### Description

Having a problem fetching my data using Graphql. using the question model below 

```dart
/** This is an auto generated class representing the Question type in your schema. */
class Question extends amplify_core.Model {
  static const classType = const _QuestionModelType();
  final String id;
  final String? _Text;
  final List<QuestionAnswer>? _Answers;
  final Answer? _AcceptedAns;
  final amplify_core.TemporalDateTime? _createdAt;
  final amplify_core.TemporalDateTime? _updatedAt;
  final String? _questionAcceptedAnsId;

  @override
  getInstanceType() => classType;
  
  @Deprecated('[getId] is being deprecated in favor of custom primary key feature. Use getter [modelIdentifier] to get model identifier.')
  @override
  String getId() => id;
  
  QuestionModelIdentifier get modelIdentifier {
      return QuestionModelIdentifier(
        id: id
      );
  }
  
  String? get Text {
    return _Text;
  }
  
  List<QuestionAnswer>? get Answers {
    return _Answers;
  }
  
  Answer? get AcceptedAns {
    return _AcceptedAns;
  }
  
  amplify_core.TemporalDateTime? get createdAt {
    return _createdAt;
  }
  
  amplify_core.TemporalDateTime? get updatedAt {
    return _updatedAt;
  }
  
  String? get questionAcceptedAnsId {
    return _questionAcceptedAnsId;
  }
  
  const Question._internal({required this.id, Text, Answers, AcceptedAns, createdAt, updatedAt, questionAcceptedAnsId}): _Text = Text, _Answers = Answers, _AcceptedAns = AcceptedAns, _createdAt = createdAt, _updatedAt = updatedAt, _questionAcceptedAnsId = questionAcceptedAnsId;
  
  factory Question({String? id, String? Text, List<QuestionAnswer>? Answers, Answer? AcceptedAns, String? questionAcceptedAnsId}) {
    return Question._internal(
      id: id == null ? amplify_core.UUID.getUUID() : id,
      Text: Text,
      Answers: Answers != null ? List<QuestionAnswer>.unmodifiable(Answers) : Answers,
      AcceptedAns: AcceptedAns,
      questionAcceptedAnsId: questionAcceptedAnsId);
  }
  
  bool equals(Object other) {
    return this == other;
  }
  
  @override
  bool operator ==(Object other) {
    if (identical(other, this)) return true;
    return other is Question &&
      id == other.id &&
      _Text == other._Text &&
      DeepCollectionEquality().equals(_Answers, other._Answers) &&
      _AcceptedAns == other._AcceptedAns &&
      _questionAcceptedAnsId == other._questionAcceptedAnsId;
  }
  
  @override
  int get hashCode => toString().hashCode;
  
  @override
  String toString() {
    var buffer = new StringBuffer();
    
    buffer.write("Question {");
    buffer.write("id=" + "$id" + ", ");
    buffer.write("Text=" + "$_Text" + ", ");
    buffer.write("createdAt=" + (_createdAt != null ? _createdAt!.format() : "null") + ", ");
    buffer.write("updatedAt=" + (_updatedAt != null ? _updatedAt!.format() : "null") + ", ");
    buffer.write("questionAcceptedAnsId=" + "$_questionAcceptedAnsId");
    buffer.write("}");
    
    return buffer.toString();
  }
  
  Question copyWith({String? Text, List<QuestionAnswer>? Answers, Answer? AcceptedAns, String? questionAcceptedAnsId}) {
    return Question._internal(
      id: id,
      Text: Text ?? this.Text,
      Answers: Answers ?? this.Answers,
      AcceptedAns: AcceptedAns ?? this.AcceptedAns,
      questionAcceptedAnsId: questionAcceptedAnsId ?? this.questionAcceptedAnsId);
  }
  
  Question copyWithModelFieldValues({
    ModelFieldValue<String?>? Text,
    ModelFieldValue<List<QuestionAnswer>?>? Answers,
    ModelFieldValue<Answer?>? AcceptedAns,
    ModelFieldValue<String?>? questionAcceptedAnsId
  }) {
    return Question._internal(
      id: id,
      Text: Text == null ? this.Text : Text.value,
      Answers: Answers == null ? this.Answers : Answers.value,
      AcceptedAns: AcceptedAns == null ? this.AcceptedAns : AcceptedAns.value,
      questionAcceptedAnsId: questionAcceptedAnsId == null ? this.questionAcceptedAnsId : questionAcceptedAnsId.value
    );
  }
  
  Question.fromJson(Map<String, dynamic> json)  
    : id = json['id'],
      _Text = json['Text'],
      _Answers = json['Answers'] is List
        ? (json['Answers'] as List)
          .where((e) => e?['serializedData'] != null)
          .map((e) => QuestionAnswer.fromJson(new Map<String, dynamic>.from(e['serializedData'])))
          .toList()
        : null,
      _AcceptedAns = json['AcceptedAns']?['serializedData'] != null
        ? Answer.fromJson(new Map<String, dynamic>.from(json['AcceptedAns']['serializedData']))
        : null,
      _createdAt = json['createdAt'] != null ? amplify_core.TemporalDateTime.fromString(json['createdAt']) : null,
      _updatedAt = json['updatedAt'] != null ? amplify_core.TemporalDateTime.fromString(json['updatedAt']) : null,
      _questionAcceptedAnsId = json['questionAcceptedAnsId'];
  
  Map<String, dynamic> toJson() => {
    'id': id, 'Text': _Text, 'Answers': _Answers?.map((QuestionAnswer? e) => e?.toJson()).toList(), 'AcceptedAns': _AcceptedAns?.toJson(), 'createdAt': _createdAt?.format(), 'updatedAt': _updatedAt?.format(), 'questionAcceptedAnsId': _questionAcceptedAnsId
  };
  
  Map<String, Object?> toMap() => {
    'id': id,
    'Text': _Text,
    'Answers': _Answers,
    'AcceptedAns': _AcceptedAns,
    'createdAt': _createdAt,
    'updatedAt': _updatedAt,
    'questionAcceptedAnsId': _questionAcceptedAnsId
  };

  static final amplify_core.QueryModelIdentifier<QuestionModelIdentifier> MODEL_IDENTIFIER = amplify_core.QueryModelIdentifier<QuestionModelIdentifier>();
  static final ID = amplify_core.QueryField(fieldName: "id");
  static final TEXT = amplify_core.QueryField(fieldName: "Text");
  static final ANSWERS = amplify_core.QueryField(
    fieldName: "Answers",
    fieldType: amplify_core.ModelFieldType(amplify_core.ModelFieldTypeEnum.model, ofModelName: 'QuestionAnswer'));
  static final ACCEPTEDANS = amplify_core.QueryField(
    fieldName: "AcceptedAns",
    fieldType: amplify_core.ModelFieldType(amplify_core.ModelFieldTypeEnum.model, ofModelName: 'Answer'));
  static final QUESTIONACCEPTEDANSID = amplify_core.QueryField(fieldName: "questionAcceptedAnsId");
  static var schema = amplify_core.Model.defineSchema(define: (amplify_core.ModelSchemaDefinition modelSchemaDefinition) {
    modelSchemaDefinition.name = "Question";
    modelSchemaDefinition.pluralName = "Questions";
    
    modelSchemaDefinition.authRules = [
      amplify_core.AuthRule(
        authStrategy: amplify_core.AuthStrategy.PUBLIC,
        operations: const [
          amplify_core.ModelOperation.CREATE,
          amplify_core.ModelOperation.UPDATE,
          amplify_core.ModelOperation.DELETE,
          amplify_core.ModelOperation.READ
        ])
    ];
    
    modelSchemaDefinition.addField(amplify_core.ModelFieldDefinition.id());
    
    modelSchemaDefinition.addField(amplify_core.ModelFieldDefinition.field(
      key: Question.TEXT,
      isRequired: false,
      ofType: amplify_core.ModelFieldType(amplify_core.ModelFieldTypeEnum.string)
    ));
    
    modelSchemaDefinition.addField(amplify_core.ModelFieldDefinition.hasMany(
      key: Question.ANSWERS,
      isRequired: false,
      ofModelName: 'QuestionAnswer',
      associatedKey: QuestionAnswer.QUESTION
    ));
    
    modelSchemaDefinition.addField(amplify_core.ModelFieldDefinition.hasOne(
      key: Question.ACCEPTEDANS,
      isRequired: false,
      ofModelName: 'Answer',
      associatedKey: Answer.ID
    ));
    
    modelSchemaDefinition.addField(amplify_core.ModelFieldDefinition.nonQueryField(
      fieldName: 'createdAt',
      isRequired: false,
      isReadOnly: true,
      ofType: amplify_core.ModelFieldType(amplify_core.ModelFieldTypeEnum.dateTime)
    ));
    
    modelSchemaDefinition.addField(amplify_core.ModelFieldDefinition.nonQueryField(
      fieldName: 'updatedAt',
      isRequired: false,
      isReadOnly: true,
      ofType: amplify_core.ModelFieldType(amplify_core.ModelFieldTypeEnum.dateTime)
    ));
    
    modelSchemaDefinition.addField(amplify_core.ModelFieldDefinition.field(
      key: Question.QUESTIONACCEPTEDANSID,
      isRequired: false,
      ofType: amplify_core.ModelFieldType(amplify_core.ModelFieldTypeEnum.string)
    ));
  });
}

class _QuestionModelType extends amplify_core.ModelType<Question> {
  const _QuestionModelType();
  
  @override
  Question fromJson(Map<String, dynamic> jsonData) {
    return Question.fromJson(jsonData);
  }
  
  @override
  String modelName() {
    return 'Question';
  }
}

/**
 * This is an auto generated class representing the model identifier
 * of [Question] in your schema.
 */
class QuestionModelIdentifier implements amplify_core.ModelIdentifier<Question> {
  final String id;

  /** Create an instance of QuestionModelIdentifier using [id] the primary key. */
  const QuestionModelIdentifier({
    required this.id});
  
  @override
  Map<String, dynamic> serializeAsMap() => (<String, dynamic>{
    'id': id
  });
  
  @override
  List<Map<String, dynamic>> serializeAsList() => serializeAsMap()
    .entries
    .map((entry) => (<String, dynamic>{ entry.key: entry.value }))
    .toList();
  
  @override
  String serializeAsString() => serializeAsMap().values.join('#');
  
  @override
  String toString() => 'QuestionModelIdentifier(id: $id)';
  
  @override
  bool operator ==(Object other) {
    if (identical(this, other)) {
      return true;
    }
    
    return other is QuestionModelIdentifier &&
      id == other.id;
  }
 
  @override
  int get hashCode =>
    id.hashCode;
}

````
with the fetch query function 
````dart
Future<List<Question?>> queryListItems() async {
  try {
    final request = ModelQueries.list(Question.classType);
    final response = await Amplify.API.query(request: request).response;

    final todos = response.data?.items;
    if (todos == null) {
      safePrint('errors: ${response.errors}');
      return const [];
    }

    // Print the entire list of items
    print('Items: $todos');
    
    // Check if there is at least one item in the list
    if (todos.isNotEmpty) {
      // Access the first item in the list
      final firstItem = todos[0];
      
      // Check if the first item has the Answers field
      if (firstItem?.Answers != null) {
        // Access the Answers field of the first item
        final todo = firstItem?.Answers;
        print('Answers: $todo'); // Print the Answers field
      }
    }

    return todos;
  } on ApiException catch (e) {
    safePrint('Query failed: $e');
    return const [];
  }
}
``````
The  Answer model was giving me null but using the graphql  test data in the amplify studio I received data to my answer model with the query below
`````graphql
query MyQuery {
  listQuestions {
    items {
      Text
      id
      Answers {
        items {
          answer {
            id
            Text
          }
        }
      }
    }
  }
}

``````
output

`````shell

{
  "data": {
    "listQuestions": {
      "items": [
        {
          "Text": "image of mark",
          "id": "ba28e809-e55a-4646-b7d7-8f4e46cf9a07",
          "Answers": {
            "items": [
              {
                "answer": {
                  "id": "6ec04ef9-62be-420a-8aef-6e7be9b28115",
                  "Text": "mark"
                }
              },
              {
                "answer": {
                  "id": "0b2da66e-dffb-481e-a7cc-2b3b32fc2689",
                  "Text": "Elon Musk"
                }
              },
              {
                "answer": {
                  "id": "028c1d2b-238b-491d-90d9-1e82aabce27e",
                  "Text": "Jack Dorsey"
                }
              },
              {
                "answer": {
                  "id": "7c5656e5-1b3c-4289-bb71-4c39dc252f97",
                  "Text": "ronaldo"
                }
              }
            ]
          }
        },
        {
          "Text": "image of messi",
          "id": "6074361b-34dd-46fd-bf6f-79498f74859c",
          "Answers": {
            "items": [
              {
                "answer": {
                  "id": "616150a6-9a4d-4e2c-930c-c31993fd751f",
                  "Text": "nemar"
                }
              },
              {
                "answer": {
                  "id": "7c5656e5-1b3c-4289-bb71-4c39dc252f97",
                  "Text": "ronaldo"
                }
              },
              {
                "answer": {
                  "id": "2087bd51-b3d4-4214-8cf1-70e7169060f0",
                  "Text": "messi"
                }
              },
              {
                "answer": {
                  "id": "028c1d2b-238b-491d-90d9-1e82aabce27e",
                  "Text": "Jack Dorsey"
                }
              }
            ]
          }
        },
        {
          "Text": null,
          "id": "7d1c285c-5033-44d7-8a6d-41aadf40c9aa",
          "Answers": {
            "items": []
          }
        }
      ]
    }
  }
}

`````

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

no response

### Screenshots

![code](https://github.com/aws-amplify/amplify-flutter/assets/31292486/7c371303-8681-4474-aaf7-d4fa62a1ba9a)

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

1.0.0

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type Answer @model @auth(rules: [{allow: public}]) {
  id: ID!
  Text: String
  questions: [Question] @manyToMany(relationName: "QuestionAnswer")
}

type Question @model @auth(rules: [{allow: public}]) {
  id: ID!
  Text: String
  Answers: [Answer] @manyToMany(relationName: "QuestionAnswer")
  AcceptedAns: Answer @hasOne
}
```

**Comment by dnys1** [comment] 2023-07-24 21:58
I was able to reproduce this. The issue is that the query generated by `ModelQueries.list` does not include nested fields.

![Screenshot 2023-07-24 at 2 41 49 PM](https://github.com/aws-amplify/amplify-flutter/assets/24740863/25da71ef-8025-4dee-acec-4cb4a09b6608)

This is a current limitation of model helpers and models with relationships. We are currently tracking support for this as a feature request here: https://github.com/aws-amplify/amplify-flutter/issues/1449. I will be closing this issue in favor of that issue so please leave a thumbs up and follow that ticket.

The current workaround, as you discovered, is to write a GraphQL request by hand which will return the nested data.

**Closed by dnys1** 2023-07-24 21:58 UTC
Labels: GraphQL API, pending-triage

**Comment by lebe24** [comment] 2023-07-25 17:38
Generally, it doesn't query arrays

**Comment by dnys1** [comment] 2023-07-25 17:51
It will not query arrays on models, that is correct.

**Comment by lebe24** [comment] 2023-07-31 06:27
Does I have a fix
