### ISSUE TITLE
Making One Field in the Model Unchageable With Auth Directive Will Cause All Fields to Be Unchangeable

### ISSUE THREAD

**Issue by kuoaid** [aws-amplify/amplify-flutter#2678] opened 2023-02-17 21:26 UTC
### Description

Say we have a model like this:

```
type UserData @model @auth(rules: [{allow: private, operations: [read]}, {allow: owner}])
{
    id: ID!
    agreedToPolicy: Boolean
    userEmail: String
    points: Int
    premiumStatus: Int
}
```

And I want one of the data to be not changeable with an auth directive:
```
type UserData @model @auth(rules: [{allow: private, operations: [read]}, {allow: owner}]) {
    id: ID!
    agreedToPolicy: Boolean
    userEmail: String
    points: Int
    premiumStatus: Int @auth(rules:[{allow: owner, operations: [read, create, delete]},
        {allow: private, operations: [read]}])
}
```

If I run a query with DataStore to update the userEmail, DataStore will respond with "UNAUTHORIZED". It seems like even when just one field is being updated, DataStore requires update authorization for all fields. The graphQL API also acts similarly.

Please help and instruct how I can mutate data within a model with field-level auth directives, which are important for data security.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Steps to Reproduce

1. Create any model with more than one fields for which the owner has full access.
2. Assign one of the fields with an auth directive forbidding the owner from UPDATE.
3. Run a mutation/datastore.save to update the value **without** the field-level auth directive. Leave the one with auth directive alone.
4. You should encounter the error.

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.6

### Amplify Flutter Version

0.6.10

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type UserData @model @auth(rules: [{allow: private, operations: [read]}, {allow: owner}]) 
{
    id: ID!
    agreedToPolicy: Boolean
    userEmail: String
    points: Int
    premiumStatus: Int @auth(rules:[{allow: owner, operations: [read, create, delete]},
        {allow: private, operations: [read]}])
}
```

**Comment by HuiSF** [comment] 2023-02-22 17:15
Hi @kuoaid thanks for reporting this issue.

The behavior you observed is expected, as DataStore doesn't support field level auth. Please feel free to plus one on this feature enhancement request issue https://github.com/aws-amplify/amplify-category-api/issues/230 

For DataStore supported authorization strategies please refer to the documentation https://docs.amplify.aws/lib/datastore/setup-auth-rules/q/platform/flutter/. 

I'm closing this issue as a duplicate of above linked issue.

**Closed by HuiSF** 2023-02-22 17:15 UTC
Labels: DataStore, pending-triage, requires-api-data-fix

**Comment by kuoaid** [comment] 2023-02-22 19:47
> 

Hello @HuiSF , thank you for your response and help!

Can you confirm that in the Flutter GraphQL API, not DataStore API, the same issue persists and is expected?

**Comment by HuiSF** [comment] 2023-02-22 21:40
Hi @kuoaid I need to some digging and testing to confirm. Will get back to your question.

**Comment by kuoaid** [comment] 2023-02-28 18:46
Thank you @HuiSF .
1. Any updates?
2. Can we mark this issue as open since a big part of it is still under investigation?
